### ISSUE TITLE
Build a server extension (using tornado) which can communicate with terminal.

### ISSUE THREAD

**Issue by ashutoshbondre** [jupyterlab/jupyterlab-git#10]
Build a server extension(using tornado) which can communicate with terminal & try to send a command and receive its response using the server extension

**Comment by ddavidebor** [comment]
You want to use git commands through the terminal? have you checked out https://github.com/gitpython-developers/GitPython ?

**Comment by zzhangjii** [comment]
thx, that's exactly what we are looking for.
