### ISSUE TITLE
jupyterlab_git is not in pypi

### ISSUE THREAD

**Issue by oersted** [jupyterlab/jupyterlab-git#102]
Just run `pip install jupyterlab_git/` like the README says and got an error message saying that the package doesn't exist.

A quick search confirms it: https://pypi.python.org/pypi?%3Aaction=search&term=jupyterlab&submit=search

**Comment by ddavidebor** [comment]
https://github.com/fermiumlabs/data-chan-python/blob/master/wercker.yml may be useful if you want to set up a CI for releasing python packages

**Comment by ellisonbg** [comment]
Adding this to the 0.3 milestone for JupyterCon
