### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#1023]
Translation missing for file status in

https://github.com/MLH-Fellowship/jupyterlab-git/blob/489ac202af15bb262107dcfe54728f78486818d7/src/components/FileItem.tsx#L140

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab-git/pull/980#discussion_r699573337_

- [ ] codemirror merge addon -> needs to define [`phrases`](https://codemirror.net/doc/manual.html#option_phrases) for `phrase(<string>)` calls in [mergeview](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/components/diff/mergeview.ts).
- [ ] nbdime

**Comment by krassowski** [comment]
- [ ] Git clone button
- [ ] Set Up Remotes and Git Documentation in git menu
- [ ] "Git" menu label
- [ ] diff ("HEAD", "REMOTE")

**Comment by krassowski** [comment]
Should we tag it a good first issue?

**Comment by fcollonval** [comment]
> Should we tag it a good first issue? Edit: maybe after splitting the easier tasks like the Git button out?

I'll tag the full issue and I help any contributors even it only partially solve the task.

**Comment by my-acc-gh** [comment]
hello @fcollonval, can I work on this?

**Comment by fcollonval** [comment]
> hello @fcollonval, can I work on this? 

Sure don't hesitate to open a PR early for discussion or if you need help.

**Comment by kostyafarber** [comment]
Will try work on this is, if @my-acc-gh work has stalled.

**Comment by kostyafarber** [comment]
> * [ ]  Git clone button
>   https://github.com/jupyterlab/jupyterlab-git/blob/9df356280b544b8f0e2236ef0757d57a6239ca7c/src/widgets/gitClone.tsx#L36
> * [ ]  Set Up Remotes and Git Documentation in git menu
>   no idea why this does not work
> * [ ]  "Git" menu label
>   https://github.com/jupyterlab/jupyterlab-git/blob/b4876a489de099fa4ee7105b1426021e69b6bb82/src/commandsAndMenu.tsx#L1041
> * [ ]  diff ("HEAD", "REMOTE") - nbdime

Looks like it's also missing for "Git" menu label at:

https://github.com/jupyterlab/jupyterlab-git/blob/master/src/commandsAndMenu.tsx#L1508

**Comment by kostyafarber** [comment]
@krassowski found the reason  

> Set Up Remotes and Git Documentation in git menu

Didn't work. It's here:

https://github.com/jupyterlab/jupyterlab-git/blob/3221c3eed0fdb447db5cfcff2f7f2db99e3c8c82/src/index.ts#L198-L201

If I move what's inside the if block outside the if block it applies the translation (and also a small text change I made to test).

Not sure the mechanics of how this works because the submenu still get's produced either way (but in the if block the translation doesn't fire). I'm not exactly sure why that `if` block is there but it looks like it's only for jlab versions less than 3.0? Don't what the workaround is or if we need that check here?

**Comment by fcollonval** [comment]
In JupyterLab 3.2 there is a new way of defining menus to make them customizable by the users. For that the menus need to be define in the settings schema:

https://github.com/jupyterlab/jupyterlab-git/blob/3221c3eed0fdb447db5cfcff2f7f2db99e3c8c82/schema/plugin.json#L82

We try to be smart about those menus items to extract the string requiring translation. But for the two of interests here, it is not straightforward as they are `args`:

https://github.com/jupyterlab/jupyterlab-git/blob/3221c3eed0fdb447db5cfcff2f7f2db99e3c8c82/schema/plugin.json#L148-L155

I guess the fix is to change that line:

https://github.com/jupyterlab/jupyterlab-git/blob/3221c3eed0fdb447db5cfcff2f7f2db99e3c8c82/src/commandsAndMenu.tsx#L237

```diff
-    label: args => args['text'] as string,
+    label: args => trans.__(args['text'] as string),
```

And fix the internationaliztion settings as described in the [documentation](https://jupyterlab.readthedocs.io/en/stable/extension/internationalization.html#settings-translation) by adding to the schema:

```json
"jupyter.lab.internationalization": {
    "selectors": [
        "jupyter.lab.menus/.*/args/text",
    ],
    "domain": "jupyterlab_git"
}
```

**Comment by kostyafarber** [comment]
Thanks for the clarification @fcollonval!

**Comment by kostyafarber** [comment]
Having trouble figuring out why the `nbdime` translation isn't working, I've changed the parameters for `ITranslator` to not be optional but that hasn't fixed it. 

I can start working on `phrases` and implement something similar to what is in jupyerlab?

**Comment by fcollonval** [comment]
> Having trouble figuring out why the `nbdime` translation isn't working, I've changed the parameters for `ITranslator` to not be optional but that hasn't fixed it.

For `nbdime`, it is unfortunately not possible to add the translation as the code is [an external library](https://github.com/jupyter/nbdime) that does not support translation for now.

> I can start working on `phrases` and implement something similar to what is in jupyerlab?

The documentation for that feature is the one of CodeMirror 5 that you can find [there](https://codemirror.net/5/doc/manual.html#option_phrases).

**Comment by fcollonval** [comment]
Yes let's close it and open a new issue about nbdime.
