### ISSUE TITLE
"jupyter server extension" is a not valid command

### ISSUE THREAD

**Issue by sunyuding** [jupyterlab/jupyterlab-git#1043]
## Description

`jupyter server extension` is a not valid command. It should be `jupyter serverextension`. Available subcommands: bundlerextension kernel kernelspec lab labextension labhub migrate nbconvert nbextension notebook.

## Reproduce

```
$ jupyter server extension enable --py jupyterlab_git

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir] [--paths] [--json] [--debug] [subcommand]

 

Jupyter: Interactive Computing

 

positional arguments:

  subcommand     the subcommand to launch

 

optional arguments:

  -h, --help     show this help message and exit

  --version      show the versions of core jupyter packages and exit

  --config-dir   show Jupyter config dir

  --data-dir     show Jupyter data dir

  --runtime-dir  show Jupyter runtime dir

  --paths        show all Jupyter paths. Add --json for machine-readable format.

  --json         output paths as machine-readable json

  --debug        output debug information about paths

 

Available subcommands: bundlerextension kernel kernelspec lab labextension labhub migrate nbconvert nbextension notebook

run serverextension troubleshoot trust

 

Jupyter command `jupyter-server` not found.
```

## Expected behavior

```
$ jupyter serverextension list

config dir: /opt/.jupyter

    odsc_cli.extension  enabled

    - Validating...

      odsc_cli.extension  OK

    jupyterlab_templates.extension  enabled

    - Validating...

     jupyterlab_templates.extension  OK

config dir: /opt/conda/etc/jupyter

    jupyterlab  enabled

    - Validating...

      jupyterlab 2.2.6 OK

    jupyterlab_git  enabled

    - Validating...

      jupyterlab_git 0.24.0 OK

    jupyterlab_templates  enabled

    - Validating...

      X is jupyterlab_templates importable?

    nbdime  enabled

    - Validating...

      nbdime 2.1.0 OK
```

## Context

- Python package version:

```
$ conda list jupyterlab-git

# packages in environment at /opt/conda:

#

# Name                    Version                   Build  Channel

jupyterlab-git            0.24.0             pyhd8ed1ab_0    conda-forge
```
```
$ pip show jupyterlab-git

Name: jupyterlab-git

Version: 0.24.0

Summary: A server extension for JupyterLab's git extension

Home-page: https://github.com/jupyterlab/jupyterlab-git

Author: Jupyter Development Team

Author-email:

License: BSD

Location: /opt/conda/lib/python3.6/site-packages

Requires: packaging, notebook, pexpect, nbdime

Required-by:
```
- Extension version:

```
$ jupyter labextension list

JupyterLab v2.2.6

Known labextensions:

   app dir: /opt/conda/share/jupyter/lab

        @bokeh/jupyter_bokeh v2.0.4  enabled  OK

        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK

        @jupyterlab/cellone-extension v0.1.4  enabled  OK

        @jupyterlab/explorer-extension v0.2.16  enabled  OK

        @jupyterlab/fasta-extension v2.0.0  enabled  OK

        @jupyterlab/geojson-extension v2.0.1  enabled  OK

        @jupyterlab/git v0.24.0  enabled  OK

        @jupyterlab/katex-extension v2.0.0  enabled  OK

        @jupyterlab/mathjax2-extension v2.2.4  enabled  OK

        @jupyterlab/mathjax3-extension v3.0.0  enabled  OK

        @jupyterlab/oracle-splash-screen v0.1.0  enabled  OK

        @jupyterlab/templates-extension v0.2.4  enabled  OK

        @jupyterlab/toc v4.0.0  enabled  OK

        @jupyterlab/vega5-extension v2.2.0  enabled  OK

        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK

        jupyter-leaflet v0.13.0  enabled  OK

        jupyterlab-plotly v4.8.2  enabled  OK

        jupyterlab_templates v0.2.2  enabled   X

        nbdime-jupyterlab v2.0.1  enabled  OK

        plotlywidget v4.8.2  enabled  OK

 

   The following extension are outdated:

        jupyterlab_templates

       

   Consider running "jupyter labextension update --all" to check for updates.
```
- Git version:

```
$ git --version

git version 2.27.0
```
- Operating System and its version:
```
$ uname -a

Linux ad3691171831 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

<details><summary>Command Line Output</summary>
<pre>
$ jupyter lab --debug

[D 19:06:47.904 LabApp] Searching ['/home/datascience', '/opt/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files

[D 19:06:47.907 LabApp] Looking for jupyter_config in /etc/jupyter

[D 19:06:47.907 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter

[D 19:06:47.907 LabApp] Looking for jupyter_config in /opt/conda/etc/jupyter

[D 19:06:47.907 LabApp] Looking for jupyter_config in /opt/.jupyter

[D 19:06:47.908 LabApp] Looking for jupyter_config in /home/datascience

[D 19:06:47.910 LabApp] Looking for jupyter_notebook_config in /etc/jupyter

[D 19:06:47.910 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter

[D 19:06:47.910 LabApp] Looking for jupyter_notebook_config in /opt/conda/etc/jupyter

[D 19:06:47.911 LabApp] Loaded config file: /opt/conda/etc/jupyter/jupyter_notebook_config.json

[D 19:06:47.912 LabApp] Looking for jupyter_notebook_config in /opt/.jupyter

[D 19:06:47.913 LabApp] Loaded config file: /opt/.jupyter/jupyter_notebook_config.py

[D 19:06:47.914 LabApp] Loaded config file: /opt/.jupyter/jupyter_notebook_config.json

[D 19:06:47.915 LabApp] Looking for jupyter_notebook_config in /home/datascience

[D 19:06:47.921 LabApp] [nb_conda_kernels] refreshing conda info

[I 19:06:48.238 LabApp] [nb_conda_kernels] enabled, 1 kernels found

[D 19:06:48.243 LabApp] Paths used for configuration of jupyter_notebook_config:

        /etc/jupyter/jupyter_notebook_config.json

[D 19:06:48.244 LabApp] Paths used for configuration of jupyter_notebook_config:

        /usr/local/etc/jupyter/jupyter_notebook_config.json

[D 19:06:48.245 LabApp] Paths used for configuration of jupyter_notebook_config:

        /opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json

        /opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab_git.json

        /opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab_templates.json

        /opt/conda/etc/jupyter/jupyter_notebook_config.d/nbdime.json

        /opt/conda/etc/jupyter/jupyter_notebook_config.json

[D 19:06:48.246 LabApp] Paths used for configuration of jupyter_notebook_config:

        /opt/.jupyter/jupyter_notebook_config.json

[I 19:06:48.252 LabApp] Authentication of /metrics is OFF, since other authentication is disabled.

[W 19:06:48.473 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.

[I 19:06:48.473 LabApp] The port 8888 is already in use, trying another port.

[I 19:06:50.081 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab

[I 19:06:50.082 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab

Installing jupyterlab_templates handler on path /templates

Search paths:

        /home/datascience/conda

        /opt/conda/lib/python3.6/site-packages/jupyterlab_templates/templates

        /home/datascience/.local/share/jupyter/notebook_templates

        /opt/conda/share/jupyter/notebook_templates

        /usr/local/share/jupyter/notebook_templates

        /usr/share/jupyter/notebook_templates

Available templates:

        /jupyterlab_templates/Sample.ipynb

[D 19:06:50.255 LabApp] Using default logger

[D 19:06:50.255 LabApp] Using default logger

[D 19:06:50.255 LabApp] Using default logger

[D 19:06:50.255 LabApp] Using default logger

[D 19:06:50.256 LabApp] Using default logger

[I 19:06:52.266 LabApp] Serving notebooks from local directory: /home/datascience

[I 19:06:52.267 LabApp] Jupyter Notebook 6.3.0 is running at:

[I 19:06:52.267 LabApp] http://ad3691171831:8889/

[I 19:06:52.267 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by krassowski** [comment]
@sunyuding thanks for opening the issue. The README is correct - `jupyter server extension` is a valid command for JupyterLab 3.0+ (with `jupyter-server` installed). `jupyter serverextension` is a legacy command for old `notebook` server which is still used by old JupyterLab versions; if you want to learn more I written a summary [here](https://stackoverflow.com/a/67804732/6646912). I would recommend upgrading JupyterLab.

If you really cannot upgrade (but again I recommend keeping up with current major version), there is an older version of the extension linked in the README: https://github.com/jupyterlab/jupyterlab-git/tree/jlab-2 and this branch correctly uses `jupyter serverextension list`.

**Comment by sunyuding** [comment]
@krassowski - thanks for your reply. Now it makes sense to me.

**Comment by fcollonval** [comment]
Thanks @krassowski for the support. Closing as answered.
