### ISSUE TITLE
How to avoid this error? 

### ISSUE THREAD

**Issue by statiksof** [jupyterlab/jupyterlab-git#1058]
## Description

I see these errors in the log file:

```
[D 2021-11-23 12:19:27.820 SingleUserNotebookApp.jupyterlab_git git:133] Execute ['git', '--version'] in ..
[D 2021-11-23 12:19:29.642 SingleUserNotebookApp.jupyterlab_git git:153] Code: 0
    Output: git version 2.28.0
    
    Error:
```
and 

```
[D 2021-11-23 12:19:32.516 SingleUserNotebookApp.jupyterlab_git git:133] Execute ['git', 'rev-parse', '--show-prefix'] in /.
[D 2021-11-23 12:19:32.541 SingleUserNotebookApp.jupyterlab_git git:153] Code: 128
    Output: 
    Error: fatal: not a git repository (or any of the parent directories): .git
    
```

and:

```
Execute ['git', 'rev-parse', '--show-prefix'] in /home/
[D 2021-11-23 12:19:32.766 SingleUserNotebookApp.jupyterlab_git git:153] Code: 128
    Output: 
    Error: fatal: not a git repository (or any parent up to mount point /mnt)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

## Reproduce

Open jupyter lab in jupyterhub

## Context

- Python package version:

- Extension version: 0.33.0

-         @jupyterlab/git v0.33.0 enabled OK (python, jupyterlab-git)

- 2.28

**Comment by fcollonval** [comment]
Hey @statiksof 

The messages you are seeing are at debug level (indicated by the `D` in front of the date) - nothing to worry about. At that level, all executed git commands are reported in the log. An error at the git commands may be handled by the extension (and therefore not be reported as error). This is the case with the ones you are reporting. There are nothing you can do about them (except changing the log level if you don't want them).

FYI those commands are testing if the current folder is in a git repository. They fail if this is not the case (as you reported).

**Comment by statiksof** [comment]
Thanks, can be closed.
