### ISSUE TITLE
Improve UI around commit button and summary field

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab-git#1059]
## Is your feature request related to a problem? Please describe.
The UX for committing is unclear and relies on tooltips to explain the reason to users.

## Describe the solution you'd like
It would help if the UI made it clear in some way other than a tooltip that the summary field is required to commit

## Describe alternatives you've considered
Some ideas pitched by our requesting customers include highlighting the field (in red?) if the field is not filled out or having the tooltip message more clearly shown if a user tries to click the disabled commit button.

## Additional context

<img width="428" alt="Screen Shot 2021-12-07 at 10 29 34 AM" src="https://user-images.githubusercontent.com/13952758/145068869-8993643c-7912-446d-8961-2e17aae0e7b5.png">

- Python package version:
0.34.0
- Extension version:
v0.34.0
- Git version:
2.33.0
- Operating System and its version:
macOS 11.6

**Comment by fcollonval** [comment]
I support the idea to get a red highlight on the `Summary` field

**Comment by fcollonval** [comment]
Closing as the red highlight was implemented in https://github.com/jupyterlab/jupyterlab-git/pull/1113
