### ISSUE TITLE
(Double) clicking on items causes distracting highlight

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#1060]
## Description

(Double) clicking on items causes distracting highlight.

## Reproduce

1. Open git panel
2. Double click on a file listed as stage/changed or untracked
3. See highlight show up in addition to the blue background indicating that it is active

![Screenshot from 2021-12-10 12-47-27](https://user-images.githubusercontent.com/5832902/145576729-e61a4dd4-93e2-471e-9a45-93b20704204f.png)

## Expected behavior

No selection is shown on items which respond to click events in a programmatic fashion.

Adding CSS rule: `user-select: none` should solve the issue.

## Context

- Python package version: 0.34.0
- Extension version: v0.34.0

**Comment by fcollonval** [comment]
Thanks for the nice suggestion @krassowski

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue, can someone help me find the file!?

**Comment by fcollonval** [comment]
Hey @himanshu007-creator thanks for reaching us. You should be able to fix this one by updating the style (aka adding `userSelect: null`) at https://github.com/jupyterlab/jupyterlab-git/blob/961e1213863f2faed4554a68c6cf0c317cce0f23/src/style/FileItemStyle.ts#L4

When you are at it, it would be nice to add the same style to branch and tag items at https://github.com/jupyterlab/jupyterlab-git/blob/961e1213863f2faed4554a68c6cf0c317cce0f23/src/style/BranchMenu.ts#L116

If you could also test if this occurs in the history panel (for the commit message), it would be awesome.
