### ISSUE TITLE
Update specification of REST API

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#108]
Before releasing 0.1, the markdown document should be updated to include information about all REST API calls. For each call this should include:

* A one sentence description of what it does.
* The URL
* Example input JSON
* Possible HTTP error codes
* Example output JSON

All JSON code blocks should be formatting using triple-back-tick markdown blocks. For an example of a document see this:

https://github.com/jupyterhub/hubshare/blob/master/specification.md

**Comment by zzhangjii** [comment]
for git/API request, it consists 4 seperate subprocess executions on server side (showtoplevel, branch, log, status) and can fail individually. So the form of final reply JSON may vary, in document, do we just show the all-success condition?

**Comment by zzhangjii** [comment]
updated
