### ISSUE TITLE
Ssh key setup for the plugin on k8s

### ISSUE THREAD

**Issue by NickSchouten** [jupyterlab/jupyterlab-git#1082]
### Discussed in https://github.com/jupyterlab/jupyterlab-git/discussions/1081

<div type='discussions-op-text'>

<sup>Originally posted by **NickSchouten** February 18, 2022</sup>
Hi,

I'm trying to setup the plugin in a jupyterhub environment on k8s. It works via https with access keys, but feels incredibly slow while doing so. I am trying to switch to ssh keys. 

I set them up [accordingly](https://github.com/jupyterlab/jupyterlab-git#settings) and when in terminal git clone and push both work, however via the plugin neither works. Only stage and commit work there.

Here is my flow:

I first tried to clone with the ssh link.
Error
Cloning into 'repo-name'... Permission denied, please try again.
 Permission denied, please try again.
 git@ssh.dev.azure.com: Permission denied (password,publickey).
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

So I instead cloned via terminal, which worked.

Then made some changes, staged and committed them via the plugin.

Then tried to push but got this similar error 
Error
Permission denied, please try again.
 Permission denied, please try again.
 git@ssh.dev.azure.com: Permission denied (password,publickey).
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

Then pushed via terminal, which again worked.

What am I missing?

Thanks in Advance for you help!</div>

**Comment by fcollonval** [comment]
@NickSchouten when using the terminal directly do you need to type the ssh key passphrase?

**Comment by NickSchouten** [comment]
@fcollonval No, I ran this `ssh-add ~/.ssh/id_rsa` and entered the passphrase at that point.

**Comment by fcollonval** [comment]
The extension does not handle credentials using ssh case as of now. But did you try by chance to add your key with `ssh-add` in a terminal and then carry the clone (or else) operation through the extension? As you are using ssh-agent, I would image unlocking the key in the terminal will allow its usage anywhere.

**Comment by NickSchouten** [comment]
Yes, I did the ssh-add before I tried cloning and other actions. Would there be anything thing related to it being in a container that hampers the ssh-agent being used in the same way by the plugin?

**Comment by fcollonval** [comment]
I don't think so. I would say it is more about access to the ssh-agent within the subprocess in which this extension is running the git command.

**Comment by fcollonval** [comment]
It seems that ssh-agent needs some environment variables to be set to work properly. Could you run within a notebook or Python console in JupyterLab `print(os.environ)` and see if it contains SSH_AUTH_SOCK and SSH_AGENT_PID.

If it does, could you try emulating what the extension is doing (in a notebook or Python console):

```python
import os
from subprocess import run

env = os.environ.copy()
env["GIT_TERMINAL_PROMPT"] = "0"
run(["git", "clone", <test_url>], cwd=<path_where_to_clone>, env=env, check=True)
```

**Comment by NickSchouten** [comment]
Ok, will do, but might not have time until tomorrow.

**Comment by NickSchouten** [comment]
Ok, so here's what I have so far:

- Indeed neither ENV var is set in a default terminal or notebook.
- Presumably it will therefore also not be set for the plugin at its startup, which would explain it not working.
- When I got it working via terminal, the env vars were set, but only for that terminal, which in hindsight is logical, but I didn't make this connection.
- When I manually set the environment variables to link to an already running ssh-agent that has the key added, the snippet you provided worked in both a fresh terminal and a notebook.

Currently I'm trying to set the environment variables in the jhub_startup_folder or incorporate it in the docker image. Will post if it brings results.

**Comment by dingobar** [comment]
@NickSchouten  I'm facing this. Any luck?

**Comment by NickSchouten** [comment]
No Sadly no real luck. Getting the ssh-agent running anywhere accessible to the jhub_startup_folder took so long, that I eventually had to stop working on it.

**Comment by Hoid** [comment]
I'm facing this issue. Interestingly, though, I'm not able to work around it in the way Nick was with the env vars.

When I try and clone the repo from the terminal inside jupyter lab, it succeeds. That leads me to believe I have my ssh key set up correctly. When I run the code snippet above in a jupyter notebook I get this error:

```
Cloning into 'temp'...
git@gitea-ssh: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I get the same error when trying from the extension's UI in the sidebar, which is what initially drove me to try in the terminal and then search for this issue when it worked there.

Also, the env vars @fcollonval mentioned above are not present either in the terminal where the clone works or in a jupyter notebook where I run this:

```
import os

print(os.environ['SSH_AGENT_PID'])
```

Any ideas?

**Comment by Hoid** [comment]
I realized what my issue was: my ssh key required a password to unlock, and the UI doesn't have an ssh-agent capable of helping you input that password, whereas the terminal just asks you to type it in. The lesson here is that you can't add a password to your ssh key and use this extension!
