### ISSUE TITLE
Un-nest the python package

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#109]
Right now, the `jupyterlab_git` directory has the python package. The `setup.py` file is inside that directory as is another `jupyterlab_git` directory. For the 0.1 release:

* Move the `setup.py` to the top-level of the repo.
* Move the inner `jupyterlab_git` directory up one level.

You will end up like this:

```
/package.json
/src
/setup.py
/jupyterlab_git
    __init__.py
    static
```

**Comment by ashutoshbondre** [comment]
Done, posting in the next pull request I'll make today.
