### ISSUE TITLE
Hide or Un-Hide Different Branch's Features from Current Branch? 

### ISSUE THREAD

**Issue by innat** [jupyterlab/jupyterlab-git#1107]
# Hide or Un-Hide Different Branch's Features from Current Branch? 

Let's say, I've created a new git repository, named **GitTest**. Currently, it contains only one branch (`main`). Now, in jupyter lab, I clone this repo and go to the `GitTest` folder. After that, in jupyter-lab, there is a Git extension on the left side. From there, I created a new branch called `add_text` from the `main` branch. I added some dummy text files and commits and push to the remote repository. Now, if I go to the `GitTest` folded, I can see some dummy text files, which come from the `add_test` branch. 

Now, again I created a new branch from the `main` branch, called it `add_html`, and set it as a current branch. So my current branch is `add_html`. Now, if I go to the `GitTest` folder to add some dummy HTML, I can still view the dummy text file which I added from the `add_text` branch.  And I think it should not be visible by now as I switch to another branch. 

Is it expected? (This behavior is unlike to VS-Code. ).

**Comment by innat** [comment]
**Update**

It happens in a special case. Let's say I've the following branches:

- main
- branch_1
- branch_2
- branch_3

And, currently, I'm on `branch_2`. But next, I want to create a new branch from the `main` branch. To do that, I've to switch to the main branch first. Even though I selected the `main` branch from the pop-up window. Please see the image file below.

![1](https://user-images.githubusercontent.com/17668390/162608397-e5955214-ca96-4f4d-a2a1-dbd1f99e3c4b.png)

Above, my current branch is `check_make`. And I wanted to create a new branch, called `New Brach` from the main branch. To successfully do that, I've to first switch to the `main` branch from the `check_make` branch. Otherwise, a new branch will be created from `check_make` even if I selected the `main` branch from the pop-up window.

**Comment by fcollonval** [comment]
@innat thanks for reporting the issue. Which extension version are you using? 

> The latest v0.36.0 contains a fix for a similar issue (https://github.com/jupyterlab/jupyterlab-git/issues/1089).

**Comment by innat** [comment]
It's `git version 2.20.1`

**Comment by fcollonval** [comment]
Could you please provide the output of the following command: `jupyter labextension list`?

**Comment by innat** [comment]
```yaml
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2022-04-13 11:20:05.946 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.2.9
/opt/conda/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyterlab-jupytext v1.3.8 enabled OK (python, jupytext)
        @jupyterlab/git v0.34.2 enabled OK (python, jupyterlab-git)
        @jupyterlab/server-proxy v3.2.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        beatrix_jupyterlab v3.1.7 disabled OK
        jupyterlab-plotly v5.6.0 enabled OK
        plotlywidget v4.14.3 enabled OK
        wit-widget v1.8.1 enabled OK


Disabled extensions:
    beatrix_jupyterlab (all plugins)
```

**Comment by fcollonval** [comment]
Would you mind testing the latest `jupyterlab-git` version to see if that error is still there?

To upgrade, execute:

```
pip install -U jupyterlab-git
```
