### ISSUE TITLE
Support branch visualization similar to `git log --graph`

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab-git#1109]
## Is your feature request related to a problem? Please describe.

When working with multiple branching, it can be quite helpful to visualize when they branched of from the trunk of the repo and also when they are merged back in. Particularly for teaching purposes it is valuable to visualize these relationships. From the command line it is possible to run `git log --oneline --all --graph` and display this information:

![image](https://user-images.githubusercontent.com/4560057/163680102-13d4db42-df0f-474e-9057-84011bbd8261.png)

Many IDEs include something similar, for example VSCode which is where the next screenshot is from

![image](https://user-images.githubusercontent.com/4560057/163680116-fe40c93e-80ff-4be1-8605-d6f05cd7725c.png)

## Describe the solution you'd like

I saw that this was included in the mock suggestions for improving the the history panel in https://github.com/jupyterlab/jupyterlab-git/issues/245, but it seems like it wasn't implemented in the PR that closed that issue (https://github.com/jupyterlab/jupyterlab-git/pull/270) (or I am missing where it is).

I like the mock pictures included there for how this could look in jupyterlab-git:

![image](https://user-images.githubusercontent.com/4560057/163680393-799b4061-2f91-46ce-a013-d2eb03d655c9.png)

## Describe alternatives you've considered

I currently use either command line or VScode for this purpose instead as a workaround solution. Not sure what an alternative in jupyterlab git would look like

## Additional context

- Python package version:
 ```
jupyterlab                3.3.4             
jupyterlab-git            0.36.0  
```
- Extension version:
```
JupyterLab v3.3.4
/home/joel/.local/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

/home/joel/miniconda3/envs/jlgit/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.1.1 enabled OK
        @jupyterlab/git v0.36.0 enabled OK (python, jupyterlab-git)

Other labextensions (built into JupyterLab)
   app dir: /home/joel/miniconda3/envs/jlgit/share/jupyter/lab
```
- Git version:
```
git version 2.32.0
```
- Operating System and its version:
```
Pop!OS 21.10
5.16.15-76051615-generic
```

**Comment by fcollonval** [comment]
Thanks @joelostblom that visualization was indeed not implemented.
