### ISSUE TITLE
Icons for UI

### ISSUE THREAD

**Issue by hzarea** [jupyterlab/jupyterlab-git#111]
Write code and design icons for the plugin. These icons will be used to replace text, especially in the past commit information section. 

Icons we need to add:
-Addition and deletion (plus and minus) for changes made 
-Author of commit
-Branch (for the branch dropdown)

**Comment by hzarea** [comment]
Yes! I should be able to finish it in the next couple of days.

**Comment by ellisonbg** [comment]
ok, targeting this to 0.1
