### ISSUE TITLE
Delete multiple untracked files from left sidebar view

### ISSUE THREAD

**Issue by romeokienzler** [jupyterlab/jupyterlab-git#1111]
## Is your feature request related to a problem? Please describe.
Untracked files appear in the left sidebar, but need to be deleted one by one (3 clicks per file)

## Describe the solution you'd like
Select 1-n files and delete them all with a single key e.g. Del - key - add a checkbox to prevent confirmation for the next time

## Describe alternatives you've considered
Doing it the UX unfriendly way as mentioned above

## Additional context

- Python package version: 0.34.2
Name: jupyterlab-git
Version: 0.34.2
Summary: A JupyterLab extension for version control using git
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: 
License: BSD-3-Clause
Location: /home/romeokienzler/gitco/new_horizons/elyra/venv/lib/python3.9/site-packages
Requires: jupyter-server, nbdime, nbformat, packaging, pexpect
Required-by: elyra

- Extension version:
upyterLab v3.2.8
/home/romeokienzler/gitco/new_horizons/elyra/venv/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.1 enabled OK
        @krassowski/jupyterlab-lsp v3.10.0 enabled OK (python, jupyterlab-lsp)
        @jupyterlab/git v0.34.2 enabled OK (python, jupyterlab-git)
        @jupyter-server/resource-usage v0.6.1 enabled OK (python, jupyter-resource-usage)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/romeokienzler/gitco/new_horizons/elyra/venv/share/jupyter/lab
        @elyra/code-snippet-extension v3.5.2 enabled OK
        @elyra/metadata-extension v3.5.2 enabled OK
        @elyra/pipeline-editor-extension v3.5.2 enabled OK
        @elyra/python-editor-extension v3.5.2 enabled OK
        @elyra/r-editor-extension v3.5.2 enabled OK
        @elyra/theme-extension v3.5.2 enabled OK
        @voila-dashboards/jupyterlab-preview v2.1.1 enabled OK

Disabled extensions:
    @jupyterlab/launcher-extension (all plugins)

Build recommended, please run `jupyter lab build`:
    @voila-dashboards/jupyterlab-preview needs to be included in build
- Git version:
git version 2.27.0
- Operating System and its version:
Red Hat Enterprise Linux release 8.5 (Ootpa)

**Comment by fcollonval** [comment]
Thanks for the suggestion @romeokienzler 

Xref: https://github.com/jupyterlab/jupyterlab-git/issues/379

**Comment by fcollonval** [comment]
Closing as fixed by  #1136
