### ISSUE TITLE
Trim whitespace around git clone path

### ISSUE THREAD

**Issue by dudash** [jupyterlab/jupyterlab-git#1121]
### Summary
If someone cuts and pastes a url that has whitespace in front of it the clone operation fails (extra spaces is pretty common if following along with a blog tutorial).

### Details
There will be a little error box in the bottom right and if you show the details you will see something like:
`Cloning into 'metrobus-repairs-nlp-workshop'... fatal: protocol ' https' is not supported`

### Fix
To fix, I think it's as simple as `trim()` - I think that might go here:
https://github.com/jupyterlab/jupyterlab-git/blob/9df356280b544b8f0e2236ef0757d57a6239ca7c/src/commandsAndMenu.tsx#L310

**Comment by fcollonval** [comment]
Hey @dudash 

Thanks for reaching out. Do you want to push a PR for this?

A better place for the trim will be there:

https://github.com/jupyterlab/jupyterlab-git/blob/9df356280b544b8f0e2236ef0757d57a6239ca7c/src/widgets/GitCloneForm.ts#L20

**Comment by dudash** [comment]
sure, I can change and put in a PR
