### ISSUE TITLE
Failed to load the jupyterlab-git  on z2jh

### ISSUE THREAD

**Issue by direxe** [jupyterlab/jupyterlab-git#1127]
## Description

<can not be inttalled propoly on z2jh>
try to install jupyterlab-git  extension on z2jh  https://zero-to-jupyterhub.readthedocs.io
I always get this information: 

Failed to load the jupyterlab-git server extension
Git server extension is unavailable. Please ensure you have installed the JupyterLab Git server extension by running: pip install --upgrade jupyterlab-git. To confirm that the server extension is installed, run: jupyter server extension list.

## Reproduce

1. Install jupterlab with z2jh  using helm ( https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html#initialize-a-helm-chart-configuration-file)
2.  pip install --upgrade jupyterlab jupyterlab-git
3. 5. See error 'Failed to load the jupyterlab-git server extension.'

## Expected behavior
install this extension properly

## Context
- Python package version:
jupyterlab-git            0.37.1             pyhd8ed1ab_0    conda-forge
- Extension version:

JupyterLab v3.4.2
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyter-matplotlib v0.11.1 enabled OK
        @jupyterlab/git v0.37.1 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab

- Git version:
git version 2.25.1

- Operating System and its version:
cat /etc/issue
Ubuntu 20.04.4 LTS \n \l

<details><summary>Command Line Output</summary>
<pre>
jupyter lab --debug

[D 2022-05-25 08:43:03.567 ServerApp] Searching ['/home/jovyan/jupyterlab-git', '/home/jovyan/.jupyter', '/home/jovyan/.local/etc/jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2022-05-25 08:43:03.567 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2022-05-25 08:43:03.567 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2022-05-25 08:43:03.567 ServerApp] Looking for jupyter_config in /opt/conda/etc/jupyter
[D 2022-05-25 08:43:03.567 ServerApp] Looking for jupyter_config in /home/jovyan/.local/etc/jupyter
[D 2022-05-25 08:43:03.567 ServerApp] Looking for jupyter_config in /home/jovyan/.jupyter
[D 2022-05-25 08:43:03.568 ServerApp] Looking for jupyter_config in /home/jovyan/jupyterlab-git
[D 2022-05-25 08:43:03.569 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2022-05-25 08:43:03.570 ServerApp] Loaded config file: /etc/jupyter/jupyter_server_config.py
[D 2022-05-25 08:43:03.570 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2022-05-25 08:43:03.570 ServerApp] Looking for jupyter_server_config in /opt/conda/etc/jupyter
[D 2022-05-25 08:43:03.570 ServerApp] Looking for jupyter_server_config in /home/jovyan/.local/etc/jupyter
[D 2022-05-25 08:43:03.570 ServerApp] Looking for jupyter_server_config in /home/jovyan/.jupyter
[D 2022-05-25 08:43:03.570 ServerApp] Looking for jupyter_server_config in /home/jovyan/jupyterlab-git
[D 2022-05-25 08:43:03.574 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2022-05-25 08:43:03.575 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2022-05-25 08:43:03.575 ServerApp] Paths used for configuration of jupyter_server_config: 
        /opt/conda/etc/jupyter/jupyter_server_config.d/jupyter_server_mathjax.json
        /opt/conda/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /opt/conda/etc/jupyter/jupyter_server_config.d/jupyterlab_git.json
        /opt/conda/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /opt/conda/etc/jupyter/jupyter_server_config.d/nbdime.json
        /opt/conda/etc/jupyter/jupyter_server_config.d/notebook_shim.json
        /opt/conda/etc/jupyter/jupyter_server_config.json
[D 2022-05-25 08:43:03.576 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/jovyan/.local/etc/jupyter/jupyter_server_config.json
[D 2022-05-25 08:43:03.577 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/jovyan/.jupyter/jupyter_server_config.json
[D 2022-05-25 08:43:03.577 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/jovyan/jupyterlab-git/jupyter_server_config.json
[D 2022-05-25 08:43:03.618 MathJaxExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'ip': '0.0.0.0', 'port': 8888, 'open_browser': False, 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_server_mathjax': True, 'jupyterlab_git': True, 'nbclassic': True, 'nbdime': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}, 'FileContentsManager': {'delete_to_trash': False}}
[D 2022-05-25 08:43:03.620 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'ip': '0.0.0.0', 'port': 8888, 'open_browser': False, 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyterlab_git': True, 'nbclassic': True, 'nbdime': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}, 'FileContentsManager': {'delete_to_trash': False}}
[I 2022-05-25 08:43:03.621 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[D 2022-05-25 08:43:03.641 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'ip': '0.0.0.0', 'port': 8888, 'open_browser': False, 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyterlab_git': True, 'nbclassic': True, 'nbdime': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}, 'FileContentsManager': {'delete_to_trash': False}}
[I 2022-05-25 08:43:03.643 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-05-25 08:43:03.644 ServerApp] jupyterlab_git | extension was successfully linked.
[W 2022-05-25 08:43:03.649 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-25 08:43:03.649 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-05-25 08:43:03.649 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[D 2022-05-25 08:43:03.659 NotebookApp] Config changed: {'NotebookApp': {'open_browser': False}, 'ServerApp': {'ip': '0.0.0.0', 'port': 8888, 'log_level': 'DEBUG', 'open_browser': False, 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyterlab_git': True, 'nbclassic': True, 'nbdime': True, 'notebook_shim': True}>}, 'FileContentsManager': {'delete_to_trash': False}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-05-25 08:43:03.661 ServerApp] nbclassic | extension was successfully linked.
[I 2022-05-25 08:43:03.661 ServerApp] nbdime | extension was successfully linked.
[I 2022-05-25 08:43:03.663 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[D 2022-05-25 08:43:04.005 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/jovyan/.jupyter/jupyter_notebook_config.json
[D 2022-05-25 08:43:04.006 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 2022-05-25 08:43:04.006 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2022-05-25 08:43:04.007 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab_git.json
        /opt/conda/etc/jupyter/jupyter_notebook_config.d/nbdime.json
        /opt/conda/etc/jupyter/jupyter_notebook_config.json
[D 2022-05-25 08:43:04.008 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/jovyan/.local/etc/jupyter/jupyter_notebook_config.json
[D 2022-05-25 08:43:04.008 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/jovyan/.jupyter/jupyter_notebook_config.json
[I 2022-05-25 08:43:04.008 ServerApp] notebook_shim | extension was successfully linked.
[D 2022-05-25 08:43:04.010 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'FileContentsManager': {'delete_to_trash': False}, 'NotebookApp': {'open_browser': False}, 'ServerApp': {'ip': '0.0.0.0', 'port': 8888, 'log_level': 'DEBUG', 'open_browser': False, 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyterlab_git': True, 'nbclassic': True, 'nbdime': True, 'notebook_shim': True}>}}
[I 2022-05-25 08:43:04.035 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-05-25 08:43:04.037 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2022-05-25 08:43:04.039 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2022-05-25 08:43:04.039 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-05-25 08:43:04.054 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-05-25 08:43:04.061 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2022-05-25 08:43:04.065 ServerApp] nbclassic | extension was successfully loaded.
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[D 2022-05-25 08:43:04.180 ServerApp] Using default logger
[I 2022-05-25 08:43:04.183 ServerApp] nbdime | extension was successfully loaded.
[I 2022-05-25 08:43:04.183 ServerApp] The port 8888 is already in use, trying another port.
[I 2022-05-25 08:43:04.184 ServerApp] Serving notebooks from local directory: /home/jovyan/jupyterlab-git
[I 2022-05-25 08:43:04.184 ServerApp] Jupyter Server 1.17.0 is running at:
[I 2022-05-25 08:43:04.184 ServerApp] http://jupyter-test4:8889/lab?token=c57e594215655b04298cac523d56ad4e27f4f113e73ff11d
[I 2022-05-25 08:43:04.184 ServerApp]  or http://127.0.0.1:8889/lab?token=c57e594215655b04298cac523d56ad4e27f4f113e73ff11d
[I 2022-05-25 08:43:04.184 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-05-25 08:43:04.188 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-3664-open.html
    Or copy and paste one of these URLs:
        http://jupyter-test4:8889/lab?token=c57e594215655b04298cac523d56ad4e27f4f113e73ff11d
     or http://127.0.0.1:8889/lab?token=c57e594215655b04298cac523d56ad4e27f4f113e73ff11d
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

jupyter labextension list
JupyterLab v3.4.2
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyter-matplotlib v0.11.1 enabled OK
        @jupyterlab/git v0.37.1 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab

**Comment by momomobinx** [comment]
兄弟解决了吗

**Comment by Alephant6** [comment]
I have this problem too

**Comment by momomobinx** [comment]
> I have this problem too

restart jupyter

**Comment by direxe** [comment]
Hi,all. I solve this problem in a tricky way.  The only thing I have done is I put this extension into the dockfile and everything works properly. Now I close this issue

**Comment by direxe** [comment]
Hi,all. I solve this problem in a tricky way. The only thing I have done is I put this extension into the dockfile and everything works properly. Now I close this issue
