### ISSUE TITLE
Binder: Failed to init notebook diff view: InternalError: too much recursion 

### ISSUE THREAD

**Issue by emirkmo** [jupyterlab/jupyterlab-git#1137]
## Description

When viewing the diff between 2 different version of the demo notebook on Binder (after making some changes, staging, and committing), the diff viewer opens for a second before automatically closing and gives an InternalError: too much recursion.

## Reproduce

1. Press on the demo link for Binder on the github page (from README).
2. Make some trivial changes to a cell in `demo.ipynb`, run it, then save.
3. Stage changes, commit, enter commit title and name and email (can be arbitrary).
4. Go to (commit) history view.
5. Select tje previous version of the demo notebook, and click on view diff (with respect to current version).
6. The diff file loads for a second, shows briefly, but then is force closed.

## Expected behavior

The diff file should not close until closed by the user, or should be open for longer.

## Context

- Python package version:
Binder demo version
- Extension version:
Binder demo version
- Git version:
Binder demo version
- Operating System and its version:
Ubuntu 21.10 (irrelevant, web browser important)
 - **Browser**:
 Firefox 101.0.1 (64-bit; Mozilla Firefox Snap for Ubuntu canocial-002 - 1.0)

<details><summary>Web Browser Output</summary>
<pre>
Failed to init notebook diff view: InternalError: too much recursion [742.a09f65fa79d4f0b995e8.js:1:89857](https://hub-binder.mybinder.ovh/user/jupyterlab-jupyterlab-git-9fgmwnmv/lab/extensions/@jupyterlab/git/static/742.a09f65fa79d4f0b995e8.js?v=a09f65fa79d4f0b995e8)
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks @emirkmo for reporting 

I can confirm this is happening on Binder for notebook and text files. Did you encountered such trouble locally - I cannot reproduce it on my computer?

> The browser console message is not related.

**Comment by emirkmo** [comment]
I think this is a binder issue, I cannot locally reproduce

**Comment by fcollonval** [comment]
Ok I think it is related to the not yet release feature: https://github.com/jupyterlab/jupyterlab-git/pull/1132
