### ISSUE TITLE
Load Diff Model Error (Cannot read properties of undefined (reading 'widgets')) when trying to resolve merge conflict

### ISSUE THREAD

**Issue by DeanLight** [jupyterlab/jupyterlab-git#1147]
## Description

When trying to solve a merge conflict using jupyter lab with jupyterlab-git installed,
I cant open the conflict resolution window and i get this message

![image](https://user-images.githubusercontent.com/12111030/179398805-5a9f468b-abc3-408e-9efd-88d465d3ef69.png)

Looking at the logs i see the following
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/12111030/179398743-1e2c44cc-dd86-4352-855d-8ce20b9620f5.png">

I do indeed dont have cell ids on my notebooks since i cleaned it using a notebook cleaning tool.
I think that instead of deleting `cell["id"]` we should check if it exists and only delete it if it exists.

## Expected behavior

See the conflict resolution window

## Context

- Python package version:
0.37.1
- Extension version:
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2022-07-17 15:44:50.232 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.4.3
/Users/dean/miniconda3/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.1 enabled OK
        @jupyterlab/git v0.37.1 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /Users/dean/miniconda3/share/jupyter/lab
- Git version:
git version 2.34.0
- Operating System and its version:
Mac OS

**Comment by DeanLight** [comment]
I tried running a local install of the current main branch and changed
line 383 in `git.py` to 
```python
cell.pop("id",None)
```
and it solved the problem

**Comment by fcollonval** [comment]
@DeanLight thanks for reporting and providing a fix. Would you mind opening a pull request with your fix?

**Comment by DeanLight** [comment]
sure thing, here you go
