### ISSUE TITLE
Add "Hide Output Cells" to diff screen

### ISSUE THREAD

**Issue by maxima120** [jupyterlab/jupyterlab-git#1167]
I have fairly long notebooks. If I look at the diff

![image](https://user-images.githubusercontent.com/10121753/191238274-e8f47e2c-866d-4fd7-a7b7-4b458dda9474.png)

it generates a very long document where 99% of changes are in the output. Use case: you change 2-3 lines of code with hyperparameters which generates different output but you only are interested to see diff in code which is a few lines.

I would like to have a checkbox (similar to "Hide Unchanged Cells") which would hide output cells

- Python package version:
Name: jupyterlab-git
Version: 0.39.2

- Extension version:
@jupyterlab/git v0.39.2 enabled OK (python, jupyterlab-git)

- Git version:
git version 2.34.1

- Operating System and its version:
Ubuntu 22.04

**Comment by fcollonval** [comment]
Thanks for the proposal @maxima120 

The diff view you are mentioning is actually provided by a dependency of this extension called `nbdime`. Would you mind opening an issue [there](https://github.com/jupyter/nbdime/issues)?
