### ISSUE TITLE
File Load Error for .gitignore

### ISSUE THREAD

**Issue by Lagroth** [jupyterlab/jupyterlab-git#1168]
## Description

The jupyterlab-git extension is telling me it can't find the .gitignore file even though I can see it and it can interact with it.

## Reproduce
When I use the Git menu to view .gitignore 
![image](https://user-images.githubusercontent.com/4657788/192134863-f16ed54a-4b23-4a4e-bffd-738e5978ef27.png)

or try and right click on a file and add to .git ignore 
![image](https://user-images.githubusercontent.com/4657788/192134912-65abbdec-f761-45a9-b8b7-70cce8cbe227.png)

I get the following error ![image](https://user-images.githubusercontent.com/4657788/192134686-eb3b308d-3fdc-464c-9b56-7b41d32be030.png)

My .gitignore is at ~/Jupyterlab/.gitignore. 

When I right click on a file to add it to .gitignore it does actually get added even though the error message is displayed.

## Expected behavior

I expected the .gitignore file to open up in the terminal (or text editor) to be edited

## Context

- Python package version:
Name: jupyterlab-git
Version: 0.39.2
Summary: A JupyterLab extension for version control using git
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: 
License: BSD-3-Clause
Location: /opt/conda/lib/python3.10/site-packages
Requires: jupyter-server, nbdime, nbformat, packaging, pexpect, traitlets
Required-by:

- Extension version:
JupyterLab v3.4.3
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyterlab-tabular-data-editor v1.0.0 enabled OK (python, jupyterlab-tabular-data-editor)
        jupyter-matplotlib v0.11.1 enabled OK
        @jupyterlab/git v0.39.2 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
- Git version:
git version 2.25.1
- Operating System and its version:
running in docker container jupyter/scipy-notebook:latest
from https://hub.docker.com/r/jupyter/scipy-notebook
<details><summary>Command Line Output</summary>
<pre>
I'm not confident on how to do this in docker. If you need it I will look up how to access the terminal inside the docker container and run this
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
There is a wall of output here. Again if needed I will work out how to trawl through and find what is relevant.
</pre>
</details>

**Comment by fcollonval** [comment]
@Lagroth would you mind providing the server log - best is even to run the server with the flag `--debug`. And report here the log (focusing only on the action failing)?

Is the file `~/JupyterLab/.gitignore` accessible from JupyterLab? Aka in which folder are you executing the server?
This is important because if you run the server in `~/JupyterLab/myProject`. Then for security reason you are not authorize to open file above that directory within JupyterLab.

**Comment by Lagroth** [comment]
Thank you very much for your time. If I can do any more leg work to make this easier please let me know. Apologies if some of the answers are wordy I know enough to get myself in deep, but not to provide concise answers.

> Is the file `~/JupyterLab/.gitignore` accessible from JupyterLab? Aka in which folder are you executing the server?
> This is important because if you run the server in `~/JupyterLab/myProject`. Then for security reason you are not authorize to open file above that directory within JupyterLab.

The folder listed as '\~/' in Jupyterlab is the home-folder of the user account running the server and is set as the working folder of the server. The "~/Jupyterlab" folder is the folder that I have cloned the repository into, is within the home-folder of the user (and so I think has the right access controls) and contains the .gitignore file. I can use the terminal in the Jupyterlab webpage to create files in that folder and edit the .gitignore file
![image](https://user-images.githubusercontent.com/4657788/192258674-624feee6-0c07-4f87-a84d-ad942fcce479.png)
This is the terminal output of the access controls.
<pre>
jovyan@74dcb98d022f:~/JupyterLab$ ls ./.gitignore -al
-rw-r--r-- 1 jovyan users 40 Sep 25 09:11 ./.gitignore
</pre>


> @Lagroth would you mind providing the server log - best is even to run the server with the flag `--debug`. And report here the log (focusing only on the action failing)?

From the logs using the command _docker-compose logs -f -t_. I have not worked out how to add the debug setting to my docker container I will look into it.
<pre>
jupyter_1  | 2022-09-26T10:43:08.594502165Z Entered start.sh with args: jupyter lab
jupyter_1  | 2022-09-26T10:43:08.648147028Z Executing the command: jupyter lab
jupyter_1  | 2022-09-26T10:43:17.984006349Z [I 2022-09-26 10:43:17.982 ServerApp] jupyter_server_mathjax | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:18.099994144Z [I 2022-09-26 10:43:18.099 ServerApp] jupyterlab | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:18.102094079Z [I 2022-09-26 10:43:18.100 ServerApp] jupyterlab_git | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:18.138477751Z [W 2022-09-26 10:43:18.137 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
jupyter_1  | 2022-09-26T10:43:18.138985820Z [W 2022-09-26 10:43:18.138 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
jupyter_1  | 2022-09-26T10:43:18.139964200Z [W 2022-09-26 10:43:18.139 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
jupyter_1  | 2022-09-26T10:43:18.206699135Z [I 2022-09-26 10:43:18.205 ServerApp] nbclassic | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:18.208019908Z [I 2022-09-26 10:43:18.207 ServerApp] nbdime | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:20.070848289Z [I 2022-09-26 10:43:20.070 ServerApp] notebook_shim | extension was successfully linked.
jupyter_1  | 2022-09-26T10:43:20.225534742Z [I 2022-09-26 10:43:20.224 ServerApp] notebook_shim | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.233377087Z [I 2022-09-26 10:43:20.232 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.242806975Z [I 2022-09-26 10:43:20.242 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
jupyter_1  | 2022-09-26T10:43:20.244722848Z [I 2022-09-26 10:43:20.242 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
jupyter_1  | 2022-09-26T10:43:20.278621536Z [I 2022-09-26 10:43:20.277 ServerApp] jupyterlab | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.332864156Z [I 2022-09-26 10:43:20.331 ServerApp] jupyterlab_git | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.367430027Z [I 2022-09-26 10:43:20.366 ServerApp] nbclassic | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.772349297Z [I 2022-09-26 10:43:20.771 ServerApp] nbdime | extension was successfully loaded.
jupyter_1  | 2022-09-26T10:43:20.776098596Z [I 2022-09-26 10:43:20.775 ServerApp] Serving notebooks from local directory: /home/jovyan
jupyter_1  | 2022-09-26T10:43:20.776860727Z [I 2022-09-26 10:43:20.776 ServerApp] Jupyter Server 1.17.1 is running at:
jupyter_1  | 2022-09-26T10:43:20.777985407Z [I 2022-09-26 10:43:20.776 ServerApp] http://74dcb98d022f:8888/lab?token=...
jupyter_1  | 2022-09-26T10:43:20.779038056Z [I 2022-09-26 10:43:20.778 ServerApp]  or http://127.0.0.1:8888/lab?token=...
jupyter_1  | 2022-09-26T10:43:20.780573567Z [I 2022-09-26 10:43:20.779 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jupyter_1  | 2022-09-26T10:43:33.616665110Z [I 2022-09-26 10:43:33.615 LabApp] Build is up to date
jupyter_1  | 2022-09-26T10:43:34.047144685Z [W 2022-09-26 10:43:34.046 ServerApp] Notebook JupyterLab/Dev - BudgetStats.ipynb is not trusted
jupyter_1  | 2022-09-26T10:43:34.657354978Z [I 2022-09-26 10:43:34.656 ServerApp] Kernel started: 83b3b665-6a4e-428e-aee8-d2d3d9fc4530
jupyter_1  | 2022-09-26T10:43:34.687445618Z [I 2022-09-26 10:43:34.686 ServerApp] Kernel started: 75a2d883-a6e2-4ccf-bec0-d9042bfd48a1
jupyter_1  | 2022-09-26T10:43:42.182056625Z [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
jupyter_1  | 2022-09-26T10:43:42.228200391Z [IPKernelApp] WARNING | No such comm: 4caab8dd-b697-439e-94e2-2c9b23a2b2d1
jupyter_1  | 2022-09-26T10:43:42.483872808Z [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
jupyter_1  | 2022-09-26T10:43:42.514780474Z [IPKernelApp] WARNING | No such comm: d4f01892-120c-488d-81a8-fc2fe9a33d7d
jupyter_1  | 2022-09-26T10:43:45.765084878Z [W 2022-09-26 10:43:45.764 ServerApp] 404 GET /api/contents/JupyterLab/.gitignore?type=file&content=1&format=text&1664189028485 (192.168.1.211): file or directory '/JupyterLab/.gitignore' does not exist
jupyter_1  | 2022-09-26T10:43:45.767460435Z [W 2022-09-26 10:43:45.766 ServerApp] file or directory '/JupyterLab/.gitignore' does not exist
jupyter_1  | 2022-09-26T10:43:45.771005413Z [W 2022-09-26 10:43:45.770 ServerApp] 404 GET /api/contents/JupyterLab/.gitignore?type=file&content=1&format=text&1664189028485 (192.168.1.211) 11.01ms referer=http://192.168.1.251:8888/lab
</pre>

**Comment by krassowski** [comment]
I can reproduce it with the latest jupyter-server. It works again if you start jupyterlab with `--ContentsManager.allow_hidden=True`. It is another piece of fallout from the security hardening of jupyter-server aimed at preventing access to hidden files by default.

**Comment by krassowski** [comment]
For LSP I proposed a contents manager addition that would selectively allow access to filesystem outside of JupyterLab root (https://github.com/jupyter-lsp/jupyterlab-lsp/issues/850); in the same manner we could selectively allow-list some hidden files like `.gitignore`, though this could be misleading for the user. IMO the core of the problem is that users expect hidden files (like `.gitignore`) to _just work_ as it just works in other IDEs and the UI does not tell them how to switch it on and gives very misleading errors if they try to access hidden files when the access is not allowed.

**Comment by fcollonval** [comment]
Thanks for looking into this @krassowski 

I agree that the story around hidden file is clumsy.

For now I would suggest to tackle this issue, 

1. Sending the server capability to the frontend, that could be part of the following request

https://github.com/jupyterlab/jupyterlab-git/blob/8b791016ef29c24a3ac2c78a1eb97fd19998f0a9/src/index.ts#L95

2. According the capability, open or not the `.gitignore` file.
3. If the user trigger the menu _Open .gitignore File_, display a dialog explaining how to turn on hidden files on the server if it is off.

> It may be good to discuss the default behavior on the server side. I think a better way of dealing with hidden files is a pure UI settings like we have in OS to show/hide hidden files.

**Comment by fcollonval** [comment]
Fix by #1273
