### ISSUE TITLE
logger inaccessible externally.

### ISSUE THREAD

**Issue by Reginald-King** [jupyterlab/jupyterlab-git#1171]
## Description

I disabled the cloneCommand Plugin to replace it with my own UI to handle cloning, as was intended here: https://github.com/jupyterlab/jupyterlab-git/pull/1051 However, the logger instance used to log the cloning opperation's progress is inaccessible. Since it's an instance, not a class, the one I access in '@jupyterlab/git/lib/logger' is not the same, but another instance of the Logger class. I tested in my workplace and in a sterile environment using cookiecutter, the issue remains. can you make the logger instance (Which sends a signal to the feedback component for the MUI snack-bar to pup-up and show the messages it sends) accessible externally? or change the Feedback component to use any Logger? The cloning operations do not show progress otherwise.

logger I am referring to is defined here:
https://github.com/jupyterlab/jupyterlab-git/blob/master/src/logger.ts

Feedback component here:
https://github.com/jupyterlab/jupyterlab-git/blob/master/src/components/Feedback.tsx

Image of pop-up I'm referring to, defined in the Alert class component:
![image](https://user-images.githubusercontent.com/110697951/192867146-7388a638-dfe6-4b03-bcdc-3329a1c3b463.png)

## Reproduce

1. add below to "jupyterlab" section of package.json:
`"disabledExtensions": [
      "@jupyterlab/git:clone"
  ]` 
2. Make a new cloneCommand plugin based on the old one
3. import logger from '@jupyterlab/git/lib/logger'
4. See no pop-up from MUI snack-bar.

## Expected behavior

I should be able to access the same logger instance used by the cloneCommand Plugin.
## Context

- Python package version: tried 0.39.2 && 0.34.2

- Extension version:  3.3.2

- Git version: 2.8.1

- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for the report @Reginald-King 

Would you mind opening a PR for this? I would go for exporting both `logger` and `LoggerContext` in `index.ts`:

https://github.com/jupyterlab/jupyterlab-git/blob/8b791016ef29c24a3ac2c78a1eb97fd19998f0a9/src/logger.ts#L35-L40

> Comment for the future: a notification system will come to JupyterLab core - https://github.com/jupyterlab/jupyterlab/pull/12959

**Comment by Reginald-King** [comment]
Thank you very much for getting back to me. I'll work on making that PR 🌊

**Comment by Reginald-King** [comment]
made a PR here: https://github.com/jupyterlab/jupyterlab-git/pull/1172
