### ISSUE TITLE
Passwords no longer accepted by GitHub for pushing to https repos

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab-git#1176]
## Description

When I try to push from a Git repo cloned with `https` I see this box:

![image](https://user-images.githubusercontent.com/4560057/193834765-09962098-63e2-4606-a4ca-52483d85bf39.png)

While it says that I could enter my password, this is no longer supported by GitHub and if I do so I am shown this error message:

![image](https://user-images.githubusercontent.com/4560057/193835025-43194160-fbe8-4160-98e0-b18706581195.png)

## Reproduce

Clone a repo via https, change something and commit it, try to push

## Expected behavior

Only mention PAT and include a link to https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls or https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

## Context

- Extension version: 0.37.1

**Comment by fcollonval** [comment]
Thanks for reporting @joelostblom 

The difficulty here is that this is specific to GitHub and the extension is used with other platforms.

**Comment by joelostblom** [comment]
Yeah that makes sense. Maybe the extension could fill the placeholder text dynamically depending on the url of the first remote it finds in the repo? But I understand if that is too complicated for a small feature.

**Comment by fcollonval** [comment]
@joelostblom feel free to push a PR to deal with `github.com`. I don't see another way here.

**Comment by shawnesquivel** [comment]
I was able to reproduce the bug when using my password. According to the link mentioned in the error message, only the personal access token [2] should be used.

The reasoning is mentioned as below: 
"Password-based authentication for Git has been removed in favor of more secure authentication methods" [1]

[1] https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls
[2] https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

My recommendation is to remove the "password" from the password placeholder text as it is not supported. When using my PAT token, it successfully works.

![image](https://user-images.githubusercontent.com/94336773/217651476-0a663be9-2315-4877-a359-6ca1dcddd28c.png)

**Comment by shawnesquivel** [comment]
@joelostblom are you still having this issue? I tried reproducing the bug today by cloning a repository using https, making a commit, and pushing with @jupyterlab/git v0.41.0. 

it successfully pushes and i'm not prompted to enter my password. unfortunately there are no console logs so it's difficult to say why it's working now.

@fcollonval any tips on how to navigate this if I can no longer reproduce the bug with the latest version, should I attempt to fix it in v0.37.0?

**Comment by fcollonval** [comment]
@shawnesquivel a way to reproduce it without actually having to deal with git command is to temporary modify the Python code to emulate an authentication error.
For example, for the clone action, you could replace the following:

https://github.com/jupyterlab/jupyterlab-git/blob/c7e7363a5e749ea4590984f3a0303694f25212aa/jupyterlab_git/handlers.py#L91-L102

by 

```py
self.set_status(500)
self.finish(json.dumps({"code": 128, "message": "Invalid username or password"}))
```

**Comment by shawnesquivel** [comment]
I changed my handlers.py class GitPushHandler to be the following (see EDIT comments):

However, it looks like I can still push.

I also tried `git config --global --unset credential.helper`. I'm still able to push without prompting the dialog box. Not sure if I'm making the error throw properly?

```
class GitPushHandler(GitHandler):
    """
    Handler for 'git push <first-branch> <second-branch>.
    Pushes committed files to a remote branch.
    """

    @tornado.web.authenticated
    async def post(self, path: str = ""):
        """
        POST request handler,
        pushes committed files from your current branch to a remote branch

        Request body:
        {
            remote?: string # Remote to push to; i.e. <remote_name> or <remote_name>/<branch>
            force: boolean # Whether or not to force the push
        }
        """
        # EDIT: Force authentication error before the code runs
        self.set_status(500)    
        self.finish(json.dumps({"code": 128, "message": "Invalid username or password"}))

        console.log('push')

        local_path = self.url2localpath(path)
        data = self.get_json_body()
        known_remote = data.get("remote")
        force = data.get("force", False)

        current_local_branch = await self.git.get_current_branch(local_path)

        set_upstream = False
        current_upstream_branch = await self.git.get_upstream_branch(
            local_path, current_local_branch
        )

        if known_remote is not None:
            set_upstream = current_upstream_branch["code"] != 0

            remote_name, _, remote_branch = known_remote.partition("/")

            current_upstream_branch = {
                "code": 0,
                "remote_branch": remote_branch or current_local_branch,
                "remote_short_name": remote_name,
            }

        if current_upstream_branch["code"] == 0:
            branch = ":".join(["HEAD", current_upstream_branch["remote_branch"]])
            response = await self.git.push(
                current_upstream_branch["remote_short_name"],
                branch,
                local_path,
                data.get("auth", None),
                set_upstream,
                force,
            )

        else:
            # Allow users to specify upstream through their configuration
            # https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault
            # Or use the remote defined if only one remote exists
            config = await self.git.config(local_path)
            config_options = config["options"]
            list_remotes = await self.git.remote_show(local_path)
            remotes = list_remotes.get("remotes", list())
            push_default = config_options.get("remote.pushdefault")

            default_remote = None
            if push_default is not None and push_default in remotes:
                default_remote = push_default
            elif len(remotes) == 1:
                default_remote = remotes[0]

            if default_remote is not None:
                response = await self.git.push(
                    default_remote,
                    current_local_branch,
                    local_path,
                    data.get("auth", None),
                    set_upstream=True,
                    force=force,
                )
            else:
                response = {
                    "code": 128,
                    "message": "fatal: The current branch {} has no upstream branch.".format(
                        current_local_branch
                    ),
                    "remotes": remotes,  # Returns the list of known remotes
                }

        # EDIT: Force authentication at the end too      
        self.set_status(500)
        self.finish(json.dumps({"code": 128, "message": "Invalid username or password"}))


```
