### ISSUE TITLE
Clone git submodules

### ISSUE THREAD

**Issue by seignovert** [jupyterlab/jupyterlab-git#1187]
Feature request
----------------
At the moment, `jupyterlab-git` plugin is able to clone git repository in a JupyterLab environment in a very convenient way.
Unfortunately for git repo that have [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) only the parent is cloned and you get empty folders on the submodules.

Would it possible to add the `--recurse-submodules` flag by default when the project is cloned:
```
git clone --recurse-submodules my_repo_url
```
(or to add an optional recursive check box on the clone window)

Current workaround
--------------------
It is possible to pull the submodules after the clone with this command:
```
git submodule update --init --recursive
```
But it requires an additional step from the user (and do it at the right location…)

**Comment by fcollonval** [comment]
Thanks @seignovert for the suggestion. Would you be willing to create a pull request for this?

The line to change is:

https://github.com/jupyterlab/jupyterlab-git/blob/da6ed22f718ead0cc292a70c4e3dd3fbc2563493/jupyterlab_git/git.py#L287

**Comment by seignovert** [comment]
@fcollonval thanks for your feedback. I will try to do a PR.
