### ISSUE TITLE
Files do not open from side panel if lab started from subdirectory of git

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#1205]
## Description

When working on jupyterlab repo if I start jupyterlab from `packages` sub-directory and try to open a modified file from the git sidebar it shows:

```
Uncaught (in promise) Error: No such file or directory: packages/completer/style/base.css
```

The path here is wrong: it starts at the git root, but it should be relative to jupyterlab root.

## Context

- Python package version: 0.41.0
- Extension version: `@jupyterlab/git v0.41.0 enabled OK (python, jupyterlab-git)`
- Git version: 2.37.2
- Operating System and its version: Ubuntu, latest

**Comment by fcollonval** [comment]
That case is really tricky. I think the only correct behavior we should accept is denying the folder as being a git repository.

The reason is that otherwise we do not respect the security rule of not accessing files upper than the server root directory.

**Comment by Zxun2** [comment]
Is there a way i can reproduce this, given the current version?
