### ISSUE TITLE
The "add" (stage changes) button of last entry runs away 

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#1210]
When you try to click the + button on the last entry with mouse it sometimes shifts away because scrollbar appears which makes clicking it difficult:

![cannot-click](https://user-images.githubusercontent.com/5832902/214081552-0b923b26-4593-41a3-94f7-b735120bcd3b.gif)

**Comment by drush0** [comment]
Seeing the same after upgrading to 0.41.0 and JupyterLab 3.5.3
