### ISSUE TITLE
Feature Request: Git commands in the command palette

### ISSUE THREAD

**Issue by cezarymierzejek** [jupyterlab/jupyterlab-git#1238]
## Is your feature request related to a problem? Please describe.

Often when working with a notebook or script, I use the command palette (ctrl + shift + c) for quick operations on my files or interact with the interface. However none of the git commands are available in the palette. 

## Describe the solution you'd like

It would be great if common git operations (e.g., clone, commit, push, etc) could be exposed in the command palette. VS Code has a good implementation of this. 

In VS Code you can open the command palette, type Git, and you have a drop down of operations available: 

![git_screenshot](https://user-images.githubusercontent.com/20960805/234881301-100c6725-ff22-40a7-8540-8a9c96278ffb.png)

## Describe alternatives you've considered

Right now I use a mix of the current JupyterLab git interface and VS Code but this would increase the amount of time I stay in JupyterLab. 

## Additional context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

**Comment by fcollonval** [comment]
Thanks for the suggestion @cezarymierzejek

would you be willing to contribute by opening a PR? I can provide some pointers to add this feature.

**Comment by tsabbir96** [comment]
Hey @fcollonval, in case @cezarymierzejek isn't available to work on this, can I pick it up? Is that okay with you guys?

**Comment by fcollonval** [comment]
Sure @tsabbir96 don't hesitate to open a PR.

**Comment by tsabbir96** [comment]
@fcollonval Thanks, too excited!! Could you give me a headstart on exactly where I should be implementing this?

**Comment by fcollonval** [comment]
Sure, I advice you first to understand the [command palette](https://github.com/jupyterlab/extension-examples/tree/main/command-palette) example.

Then you should figure out how to modify the extension plugin defined there:

https://github.com/jupyterlab/jupyterlab-git/blob/dda8e82b9b2751e1b2006f71cb101accef261d10/src/index.ts#L39

Using the command IDs defined there:

https://github.com/jupyterlab/jupyterlab-git/blob/dda8e82b9b2751e1b2006f71cb101accef261d10/src/tokens.ts#L1196

> I encourage you to open a PR early it will be easier for me to comment the code and provide suggestions.

**Comment by cezarymierzejek** [comment]
> Thanks for the suggestion @cezarymierzejek
> 
> would you be willing to contribute by opening a PR? I can provide some pointers to add this feature.

Hey sorry for the delay. I would say if @tsabbir96 wants to take it on then that is cool with me. 

I don't have a ton of experience working with typescript so admittedly this was going to be more of an aspirational side project for me.

**Comment by tsabbir96** [comment]
@cezarymierzejek Thank you, will be happy to see you around collaborating o things you like on this project.
@fcollonval Thank you for your help, I will explore the example and will create a PR for your review.

**Comment by tsabbir96** [comment]
Hi @fcollonval, I am so sorry for the late reply, I was really busy with my full-time job the last 3 weeks. I managed to free up this week so that I can work on this issue. 
I have forked the repo, and have set up my project for development. 
I noticed that in VS CODE there are a huge number of Git Commands. Is there any sort of plan on which commands should be given priority first?

**Comment by fcollonval** [comment]
> Is there any sort of plan on which commands should be given priority first?

The command palette is an unordered list - user are expected to typing characters to filter it.

So no priority

**Comment by tsabbir96** [comment]
@fcollonval I have opened an initial PR for the feature. #1243 . It's nowhere near yet. I have experimented by adding a single command to the palette. The extension builds successfully, but when I go to Jupyterlab to search for the newly added command in the palette, I don't find it. Is there something specific I need to do before I can find it one the palette?

**Comment by fcollonval** [comment]
Closing as done in #1243 -> Thanks to @tsabbir96
