### ISSUE TITLE
Failed to save secrets with libsecret

### ISSUE THREAD

**Issue by cointreauu** [jupyterlab/jupyterlab-git#1241]
## Description

Hello. 
I'm trying to setup jupyterlab-git in my jupyterhub. I installed jupyterhub on k8s(following the guide of [zero-to-jupyterhub-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s)).

I can use jupyterlab-git extension in user's pod but need to enter secrets every time to push, clone... etc.
So I searched how to save git user credentials, and found this issue #672 .
Following the last comment, I installed `libsecret`. However it does not seem to work properly. This is the error message when I enter my credential for clone or push. (and I'm using github enterprise version, so github url is a bit different)

```shell
[D 2023-05-03 08:44:03.623 SingleUserLabApp.jupyterlab_git git:138] Execute ['git', 'fetch', '--all', '--prune'] in /home/jovyan/airflow_dag/test2/myrepo.
[D 2023-05-03 08:44:04.103 SingleUserLabApp.jupyterlab_git git:159] Code: 0
    Output:
    Error:

    ** (process:3703): CRITICAL **: 08:44:03.945: store failed: The name org.freedesktop.secrets was not provided by any .service files

[I 2023-05-03 08:44:04.104 SingleUserLabApp log:186] 200 POST /user/myname/git/test2/myrepo/remote/fetch?1683071043593 (myname@::ffff:someip) 482.58ms


```

## Reproduce

1. Click git clone button
2. Enter my repository URL and click download the repository. then clone.
3. Clone is succeeded, but on the bottom line I can see `Git: credentials required` (and small orange dot).
4. After clicking it and I re-enter my credential. Orange dot disappeared and appeared again in a few second.

## Expected behavior

I expect my credential saved, so that I do not need to enter my credential to push or clone.

## Context

- Python package version: 0.41.0

- Extension version: @jupyterlab/git v0.41.0 enabled OK (python, jupyterlab-git)

- Git version: 2.34.1

- Operating System and its version: Ubuntu 22.04.1 LTS

<details><summary>Command Line Output</summary>
<pre>
I appended some debugging logs above.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
It looks like libsecret is not configure properly on your OS.

**Comment by cointreauu** [comment]
I found the solution finally.

Libsecret uses dbus API to communicate with gnome-keyring, so it's needed to install `libsecret-1-0`, `libsecre-1-dev`, `gnome-keyring`, and `dbus`, `dbus-x11` (on ubuntu).
Also, dbus should be launched on a session, not a service. In my case this was the problem.

At first I had launched dbus as a service and exported `DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket` as the environment variable. 
With this, it seemed libsecret does not operate properly.

When I change to launch dbus on the session it starts to work. 
For that, `DBUS_SESSION_BUS_ADDRESS` should be assigned.
Usually it can vary every time I launch, but be fixed like `unix:path=some_dir`. 
And enter the command following

```shell
# for libsecret to use dbus and gnome-keyring
dbus-daemon --session --fork --address=$DBUS_SESSION_BUS_ADDRESS > somefile
echo -n $JUPYTERHUB_USER | gnome-keyring-daemon --unlock

# for git to use libsecret
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
git config --global user.name $JUPYTERHUB_USER
```

With this, libsecret saves the git credential safely.

**Comment by fcollonval** [comment]
Thanks @cointreauu for sharing your solution.
