### ISSUE TITLE
Support for JupyterLab 4.0

### ISSUE THREAD

**Issue by adalseno** [jupyterlab/jupyterlab-git#1245]
## Is your feature request related to a problem? Please describe.
The extension (0.41) does not work with JupyterLab 4.0.0

## Describe the solution you'd like
It would be great to add support for the new version

**Comment by tarrade** [comment]
Same issue for me. I don't get more information that:

`@jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)`

Here is my setup, conda env using python 3.10.0 using the following packages from conda-forge channel
- jupyterlab=4.0.0
- ipykernel=6.23.1
- jupyter_server=2.5.0
- nb_conda_kernels=2.3.1
- jupyter_core=5.3.0
- jupyterlab_widgets=3.0.7
- ipywidgets=8.0.6
- ipyleaflet=0.17.2
- jupytext=1.14.5
- jupyterlab-git=0.41.0
- ipympl=0.9.2
- tqdm=4.64.1
- matplotlib=3.5.2

Here the full log when running `jupyter labextension list`:
```
~  jupyter labextension list
JupyterLab v4.0.0
/opt/conda/envs/jupyter-notebook/share/jupyter/labextensions
        nbdime-jupyterlab v2.2.0 enabled  X
        jupyter-matplotlib v0.11.2 enabled OK
        jupyterlab-jupytext v1.3.8+dev enabled  X (python, jupytext)
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyter-leaflet v0.17.2 enabled OK
        @jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled  X (python, jupyterlab_widgets)
   The following extensions are outdated:
        nbdime-jupyterlab
        jupyterlab-jupytext
        jupyterlab_pygments
        @jupyterlab/git
        @jupyter-widgets/jupyterlab-manager
   Consider running "jupyter labextension update --all" to check for updates.
Other labextensions (built into JupyterLab)
   app dir: /opt/conda/envs/jupyter-notebook/share/jupyter/lab
```

**Comment by JulienLrx** [comment]
Same here, no error but the extension isn't loaded.
jupyter 4 is now released, making this issue quite a bit critical in my opinion.

**Comment by klwb** [comment]
Same here
I guess 
`JupyterLab v4.0.2
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyter-matplotlib v0.11.3 enabled OK
        nbdime-jupyterlab v2.2.0 enabled  X
        @jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled  X (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments
        nbdime-jupyterlab
        @jupyterlab/git
        @jupyter-widgets/jupyterlab-manager
        
   Consider running "jupyter labextension update --all" to check for updates.

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab`

**Comment by jaffe-fly** [comment]
jupyter labextension list
```
JupyterLab v4.0.2
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.2.0 enabled OK (python, nbdime-jupyterlab)
        @jupyterlab/git v0.41.0 enabled OK (python, jupyterlab_git)
```
but no git in web UI
![image](https://github.com/jupyterlab/jupyterlab-git/assets/49515380/42eb7626-ec5c-4877-9d18-664b0715ecdd)
so ,what should i do???

**Comment by mfakaehler** [comment]
Until this issue is solved, do you think one should mention the incompatibility to JupyterLab 4.0 in the Readme?

**Comment by kerphi** [comment]
Same issue on my side, I noticed a workaround if you install jupyterlab-git AND jupyterlab-github then the jupyterlab-git plugin reapears and work again.

**Comment by kerphi** [comment]
> Same issue on my side, I noticed a workaround if you install jupyterlab-git AND jupyterlab-github then the jupyterlab-git plugin reapears and work again.

Sorry but I was wrong because when doing `pip install  jupyterlab-github`, I got an uninstallation of jupyterlab-4.0.2
```
pip install  jupyterlab-github
[...]
  Attempting uninstall: jupyterlab
    Found existing installation: jupyterlab 4.0.2
    Uninstalling jupyterlab-4.0.2:
      Successfully uninstalled jupyterlab-4.0.2
Successfully installed aiofiles-22.1.0 aiosqlite-0.19.0 jupyter-server-fileid-0.9.0 jupyter-server-ydoc-0.8.0 jupyter-ydoc-0.2.4 jupyterlab-3.6.4 jupyterlab-github-3.0.1 y-py-0.5.9 ypy-websocket-0.8.2
```

**Comment by arthuralbarelli** [comment]
Downgrade for version 3.6.3 while the it is not solverd ;)

**Comment by nibheis** [comment]
Dear jupyterlab-git team,

As mentioned above, jupyterlab 4.x has been released a few months ago now.
Summer break is almost there in the northern part of the globe and we are actively preparing the next version of our jupyterhub/lab installation and want to have profs and researchers testing it as soon as possible. Not having jupyterlab_git is a complete no-go for a migration to jupyterlab 4, so we have to know really soon.

Could anyone from the team please give us some information? Is it something that is already being worked on? Can we help in any way? Can we expect this issue to be solved soon?

Thanks!

**Comment by nibheis** [comment]
I tested the latest `jupyterlab_git 0.42.0--rc0` and it is still not functional with jupyterlab 4.x. I checked the jupyterlab logs in debug mode for anything `git` related during startup, but I could not find anything relevant other than:
`[I 2023-06-30 07:31:22.685 SingleUserLabApp manager:364] jupyterlab_git | extension was successfully loaded.`

**Comment by gmarcusm** [comment]
Installation instructions do not work at this moment. Troubleshooting does not help either. At this point, I think the instructions need to be fixed to reflect this.

I am aware of [#14590](https://github.com/jupyterlab/jupyterlab/issues/14590), nonetheless I share what I am doing (inside a clean virtual env):
`pip install jupyterlab jupyterlab-git`

enabling the extension to be sure:

`jupyter server extension enable --py jupyterlab_git`

leads to:

```
$ jupyter labextension list
<redacted>/jupyter-env/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.2.0 enabled  X
        @jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)

<redacted>/.local/share/jupyter/labextensions
        jupyter-threejs v2.4.1 enabled OK (python, pythreejs)
        jupyterlab-datawidgets v7.1.2 enabled OK
        jupyter-webrtc v0.6.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled  X (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments
        nbdime-jupyterlab
        @jupyterlab/git
        @jupyter-widgets/jupyterlab-manager
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: <redacted>/jupyter-env/share/jupyter/lab
```

going into `jupyter-env/share/jupyter/labextensions/@jupyterlab/git` shows that the package is indeed 0.41.0, so the latest. Trying with `jupyter labextension build .` in the directory leads to the following, which might help:

```
Conflicting Dependencies:
JupyterLab                  Extension        Package
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/application
>=4.1.3 <4.2.0              >=3.0.0 <4.0.0   @jupyterlab/apputils
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/codemirror
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/console
>=6.0.3 <6.1.0              >=5.0.0 <6.0.0   @jupyterlab/coreutils
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/filebrowser
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/mainmenu
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/rendermime
>=7.0.3 <7.1.0              >=6.0.0 <7.0.0   @jupyterlab/services
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/settingregistry
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/terminal
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/translation
>=4.0.3 <4.1.0              >=3.0.0 <4.0.0   @jupyterlab/ui-components
>=2.0.1 <3.0.0              >=1.12.0 <2.0.0  @lumino/commands
>=2.0.0 <3.0.0              >=1.5.3 <2.0.0   @lumino/coreutils
>=2.0.0 <3.0.0              >=1.4.3 <2.0.0   @lumino/disposable
>=2.0.0 <3.0.0              >=1.7.1 <2.0.0   @lumino/messaging
>=2.0.0 <3.0.0              >=1.3.3 <2.0.0   @lumino/polling
>=2.0.0 <3.0.0              >=1.4.3 <2.0.0   @lumino/signaling
>=2.0.1 <3.0.0              >=1.17.0 <2.0.0  @lumino/widgets
>=18.2.0 <19.0.0            >=17.0.1 <18.0.0 react
>=18.2.0 <19.0.0            >=17.0.1 <18.0.0 react-dom
```

**Comment by taugwalder** [comment]
Is there any status update? Are there any timelines planned for a new release to fix this issue?

**Comment by psychemedia** [comment]
The [`jupyterlab-github`](https://github.com/jupyterlab/jupyterlab-github) extension seems to have been updated to work with JL v4.

**Comment by taugwalder** [comment]
The problem still persists for us. Same error message, jupyterlab-git does not work and shows console errors. 


![image](https://github.com/jupyterlab/jupyterlab-git/assets/92717833/b93b84d9-25b9-450e-b587-372fb3c5cb95)

**Comment by stelios-c** [comment]
I think this would particularly affect Codespaces JupyterLab users, by default a new codespace seems to use something close to the latest version of JupyterLab.

**Comment by jankap** [comment]
> The [`jupyterlab-github`](https://github.com/jupyterlab/jupyterlab-github) extension seems to have been updated to work with JL v4.

Agreed, that one works. `jupyterlab-git` however does not. There's a red "x" and the extension does not show up. I'm using JupyterLab Version 4.0.5

**Comment by thesuperzapper** [comment]
@fcollonval, I just want to confirm if `jupyterlab-git` is still maintained and planning to support JupyterLab 4.0, as it has been out since June 2023.

**Comment by fcollonval** [comment]
A prerelease has been done and you can test it using:

```sh
pip install --pre "jupyterlab-git==0.50.0a0"
```

**Comment by fcollonval** [comment]
Version [0.50.0a1](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0a1) has been released; may highlight is the fix for the message commit #1281 

```sh
pip install --pre "jupyterlab-git==0.50.0a1
```

**Comment by absentio** [comment]
> Version [0.50.0a1](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0a1) has been released; may highlight is the fix for the message commit #1281
> 
> ```shell
> pip install --pre "jupyterlab-git==0.50.0a1"
> ```

It still does not work with JupyterLab 4.0.7

**Comment by krassowski** [comment]
> It still does not work with JupyterLab 4.0.7

It does:

![image](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/04266620-5189-4339-a675-0a64b27e5bd5)

Did you restart JupyterLab? Did you install it in environment with 4.0 (check `jupyter --version`). Does it show up in `jupyter labextension list` and `jupyter server extension list`?

**Comment by absentio** [comment]
> > It still does not work with JupyterLab 4.0.7
> 
> It does:
> 
> ![image](https://user-images.githubusercontent.com/5832902/278410148-04266620-5189-4339-a675-0a64b27e5bd5.png)
> 
> Did you restart JupyterLab? Did you install it in environment with 4.0 (check `jupyter --version`). Does it show up in `jupyter labextension list` and `jupyter server extension list`?

Alright, I had to stop and start Jupyter to get it work. Thanks.

**Comment by fcollonval** [comment]
Version [0.50.0a2](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0a2) has been released

```sh
pip install --pre "jupyterlab-git==0.50.0a2"
```

**Comment by fcollonval** [comment]
Version [0.50.0rc0](https://github.com/jupyterlab/jupyterlab-git/releases) has been released

```sh
pip install --pre "jupyterlab-git==0.50.0rc0"
```

**Comment by jabbera** [comment]
rc0 works great for me! Can't wait for stable.

**Comment by HYBG-1126** [comment]
I use the JupyterLab service started by JupyterHub on k8s. How to restart the jupyter lab service after installing the git plug-in to ensure that the plug-in is available?

**Comment by mfakaehler** [comment]
Usually, if you have an active jupyterlab-session spawned by jupyterhub, you can go for File / Hub Control Panel and then press "Stop my Server" followed by "Start my Server". If the git-plugin was installed properly, it should become visible then.

**Comment by markub3327** [comment]
Hi, I have jupyterlab 4.1.4 and install the jupyterlab_git 0.50.0rc0 by pip: `pip install "jupyterlab-git==v0.50.0rc0"`

But after reloading the jupyterlab website, I got an alert:
> Failed to load the jupyterlab-git server extension
> Git server extension is unavailable. Please ensure you have installed the JupyterLab Git server extension by running: pip install --upgrade jupyterlab-git. To confirm that the server extension is installed, run: jupyter server extension list.


Here is a log from lab and server:
># jupyter server extension list
> Config dir: /root/.jupyter
> 
> Config dir: /usr/etc/jupyter
> 
> Config dir: /usr/local/etc/jupyter
>     jupyter_lsp enabled
>     - Validating jupyter_lsp...
>       jupyter_lsp 2.2.4 OK
>     jupyter_server_mathjax enabled
>     - Validating jupyter_server_mathjax...
>       jupyter_server_mathjax  OK
>     jupyter_server_terminals enabled
>     - Validating jupyter_server_terminals...
>       jupyter_server_terminals 0.5.2 OK
>     jupyterlab enabled
>     - Validating jupyterlab...
>       jupyterlab 4.1.4 OK
>     jupyterlab_git enabled
>     - Validating jupyterlab_git...
>       jupyterlab_git 0.50.0rc0 OK
>     nbdime enabled
>     - Validating nbdime...
>       nbdime 4.0.1 OK
>     notebook enabled
>     - Validating notebook...
>       notebook 7.1.1 OK
>     notebook_shim enabled
>     - Validating notebook_shim...
>       notebook_shim  OK 

> # jupyter lab extension list
> Config dir: /root/.jupyter
> 
> Config dir: /usr/etc/jupyter
> 
> Config dir: /usr/local/etc/jupyter
>     jupyter_lsp enabled
>     - Validating jupyter_lsp...
>       jupyter_lsp 2.2.4 OK
>     jupyter_server_mathjax enabled
>     - Validating jupyter_server_mathjax...
>       jupyter_server_mathjax  OK
>     jupyter_server_terminals enabled
>     - Validating jupyter_server_terminals...
>       jupyter_server_terminals 0.5.2 OK
>     jupyterlab enabled
>     - Validating jupyterlab...
>       jupyterlab 4.1.4 OK
>     jupyterlab_git enabled
>     - Validating jupyterlab_git...
>       jupyterlab_git 0.50.0rc0 OK
>     nbdime enabled
>     - Validating nbdime...
>       nbdime 4.0.1 OK
>     notebook enabled
>     - Validating notebook...
>       notebook 7.1.1 OK
>     notebook_shim enabled
>     - Validating notebook_shim...
>       notebook_shim  OK
