### ISSUE TITLE
Disable upload functionality in jupyter notebook

### ISSUE THREAD

**Issue by betac0de** [jupyterlab/jupyterlab-git#1258]
## Describe the solution you'd like

I need to disable jupyter note book upload functionality completely including drag and drop
We are using aws sagemaker to access jupyter notebook we need assistance reg disable download using lifecycle configuration script
## Additional context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

**Comment by fcollonval** [comment]
@betac0de this repository is about the git extension for JupyterLab. What tooling are you targeting JupyterLab or classical notebook and in which version. Moreover we are not affiliated in any way with AWS Sagemaker. So you should contact their support I guess.
