### ISSUE TITLE
Diff any two local notebooks or files

### ISSUE THREAD

**Issue by robna** [jupyterlab/jupyterlab-git#1266]
## Is your feature request related to a problem? Please describe.

I couldn't figure out a way to diff two notebooks that are in a project directory. So I mean, to diff the files against each other, instead of against a certain commit.

## Describe the solution you'd like

It would be nice to be able to select two files in the file browser panel, 
and then have an option in the Git top menu: `Diff selected files` (or maybe a short cut like Ctrl + D or something)

**Comment by krassowski** [comment]
This was also recently proposed in nbdime: https://github.com/jupyter/nbdime/issues/660 which might be a better place to implement this.

**Comment by robna** [comment]
ok, I agree
