### ISSUE TITLE
UI modification list

### ISSUE THREAD

**Issue by zzhangjii** [jupyterlab/jupyterlab-git#127]
list of needs for UI improvement(small issues)
1:  in past commit, display 'XX file changed, xxx insertions, xxx deletions' note with symbols and number(like VScode)

2. in past commit for each file, insertion mark  and deletion mark should be different color

3. commit button should be light-grey when disabled, and green when enabled

4. pastcommit timeline scroll faster

**Comment by zzhangjii** [comment]
3, 4 solved

**Comment by ashutoshbondre** [comment]
pull request #130 solves 1 & 2 now.
