### ISSUE TITLE
commit message always set to "Committing changes..." (v0.50.0a0)

### ISSUE THREAD

**Issue by CagtayFabry** [jupyterlab/jupyterlab-git#1281]
Thanks for releasing with support for JupyterLab 4 !
Trying out the `0.50.0a0` release, I noticed that my commit messages (summary and/or description) are not registered with git, instead every commit shows `Committing changes...` as commit message.

## Description

When committing changes using the extension UI, the commit message is always set to `Committing changes...` .
This can be verified using `git log` or the history view of the extension (commit `console` was created from command line):
![image](https://github.com/jupyterlab/jupyterlab-git/assets/43667554/11de33eb-c313-400c-9bc5-47630390b1f8)

## Reproduce

1. Go to any git repository (or create a new one)
2. Stage changes
3. Enter commit summary (and optionally description)
4. click `COMMIT` in the extension UI
5. verify `git log`

## Expected behavior

The commit message summary and description provided by the user should be attached to the commit.

## Context

- Python package version:
`
```
# Name                    Version                   Build  Channel
jupyterlab-git            0.50.0a0                 pypi_0    pypi
```
- Extension version:

```
JupyterLab v4.0.7
/opt/tljh/user/share/jupyter/labextensions
        nbdime-jupyterlab v3.0.0-alpha.1 enabled OK
        k3d v2.15.3 enabled OK (python, k3d)
        jupyterlab-jupytext v1.3.9 enabled  X (python, jupytext)
        jupyter-matplotlib v0.11.3 enabled OK
        jupyterlab-myst v2.1.0 enabled OK (python, jupyterlab_myst)
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyterlab_code_formatter v2.2.1 enabled  X (python, jupyterlab_code_formatter)
        @jupyterlab-contrib/spellchecker v0.8.4 enabled OK (python, jupyterlab-spellchecker)
        @jupyterlab/git v0.50.0-a0 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.8 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v1.0.0 enabled OK (python, jupyter-resource-usage)
        @voila-dashboards/jupyterlab-preview v2.3.0 enabled OK (python, voila)
        @jupyter-notebook/lab-extension v7.0.2 enabled OK


   The following extensions are outdated:
        jupyterlab-jupytext
        jupyterlab_pygments
        jupyterlab_code_formatter
        
   Consider checking if an update is available for these packages.
```
- Git version:

```
git version 2.34.1
```
- Operating System and its version:
```
ubuntu 22.04
```

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by krassowski** [comment]
Indeed, `message` gets overridden here:

https://github.com/jupyterlab/jupyterlab-git/blob/e95a9e56613b3827b90fdf50a2c0d71687ae37af/src/components/GitPanel.tsx#L782-L806

It is quite interesting case of TypeScript not picking it up because it is in another scope (try-catch context).
