### ISSUE TITLE
Requirement in README and install instructions contradictory.

### ISSUE THREAD

**Issue by Northo** [jupyterlab/jupyterlab-git#1291]
After #1271, there seem to be a contradiction in the README. The top parts says "JupyterLab >= 4.0" in requirements, while the installation instructions are `pip install --upgrade "jupyterlab<4" jupyterlab-git`.
From my experiments, it seems like 4.0 does _not_ work.

> It seems like the [Requirements section of README](https://github.com/jupyterlab/jupyterlab-git/#requirements) does not agree with the installation guide anymore. While the installation guide asks for "jupyterlab<4", the Requirements say "JupyterLab >= 4.0". This sounds contradictory to me.

_Originally posted by @markusReinert in https://github.com/jupyterlab/jupyterlab-git/issues/1271#issuecomment-1777435410_

**Comment by krassowski** [comment]
The jupyterlab-git [v0.50.0rc0](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0rc0) supporting JupyterLab 4.0 is in release candidate phase, and as such you will need to add `--pre` to the `pip install` command, for example:

```
pip install --pre "jupyterlab-git==0.50.0rc0"
```

(see https://github.com/jupyterlab/jupyterlab-git/issues/1245#issuecomment-1798057095).

As soon as the final version is released (hopefully very soon) the plain pip install will just work.

**Comment by Northo** [comment]
Great!

However, I still believe the docs should be updated. As it seems 0.50 will be released quite soon, maybe it is sufficient to simply remove the `<4` constraint from the installation instructions in the README?

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab-git/pull/1305
