### ISSUE TITLE
Small jitter when hovering over Changes section and items

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#1296]
## Description

There is a small but slightly annoying jitter when hovering over Changes section and items

## Reproduce

![height-glitch](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/545f9838-5089-4382-ad95-06acc3738a74)

## Expected behavior

No jitter

## Context

0.50.0rc0

**Comment by krassowski** [comment]
Also, the scrollbars a bit annoying. Maybe they are the reason? The screecast is from Chrome/Chromium browser

**Comment by fcollonval** [comment]
@krassowski would you mind digging into this one if you have time?

I don't see it on a fresh environment JupyterLab 4.0.8 and jupyterlab-git 0.50.0rc0; tested on Debian with Firefox 114 and Chromium 119

**Comment by krassowski** [comment]
I guess there are differences in fonts used between Debian and Ubuntu so the intrinsic height when not hovered ends up different. I believe setting min-height of the section to 16px (the height of the icon) should solve the jitter but not sure where to set the overflow to disable the scrollbars.
