### ISSUE TITLE
bug task

### ISSUE THREAD

**Issue by mikeknack86** [jupyterlab/jupyterlab-git#1367]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by krassowski** [comment]
Closing, it appears this was opened by mistake.
