### ISSUE TITLE
Sioux Cinemas

### ISSUE THREAD

**Issue by Wom-Di-Tanka** [jupyterlab/jupyterlab-git#1378]
## Additional context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

**Comment by Wom-Di-Tanka** [comment]
Create a link to Sioux Cinemas  #[button][](url)

**Comment by Wom-Di-Tanka** [comment]
Creating horror movies films is my favorite!

**Comment by fcollonval** [comment]
Closing as spam your behavior will be reported as such to GitHub.
