### ISSUE TITLE
Some feedback?

### ISSUE THREAD

**Issue by amueller** [jupyterlab/jupyterlab-git#154]
Just checked this out with little context as it was mentioned at JypyterCon.
This looks amazing!

Two things in the interface that surprised me:
If I click on the unstaged or staged files, I see the full file, not the diff.
On the other hand, if I go back to the last commit, the interface will just show me the diff, and I don't see a way to view the full notebook.
I think it would be good to be able to view both the diff and the full notebook snapshot, both for earlier commits and for the unstaged and staged files. Having different behavior for commits and the current state was a bit surprising.

The other thing I was surprised by (which I imagine is on your todo) is that the diff is just a git diff of the json, and not an nbdime style diff.

Maybe I would show the diff by default, both for commits and the staging area, and allow viewing the full file via the context menu (looks like there is no context menu yet).

Keep up the good work!

**Comment by zzhangjii** [comment]
thanks for those advices, we will keep working on that. We have been trying different designs to solve this diff and open-full-file issue. context-menu definitely is a good solution

**Comment by amueller** [comment]
cool. feel free to close. Are you at jupytercon?

**Comment by zzhangjii** [comment]
yep, see u around and welcome to our user-test
