### ISSUE TITLE
User Testing Revelation 

### ISSUE THREAD

**Issue by ashutoshbondre** [jupyterlab/jupyterlab-git#162]
##  Few of the main issues I found while doing user testing.
1. The Square brackets [ ] in the 'Untracked Section' should be replaced with a '+' symbol, just to make them compatible with other sections.
![image](https://user-images.githubusercontent.com/13174154/29954623-422dc2a4-8ea7-11e7-8669-9ec103daeff2.png)

2. Users had a hard time understanding that files are already in the staged area, for example in the image below, users couldn't really understand that, 'sample.txt' & 'git_mainmenu_command.ts' are already staged. Maybe we should border the entire staged area with green color to associate that.
![image](https://user-images.githubusercontent.com/13174154/29954655-8d827c22-8ea7-11e7-89ff-01252080f770.png)

3. Almost nobody clicked the 'add_all', 'track_all', 'unstage_all' buttons (the buttons in the section header). They are somewhat hidden from a normal user's vision. Needs a keen eye to see them for now, we must make them more prominent. 

4. After the user hit the commit button, they were confused as the files instantly disappeared from the Staged Section. Probably we should make some animation which shows file icon moving up from the staging into the circular past commit section.

5. Many users tried to drag and drop of files from one stage to the other, looking back I think that's a pretty obvious choice. Maybe we should add the drag & drop facility from section to section.

6. (less priority) If we are doing the animation, we should also add animation for files moving from section to section (up as well as down)

**Comment by hzarea** [comment]
We are working with Bloomberg to get more info about User Testing results as well, so possibly more information to come!
