### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab-git#163]
I've been tracking this repo for a while, and it seems that the activity has dropped (summer interns done?). Is there a plan for what to do with this repository now? I might be able to spend some time on it, but I'm interested to hear if there is any long term strategy planned. E.g. are there many more features that need to go in, or is this now in maintenance mode? Who will review PRs that come in? etc.

I'm asking since this offers a very nice tie-in with nbdime and the overarching goal of that task in our project (https://github.com/OpenDreamKit/OpenDreamKit/issues/95), and as such I'm invested in getting this to a workable release. I believe integration with JupyterLab/Notebook will help drive adaption and improve usability significantly.

CC @ellisonbg

**Comment by zzhangjii** [comment]
Hi, Vidar, thanks for your suggestion. 
Our recent plans for Git-plugin are:
1. Based on user testing results, change and improve the UI and functionalities;
2. Animation for git operations;
3. Improve git diff and other version comparing features based on nbdime;
4. Publish it!

We were working on analyzing the User testing data from JupyterCon in the past few weeks and the next steps will be focusing on the UI design changes(Plan 1&2). For plan 3, it may need some long time work, so we are thinking about publishing a useable version first, and then improve it with your help!

**Comment by Analect** [comment]
@zzhangjii 
We discussed this extension at JupyterCon together.  As per your instincts above, I think it would be great to get something basic out there and working against the pending jupyterlab 0.28 so that we can see it working, particularly in conjunction with nbdime (which I would be interested in seeing) as per @vidartf suggestion.

From there, I think it will become easier for others to get involved with a view to improving the feature-set.

Thanks for your efforts.

**Comment by zzhangjii** [comment]
Thx for the suggestion, currently, Vidar has added a nbdime diff provider for ipynb files, other files are still using the old diff. I'm working on some UI changes and probably will keep the diff part as it is right now. Hopefully we can have some basic out there next week!

**Comment by vidartf** [comment]
> Hopefully we can have some basic out there next week!

Thanks, I'll consider these questions answered!

**Comment by Analect** [comment]
@zzhangjii ... any update on a preliminary version that might be compatible with jupyterlab 0.28.x? Thanks

**Comment by zzhangjii** [comment]
Still working on button icon redesign and other UI changes...
