### ISSUE TITLE
Trying to determine if it's a user's responsibility that a given folder is already git-enabled

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab-git#169]
@zzhangjii 
I realise this is a WIP and that you are working towards getting something initial working for the coming week.

My context is that I have a jupyterlab image (potentially with this jupyterlab-git plugin installed) which I am using in conjunction with kubespawner in order to have a running notebook server (with jupyterlab and this this plugin on board).

From what I can see, the code in this repo includes a subset of git commands ... while it has `git init`, however it excludes commands like `git remote` ... therefore does it expect a given folder to be already be git-enabled?

From my context, using kubespawner, it is up to me to ensure a particular folder that will be exposed to jupyterlab is already git-enabled?

I've solved this before using a side-car 'git' container in conjunction with the notebook container whose function is to clone a repo to a given folder on start-up ... and I am looking to see if I can achieve it, in the context of kubernetes, with an `init-container`, akin to the one illustrated in [this SO question](https://stackoverflow.com/a/44149704/2425348).

**Comment by zzhangjii** [comment]
Currently, we haven't come up with a design for git remote commands. A git init is only the first step for beginners users to learn, currently user needs to clone the repo by themselves, and type in the repo to push and pull (_and yes, I know it's lame_). 
Thx for the init-container suggestion, I will check it out and make some design to combine init with clone repo together
