### ISSUE TITLE
rate limited by GitHub

### ISSUE THREAD

**Issue by epifanio** [jupyterlab/jupyterlab-git#171]
Tring to use the extension, I load the Gihub tab and added my username on top.
I've been able to see all my repository listed, then trying to reload jupyterlab (which is running in a docker container) when I reload the GitHub extension tab I got this log:

#  You have been rate limited by GitHub! You will need to wait about an hour before continuing

Have you any clue on how to deal with it?

**Comment by ian-r-rose** [comment]
Hi @epifanio , as described in the [readme](README.md), if you want to avoid being rate-limited you will need to set up a GitHub OAuth App and install the server extension.

**Comment by ian-r-rose** [comment]
Also, I just now realize that this is the in the wrong repository :smile:.
The right place is [here](https://github.com/jupyterlab/jupyterlab-github)

**Comment by epifanio** [comment]
Hoops! :) and thanks!!!
