### ISSUE TITLE
jupyterlab-git doesn't work with JupyterLab 0.29.1

### ISSUE THREAD

**Issue by cfregly** [jupyterlab/jupyterlab-git#172]
is this a known issue?  or am i doing something wrong?

the git tab just doesn't show up.  seems to be incompatible with 0.29.1 per the following:

```
"jupyterlab-git@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.12.0-0 <0.13.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/console
>=0.12.0-0 <0.13.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/application
>=0.12.4-0 <0.13.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/apputils
>=0.12.0-0 <0.13.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/filebrowser
>=0.12.0-0 <0.13.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/terminal
```

are there plans to keep this project up-to-date with jupyterlab?  this is a hot feature.  we'd love to use it.

thanks!!

**Comment by ian-r-rose** [comment]
Hi @cfregly, it looks like you are using the previous version. `v0.2.0` has been released, which is compatible with JupyterLab 0.29: https://www.npmjs.com/package/@jupyterlab/github

**Comment by cfregly** [comment]
@ian-r-rose ah, should i be using the other repo instead?  i didn't know about that one...

i'll try it now.  thanks for the immediate reply!!

**Comment by ian-r-rose** [comment]
It depends, did you intend to be posting at that repo :smile: ? That extension provides a viewer for repositories on GitHub, this one is for git integration on the server.
