### ISSUE TITLE
Extension does not respect the base_url setting for JupyterLab

### ISSUE THREAD

**Issue by LucasRoesler** [jupyterlab/jupyterlab-git#175]
If you modify the base_url setting for the JupyterLab app, then the application breaks because the urls are not formed correctly.

I ran into this issue when I was trying to proxy requests to a JupyterLab instance and I have created a pull request #174 to address it.

**Comment by zzhangjii** [comment]
Thx, that help a lot!

**Comment by LucasRoesler** [comment]
Closing this since it was resolved in #174
