### ISSUE TITLE
Rebuilding python code

### ISSUE THREAD

**Issue by rowandempster** [jupyterlab/jupyterlab-git#190]
Hello,

I would like to make some modifications to the server extension python code (the handlers and git python files), but my changes are not being reflected after I rebuild (`jupyter lab build`).
Is there different steps I have to take to rebuild the server extension part of this extension?

Note that I am able to modify the UI code and see those changes reflected after a rebuild. 

Thanks a bunch,
Rowan

**Comment by zzhangjii** [comment]
hi, @rowandempster , the server side needs to be installed and activated by 
`pip install . e`
`jupyter serverextension enable --py jupyterlab_git`

You don't need to rebuild (`jupyter lab build`) to change the server side.

**Comment by rowandempster** [comment]
Ah, I wasn't putting the `e` at the end of the `pip install`, thanks for the tip!
What does adding the `e` do? I can't find documentation about it online. 

Should that command be updated in the README? Or does adding `e` break something else? 

Feel free to close this whenever :)

**Comment by zzhangjii** [comment]
the `e` is to to make sure it updates automatically, so you don't need to do `pip install` every time when you made changes on server side.  
choosing `pip install .` or `pip install . e` is personal choice. But we will update it in the README later.
