### ISSUE TITLE
Git repository not recognized

### ISSUE THREAD

**Issue by KPreal** [jupyterlab/jupyterlab-git#202]
I am not sure if I have to do something special to make jupyterlab-git recognize the repository I'm in.
I have launched jupyter lab in the repo, and trying to use the extension I only get the following view:
![image](https://user-images.githubusercontent.com/25557080/43501131-b4a15eb0-955c-11e8-88c0-73dd7f34cafd.png)

I am running JupyterLab  v0.33.4 with these two extensions:
@jupyterlab/git v0.1.3 (this extension)
@jupyterlab/toc v0.3.1 (table of contents)

**Comment by jturney** [comment]
Did you install and enable the server extension?

```
pip install jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```

**Comment by vnijs** [comment]
This looks like a really great extension but I'm seeing the same issue as @KPreal. My Docker file includes a line to install jupyterlab-git and the two lines below

```
RUN jupyter labextension install @jupyterlab/git
RUN jupyter serverextension enable --py jupyterlab_git
```

As you can see, the directory in the screenshot below has a .git directory (see below) but even if I enable the extension again it doesn't pick up the repo. Any suggestions?

![image](https://user-images.githubusercontent.com/2998956/43565074-43983dd8-95de-11e8-92c8-34e5f6746793.png)

**Comment by KPreal** [comment]
@jturney Ah, I had some problem here. I don't remember what exactly I did wrong, but (re)running those lines fixed it for me at least.

**Comment by vnijs** [comment]
The issue was on my end. Issue can be closed it seems. I had to add `--system` to the command as I'm mounting the docker container to the users home directory.

`jupyter serverextension enable --py jupyterlab_git --system`
