### ISSUE TITLE
Always complains "You aren’t in a git repository" after launching juputerlab from jupyterhub

### ISSUE THREAD

**Issue by jason4zhu** [jupyterlab/jupyterlab-git#212]
My notebook_url is set to /home/admin, and when admin logged in, it is automatically navigated to /home/admin as default. I've tried to create a new gitlab repo and apply /home/admin to this git repo after commands like (`git init; git add .; git commit -m '...'; git push origin master`). After all these done, the directory looks as below:

```
[root@9b27d6147671 admin]# pwd
/home/admin
[root@9b27d6147671 admin]# ll -a
total 40
drwxrwx---  8 admin admin 4096 Aug 16 18:56 .
drwxr-xr-x 14 root  root  4096 Aug 16 18:33 ..
-rw-------  1 admin admin   56 Aug 16 19:10 .bash_history
drwx------  3 admin admin 4096 Aug 16 18:55 .config
drwxr-xr-x  7 admin admin 4096 Aug 16 19:16 .git
```

 I launched jupyterhub from path '/' via command `jupyterhub --port 8080` and the git extension always complains "You aren’t in a git repository" even though the git repo exists there. Any ideas? Thanks.

**Comment by h4gen** [comment]
I am encountering the same problem. On my worker node spawned by jupyterhub the only thing I get is "You aren’t in a git repository".

**Comment by daldridge-cs** [comment]
Same here.  I tried installing a fork of the extension [here](https://github.com/SwissDataScienceCenter/jupyterlab-git/tree/fix-git-current-dir), but that didn't help.  Is there any way to debug the Python server extension?

**Comment by masip85** [comment]
Same here with jupyterlab 0.34 editor:
"You aren’t in a git repository".

**Comment by leafty** [comment]
@jason4zhu For use with JupyterHub, I have made PR #210
You can try it with:
```bash
jupyter labextension install @jupyterlab/git
pip install -e git+https://github.com/SwissDataScienceCenter/jupyterlab-git.git@fix-git-current-dir#egg=jupyterlab_git
jupyter serverextension enable --py jupyterlab_git
```

**Comment by JosCline** [comment]
I got this to work by going to the drop down menu, "Git" and selecting Init. It made the folder I was in (from the "files" tab) a local repo, then the Git tab populated with the files from the "files" tab"

**Comment by daldridge-cs** [comment]
I've installed the extension as @leafty described above, but I'm still getting 404s when making requests to the server extension's git APIs.  It's like the extension isn't actually enabled, even though `jupyter serverextension list` shows it's registered.  Any suggestions on what else to check?

**Comment by AmadeusSG** [comment]
Just to point out as well - the `pip install jupyterlab-git` + `serverextension` part is important, otherwise it will result in a 404 error due to those missing extensions, thus showing that `You aren't in a git repository`. If you're using < `jupyterlab@0.35.0`, use [solution provided by @leafty](https://github.com/jupyterlab/jupyterlab-git/issues/212#issuecomment-416625944). I would suggest to add `--sys-prefix` to the `serverextension` command to apply system-wide as well.

**Comment by leafty** [comment]
@AmadeusSG note that the PR has been merged, so it should be:
```bash
pip install -e git+https://github.com/jupyterlab/jupyterlab-git.git#egg=jupyterlab_git
```

**Comment by AmadeusSG** [comment]
@leafty Ah, right, the version for the server extension is still 2.2, so it should still be compatible with JLab < 35.0. So, to summarise:

```bash
jupyter labextension install @jupyterlab/git
pip install -e git+https://github.com/jupyterlab/jupyterlab-git.git#egg=jupyterlab_git
jupyter serverextension enable --py jupyterlab_git --sys-prefix
```

**Comment by gsemet** [comment]
Same on jupyterlab 0.34, I always get the error "You aren’t in a git repository".

Apparently, the requested URL does not exist: 
```
POST http://jupyter.mycompany.fr/user/myusername/git/all_history
{"current_path":"local/path/to/gitproject"}
```

Installed by
```bash
jupyter labextension install @jupyterlab/git
pip install -e git+https://github.com/jupyterlab/jupyterlab-git.git#egg=jupyterlab_git
jupyter serverextension enable --py jupyterlab_git --sys-prefix
```

version installée:
- jupyterlab/git: 0.2.2
- packet python: https://github.com/jupyterlab/jupyterlab-git.git

**Comment by gsemet** [comment]
Same with jupyterlab 0.35.2, but:
- no more error on jupyterlab start (`jupyterlab_git` pypi module seem well installed)
- 404 still returned on the `git/all_history` endpoint. The log displays:
```
04 POST /user/myusername/git/all_history?1540396029715 (myusername@12.13.14.15) 30.64ms
```

**Comment by AmadeusSG** [comment]
You may need to restart your own spawner, i.e. go to Jupyterhub's control panel, then stop and start your server again.

**Comment by gsemet** [comment]
did that a lot. It seems like the endpoints are not registered within jupyterlab, how can I debug it?

There is also the fact that the base url is not the /, but under `staging/` directory. Can this break the endpoint registration? I see no errors on the log :(

I use the kube_spawner on jupyterhub, for using docker images derived from official jupyter images, but with jupyterlab enabled by default. Does know if that helps.

**Comment by CerebralMastication** [comment]
I'm also getting the "You aren't in a git repository" in the git pane. 

I'm running:

jupyterlab~=0.35.0 jupyterhub~=0.9.4 notebook~=5.7

I thought maybe pypi was out of date so I installed directly from https://github.com/jupyterlab/jupyterlab-git  with no change in behavior.

**Comment by martintb** [comment]
Same issue for the most part: "You aren't in a git repository". The really interesting part is that the extension **works** in the cloned jupyterlab_git directory but nowhere else. 

Ubuntu 16.04.5 LTS
Jupyterlab=0.35.4
Installed extension from cloned repository
linked extension
enabled serverextension
No errors in console

**Comment by sblack4** [comment]
Same problem as the above two. None of the git APIs are available and all return 404, ex `https://<IP>:8000/user/steven/git/all_history` returns `404 not found`. 

I'm going to be spending a good bit of time getting this working so any direction is appreciated. Feel free to reach out to me to see where I am and I'll post an answer when it's solved/I've given up.

**Comment by jaipreet-s** [comment]
@neelamgehlot Do you mind taking a look at this when you have a chance?

**Comment by sblack4** [comment]
Here's what I did that got it to work: 
1. installed `jupyterlab` and `jupyterlab-git` through `pip`
2. added the below to my `jupyterhub_config.py`
```
c.NotebookApp.nbserver_extensions = {
    'jupyterlab_git': True,
} 
```

---
I'm using this installer script on Azure's Ubuntu Data Science VM: 
```
#!/bin/bash 


ANACONDA_BIN="/anaconda/envs/py35/bin"
JUPYTERHUB_CONFIG_FILE="/etc/jupyterhub/jupyterhub_config.py"

update_path() {
  echo "export PATH=\"${ANACONDA_BIN}:${PATH}\"" | sudo tee -a /etc/profile
  echo "source ${ANACONDA_BIN}/activate" | sudo tee -a /etc/profile
}

install_jupyterlab_and_packages() {
  sudo $ANACONDA_BIN/conda update --all -y
  sudo $ANACONDA_BIN/pip install -U pip 

  sudo $ANACONDA_BIN/conda install -y -c conda-forge 
  sudo $ANACONDA_BIN/pip install -U oauthenticator jupyterlab jupyterlab-git
  sudo $ANACONDA_BIN/jupyter serverextension enable --py jupyterlab_git
  sudo $ANACONDA_BIN/jupyter labextension install @jupyterlab/hub-extension
  sudo $ANACONDA_BIN/jupyter labextension install @jupyterlab/git
}

setup_jupyter_configs() {

  # default to jupyterlab
  sed -i.bak 's/^c\.Spawner\.cmd/#&/' $JUPYTERHUB_CONFIG_FILE
  echo "c.Spawner.cmd = ['/data/anaconda/envs/py35/bin/jupyter-labhub']" | sudo tee -a $JUPYTERHUB_CONFIG_FILE

  # switch to OAuth
  # sed -i.bak 's/^c\.PAMAuthenticator\.service/#&/' $JUPYTERHUB_CONFIG_FILE
# cat <<EOM >>/etc/jupyterhub/jupyterhub_config.py

# # GitHub OAuthentication 
# c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
# c.LocalGitHubOAuthenticator.create_system_users = True
# c.GitHubOAuthenticator.oauth_callback_url = 'https://137.116.89.195:8000/hub/oauth_callback'
# c.GitHubOAuthenticator.client_id = ''
# c.GitHubOAuthenticator.client_secret = ''
# EOM

echo "c = get_config()" | sudo tee -a $JUPYTERHUB_CONFIG_FILE
echo "c.NotebookApp.nbserver_extensions = {" | sudo tee -a $JUPYTERHUB_CONFIG_FILE
echo "    'jupyterlab_git': True," | sudo tee -a $JUPYTERHUB_CONFIG_FILE
echo "}   " | sudo tee -a $JUPYTERHUB_CONFIG_FILE

}


main() {
  sudo systemctl stop jupyterhub

  update_path
  install_jupyterlab_and_packages
  setup_jupyter_configs

  sudo systemctl start jupyterhub
}

main "$@"
```

**Comment by sblack4** [comment]
Following up to the above, it looks like the extension only works for the user that ran `sudo $ANACONDA_BIN/jupyter serverextension enable --py jupyterlab_git`, but not for the other users on the jupyterhub server

**Comment by CerebralMastication** [comment]
I finally got it working in my docker build. For me the secrets were 1) ensuring I ran `jupyter labextension link` and 2) making sure my `serverextension` command included  `--sys-prefix jupyterlab_git`

Below is my docker file excerpt showing how I'm loading jupyterlab-git. Note that I'm cloning from github and doing a checkout at a specific hash just to ensure nothing changes underneath me over time. 

```
RUN git clone https://github.com/jupyterlab/jupyterlab-git 
WORKDIR ./jupyterlab-git
RUN git checkout 276a42d772e0a13eb4b880c1ea45044cd5821a45
RUN npm install 
RUN npm run build
RUN jupyter labextension link . 
RUN npm run build 

RUN pip3.6 install .
RUN jupyter serverextension enable --py --sys-prefix jupyterlab_git 
```

**Comment by sblack4** [comment]
@CerebralMastication  Thank you!!! Adding `--sys-prefix` to `jupyter serverextension enable --py --sys-prefix jupyterlab_git` fixed the issue in my previous comment!

**Comment by gsemet** [comment]
did not worked for me :( Can I get the full dockerfile please?

**Comment by satary** [comment]
I have got  different and weird behavior. I also use lab via jupyterhub and used commands that @sblack4 suggested. 
Now when I browse to the repo, the "git clone" button becomes greyed out, so it detects the repo. But still, I have "You aren’t in a git repository." error and the path is wrong. Interestingly, the path is correct when I am outside of git repo.
The only significant difference is that I have jupyterhub prefix configured, so it is located under name.domain/**jupyter**/user/someuser/lab
There also is an error in the debug console:
```
vendors~main.7e71eb0a64ad60f412b6.js:78606 TypeError: Cannot read property 'length' of undefined
    at GitPanel.<anonymous> (vendors~main.7e71eb0a64ad60f412b6.js:78522)
    at Generator.next (<anonymous>)
    at fulfilled (vendors~main.7e71eb0a64ad60f412b6.js:78476)
```

**Comment by orome** [comment]
I'm a bit confused as to what the current correct approach is. Could someone summarize the full set of commands to completely install?

So far all I've done is

    jupyter labextension install @jupyterlab/git

which the readme seems to say should be sufficient.

**Comment by mlucool** [comment]
I too am having issues, even after running this with:
```
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git --sys-prefix
```

**Comment by orome** [comment]
@mlucool So installation requires _all three_ of those steps? That's not clear from the readme.

**Comment by mlucool** [comment]
I agree, the `README` was not clear. It does require all three.

**Comment by orome** [comment]
@mlucool PR #295

**Comment by orome** [comment]
@mlucool What steps are required to keep `jupyterlab-git` up to date? Is `pip install -U jupyterlab-git` sufficient?

**Comment by mlucool** [comment]
I haven't looked at this really, but it appears the first step is the JS install and the second is the python. Therefore you'd need to update both to update. A maintainer will know better as I have only tried this for 30 minutes now :)

**Comment by satary** [comment]
Updating to the latest jupyterlab-git fixed the issue for me!

**Comment by orome** [comment]
@satary What steps are required to keep jupyterlab-git updated? Is `pip install -U jupyterlab-git` sufficient?

**Comment by satary** [comment]
I did 
```
pip install -U jupyterlab-git
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git --sys-prefix
```
But I have no idea if the last two lines are mandatory =)

**Comment by orome** [comment]
We need a maintainer's input.

**Comment by jaipreet-s** [comment]
Yes, @satary's commands are correct.

Basically, we need those commands to keep both the Python and the TS source updated.

**Comment by argoneus** [comment]
> 
> 
> Here's what I did that got it to work:
> 
>     2. added the below to my `jupyterhub_config.py`
> 
> 
> ```
> c.NotebookApp.nbserver_extensions = {
>     'jupyterlab_git': True,
> } 
> ```

This got it working for me in Jupyterlab.  Thanks for the tip!

**Comment by ronid** [comment]
I'm using lab and I think I've tried everything here and it's still not working for me.

**Comment by gsemet** [comment]
Same. using --sys-prefix does not work (complain about missing "six" package).

**Comment by wajditcb** [comment]
Same thing here... I have tried everything here and it still saying that I am not in a git repo

**Comment by lambdamusic** [comment]
> The front page directions do work after upgrading jupyter lab to the latest.
> 
> ```
> jupyter labextension install @jupyterlab/git
> pip install jupyterlab-git
> jupyter serverextension enable --py jupyterlab_git
> ```

I originally installed the extension with via the UI (ext manager) but couldn't get it to work. 

Running the steps above from the command line solved the issue!

**Comment by jaipreet-s** [comment]
@lambdamusic : Thanks for the report. I'm creating a separate issue () for the issue with installing from the extension manager. Since the README instructions work, this issue will be resolved to avoid multiple reports in one issue. Thanks!
