### ISSUE TITLE
Not able to see push pull buttons. 

### ISSUE THREAD

**Issue by bpoti** [jupyterlab/jupyterlab-git#214]
Hi All, 

I recently installed this extension, setup up with my organization git repo. We are using enterprise git. 
I am able to see all the branches available in our organization and also local branches which I created. 

After doing some changes to the files I able to write comments, but I don't see a `push` Botton available to push changes to remote tracking. I am able to open the terminal and launch the git push command but it will be more helpful if we have the buttons in the extension. 
I see there are issues regarding the `push` and `pull` buttons which are close. But I am not able to see them in the JupyterLab. 

Not sure if I am doing anything wrong. 

Thanks,
Teja

**Comment by NoahStapp** [comment]
Hi @bpoti,

There is not currently support for Git remotes or pushing/pulling. This is not a GitHub extension, this extension is intended for managing local repositories only.

There is a GitHub extension located [here](https://github.com/jupyterlab/jupyterlab-github)

**Comment by bpoti** [comment]
ah!! I see. The extension mentioned here, 
https://github.com/jupyterlab/jupyterlab-github
is only to pull view and run the code right as per the description!
