### ISSUE TITLE
Panel header should have clearer connection to repo and branch 

### ISSUE THREAD

**Issue by NoahStapp** [jupyterlab/jupyterlab-git#224]
The current header shows breadcrumbs leading from the home directory, exactly like the file browser.

![](https://user-images.githubusercontent.com/30483654/44940287-57a96980-ad41-11e8-9465-3d5b63f08993.png)

To create a better visual hierarchy, the branch name, branch dropdown list, and button to create a new branch should all be moved to the header. 

For the branch name and dropdown list, something like the cell type selector in the notebook toolbar is likely the best idea.

![](https://user-images.githubusercontent.com/30483654/44940317-d1d9ee00-ad41-11e8-8041-aa4d933e6e0e.png) ![](https://user-images.githubusercontent.com/30483654/44940319-d900fc00-ad41-11e8-834c-f3b2995353c8.png)

A quick non-styled visual prototype of such a design might look something like this:

![screen shot 2018-08-31 at 5 28 32 pm](https://user-images.githubusercontent.com/30483654/44940441-4eb99780-ad43-11e8-9ee6-6efb905a5273.png)

**Comment by tgeorgeux** [comment]
@weihwang , can you let me know if this issue is stale given your current design? If so I will close it.

**Comment by weihwang** [comment]
@tgeorgeux I think the new design I have will cover this issue. Please close and I will open an issue specific to the header/branch updates

**Comment by jaipreet-s** [comment]
This was done in the newer releases.
