### ISSUE TITLE
Deleting changes should have more friction

### ISSUE THREAD

**Issue by jennalandy** [jupyterlab/jupyterlab-git#226]
Deleting items from 'Changed' section should potentially have a pop-up similar warning to deleting a file (shown below). Deleting changes since last commit is a destructive action and there should be more friction to make sure users know what they're doing.

current delete changes warning
<img width="267" alt="screen shot 2018-08-31 at 5 42 31 pm" src="https://user-images.githubusercontent.com/35237833/44940603-8d505180-ad45-11e8-9b86-1f3a4b7fc5ee.png">

delete file pop up
<img width="407" alt="screen shot 2018-08-31 at 5 41 56 pm" src="https://user-images.githubusercontent.com/35237833/44940574-32b6f580-ad45-11e8-8b6a-8bd3dfb9d11f.png">

**Comment by weihwang** [comment]
Proposal for modal for destructive actions: https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=513%3A2513

![image](https://user-images.githubusercontent.com/551333/46840012-c97bc680-cd75-11e8-8518-c5148edeb456.png)

The change move the current inline confirmation into a modal for higher friction and opportunity to be more descriptive about the potential impact of actions. Strings TBD.

**Comment by tgeorgeux** [comment]
Looks great to me.
