### ISSUE TITLE
Style of file list

### ISSUE THREAD

**Issue by jennalandy** [jupyterlab/jupyterlab-git#227]
Suggestions for style changes to file list
- Add file path to each line
- Change trash icon for deleting changes. consider material design undo (https://www.materialui.co/icon/undo)
- Consistent margins 
- Right align track/untrack/stage/unstage/delete buttons

**Comment by ellisonbg** [comment]
VS Code does a good job of showing all the relevant information in the list of changed files.

**Comment by weihwang** [comment]
Proposed changes to file list for commit:
- margin
- right-aligned actions
- right-aligned status for consistency with file browser view

![image](https://user-images.githubusercontent.com/551333/47047439-72e30380-d14c-11e8-94c7-9810ac68e8fc.png)

**Comment by weihwang** [comment]
@jaipreet-s this is the closest issue for the right-align icon actions.

**Comment by weihwang** [comment]
I think we can find a color for red that is visible on both. As an alternative we can rely on the strikethrough styling too. I'll test this out.

**Comment by jaipreet-s** [comment]
@weihwang thanks! Tagging this to the 0.5 release.

**Comment by fcollonval** [comment]
Closing this issue as the styles in 0.10.0 fit this proposal.
