### ISSUE TITLE
Repo not recognized

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab-git#228]
I tried to use this promising-looking extension, but none of my repos are recognized by the extension. I tried re-installing the extension which made no difference.
Am I missing something ?

using jlab 0.34.7, installed jupyterlab-git with the included extension manager.

**Comment by mocquin** [comment]
I got it to work after doing :
`
jupyter labextension install @jupyterlab/git

pip install jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
`

**Comment by dhirschfeld** [comment]
From [gitter](https://gitter.im/jupyterlab/jupyterlab?at=5b9f6b05e5c2cc56ad9fc70b):
> *If you add metadata to package.json, the extension manager will inform the user of any required server-extensions and/or kernel packages the git package doesn't currently have this metadata*

Given this I'd be inclined to change the title to something more descriptive like:
**Please implement metadata to work with the extension manager**

Repo not recognized is the generic error message for _any_ problem.

**Comment by jo9k** [comment]
I am also having the issue. I am using the newest jupyterlab available through pip. I did run aforementioned commands but it does not resolve the problem.

**Comment by ellisonbg** [comment]
Thanks for the feedback everyone!
