### ISSUE TITLE
JupyerLab 0.32.0 @jupyterlab/git@0.2.2  not compatible

### ISSUE THREAD

**Issue by jaganadhg** [jupyterlab/jupyterlab-git#229]
Hi
I installed JupyterLab 0.32.0 and jupyterlab-git. In the server it is saying that "@jupyterlab/git@0.2.2" is not compatible with the current JupyterLab
Is there any way to upgrade or downgrade the same.

**Comment by ellisonbg** [comment]
JupyterLab is now on 0.35.x now, and this extension is undergoing some major work right now. It may be a month or so, but we should have this working well against 0.35 or 0.36 soon. Thanks for being patient ;-)

**Comment by blink1073** [comment]
The JS was updated in #239, working on a PyPI release now.

**Comment by blink1073** [comment]
0.3 released to PyPI
