### ISSUE TITLE
Setup CI/CD tooling

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#231]
Hi all,

Creating this issue to start the conversation around the CI/CD tooling to use for this repo.

Thanks,
Jaipreet

@blink1073  for feedback.

**Comment by ellisonbg** [comment]
Here is the travis config for our main JupyterLab repo:

https://github.com/jupyterlab/jupyterlab/blob/master/.travis.yml

We can make someone an Admin on this repo as needed to set this up.

**Comment by jasongrout** [comment]
Other prior art that might have interesting things to look at would be the conda-forge system: https://github.com/conda-forge/

**Comment by jaipreet-s** [comment]
Thanks all for the feedback and apologies for being late on this.

I plan to start by adding a simple unit test and having Travis run these unit tests on build. This will be a good forcing function for folks to add tests for incremental changes.

We can then expand this to do browser testing, deploy to PyPI, and so on.

@ellisonbg Could you make me an Admin so that I can setup Travis for this repo?

**Comment by blink1073** [comment]
@jaipreet-s, done!

**Comment by blink1073** [comment]
@jaipreet-s, if you send me an email I can invite you to the Appveyor team as well.

**Comment by blink1073** [comment]
The new GitHub Actions is another possible way to implement this:

https://blog.github.com/#github-actions-limited-public-beta

**Comment by echarles** [comment]
+1 for GitHub Actions

**Comment by ianhi** [comment]
I believe that https://github.com/jupyterlab/jupyterlab-git/pull/655 is an approach to this with github actions

**Comment by fcollonval** [comment]
CI and CD have both been integrated and used as GitHub actions. So I'm closing this.
