### ISSUE TITLE
Disabling branching UX

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#240]
The GitHub plugin disables branching if there are changes in the working tree.  This is intentional and desired as we don't want to encourage people to change branches while they're still changes in the current branch.

However, The current UX doesn't give feedback to the user why branching is disabled. This issue is to get some feedback on how to display this "error message" to the user.

One option is attached to show a modal.
![git_switch_branch](https://user-images.githubusercontent.com/43826141/46896699-58024d80-ce33-11e8-9284-1f6b2f571268.png)

cc: @tgeorgeux @neelamgehlot

**Comment by dhirschfeld** [comment]
Sounds good to me. What might work well in conjunction with this is the ability to stash the current changes. 

That's a workflow I use all the time - do some work, have to change branches, stash the current changes and come back to them after fixing whatever required me to change branches.

If we're aiming for awesome then a UI to show the stashes would also be great!

**Comment by ellisonbg** [comment]
Yeah, maybe in a first phase we can tell them why changing branches is disabled, and then in a second phase add stashing support.

**Comment by jaipreet-s** [comment]
Yes - stashing is a goal for a [later stage](https://github.com/jupyterlab/jupyterlab-git/blob/master/Design.md#first-stage-stretch-goals).

Also @weihwang,  do you have any feedback here?
