### ISSUE TITLE
A few recommendations to help organize work in a transparent manner

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#243]
Hi all, I am doing a bit of triage and review this morning and am finding a few things we could do to help the work in the repo to be more productive and transparent. 

* There are milestones for a 0.3, 0.4 and 0.5 release. It would be helpful if we could started to map the roadmap document onto those releases. This would include targeting any issues and PRs to these milestones and adding release dates and descriptions to the milestones.
* Let's open issues for each of the main things listed on the roadmap document (and target those to milestones).
* Assign labels to issues and PRs to help people navigate. We could use the jupyterlab label system here if that helps (https://github.com/jupyterlab/jupyterlab/labels).
* If we can go though the issue/PR backlog (there aren't very many) and assign labels, see what needs to be done, that would be really helpful.

**Comment by ellisonbg** [comment]
I have ported over the relevant jupyterlab labels to this repo:

https://github.com/jupyterlab/jupyterlab-git/labels

**Comment by jaipreet-s** [comment]
Thanks @ellisonbg !

We added issues for the 0.4 and 0.5 release here with the relevant tags [here](https://github.com/jupyterlab/jupyterlab-git/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4)

As an aside, I do not have permissions to add Labels/Milestones to issues (But @neelamgehlot does). Could I get the relevant permissions ? (Maybe @blink1073  can also help with that)

**Comment by blink1073** [comment]
@jaipreet-s, please check your email for an invite.

**Comment by jaipreet-s** [comment]
This was done a while back. Thanks all. Resolving now.
