### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab-git#251]
Master build is failing following #247: https://travis-ci.org/jupyterlab/jupyterlab-git/builds/442596499#L570.

It looks like handling of css imports needs to be added, cf https://github.com/jupyterlab/jupyterlab/blob/master/testutils/src/jest-config.ts#L9

**Comment by blink1073** [comment]
cc @neelamgehlot

**Comment by neelamgehlot** [comment]
I sent a pull request #254 to fix this.

Thanks @blink1073 !

**Comment by blink1073** [comment]
Fixed by #254
