### ISSUE TITLE
Should not this show current branch?

### ISSUE THREAD

**Issue by yelled1** [jupyterlab/jupyterlab-git#266]
When I do (on xterm) 
```$ git status
On branch hxxxxs-merge
```
But on the top left of the Git tab I see
```
production / master
History            master [\check][\+]
```
Shouldn't the tab display hxxxxs-merge as well?
May be I am missing something.
Thank u,

**Comment by weihwang** [comment]
@neelamgehlot are you able to reproduce this?

**Comment by neelamgehlot** [comment]
Yes, I was able to reproduce locally.

**Comment by neelamgehlot** [comment]
Hi @yelled1 ,

Could you confirm if you have the latest version of [jupyterlab-git](https://pypi.org/project/jupyterlab-git/) extension installed  ? If yes, what happens when you click on refresh button in the extension?

**Comment by yelled1** [comment]
Had to reinstall
$ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir:
/home/hoon/.local/share/virtualenvs/notebook-u24UL2Jw/share/jupyter/lab
        @jupyterlab/git v0.4.4  enabled  OK
        @jupyterlab/plotly-extension v0.18.0  enabled  OK
        jupyterlab_vim v0.10.1  enabled  OK
Keep on hitting the cicle on right with arrow (snake biting itself) but
still get below.
I am using pyenv with pipenv might be an issue?
Thanks,
[image: image.png]

**Comment by sntgluca** [comment]
I noticed this issue as well. The Git tab keeps showing the master branch even if I am on another branch

```
$ jupyter lab --version
0.35.4
$ jupyter labextension list 2>&1 | grep git
        @jupyterlab/git v0.5.0  enabled  OK
```

Happy to dig deeper if it would help
![screen shot 2019-01-08 at 14 33 38](https://user-images.githubusercontent.com/10941257/50833785-a51e8e80-1352-11e9-8fff-e18e3fded3dc.png)

**Comment by jaipreet-s** [comment]
Hi @sntgluca ,
What happens when you refresh the Git tab? Does it get to showing the current branch?

**Comment by sntgluca** [comment]
Hi @jaipreet-s,
sorry for the late answer. I keep seeing only the word "master", regardless.

I tried switching between tabs, and refreshing the whole page. Neither showed any change in the branch name. It's "master" in all cases

**Comment by sntgluca** [comment]
Dear @jaipreet-s and @yelled1 ,
just wanted to touch-base with this issue:

In the following configuration, things work perfectly for me:
- jupyterlab>=0.35.3
- jupyterlab-git==0.5.0
- jupyter labextension @jupyterlab/git v0.5.0 

Thank you for the great work!

**Comment by jaipreet-s** [comment]
Thanks!
