### ISSUE TITLE
Does the extension remove the outputs before a commit?

### ISSUE THREAD

**Issue by esride-stm** [jupyterlab/jupyterlab-git#267]
The output is of course a problem in version control. Does this extension remove the output before commiting the ocde to git?

**Comment by dhirschfeld** [comment]
Sometimes the output is what you want to commit and it's not the job of a source control tool to guess.

If you don't want to commit outputs then clear them before committing. If you want that done automatically - that's the job of a commit hook.

**Comment by esride-stm** [comment]
Ok. Thanks for your response. Thank you and good luck for the future
