### ISSUE TITLE
Diff any two nodes in history view

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-git#268]
Moved over from #245.

As it says in the title, it would be very convenient to be able to see the diff between any two points selected in the history view.

**Comment by jaipreet-s** [comment]
Hi @dhirschfeld , I'm consolidating discussions around visual diff into #317. Thanks

**Comment by fcollonval** [comment]
Now that #900 is in this should be easy to implement by defining a context menu in the history tab to select to node and call the `gitShowDiff` commands with the proper `DiffModel`

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab-git/pull/1108 and https://github.com/jupyterlab/jupyterlab-git/pull/1117
