### ISSUE TITLE
"@jupyterlab/git@0.5.0" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by sche0025** [jupyterlab/jupyterlab-git#283]
I tried to install the add-on, however, the following error msg popped up:

ubuntu@edward:~/internship/jupytergit$ sudo jupyter labextension install @jupyterlab/git
> /usr/bin/npm pack @jupyterlab/git
jupyterlab-git-0.5.0.tgz
Incompatible extension:

"@jupyterlab/git@0.5.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/console
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/terminal
>=0.17.3 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/filebrowser

Found compatible version: 0.1.3
> /usr/bin/npm pack @jupyterlab/git@0.1.3
jupyterlab-git-0.1.3.tgz
> node /usr/local/lib/python3.4/dist-packages/jupyterlab/staging/yarn.js install
/usr/local/lib/python3.4/dist-packages/jupyterlab/staging/yarn.js:1022
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
> node /usr/local/lib/python3.4/dist-packages/jupyterlab/staging/yarn.js run build:prod
/usr/local/lib/python3.4/dist-packages/jupyterlab/staging/yarn.js:1022
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

could someone tell me how to fix it?
thankx

**Comment by jaipreet-s** [comment]
What version of JupyterLab is this occurring with?

**Comment by sche0025** [comment]
0.33.12，  I tried to upgrade the jupyterlab, however I failed to find out the proper cmd to execute the update? Could you show me some insights?
Thank you so much

**Comment by jaipreet-s** [comment]
Did you try `pip install --upgrade jupyterlab`?
There are also detailed installation instructions in the [JupyterLab repo](https://github.com/jupyterlab/jupyterlab#pip)

**Comment by sche0025** [comment]
I tried, the version still remains 0.33, even if I executed : pip install --upgrade jupyterlab


ubuntu@edward:~/internship/jupytergit/jupyterlab-git$ pip install --upgrade jupyterlab
Requirement already up-to-date: jupyterlab in /usr/local/lib/python3.4/dist-packages (0.33.12)
Requirement already satisfied, skipping upgrade: notebook>=4.3.1 in /usr/local/lib/python3.4/dist-packages (from jupyterlab) (5.7.2)
Requirement already satisfied, skipping upgrade: ipython-genutils in /usr/local/lib/python3.4/dist-packages (from jupyterlab) (0.2.0)
Requirement already satisfied, skipping upgrade: jupyterlab-launcher<0.12.0,>=0.11.2 in /usr/local/lib/python3.4/dist-packages (from jupyterlab) (0.11.2)
Requirement already satisfied, skipping upgrade: jupyter-core>=4.4.0 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (4.4.0)
Requirement already satisfied, skipping upgrade: tornado>=4 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (5.1.1)
Requirement already satisfied, skipping upgrade: nbformat in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (4.4.0)
Requirement already satisfied, skipping upgrade: nbconvert in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (5.4.0)
Requirement already satisfied, skipping upgrade: traitlets>=4.2.1 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (4.3.2)
Requirement already satisfied, skipping upgrade: pyzmq>=17 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (17.1.2)
Requirement already satisfied, skipping upgrade: jinja2 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (2.10)
Requirement already satisfied, skipping upgrade: prometheus-client in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (0.4.2)
Requirement already satisfied, skipping upgrade: Send2Trash in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (1.5.0)
Requirement already satisfied, skipping upgrade: ipykernel in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (5.1.0)
Requirement already satisfied, skipping upgrade: terminado>=0.8.1 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (0.8.1)
Requirement already satisfied, skipping upgrade: jupyter-client>=5.2.0 in /usr/local/lib/python3.4/dist-packages (from notebook>=4.3.1->jupyterlab) (5.2.3)
Requirement already satisfied, skipping upgrade: jsonschema>=2.6.0 in /usr/local/lib/python3.4/dist-packages (from jupyterlab-launcher<0.12.0,>=0.11.2->jupyterlab) (2.6.0)
Requirement already satisfied, skipping upgrade: backports-abc>=0.4 in /usr/local/lib/python3.4/dist-packages (from tornado>=4->notebook>=4.3.1->jupyterlab) (0.5)
Requirement already satisfied, skipping upgrade: pygments in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (2.3.0)
Requirement already satisfied, skipping upgrade: mistune>=0.8.1 in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.8.4)
Requirement already satisfied, skipping upgrade: defusedxml in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.5.0)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.2.3)
Requirement already satisfied, skipping upgrade: testpath in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.4.2)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (1.4.2)
Requirement already satisfied, skipping upgrade: bleach in /usr/local/lib/python3.4/dist-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (3.0.2)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.4/dist-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (1.11.0)
Requirement already satisfied, skipping upgrade: decorator in /usr/local/lib/python3.4/dist-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (4.3.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.4/dist-packages (from jinja2->notebook>=4.3.1->jupyterlab) (1.1.0)
Requirement already satisfied, skipping upgrade: ipython>=5.0.0 in /usr/local/lib/python3.4/dist-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (6.5.0)
Requirement already satisfied, skipping upgrade: ptyprocess; os_name != "nt" in /usr/local/lib/python3.4/dist-packages (from terminado>=0.8.1->notebook>=4.3.1->jupyterlab) (0.6.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/local/lib/python3.4/dist-packages (from jupyter-client>=5.2.0->notebook>=4.3.1->jupyterlab) (2.7.5)
Requirement already satisfied, skipping upgrade: webencodings in /usr/local/lib/python3.4/dist-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab) (0.5.1)
Requirement already satisfied, skipping upgrade: pickleshare in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.7.5)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.13.1)
Requirement already satisfied, skipping upgrade: backcall in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
Requirement already satisfied, skipping upgrade: prompt-toolkit<2.0.0,>=1.0.15 in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (1.0.15)
Requirement already satisfied, skipping upgrade: pexpect; sys_platform != "win32" in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (4.6.0)
Requirement already satisfied, skipping upgrade: typing; python_version <= "3.4" in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (3.6.6)
Requirement already satisfied, skipping upgrade: simplegeneric>0.8 in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.8.1)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /usr/local/lib/python3.4/dist-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (40.6.2)
Requirement already satisfied, skipping upgrade: parso>=0.3.0 in /usr/local/lib/python3.4/dist-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.3.1)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/python3.4/dist-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.7)

**Comment by sche0025** [comment]
sovled, the version of jupyterlab caused this problem
