### ISSUE TITLE
Tagging version 0.5.0

### ISSUE THREAD

**Issue by dbast** [jupyterlab/jupyterlab-git#284]
Tagging the 0.5.0 release makes it easier to package it for conda etc. Thanks

**Comment by dbast** [comment]
Hi, is there anything to help here? npm/pypi already provide the version 0.5.0 since some months.
(though https://github.com/jupyterlab/jupyterlab-git/projects/2 is still open.)

**Comment by jaipreet-s** [comment]
Hi, we're just waiting to close on https://github.com/jupyterlab/jupyterlab-git/issues/271 before closing the 0.5 project

**Comment by jluttine** [comment]
I don't understand.. As you have 0.5.0 release in PyPI already, how does 0.5.0 still need some work? Shouldn't you just tag the commit that was pushed to PyPI as 0.5.0? Otherwise GitHub and PyPI releases will be inconsistent. Or am I missing something?

**Comment by jaipreet-s** [comment]
> I don't understand.. As you have 0.5.0 release in PyPI already, how does 0.5.0 still need some work?

I was responding to the observation that the `0.5` project is still open

> Shouldn't you just tag the commit that was pushed to PyPI as 0.5.0? Otherwise GitHub and PyPI releases will be inconsistent. Or am I missing something?

Done! https://github.com/jupyterlab/jupyterlab-git/commits/v0.5.0

**Comment by dbast** [comment]
Thanks!
