### ISSUE TITLE
Viewing repository history, the “last update” time was “<some large hexadecimal number> seconds ago

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#287]
### Steps to repro
* (Unable to confirm this)
* Create an empty AWS CodeCommit repo 
* Clone locally
* View the history tab

### Details

This was reported to me by a customer using a newly created,empty AWS CodeCommit repo and then viewing the History tab

```
Viewing repository history, the “last update” time was “<some large hexadecimal number> seconds ago
```

cc @saulshanabrook if you've seen this or are able to repro

**Comment by saulshanabrook** [comment]
I just created an empty git repo (`git init`) and tried to reproduce this but just got empty history:

<img width="650" alt="screen shot 2018-12-04 at 7 16 15 pm" src="https://user-images.githubusercontent.com/1186124/49481483-22f1f600-f7f9-11e8-81d7-3dd7379d19ec.png">

Any other ideas to reproduce?

**Comment by jaipreet-s** [comment]
No I haven't been able to repro either. This issue was reported to me by an internal user. 

Is there something in the way we get the `LastModifiedTime` that may cause it to get  `some large hexadecimal number`

**Comment by jaipreet-s** [comment]
Looks like we haven't been able to repro this and there haven't been any reports of it since then. I'm inclined to close this and re-open if required.
