### ISSUE TITLE
Git tab is not visible

### ISSUE THREAD

**Issue by abbasiehsan1991** [jupyterlab/jupyterlab-git#292]
I did these lines:
`jupyter labextension install @jupyterlab/git`

`pip install jupyterlab-git`
`jupyter serverextension enable --py jupyterlab_git`

But In my Jupyter, I couldn't see the Git tab on the left side of the screen.

**Comment by mschroen** [comment]
Was the build successful? (show your message log) 
Did you restart jupyter lab?

**Comment by abbasiehsan1991** [comment]
It shows this error:

`UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator==1.9.4
  - anaconda-nb-extensions
  - python=3
Use "conda info <package>" to see the dependencies for each package.`

**Comment by jaipreet-s** [comment]
> After run this code:
> `conda install anaconda-nb-extensions -c anaconda-nb-extensions `
> It shows this error:

I don't follow how this is related to the installation of this extension.  Could you try using a fresh Conda environment ?

**Comment by jaipreet-s** [comment]
Hi @abbasiehsan1991 ,
Were you able to get this resolved? Please see mchroen's recommendations as well.

**Comment by jaipreet-s** [comment]
I'm going to close this issue since it has had no traction for 3 months. Please open a new issue if there is still an issue.
