### ISSUE TITLE
delete/rename can't be done

### ISSUE THREAD

**Issue by neverload** [jupyterlab/jupyterlab-git#294]
delete/rename can't be done, deleted files can't be stages, and can't be pushed

**Comment by jaipreet-s** [comment]
I'm going to temporarily mark this as a `Bug` while we work to repro and determine the actual issue.

**Comment by saulshanabrook** [comment]
There was currently a bug with unstaging deleted files. I fixed this in https://github.com/jupyterlab/jupyterlab-git/pull/324.

Otherwise, the process of staging and unstaging deleted and renamed files seems to work on my end.
