### ISSUE TITLE
Where can I find logs generated by the Jupyterlab-git plugins

### ISSUE THREAD

**Issue by sntgluca** [jupyterlab/jupyterlab-git#298]
Hi!

I have been browsing a bit around without success, hence asking it here.

I am experiencing errors in some of the plugin functionalities, i.e. I cannot clone a repo from the git tab button (see attached pic).
It can easily be a problem with my configuration, but I cannot find any log supporting my troubleshooting.
Is there a way to capture the error causing the message?

Thank you!
Gianluca

![screen shot 2019-01-08 at 14 39 02](https://user-images.githubusercontent.com/10941257/50834064-5f15fa80-1353-11e9-980b-ac5c538fae48.png)

**Comment by jaipreet-s** [comment]
HI @sntgluca ,
What is the error message when you perform `git clone` from the Terminal? Ideally, the Git clone button should propagate the error message you get from the CLI.

**Comment by dhirschfeld** [comment]
> *Ideally, the Git clone button should propagate the error message you get from the CLI*

:+1:

Maybe the dialog can have an expandable `details` box with the output of the command?

**Comment by sntgluca** [comment]
Hi @jaipreet-s ,
the weird thing is that from the terminal I don't have any error. It just works.
I tried `git clone ...`, `git pull` etc. without any problem.

Naturally, the whole point for me is to stick to the plugin.

I didn't change the logging level from the server. I could have thought about that myself really... I will try to increase it and see what comes out.

I like @dhirschfeld's idea actually...

**Comment by jaipreet-s** [comment]
Would you be able to share the full command that you are running for `git clone $repo` - If we're able to repro locally then we can debug better.

**Comment by sntgluca** [comment]
Dear @jaipreet-s ,
Actually, just as an example I can clone this very repository from a JupyterLab terminal emulator (as in the last screenshot)

```git clone https://github.com/jupyterlab/jupyterlab-git.git
Cloning into 'jupyterlab-git'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 3535 (delta 5), reused 11 (delta 4), pack-reused 3519
Receiving objects: 100% (3535/3535), 896.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2094/2094), done.
```
When I try cloning `https://github.com/jupyterlab/jupyterlab-git.git` from the plugin, the error still occurs (sorry for the number of screenshots but I don't see any other way to prove my point)
![screen shot 2019-01-11 at 18 16 59](https://user-images.githubusercontent.com/10941257/51049399-0c944280-15ce-11e9-9072-d5900ffc3412.png)
![screen shot 2019-01-11 at 18 17 08](https://user-images.githubusercontent.com/10941257/51050059-deaffd80-15cf-11e9-9523-fee5ece6ecd6.png)
![screen shot 2019-01-11 at 18 17 24](https://user-images.githubusercontent.com/10941257/51050061-e1aaee00-15cf-11e9-961e-ee905e4ab3fc.png)

**Comment by sntgluca** [comment]
I can find an interesting error in the logs when I try to push/pull (but not when I use `git clone`).

```
[E 2019-01-11 18:13:30.733 SingleUserLabApp web:1621] Uncaught exception POST /user/santagi4/git/push?1547226810715 (10.151.94.255)
    HTTPServerRequest(protocol='https', host='<HOSTNAME>', method='POST', uri='/user/santagi4/git/push?1547226810715', version='HTTP/1.1', remote_ip='<REMOTEIP>')
    Traceback (most recent call last):
      File "[...]/virtualenv/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "[...]virtualenv/lib/python3.6/site-packages/jupyterlab_git/handlers.py", line 337, in post
        origin = data["origin"]
    KeyError: 'origin'
```
I'd like to dig deeper into this error, but it's getting off-topic. The original question was about collecting the logs... Shall I open a new issue?

**Comment by sntgluca** [comment]
Final comment of the day. I don't think it matters, but it's worth to mention my configuration...
I am using JupyterHub and I am behind a proxy.
Both the Jupyter server and the terminal share the same proxy configuration.

**Comment by dirkcgrunwald** [comment]
I'm having this same problem - I can clone / etc from the terminal, but not through the jupyterhub interface. I'm using a zero-to-jupyterhub setup on Google GKE, latest release set up using helm.

**Comment by jaipreet-s** [comment]
> I'd like to dig deeper into this error, but it's getting off-topic. The original question was about collecting the logs... Shall I open a new issue?

The logs are present along with the logs generated by the Jupyter server. This would be either in the terminal window running the Jupyter server or in a file if you are pipe'ing the logs

**Comment by sntgluca** [comment]
Dear @jaipreet-s ,
I could find the logs, thank you. And the newest changes in the interface are actually helpful.

As per the second part of this thread, I noticed the work in jupyter-git==0.5.0 is actually working fine in my case.

Thank you! Do you have anything to add, or shall we close the thread?

**Comment by jaipreet-s** [comment]
Thanks for the update @sntgluca. I don't have anything to add, so let's close this thread!
