### ISSUE TITLE
Creating new branch does not work

### ISSUE THREAD

**Issue by n-a-sz** [jupyterlab/jupyterlab-git#300]
If I create a new branch via the UI - nothing happens visually (the new branch is not there and it says I'm still on master), while in the terminal I can confirm that the new branch was created and checked out.

On the console the next error message appeared:
TypeError: Cannot read property 'length' of undefined
    at GitPanel.<anonymous> (GitPanel.js:50)
    at Generator.next (<anonymous>)
    at fulfilled (GitPanel.js:4)

Version I have tested on: 0.5.0

**Comment by jaipreet-s** [comment]
Thanks for the report. I've added the appropriate labels to the issue and contributions are welcome!

**Comment by jaipreet-s** [comment]
If I understand this correctly, looks like the branch creation actually succeeded, but the UI did not immediately reflect the new branch change.

**Comment by n-a-sz** [comment]
@saulshanabrook hmm, now it also working for me. Maybe it was when my git was not configured properly? But even when unsetting every git config, it still works. Maybe it was some transient bug.

I'll let you know if I face the same issue again.
Thanks for checking!

**Comment by saulshanabrook** [comment]
@n-a-sz sounds good! Thanks for checking again.
