### ISSUE TITLE
Pull'ing with merge conflicts UX

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#301]
Creating this issue to hash out some ideas while dealing with merge conflicts

1.  Use clicks the `Pull` 
2. IF there are merge conflicts, 
    1. Manual merge: The files in question are opened up in the panel with traditional "merge markers"
    2. Visual merge:  The NBDime merge resolver UI is opened up in a panel 

CC @dimberman as we discussed this in person

**Comment by fcollonval** [comment]
Closing as covered by https://github.com/jupyterlab/jupyterlab-git/pull/1260
