### ISSUE TITLE
compatibility issue with jupyter lab version 1.0.0a1

### ISSUE THREAD

**Issue by kiranik** [jupyterlab/jupyterlab-git#303]
I installed Jupyter lab in developer mode(version=1.0.0a1). and tried to install jupyterlab-git from extensions manager in jupyter lab. It is causing the following compatibility errors.:
jupyterlab-git-0.5.0.tgz

Errored, use --debug for full output:
ValueError:
"@jupyterlab/git@0.5.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension              Package
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/terminal
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/filebrowser
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/apputils
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/console

**Comment by kiranik** [comment]
<img width="1651" alt="screen shot 2019-02-20 at 1 19 21 pm" src="https://user-images.githubusercontent.com/6435143/53075339-eccc3480-3512-11e9-981b-50b4bf1fb382.png">

**Comment by jaipreet-s** [comment]
Yes, I believe we just need to update our dependencies to enable the latest versions of JupyterLab

**Comment by madsi1m** [comment]
Any updates on v1.0.0 ?

**Comment by jaipreet-s** [comment]
Resolving in favor of #374
