### ISSUE TITLE
fatal:The current branch master has no upstream branch

### ISSUE THREAD

**Issue by HeisenbergK** [jupyterlab/jupyterlab-git#304]
Whenever I try to push, i get this message.
Then, I go Git>Open Terminal and run:
`git push origin master`
And everything works smoothly.

**Comment by jaipreet-s** [comment]
What happens if you do `git push` in the terminal? The Git plugin pushes to the currently set upstream, and this error is usually thrown when you do not have an upstream configured correctly.

**Comment by HeisenbergK** [comment]
I had not configured an upstream. I just it. I am now trying to push from jupyterlab again and the message is 

> The filename, directory name, or volume label syntax is incorrect
![annotation 2019-02-26 202212](https://user-images.githubusercontent.com/23245434/53436597-3a114000-3a04-11e9-984a-5d79d6edcb6b.jpg)

**Comment by dhirschfeld** [comment]
It's usually helpful if you provide more context than *I just did it* - e.g. copy and paste the exact commands you ran and the unabridged output.

Since we don't know what you *actually* did, could you paste the output of the following commands:
```
git remote -v
git branch -vv
```

**Comment by HeisenbergK** [comment]
You are correct. I am sorry. I added the upstream by running:
`git push --set-upstream origin master`

When I run `git remote -v`, I get:
`origin  https://github.com/HeisenbergK/SkinObs.git (fetch)
origin  https://github.com/HeisenbergK/SkinObs.git (push)`

When I run `git branch -vv`, I get:
`* master 3e44168 [origin/master: ahead 1] Added Kryoneri`

**Comment by cmosguy** [comment]
I am having the same issue, is there a solution to getting the UI to work for the push/pull instead of having to open the terminal?

**Comment by jaipreet-s** [comment]
@cmosguy: 

1. Could you provide the output of `git remote -v; git branch -vv`
2. Are you getting the exact same error message? `The filename, directory name, or volume...`

**Comment by cmosguy** [comment]
@jaipreet-s 

I am getting the following:
```
git remote -v
origin  git://snpsgit.internal.synopsys.com:NVM/nvm-case-support (fetch)
origin  git@snpsgit.internal.synopsys.com:NVM/nvm-case-support.git (push)
```
```

**Comment by petr-ponomarenko** [comment]
Had the same issue with "The current branch master has no upstream branch" on push into empty repo on AWS SageMaker JupyterLab. 

Going into Terminal, cd from home to SageMaker and than to my repo folder. Then `git push origin master` and after that GUI starts working for everything when a proper folder with repo is selected in the file browser extension. 

It looks like AWS SageMaker presents folder ~/SageMaker as home in the browser, while git extension considers ~/ to be home dir and as a result, it can not find the folder with git repo to push.

When I select another folder in the file browser extension and then go to the git extension and try to stage and push changes, it considers that selected folder to be git repo folder, and as it is not really git repo folder it throws push failed with no error message.

Hope this might help.

**Comment by bavaria95** [comment]
Any plans to fix this issue?

**Comment by larchiu** [comment]
You need to set your destination - this helped me:
https://techoverflow.net/2017/08/09/how-to-solve-git-fatal-no-configured-push-destination/

**Comment by liamraemclauchlan** [comment]
We are facing the same issue - however we don't have access to the terminal to run any git commands. Is there any way to do this completely via the UI?

**Comment by ianhi** [comment]
@liamraemclauchlan are you unable to open the jupyterlab terminal?
![image](https://user-images.githubusercontent.com/10111092/88939574-affe8400-d254-11ea-9269-46ff1d1a795e.png)

There is also a fix in the works for this from the UI: https://github.com/jupyterlab/jupyterlab-git/pull/412

**Comment by liamraemclauchlan** [comment]
No - we have disabled that explicitly for security purposes. Hence why any solution needs to be via the GUI. A user can create a new branch in the GUI but when they try to push it they receive the error `fatal: the current branch has no upstream branch`

**Comment by dhirschfeld** [comment]
@liamraemclauchlan - I'm curious how disabling the terminal improves security? If a user has a Python kernel on the system can't they do everything they could in the terminal?

**Comment by fcollonval** [comment]
> #412 might be exactly what we need

Yep

**Comment by liamraemclauchlan** [comment]
> @liamraemclauchlan - I'm curious how disabling the terminal improves security? If a user has a Python kernel on the system can't they do everything they could in the terminal?

🤷‍♂️  I'm just the engineer that implements the security team's requirements  😁
