### ISSUE TITLE
Touching base about upcoming JLab 1.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#305]
I wanted to open an issue to begin to track things that need to be addressed related to JupyterLab 1.0. We are closing in on releasing JupyterLab 1.0 in the coming months. Is there anything you are running into on the git extension that would require changes to JupyterLab leading up to the 1.0 release?

**Comment by jaipreet-s** [comment]
One known issue is #303 - The dependencies of this extension are pinned to older versions of JupyterLab.

We do depend on some  interfaces and events from the `FileManager` - I haven't kept up with how they've evolved in 1.0

**Comment by ellisonbg** [comment]
We can update the dependencies here after 1.0 is out - the only thing we need to confirm is that no changes are needed to JupyterLab and that any changes that have happened won't cause problems as we update things. I don't think there have been a ton of API changes that should affect this extension though.

**Comment by jaipreet-s** [comment]
We don't have changes JupyterLab changes required for the Git extension. We'll just update the dependencies when 1.0 is out.
