### ISSUE TITLE
@jupyterlab/git" is not a valid npm package

### ISSUE THREAD

**Issue by hugoJuhel** [jupyterlab/jupyterlab-git#306]
Hi,

I have successfully installed the git extension in the JupyterHub Docker . Both server and lab extensions are correctly detected from the docker : 

```root@jupyterhub:/usr/share# jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyterlab/git v0.5.0  enabled  OK
        @jupyterlab/toc v0.6.0  enabled  OK
        @krassowski/jupyterlab_go_to_definition v0.1.4  enabled  OK
        @oriolmirosa/jupyterlab_materialdarker v0.3.12  enabled  OK
        jupyterlab-drawio v0.5.0  enabled  OK
        jupyterlab_bokeh v0.6.3  enabled  OK
root@jupyterhub:/usr/share# jupyter serverextension list
config dir: /root/.jupyter
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git  OK
config dir: /opt/conda/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.35.4 OK

```
But, the extension's tab is not showed up in the jupyterlab. When I try to use the lab extension manager to 
directly install the git extension, i get the following error message : 

![image](https://user-images.githubusercontent.com/22279443/53845217-4a7e6900-3f76-11e9-99cc-ea9f5c61b034.png)

Do you know how the extension can be activated from the docker ? 

Thanks in advance.

**Comment by vidartf** [comment]
@hugoJuhel Does this error come when you open the extension manager, or when `@jupyterlab/git` is being installed? I suspect there might be an issue with the error reporting.

**Comment by hugoJuhel** [comment]
@vidartf thanks for your answer.

The error pop when I open the extension manager. The logs from the docker buildings does not show any error related to the extension's installation.

**Comment by vidartf** [comment]
@hugoJuhel Then it is probably an issue with the error reporting. I'll run some tests locally, and open up an issue/PR on jupyter lab if I can confirm it.

**Comment by hugoJuhel** [comment]
@vidartf  All right, Thanks a lot.  Telle me if you need some tests from my side.

**Comment by vidartf** [comment]
@hugoJuhel I'm struggling a bit in reproducing this. What is your `npm --version`?

**Comment by hugoJuhel** [comment]
@vidartf  I'm so sorry the problem was on my side. I had a DNS misconfiguration in the Docker service that was causing this issue. The jupyterlab error message was caused by the underlaying inability of the docker engine to reach the server.

**Comment by vidartf** [comment]
@hugoJuhel Sure. Thanks for getting back! I still think the error message was misleading, so I'm hoping to update that. But I agree this issue can be closed.
