### ISSUE TITLE
Make sidebar colors better for JupyterLab Dark

### ISSUE THREAD

**Issue by mwentzWW** [jupyterlab/jupyterlab-git#307]
I am using the built in JupyterLab Dark theme and the git sidebar doesn't match well with the colors. The History box is barely visible. Could there be a setting to adjust the colors easily or it auto-detect if the theme is JupyterLab Dar or JupyterLab Light?

Example of view:

![image](https://user-images.githubusercontent.com/31914755/54208315-a599e980-44a9-11e9-92e4-5ed01b35a004.png)

**Comment by jaipreet-s** [comment]
There need to be some changes done to the History tab other components to make them work better with the Dark Theme.
