### ISSUE TITLE
git branch - Delete local branch (Branch Management)

### ISSUE THREAD

**Issue by bmll-chris** [jupyterlab/jupyterlab-git#308]
Currently it is not possible to delete a local branch.  It would be useful to be able to do this from the GUI tab.

Proposal - In the git-tab, when a user clicks on a branch from the drop down list of available branches, a prompt box could be presented asking the user if they would like to checkout / delete / rename the branch.

**Comment by fcollonval** [comment]
To have a homogeneous UX, I propose adding a action button like the one for the file list to delete existing branch.
