### ISSUE TITLE
can't clone repo

### ISSUE THREAD

**Issue by zz40404991** [jupyterlab/jupyterlab-git#316]
Request URL: http://xxx.com:8000/user/admin/git/clone?1553533961259
Request Method: POST
Status Code: 404 Not Found

**Comment by jaipreet-s** [comment]
At a first glance, it appears that the `/git/clone` API path is not available on your server. Is your server extension updated to the latest version `0.5`?

```
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```

**Comment by jaipreet-s** [comment]
I'm going to close this since there hasn't been any updates. Please feel free to create a separate issue if required.
