### ISSUE TITLE
Visual diff UX and user stories

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#317]
This issue is meant to centralize the discussions around the experience visual diff.

1. The core part is a diff panel which shows a side-by-side diff across 2 versions powered by NBDime
    *  More UX discussions to follow
2. Use cases for "entry points" into this diff panel
    *  In the main Git panel, viewing changes in specific files in the "Changed" or "Staging" area
    *  In the Git History panel, viewing changes made in specific commits
    *  In the Git History panel, viewing changes in all commits made over the remote

3. Auxiliary use-cases
    *  Exporting a diff for sharing (such as HTML)

**Comment by vidartf** [comment]
I'm very interested in getting a smooth user experience here, so I'd be happy to participate in this discussion1

**Comment by vidartf** [comment]
Me and @jaipreet-s had a call today, and he shared some possible use cases, that we agreed seem to cover the main UX experience that we could think of (he said he would share here later).

We also touched on how to manage the dependency between jupyterlab-git and nbdime. To keep the issues separate, I created a new issue for that: https://github.com/jupyterlab/jupyterlab-git/issues/331

**Comment by jaipreet-s** [comment]
## UX

The base view is a "diff" panel that is invoked by actions from the Git extension. The screenshot below shows a right click option to diff a single file in the working tree

<img width="1221" alt="diff_with_panel" src="https://user-images.githubusercontent.com/43826141/55593896-6f3f3b00-56f2-11e9-8567-941d645876c5.png">

There are two additional entry points to view all changes in the "`Changed`" (Working Tree) and "`Staged`" (Index) section represented by the "`D`" button (Icon TBD)


<img width="510" alt="diff_staged" src="https://user-images.githubusercontent.com/43826141/55594035-f8567200-56f2-11e9-95c6-c643a83adbb0.png">

The remaining entry points are inside the `History` panel. The first extends the "detailed commit view" to show the diff of the changes made in single commit

<img width="381" alt="diff_single_history_commit" src="https://user-images.githubusercontent.com/43826141/55594028-f1c7fa80-56f2-11e9-8401-9824ee62c901.png">


The second entry point in the `History` panel shows the changes across all changes made over the currently set remote (Hidden if no remote is set)

![diff_changes_over_remote](https://user-images.githubusercontent.com/43826141/55594069-1ae88b00-56f3-11e9-85af-eaf20558dc22.png)

**Comment by jaipreet-s** [comment]
@weihwang and I had a discussion today around UX.
- General
   - Right align all button actions
- **Individual file diff view**
   - Keep the Right Click menu item for Diff
   - Add a button to the menu which shows on hover of each file
- **Changed/Staged section** + **History single commit view**
   - William will help with an icon for Git Diff
- History  
   - We decided to rename the _diff changes over remote_ button to _Diff Local Changes_ and right align it
   - Add a tooltip text to explain what this text explains
- NBDime Diff Panel
   - William will suggest further changes after another review and optionally post some additional UX mocks
   - For showing diff across multiple files, the proposal is to wrap the NBDime Diff Widget inside a collapsible accordion view for each file

**Comment by weihwang** [comment]
Some icon exploration: 
![image](https://user-images.githubusercontent.com/551333/55819721-374b4580-5aae-11e9-95ab-be1bb5b768b0.png)

**Comment by weihwang** [comment]
![image](https://user-images.githubusercontent.com/551333/55819744-4631f800-5aae-11e9-8749-e6b3e37643b1.png)
![image](https://user-images.githubusercontent.com/551333/55819746-492ce880-5aae-11e9-883d-10e20302ebdd.png)

**Comment by weihwang** [comment]
Here's an initial draft for the diff view improvements:
![image](https://user-images.githubusercontent.com/551333/55837748-206d1900-5ad7-11e9-9106-4f517b5e2783.png)

**Comment by weihwang** [comment]
![image](https://user-images.githubusercontent.com/551333/55837889-8659a080-5ad7-11e9-9097-78e8bb0e4cc2.png)
Alternative version that has a more explicit "Show" action on hidden unchanged cells

**Comment by weihwang** [comment]
Proposal for changed output: 
![image](https://user-images.githubusercontent.com/551333/55839643-6f1db180-5add-11e9-8924-edceef8b8f0a.png)

**Comment by jaipreet-s** [comment]
LGTM William.

@vidartf : I'm expecting these changes flow back into the NBDime Diff Widgets. Do you have any feedback on the UX?

**Comment by vidartf** [comment]
All UX improvements to nbdime are welcome (preferably as issues on the nbdime repo)! We've been trying to get a UX person affiliated with project Jupyter to have a look at it for years with no success (and for this reason kept things simple but clunky). All of this looks like a good start.

@weihwang Do you want to open one or more issues on https://github.com/jupyter/nbdime/ ? I'm not sure if it makes sense with the multi-file view there or not yet, but the other things are reasonable. Putting it on the nbdime repo will also ensure that we can get visibility and feedback from others :)

**Comment by jaipreet-s** [comment]
I've moved over the UX changes to the visual diff extension here https://github.com/jupyter/nbdime/issues/469

Apart from that, looks like we're in agreement on the UX, so I'm good to resolve this issue and taken any NBDime Widget UX improvements on the nbdime repo. Thanks @weihwang @vidartf !
