### ISSUE TITLE
Success/Fail message when pushing/pulling to/from a remote repository  

### ISSUE THREAD

**Issue by wajditcb** [jupyterlab/jupyterlab-git#323]
I installed the extension and it works perfectly. I would suggest to add a Success/Fail message when working with remote repositories.

No feedback after clicking on pull or push buttons is somehow frustrating :)

**Comment by jaipreet-s** [comment]
Hm good suggestion! Happy to take contributions if you would like want to have a stab at this :)

**Comment by dkipping** [comment]
At least when the authentication fails there already exists an error message for the push.
![image](https://user-images.githubusercontent.com/11467327/55794045-8c925180-5ac4-11e9-85ee-f53cf5d3a1c9.png)

So adding a notification on success or on other errors which might not be handled should be doable.

**Comment by jaipreet-s** [comment]
Agreed. Another enhancement would be to show a spinner while the request to the remote is in progress.

**Comment by jaipreet-s** [comment]
@wajditcb : This has been merged as part of #340 and will be available in the next release. If you wish you use this in the meantime, you can follow the installation instructions to build from source.

Thanks!
