### ISSUE TITLE
ANSI color escape codes not handled correctly

### ISSUE THREAD

**Issue by dleen** [jupyterlab/jupyterlab-git#325]
In git I am in a detached HEAD state for a particular repository:

```
HEAD detached at neelamg/headless-browser-testing
```

In my terminal the string `HEAD detached at` is displayed in red text using the ANSI codes e.g. `printf "\033[31mHello World\033[0m"` will display in red. However because of this (at least this is what I think is the issue) in the git plugin the branch is displayed as:

```
[7;33m(HEAD detached at neelamg/headless-browser-testing) [m
```

**Comment by telamonian** [comment]
In theory, fixed by the change in how branch name fetching is handled in #469
