### ISSUE TITLE
Dark theme git icons needed

### ISSUE THREAD

**Issue by dleen** [jupyterlab/jupyterlab-git#329]
As referenced in #326 we need a dark theme git icon.

@jaipreet-s Can you clarify exactly which icons you were talking about?

**Comment by jaipreet-s** [comment]
Thanks for creating this.  I noticed we could do with more icons as well to enhance the visual experience. I'll combine them here

1. Git left side bar icon in Dark theme
2. File extension icons
    * ipynb, ts, tsx, yarn.lock, yml
3. Git diff icon

**Comment by weihwang** [comment]
Shared side bar icon and diff icons with @jaipreet-s but will need examples of the ipynb, ts, tsx, yarn.lock, yml icons in SVG so I can convert them

**Comment by telamonian** [comment]
Superseded by #429
