### ISSUE TITLE
Dependency between jupyterlab-git and nbdime

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab-git#331]
Me and @jaipreet-s had a call today, trying to synchronize on diffs for notebooks in jupyterlab-git using nbdime. One of the points that was discussed was how to manage the dependency between the two packages (jupyterlab-git and nbdime). Here, we see two possible options:

1. jupyterlab-git uses nbdime as a library. Here, the nbdime server extension, and the nbdime JS library package, are dependencies of the jupyterlab-git packages. The nbdime server extension is left as is (but with a PR to allow the diff API to accept git refs). jupyterlab-git then uses the exposed classes and functions in the nbdime JS library to build and show the diff widget.

2. Following the pattern in #200, the jupyterlab-git lab plugin provides an interface that other plugins can use to register themselves as diff providers for various file extensions. Here, the only direct dependency would be from nbdime's lab extension package on jupyterlab-git (to get the token). Nbdime's lab extension would then have an optional dependency on the jupyterlab-git plugin. For convenience of distribution, jupyterlab-git's Python package would likely have a dependency on nbdime's Python package, but this would only be to ensure that nbdime is present by default.

In terms of pros and cons, both alternatives are workable, but have different aspects related to maintenance and extensibility. I'll leave the discussion of those to comments below.

**Comment by vidartf** [comment]
For point 1 (library dependency), the pros and cons that I can think of:
- Pros:
  - Little maintenance overhead in nbdime.
  - jupyterlab-git has full control of the nbdime frontend.
  - Conceptually simple.

- Cons:
  - Any API changes to the nbdime JS library package (nbdime.js from here on) can lead to needed changes in jupyterlab-git. With proper semver discipline, this should at least not break any deployments, but can cause maintenance overhead in jupyterlab-git.
  - Both python and jupyterlab prefers packages to be deduped, so there might be some version fighting if jupyter-lab git pins its version dependency.

**Comment by vidartf** [comment]
For point 2 (lab plugin dependency), the pros and cons that I can think of:
- Pros:
  - Little maintenance overhead in jupyterlab-git.
  - Clear separation between responsibilities (diff providers simply display the diff of a single file for two git refs).
  - Extensible. It would easy for someone else to add a diff provider e.g. for Microsoft Word files, without needing changes to jupyterlab-git.

- Cons:
  - Any major version bumps to jupyterlab-git would require a new release of the nbdime labextension. The size of this con depends on which factors would cause a major version bump for jupyterlab-git.
  - There might be some distribution/dependency challenges with ensuring nbdime is available by default. For up-to-date pip/notebook versions, installing nbdime with pip currently enables the jupyterlab extension by default, so this might not be a huge pain, but there are always corner cases..

**Comment by jaipreet-s** [comment]
Thanks for the summary, Vidar!

> jupyterlab-git uses nbdime as a library. Here, the nbdime server extension, and the nbdime JS library package, are dependencies of the jupyterlab-git packages. The nbdime server extension is left as is (but with a PR to allow the diff API to accept git refs). jupyterlab-git then uses the exposed classes and functions in the nbdime JS library to build and show the diff widget.

To add here, the intention is to make nbdime the canonical source of notebooks diffs both on the server API side as well as the  visual UI experience. 
The server extension will be expanded to allow git refs (enabling use cases like viewing diffs for staged, working tree, single commit, multiple commits) and any consumer can choose to use the server by itself as well as well. 
The frontend also could be expanded provide a compose-able widget/component that can be plugged into any existing UI (such as this Git extension ) to render diffs.  

A consumer could choose  to use either just the server part or the bundled experience with the widget/component  visual experience.

**Comment by jaipreet-s** [comment]
> For point 2 (lab plugin dependency), the pros and cons that I can think of:
> 
> * Pros:
>   
>   * Little maintenance overhead in jupyterlab-git.
>   * Clear separation between responsibilities (diff providers simply display the diff of a single file for two git refs).
>   * Extensible. It would easy for someone else to add a diff provider e.g. for Microsoft Word files, without needing changes to jupyterlab-git.
> * Cons:
>   
>   * Any major version bumps to jupyterlab-git would require a new release of the nbdime labextension. The size of this con depends on which factors would cause a major version bump for jupyterlab-git.
>   * There might be some distribution/dependency challenges with ensuring nbdime is available by default. For up-to-date pip/notebook versions, installing nbdime with pip currently enables the jupyterlab extension by default, so this might not be a huge pain, but there are always corner cases..

A pro here is also the extensibility and composability. The diff UI component/widget will be vended by nbdime and the Git extension will be a thin layer over it to ensure that each entry point passes the correct git refs/index/working tree. Now this component/widget has the benegit to plugged into any other UI (e.g. nteract) to get the notebook render by passing the correct parameter.

I do believe the first con is valid for both approaches. Either nbdime -> jupyter-lab git dependency will need to be maintained via semver for the second approach or vice versa for the first one.

**Comment by jaipreet-s** [comment]
> For point 2 (lab plugin dependency), the pros and cons that I can think of:

I am going to be looking into this a bit more today. More to come!

**Comment by vidartf** [comment]
I did some work previously on getting nbdime to work with pattern 2 above (for #200). I recently pushed this to my nbdime fork: https://github.com/jupyter/nbdime/compare/master...vidartf:jlgit

**Comment by jaipreet-s** [comment]
For pattern 2, I like the idea of having a registry of _diff providers_ and the decoupling between the git extension and each _diff provider_. However, the problem here is that each _diff provider_ may choose to implement the callback very differently.  For example, in the code across  #200 and https://github.com/jupyter/nbdime/compare/master...vidartf:jlgit , the diff for ipynb files is being provided by adding a panel to the JupyterLab app, and for other files by executing _git diff_ inside the JupyterLab terminal, which leads a very different UX for both cases. Even in the case where both diff providers open a panel, the look-and-feel could be very different.

The difficulty of maintaining UI cohesiveness and a standard look-and-feel make me not in favor of pattern 2.

An enhancement to pattern 1 would be to add an adapter layer between each diff provider and the Git extension. 

- jupyterlab-git defines the adapter interface
- each diff provider implements the adapter interface. This implementation can either be in a separate package or just inside the Git extention itself, to start with

![jupyterlab_git](https://user-images.githubusercontent.com/43826141/55838402-354aac00-5ad9-11e9-888d-6da3dca20c22.png)

**Comment by vidartf** [comment]
@jaipreet-s As far as I understand you, you are proposing to have an adapter interface for other extensions to provide diffing capabilities. What would the signature of this interface be? Maybe similar to now, but returning a widget instead?

**Comment by jaipreet-s** [comment]
Yes. Widget is a bit broad so likely scoped down a bit. The intention is the Git extension is in control of the layout and look-and-feel.


```

class DiffAdapter {

    contructor(fileExt: string) {}

    def doDiff (prevRevision: string, currRevision: string) : DiffWidget
}
```

I haven't finalized the exact Interface and was considering that an implementation detail. I can have further discussions on the code over a PR, provided the high level approach looks right.

**Comment by jaipreet-s** [comment]
@vidartf : IMO we've resolved sufficient high level questions that we can start implementing. I've enumerated the work across NBDime and the Git extension below.  If this looks good, I can start creating the relevant line items in either of the repos. Thanks!!


[] [NBDime] Server API to accept git refs and also work for staging area/index diffs 
[] [NBDime] Any Diff Widget changes required based on above server API
[] [NBDime] UX improvements as suggested in https://github.com/jupyter/nbdime/issues/469
[] [Git Ext] Add an adapter around NBDime Diff Widget above
[] [Git Ext] Integrate all "entry points" enumerated in https://github.com/jupyterlab/jupyterlab-git/issues/317 with NBDime Diff Widget/Adapter

**Comment by telamonian** [comment]
It seems like this issue did indeed get resolved at some point, since nbdime and jupyterlab-git do now play nicely with one another.

@vidartf @jaipreet-s @fcollonval can any of you comment upon the resolution of/close this issue?

**Comment by jaipreet-s** [comment]
Yes, this was meant to track design discussions between nbdime and jupyterlab-git, which is now done. Resolving!
