### ISSUE TITLE
is there a docker version?

### ISSUE THREAD

**Issue by roccqqck** [jupyterlab/jupyterlab-git#335]
sorry its not a issue
but i have to ask

there is THE jupyter docker
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile
almost every jupyter docker build FROM this one

is that possible to install jupyterlab-git in  jupyter/base-notebook/dockerfile

that would be helpful

**Comment by saulshanabrook** [comment]
@roccqqck Yep, that is possible!

I would try following  [their instructions on running `pip install` in a child image](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-pip-install-or-conda-install-in-a-child-docker-image) but replace pip install with `jupyter labextension install jupyterlab-git`.

**Comment by roccqqck** [comment]
actually i have tried to install jupyterlab-git in the jupyter/tensorflow-notebook container

it was not working


i followed this three command
$ jupyter labextension install @jupyterlab/git
$ pip install jupyterlab-git
$ jupyter serverextension enable --py jupyterlab_git
