### ISSUE TITLE
FYI: Used inside Google AI Platform

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-git#339]
Google just launched [a hosted JupyterLab service](https://cloud.google.com/ai-platform-notebooks/) and guess [what's included](https://cloud.google.com/ml-engine/docs/notebooks/save-to-github)?

<img width="587" alt="Screen Shot 2019-04-11 at 9 15 25 AM" src="https://user-images.githubusercontent.com/1186124/55960249-5a0a6500-5c3a-11e9-9ad0-502ce7567466.png">

**Comment by saulshanabrook** [comment]
They also added a "Git" menu that allows you to initialize the directory, which is pretty nice.

**Comment by jaipreet-s** [comment]
Yea I just saw this yesterday. Pretty cool!

AFAIK this is just the Git Menu which comes with the extension so AFAICT there aren't any features added on top.

![Screen Shot 2019-04-11 at 10 47 19 AM](https://user-images.githubusercontent.com/43826141/55979561-4fa29800-5c47-11e9-8c88-ed56bcf900d2.png)

**Comment by saulshanabrook** [comment]
Did they add the git init button the file browser?

**Comment by jaipreet-s** [comment]
> Did they add the git init button the file browser?

Which one are you talking about? 

- There's a [Git Clone ](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/gitClone.ts)button in the File Browser menu that is added by this extension
- There's an "Init" open in the Git menu

**Comment by saulshanabrook** [comment]
@jaipreet-s Ah yeah, you are totally right!
