### ISSUE TITLE
Open Terminal option in Git menu doesn't resolve Jupyter home dir

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#346]
The Open Terminal option does a "cd $REPONAME" which opens the terminal on the `home_dir`/$REPONAME

This doesn't factor in the base directory of the Jupyter server.

**Comment by mathematicalmichael** [comment]
I don't even see this option because the git menu refuses to line up with the navigation. 
I use the docker-stacks, so `/home/jovyan` is the default server entry point. Is that the problem?
