### ISSUE TITLE
UI to configure name and email settings for local user?

### ISSUE THREAD

**Issue by brylie** [jupyterlab/jupyterlab-git#351]
When committing to Git, it is important to have proper attribution. Git has two settings that must be changed before making an initial commit:

- `name`
- `email`

Please consider adding a UI that helps a user configure their `name` and `email` settings for Git, with particular consideration given to how JupyterLab may be used in multi-user environments.

## Quick references

- https://help.github.com/en/articles/setting-your-username-in-git
- https://help.github.com/en/articles/setting-your-commit-email-address-in-git

**Comment by jaipreet-s** [comment]
An incremental step could be adding an item under the Git menu with a link to this documentation.

![Screen Shot 2019-05-15 at 10 27 54 AM](https://user-images.githubusercontent.com/43826141/57796011-32f0f880-76fc-11e9-8054-2782e0e69412.png)

**Comment by brylie** [comment]
@jaipreet-s good idea. 

It is also worth mentioning that Jupyterlab-git plugin is installed in Amazon AWS EMR notebooks, so it might also be useful to allow this configuration via the UI (in case it is difficult to do via Jupyterlab terminal).
