### ISSUE TITLE
Default diff viewer

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#352]
Hey,

Work planned in #331 is awesome. I think it will be nice to provide directly within this extension a default diff viewer (supporting for instance only raw text diff).

The goals:
- Provide a default diff viewer usefull enough for raw text diff
- Provide an example how to implement the API resulting of #331 for diff viewer developers

Resources:
The [merge addon](https://codemirror.net/doc/manual.html#addon_merge) of CodeMirror could be the basis for such default viewer. See the demo: https://codemirror.net/demo/merge.html
Another candidate could be the [monaco diff viewer](https://microsoft.github.io/monaco-editor/).

Note
I hope to have time to look into this in June. Is there a plan for #331 completion?

**Comment by dhirschfeld** [comment]
The monaco diff viewer is *the* reason I use vscode - it's brilliant so I'd be very interested/excited if there were plans to use it in `jupyterlab-git`

**Comment by jaipreet-s** [comment]
Plain Text diff has been on the back of my mind but Notebook diff was first priority. Both CodeMirror and Monaco look promising. I also briefly looked at [diff-match-patch](https://github.com/google/diff-match-patch) as a general diff'ing library and then adding view layer on top of it.


> Is there a plan for #331 completion?

I hope to pick this up in the next couple of weeks so June should be good. Once we get the Notebook Diff in it'd be great to plaintext diff for a full fledged diff experience.

**Comment by jaipreet-s** [comment]
@timnlupo and I have been working on Plaintext diffs using Monaco and it has worked well so far. I'll ask him to put his WIP changes based off of #384

**Comment by telamonian** [comment]
This will be fixed once #406 is merged
