### ISSUE TITLE
Cannot open any repos due to PATH

### ISSUE THREAD

**Issue by mathematicalmichael** [jupyterlab/jupyterlab-git#353]
apologies if this is an existing issue, but I couldn't quite find reference to it.

I use docker-stacks, so all of my single-user servers launch up in `/home/jovyan`, and I think this is causing conflicts with the path that this extension is looking for? I keep being told to "find a repo" and no matter what I try I cannot get this extension to recognize one.

**Comment by saulshanabrook** [comment]
@mathematicalmichael Have you also you also installed the server extension? And the `.git` folder exists in the docker container?

**Comment by mathematicalmichael** [comment]
@saulshanabrook I followed the instructions in the README, which I do believe calls npm for the server extension. I believe the Lab version is 0.35.
The git folder does exist. Many do, but no matter where I navigate, the git tab never updates.

**Comment by saulshanabrook** [comment]
If you look at the browser console are there any errors listed?

**Comment by mathematicalmichael** [comment]
yup. sorry, I'm not a web developer, forgot that would probably be helpful.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
GitPanel.js:134 class NetworkError extends TypeError {
        /**
         * Create a new network error.
         */
        constructor(original) {
            super(original.message);
            this.stack = original.…
```

**Comment by saulshanabrook** [comment]
No worries! Could you see what file `404`ed? You might be able to see in the network tab or somewhere else in the console.

**Comment by mathematicalmichael** [comment]
looks like `git/all_history`

thanks for your responses and patience!

**Comment by saulshanabrook** [comment]
OK and if you run `jupyter serverextension list` then `jupyterlab_git` shows up there?

**Comment by saulshanabrook** [comment]
What server and port is it requesting for that file? Is it the same port as the rest of the requests?

**Comment by mathematicalmichael** [comment]
`jupyterlab_git` does show up! but it's in a different config directory ... would that have something to do with it? 

It's requesting at `/math/username` (`math` being the name of my hub), so it appears the ports are okay.

**Comment by saulshanabrook** [comment]
I think that is fine... And on the server are there any error logs? This is why my successful version of that connection looks like:

<img width="1479" alt="Screen Shot 2019-05-20 at 9 45 35 AM" src="https://user-images.githubusercontent.com/1186124/58026275-1978f380-7ae4-11e9-9a8d-084d02eb6ff8.png">


Even if I start the server not in a git repo, I get back a 200, with this body `{"code": 128, "command": "git rev-parse --show-toplevel", "message": "fatal: not a git repository (or any of the parent directories): .git\n"}` not a 404. So the issue is yeah it can't reach the server extension for some reason.

**Comment by mathematicalmichael** [comment]
thanks for explaining. I'm not 100% understanding of how these extensions function.
M¥ connection just looks like a bunch of tin dots, no green bars like you have.

the tab for git just keeps showing `/` no matter where I move around in the directory structure. Never changes. 

My theory is that this has something to do with how my `jupyterhub_config.py` sets up default entrypoints for users in the `/work` folder. The extension is clearly trying to request a folder called `git` at the "root" of my server, where no such file exists. I tried making `git/all_history` an empty file in my root directory and inside of work... still getting 404.

**Comment by saulshanabrook** [comment]
> The extension is clearly trying to request a folder called git at the "root" of my server, where no such file exists.

It is trying to request the `git/all_history` path, which should be handled by the server extension: https://github.com/jupyterlab/jupyterlab-git/blob/b3f3fbe4984e5b3f1f006936acf29f26a317a4ea/jupyterlab_git/handlers.py#L440

I don't use JupyterHub much so I am not sure of the usual pitfalls there. Could you try enabling the serverextension with `--sys-prefix`? https://stackoverflow.com/a/48621220/907060

**Comment by mathematicalmichael** [comment]
yup just tried that a couple times after finding https://github.com/jupyterlab/jupyterlab-git/issues/212
and it seems that's exactly what I'm running up against. 

After reading the stackoverflow post you linked to (thank you so much for finding that!), I tried the suggested directions and included the build in my Dockerfile rather than performing it inside the container (I included the `sys-prefix` syntax too). 

AND IT WORKED! So... lesson learned: Do not attempt to install extensions as a user of the container. Despite the fact that ... in theory... there shouldn't be a difference between running the command in the dockerfile and inside the container ... installing using the Dockerfile is what seemed to have done the trick. The config paths shown with `jupyter serverextension list` are all in the same place now... so maybe that has something to do with it? 

Thank you again so much for your time and patience. I really appreciate how helpful you have been in addressing my issue.

**Comment by saulshanabrook** [comment]
Cool, glad you got it working!

**Comment by mpilosov** [comment]
updating to jupyterlab 1.0 reintroduced this issue. Didn't want to raise a separate issue. `jupyter serverextension list` shows everything in the same path, but despite jupyterlab-git recognizing when I'm in a repo (the icon to clone grays out), the panel itself does not update. 

same situation, launching lab from hub.
