### ISSUE TITLE
Release to fix Windows issue

### ISSUE THREAD

**Issue by ameier38** [jupyterlab/jupyterlab-git#356]
Hi, I was wondering if you would be able to cut another minor release which would include the fix for windows (#344 )? Right now I have to build off of master and would rather point to a stable release from PyPi. Happy to help with any testing if needed.

**Comment by jaipreet-s** [comment]
Yes I am in favor of creating a new release for this and various other changes https://github.com/jupyterlab/jupyterlab-git/compare/v0.5.0...master

**Comment by jaipreet-s** [comment]
I found a bug that was introduced in a recent contribution. Here's a PR to fix that before we can release

#362

**Comment by jaipreet-s** [comment]
Release 0.6.0 done.
