### ISSUE TITLE
All clones with jupyterlab_git are failing (clones are OK from the terminal) - fix included

### ISSUE THREAD

**Issue by nibheis** [jupyterlab/jupyterlab-git#367]
Hello,

We recently noticed that clone actions are failing very quickly. We managed to track this issue down to the git.py file / clone(...) method:

p = subprocess.Popen(
            ['git', 'clone', unquote(repo_url)],
            shell=True,
            stdout=PIPE,
            stderr=PIPE,
            cwd=os.path.join(self.root_dir, current_path),
            env=env,
        )

Removing the 'shell=True' line makes the clone work again: the subprocess runs then as expected (on linux, behind a jupyter hub).

FYI: With 'shell=True', the following command get executed:
"/bin/sh -c git clone git_url" (=> returns git help, which is not what we want here)

Many thanks,
nibheis

**Comment by neiloncore** [comment]
I have the same problem but in my case the fix didn't work.

**Comment by nibheis** [comment]
Just to be sure: you need to restart your singleuser server after changing the line of code.

Also, you should make sure that the rest of the jlab-git interface is working (which was the case on our servers). If other git actions fails, that could be a different issue.

**Comment by neiloncore** [comment]
Hi nibheis,

I think my problem is related to AWS SSO rather than this particular issue. 

Thanks for the feedback though :)

**Comment by jaipreet-s** [comment]
This looks related to https://github.com/jupyterlab/jupyterlab-git/pull/362 and https://github.com/jupyterlab/jupyterlab-git/pull/344

**Comment by jaipreet-s** [comment]
* Code is pushed. If you wish to validate, you can use the latest build off master
* Will do a patch release early next week to fix this in PyPI

**Comment by jaipreet-s** [comment]
Version 0.6.1 released on PyPi
