### ISSUE TITLE
Checkout to remote branch gets always in detached state

### ISSUE THREAD

**Issue by DiegoPiloni** [jupyterlab/jupyterlab-git#369]
When a remote branch is selected it always get into detached state. In my opinion a simple improvement could be to change the behaviour this way: Instead of doing `git checkout <remote>/<branchname>` execute `git checkout <branchname>`.

**Note**: This works when there is only one remote. If there are more remotes the behaviour would keep the same (getting into detached state).

**Comment by DiegoPiloni** [comment]
PR associated: #370

**Comment by jaipreet-s** [comment]
cc @jindingars

**Comment by nibheis** [comment]
I just did a PR, #385 to fix this issue in a, hopefully, better way than #370.
I'm not waiting for some feedback.

**Comment by fcollonval** [comment]
Fixes by #385
