### ISSUE TITLE
Update clone dialog text with more generic URI

### ISSUE THREAD

**Issue by danielgruesso** [jupyterlab/jupyterlab-git#372]
GitLab provides an easy way to deploy JupyterHub to your k8s cluster. As part of our 12.0 release, we are including this integration by default with the Jupyter chart, so users can version their notebooks and save in their git repo.

The current clone dialog uses a `github.com` URI example:

![image](https://user-images.githubusercontent.com/7226574/60023260-74fa4c00-9663-11e9-9e50-b644ecbfa0df.png)

We'd like to make clear to users that the integration works with any git host by updating the placeholder text. I've opened https://github.com/jupyterlab/jupyterlab-git/pull/371 to this effect. Thanks.

**Comment by jaipreet-s** [comment]
Related PR merged. Closing.
