### ISSUE TITLE
Icon misalignment in Firefox

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#377]
Awesome @fcollonval, thanks for fixing the tests.

The icons in Firefox look a bit misaligned now, is that a side effect of this change?. I'm good to merge otherwise.

![Screen Shot 2019-07-05 at 11 12 14 AM](https://user-images.githubusercontent.com/43826141/60739229-01372980-9f16-11e9-8d34-ba29e773407a.png)

_Originally posted by @jaipreet-s in https://github.com/jupyterlab/jupyterlab-git/pull/374#issuecomment-508831649_

**Comment by jaipreet-s** [comment]
From @fcollonval  in https://github.com/jupyterlab/jupyterlab-git/pull/374#issuecomment-508937255


> Hey @jaipreet-s, I had a quick look. Its seems that Chrome is adding style to the button like align-items: flex-start automagically (style comes from user agent stylesheet). But this is not done in Firefox. I try playing with the align-items in Firefox but the vertical alignment didn't change.
This should come from elsewhere as in this PR I only changed the background-size attribute on the problematic buttons.

**Comment by fcollonval** [comment]
With 0.10.0, lots of style issues have been fixed. I don't have icons misalignment on Firefox with it.
