### ISSUE TITLE
[UX] Changed files always includes a scrollbar

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-git#378]
As it says in the title - e.g.

![image](https://user-images.githubusercontent.com/881019/60932093-d6771780-a2ff-11e9-8ec7-5b20bd0a7672.png)

Even when there's plenty of vertical space the scrollbar is always showing.

JLab 1.0 with latest `jupyterlab-git` installed today.

**Comment by telamonian** [comment]
This has been fixed (in #438, I think?)
