### ISSUE TITLE
[UX] icons in history view

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-git#380]
The icons should have tooltips as it's not entirely obvious what they mean:

![image](https://user-images.githubusercontent.com/881019/60932708-949ba080-a302-11e9-93d0-e7c07a703423.png)

I assume the +/- means lines added/removed?

The circles around the +/- seem a bit redundant/ugly? Simple + and - symbols would probably suffice and to reinforce what they mean standard green/red colours could be used too.

I'm not sure the revert / delete functionality is useful? I ~never need to delete a commit and if I wanted to revert to a particular commit I would just use `git reset --hard sha`. Why does the UI want a commit message to revert to a commit - what is it actually doing?

I also very rarely want to revert to a commit, but I occasionally want to checkout code at a particular commit. Rather than a revert buttom, perhaps a checkout button would be more generally useful.

In contrast, GitHub has 3 buttons:
1. Copy sha
> Very useful for working alongside in a terminal
2. View diff
> The most important functionality! Being tracked in #252 
3. Checkout (browse) code at this sha
> Also very useful to understand the state of the repo at that point in time

**Comment by fcollonval** [comment]
@telamonian @kgryte I think this can be close
