### ISSUE TITLE
Overly aggressive disabling of branching

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab-git#386]
Thanks for all the work on this extension, it's coming along nicely!

I often will make uncommited changes to a repository, then later decide I want to commit them in a new branch. Git allows one to checkout a new branch when there are uncommited changes (or even staged changes), and then proceed as normal. However, when I try that in the UI, I get an error message saying 
```
Creating new branch disabled

You have staged changes in current branch. Please commit / discard them before creating a new branch.
```
Is this disabling of branching really necessary? It's not a hard git requirement (also, note that the error message is incorrect if there are unstaged changes). Apologies if there is already an issue discussing this, I didn't find one after a quick search.

**Comment by jaipreet-s** [comment]
@ian-r-rose, IIRC the intention was to discourage users from switching branches when the current branch has un-commited or un-stashed changes to prevent inadvertently carry code between branches. 

We can relax this requirement to a "warning" - The error popup should just warn the user that there are uncommited or unstashed changes, and ask for a confirmation before creating the new branch.

**Comment by telamonian** [comment]
@jaipreet-s Features to make things easier for git novices are good! But they definitely shouldn't be the default behavior, especially if they undercut the basic functionality of git. Instead, we should in general aim to have our UI offer functionality comparable to that of the underlying `git` cmd line tool (though complete parity is, of course, a long term goal). Breaking git by default seems like an anti-pattern to me.

I've added a PR (#450) that turns off the disabling of branch ops by default, but leaves the current behavior in via a flag in user settings.

**Comment by fcollonval** [comment]
@telamonian Thx for the PR. I have one question reading comments here and your PR. It seems more interesting to allow branch creation/switch all the time. But by default, a dialog would be raised asking confirmation and emphasized it is discouraged (i.e. with default answer "Don't carry the branch action"). And your proposal of introducing a setting could be kept to deactivate that confirmation request.

**Comment by telamonian** [comment]
@fcollonval Even better would be the dialog that Github-desktop pops up in the same situation:

![image](https://user-images.githubusercontent.com/2263641/68754803-66daa700-05d5-11ea-9138-4bc77da5568d.png)

for which we'd also need some kind of autostash enable/disable. Shouldn't be too hard, but that's fodder for future PRs. The implementation for #450 is dead simple, and I think is a good first step.

I could also be convinced that the `"disableBranchWithChanges"` option isn't needed.

**Comment by fcollonval** [comment]
So let's go for prompting a warning dialog and not using a setting. This is simple and does not require advanced users to know about a setting. users tend to go to the documentation or the git repository rather that looking for settings.

**Comment by dhirschfeld** [comment]
As a power user, I *hate* unnecessary dialogs that you have to click through so I'd very much appreciate a setting to disable that.
