### ISSUE TITLE
Behavior design (under a repo vs non-repo)

### ISSUE THREAD

**Issue by zzhangjii** [jupyterlab/jupyterlab-git#39]
Currently the simple version of git-plugin works fine inside a git-repo, but we are still debating on the behavior in a non-git-repo.
I kind of prefer this behavior where jupyterlab-filebrowser determines the current directory for git:
for example:
I open the jupyterlab under Folder0 (non-repo), this folder has multiple child folders: folder1(repo), folder2(non-repo), folder3(repo);

at the beginning, jupyterlab-filebrowser shows Folder0, since it's not a repo, git-plugin will not work. warning user it's not a repo, (it may suggest user create a repo?)

user clicks into folder 1 in jupyterlab-filebrowser, now jupyterlab-filebrowser shows folder1, since it's a repo, git-plugin will work for this repo; similarly, it will also work in folder3;

user goes back to Folder0 and then clicks into folder2, since it's not a repo, git-plugin won't work just like under Folder0;

**Comment by ddavidebor** [comment]
I'd suggest enabling only the `init` command on a non-repo directory.

**Comment by zzhangjii** [comment]
we had thought about that, 
in my example above, what will happen if we init Folder0? will folder1 and folder 3 be affected?

**Comment by ddavidebor** [comment]
if you just init no, but of course other operations might

**Comment by zzhangjii** [comment]
Currently, the git plugin behaves as described above, meaning  jupyterlab-filebrowser determines the current directory path for git,
based on this path, we find the top level of the current repo,
then, pass this top-level-repo-path as cwd for git commands
