### ISSUE TITLE
Clicking on files in the Git panel should open them in the dock panel.

### ISSUE THREAD

**Issue by zzhangjii** [jupyterlab/jupyterlab-git#40]
another behavior design for git-plugin

inside git_plugin, it only shows filenames and path for  those uncommitted files, unstaged files, untracked files,
If it's necessary for users to be able to directly open those files (through double click) inside git_plugin,

and what if it's a folder here??

**Comment by ddavidebor** [comment]
Git does not track empty directories

**Comment by zzhangjii** [comment]
I mean a folder full of files,  if we display all of the files inside it, it looks really messy( just like visual studio)

**Comment by ddavidebor** [comment]
You should have in that case a "stage all" button to allow to throw everything into one commit. Happens for example if the user moves around a directory containing many files.

**Comment by zzhangjii** [comment]
Done:
in git plugin, double click on a file will open it in the main panel, but not work for folders, 
consider issue closed for now, will wait for the final designs in the future.
