### ISSUE TITLE
ui breaks if there's a local branch that have a deleted remote reference

### ISSUE THREAD

**Issue by alienczf** [jupyterlab/jupyterlab-git#402]
When remote branch have been deleted while local branch still persists, the ui extension fails to load and produces the default not a repo message.

To reproduce existing bug:
```
git branch exist-on-local-but-deleted-on-remote-branch
git push --set-upstream origin exist-on-local-but-deleted-on-remote-branch
git push --delete origin exist-on-local-but-deleted-on-remote-branch
# refresh jupyterlab-git to show generic `you aren't in a git repository` message
```
this is caused by calling
`git rev-parse --abbrev-ref exist-on-local-but-deleted-on-remote-branch@{upstream}`
which returns
```
fatal: ambiguous argument 'exist-on-local-but-deleted-on-remote-branch@{upstream}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

this small MR address the issue by addling the handle for this error message, which should `return None` for the upstream message instead of throwing an Exception which breaks `branch` function at `jupyterlab_git/git.py:335`

Furnished details in this PR: https://github.com/jupyterlab/jupyterlab-git/pull/400

**Comment by fcollonval** [comment]
Associated PR #400 merged => closing this
