### ISSUE TITLE
jupyterlab-git always differs the same file

### ISSUE THREAD

**Issue by qjtongkai** [jupyterlab/jupyterlab-git#404]
I installed jupyterlab-git and nbdime in my jupyter project. 

scenario:

step 1:
I had two files in my repo and changed them:
abc.ipynb
efg.ipynb

step 2:
I find these two files in git tab. 
Differ abc.ipynb **first**. Then a tab opened in right window for abc.ipynb.
Differ efg.ipynb **second**. Then Then a tab opened in right window for efg.ipynb. **But the content of this tab were accutally for the first file abc.ipynb I have differed.**

It always returns difference result for abc.ipynb if I try to differ any files in my repo.

<img width="1005" alt="屏幕快照 2019-09-02 下午6 10 50" src="https://user-images.githubusercontent.com/49664646/64107638-8ff8e300-cdad-11e9-87ee-13222754c829.png">
<img width="1325" alt="屏幕快照 2019-09-02 下午6 11 09" src="https://user-images.githubusercontent.com/49664646/64107656-9ab37800-cdad-11e9-9545-fe37ee75f7b6.png">

**Comment by NahsiN** [comment]
I have the same issue.

**Comment by fcollonval** [comment]
Hello thanks for reporting the bug. It has been corrected in #401 but the correction had not yet been released.

**Comment by jaipreet-s** [comment]
Sorry about the delay in releasing - I was out for a few days. Working on a NPM patch release now.

**Comment by jaipreet-s** [comment]
v0.8.2 released on NPM. `jupyter labextension install @jupyterlab/git` will get you the latest version that fixes this.

**Comment by qjtongkai** [comment]
Thanks for your reply and work!

@fcollonval
