### ISSUE TITLE
strange rendering of jupyter lab in chrome

### ISSUE THREAD

**Issue by ba4ekiko1** [jupyterlab/jupyterlab-git#405]
Hi, i installed all the prerequisites and followed the instructions and get a strange view of the jupyter lab home page.
![image](https://user-images.githubusercontent.com/25074675/64288221-35f14c80-cf6a-11e9-8507-1c61a185f65a.png)

Anyone knows how i can fix this?

**Comment by jasongrout** [comment]
Upgrade JupyterLab to 1.1.1.

**Comment by ba4ekiko1** [comment]
Thank you, upgraded but still not able to render properly. Still seeing the same view as per my screenshot above.

**Comment by fcollonval** [comment]
Could you provide the commands you used to install Jupyterlab and jupyterlab-git?

**Comment by telamonian** [comment]
@ba4ekiko1 jupyterlab/jupyterlab#7182 added a fix for this problem. If you're still having problems, you can most likely fix them by doing a clean build:

```
jupyter lab clean
jupyter lab build
```

**Comment by ba4ekiko1** [comment]
Thank you both, i did upgrade to 1.1.3 and did a clean build. The issue is fixed but i am witnessing another strange thing, the left side bar which should be showing the files in the given directory in the computer is blank.
![image](https://user-images.githubusercontent.com/25074675/65031939-42ef4200-d953-11e9-9fdc-816e4f995fb4.png)

**Comment by telamonian** [comment]
Yep, that's fixed in jupyterlab/jupyterlab#7192. It's already been merged, so when it's released in a day or two you can do another clean rebuild, and that should be fixed too.

On the other hand, Jlab `1.1.3` shouldn't have any of these package version issues at all, so it's strange that you're still getting any error after you upgraded.

**Comment by ba4ekiko1** [comment]
works fine after another clean and build, thanks!
