### ISSUE TITLE
Separate model and vue in frontend

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#408]
## Description

The frontend architecture could be improved greatly by introducing a model object separated from the UI elements.

That object should be the owner of the selected path, the bridge to the back end and the exported token.

This will help maintenance, reduce the objects to pass down the react tree and be of higher value for other extensions interested in reusing git functions.

**Comment by telamonian** [comment]
I definitely like this suggestion. The current design is a mess, and this would be a way to refactor into something more manageable.

What I'm not sure about though is how to get an encapsulated model to play nicely with the zoo of React components. Specifically, how do we set up the various `props` and `state` w.r.t. the model such that the minimal set of re-renders occur on any given update to the model state?

**Comment by telamonian** [comment]
It appears that this particular problem is exactly what [`react-redux`](https://github.com/reduxjs/react-redux) was designed to handle. However, it does not look especially simple to start using. I'll look into it.

**Comment by fcollonval** [comment]
@telamonian I'm working on this; although not looking at it through `react-redux`. I quickly created a draft PR #438 if you want to have a look.

The goal is to separate the model from the UI mainly to improve the code architecture (it is definitely a mess) and to provide useful token for third-party extension (mainly call git actions from other extensions).

Regarding model and re-rendering, I must say I'm not sure what is the best strategy. I never use `redux` and I read that it could be overkilling for small state. Another approach could be to use `Signals` in a similar fashion that the running sessions in JupyterLab core. I can see 3 differents kind of update: 
- stage/commit file list
- push/pull/checkout
- history

This will be coherent to split the refresh function into those API call (will help solve #432).

**Comment by telamonian** [comment]
> I never use `redux` and I read that it could be overkilling for small state.

I know almost nothing about `redux`. Did your source say it was overkill because of a performance hit, or was it because of how difficult it is to set up?

I took a quick look at #438. I definitely appreciate all of the additions of strong typing. I'll review it in detail later.

Also, I totally support the idea of splitting up the refresh into more specific updates.

**Comment by fcollonval** [comment]
> I know almost nothing about redux. Did your source say it was overkill because of a performance hit, or was it because of how difficult it is to set up?

It is about set up burden and strict code rules; I did not hear about performance issue - but my knowledge on the subject is closed to nothing. 
Here are one of the article you could find on the web: https://marmelab.com/blog/2018/06/27/redux-or-not-redux.html
