### ISSUE TITLE
Interface design

### ISSUE THREAD

**Issue by zzhangjii** [jupyterlab/jupyterlab-git#41]
currently the working pre-alpha version of git-plugin was based the "Running session" design, it executes "git status" in the background and displays the filename and path in 3 categories. This design is simple and clear. 

Another design was to make it more like the "File browser session". (still under debate)

**Comment by ellisonbg** [comment]
For 0.1, let's focus on the current UI/UX, and try to work on the REST protocol. Marking this for 0.2

**Comment by ellisonbg** [comment]
Targeting this to 0.1.
