### ISSUE TITLE
How to init a project

### ISSUE THREAD

**Issue by Mowar** [jupyterlab/jupyterlab-git#425]
When I select init a project, The Init button malfunction.

![init](https://user-images.githubusercontent.com/16316288/66903265-be1c4480-f034-11e9-88e0-32fcdb3fdd65.png)

**Comment by fcollonval** [comment]
Could you please provide more information?

Versions of the extension and Jupyterlab.
If possible errors in the web console and in the server console.

**Comment by telamonian** [comment]
Since there's been no followup, I'm closing this as stale. If you do run into any issues with init, please open a new issue
