### ISSUE TITLE
Create specification for REST API

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#43]
Let's create a markdown document that follows the format of the Github API () to document the following aspects of the REST API:

1. URLS
2. HTTP verbs (`GET`, `POST`, etc)
3. Request JSON
4. Reply JSON
5. How errors are handled (HTTP error codes, error JSON)

I would create this in a new `specification` directory or something like that.

Some initial ideas we talked about:

URL:

`GET /git/status`

Request:

```json
{"repo": "/absolute/path/to/root/of/repo"}
```

Reply:

```json
{
    "repo": "/absolute/path/to/root/of/repo",
     "files": [
        {"x": "", "y": "", "to": "", "from": ""}
    ]
}
```

Let's assume that all parsing will be on the server side.

**Comment by zzhangjii** [comment]
done, the flow works
