### ISSUE TITLE
Consider unbundling labextension from Python extension

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-git#430]
Currently, the Typescript for the labextension is bundled in with the Python package. This smells like an anti-pattern. Beyond the issues I ran into in #424, there's a bunch of other obvious problems. For example, every time there's a new release of the labextension, we'll also have to do a new release of the Python package, even if there's no changes to the Python code. A better solution would be to just call out to the `labextension` app in `setup.py` (`jupyter labextension install jupyterlab_git` for release, `jupyter labextension install .` for develop).

**Comment by fcollonval** [comment]
Adding a note for consideration: shipping the .js code within the python package is the strategy used by the classical notebook extension.

**Comment by telamonian** [comment]
That's a point, and it's also true the `jupyterlab` pip package includes the built/bundled `.js` of all the core packages (though not the `.ts` sources. We should at the least remove those from our `sdist`). However, we're dealing with some unique issues in this repo due to the design and intent of the JupyterLab extension system.

For example, if someone tries to install this extension by first running `jupyter labextension @jupyterlab/git` (which people definitely will) and then `pip install jupyterlab_git`, they may get unexpected behavior: the `pip install` will clobber the pre-existing labextension, which may end up being a different version if we're not very careful about keeping the Python package version, the bundled labextension version, and the labextension version on npmjs all in sync.

Sure, we could alleviate that issue somewhat by careful CD and the like, but it hardly seems worth it (it also wouldn't prevent clobbering). A much better solution would be for the Python extension and the labextension to each be the province of its own specific package manager, avoiding any worry about version syncing in the first place, simplifying testing, and speeding up the dist builds.

Thus, the `setup.py` should call `labextension install`, and `labextension install` should call the `setup.py`. The former is achievable right now. The latter unfortunately will have to wait for various improvements to be made to the labextension app. Those improvements are planned for the near future, so that's still the direction I think we should move in
