### ISSUE TITLE
wrapping of text in git UI side panel makes filenames unreadable

### ISSUE THREAD

**Issue by vnijs** [jupyterlab/jupyterlab-git#433]
When in a git repo the panel showing changed and staged files, the file names wrap in a way that makes them overlap (1st screenshot below). If the side panel is made wider all is well as you can see in the 2nd screenshot. 

![image](https://user-images.githubusercontent.com/2998956/67164650-a513dc00-f331-11e9-857d-56026eeb5355.png)

![image](https://user-images.githubusercontent.com/2998956/67164666-e7d5b400-f331-11e9-8970-48e18a8a9ffa.png)

**Comment by fcollonval** [comment]
Thx for reporting it

**Comment by fcollonval** [comment]
This has been fixed by #438. A screenshot is available in https://github.com/jupyterlab/jupyterlab-git/issues/443#issuecomment-554013803
