### ISSUE TITLE
clicking on git icon produces JS errors ("props.onClick is not a function")

### ISSUE THREAD

**Issue by vnijs** [jupyterlab/jupyterlab-git#434]
FYI Clicking on the git icon on the top-right of the image below is what generate the props.onClick is not a function error. 

![image](https://user-images.githubusercontent.com/2998956/67164823-62530380-f333-11e9-859b-702bee963309.png)

<pre>
jovyan@mini ~ jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        @jupyterlab/git v0.8.2  enabled  OK
        @ryantam626/jupyterlab_code_formatter v0.6.0  enabled  OK
        jupyterlab-jupytext v1.0.2  enabled  OK
        jupyterlab-server-proxy v2.0.0  enabled  OK*
        nbdime-jupyterlab v1.0.0  enabled  OK

   local extensions:
        jupyterlab-server-proxy: /tmp/jupyter-server-proxy/jupyterlab-server-proxy
</pre>

**Comment by fcollonval** [comment]
@vnijs thx for creating a separated issue.

**Comment by fcollonval** [comment]
The root cause for the error is that no click callback is defined for the disable clone button:

https://github.com/jupyterlab/jupyterlab-git/blob/master/src/widgets/gitClone.ts#L42-L45
