### ISSUE TITLE
Create a non-handler Python API for everything

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#44]
Our usual approach with REST APIs is to create a Python class with method that do the various actions for the service. This allows the handlers to be very simple and rely on common code in a common API object. An example of that is here:

https://github.com/jupyter/notebook/tree/master/notebook/services/contents

Another example (but in node.js) is here:

You will end up with a Python version of this class that the server will use:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/git.ts

**Comment by zzhangjii** [comment]
a "Git" python class is created, all the git operations are written as it's functions
