### ISSUE TITLE
Stage all changes -misleading / unintuitive

### ISSUE THREAD

**Issue by pfarndt** [jupyterlab/jupyterlab-git#442]
There is a "Stage all changes" button to the left of the list of the "Changed" files in my repo. Clicking on it a `git add -A` is triggered, which tries to add (in my case many) more files then just those listed under changed. I find this behavior unintuitive, since I would suspect that only those files listed there would be added.

Would it be possible to add only those files which are listed there?

Thanks for your consideration.

**Comment by fcollonval** [comment]
Thanks for reporting. 
Indeed, using `git add -u` would be more appropriate.
The call is carried out there:
https://github.com/jupyterlab/jupyterlab-git/blob/53ee4737d5de211041c579c85a8f71c2ab313914/jupyterlab_git/git.py#L539

Would you be willing to write a PR for this?
