### ISSUE TITLE
Files with long names are misaligned and incorrectly wrapped

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#443]
## Description

If a file has a rather long name, the Git extension wraps it onto the following line. This can also stomp on the next file name in the list.

<img width="475" alt="Screen Shot 2019-11-05 at 3 57 52 PM" src="https://user-images.githubusercontent.com/43826141/68256609-7f4f2e00-ffe5-11e9-9acd-a49897f73694.png">

## Reproduce

1. Go to Git panel in a Git repo with a long filename
3. Scroll down to Untracked or any other panel
4. See file names.

## Expected behavior

The JupyterLab file browser handles this gracefully by truncating long names with a "..." and revealing the full name when the panel is expanded.

<img width="444" alt="Screen Shot 2019-11-05 at 3 57 09 PM" src="https://user-images.githubusercontent.com/43826141/68256780-d523d600-ffe5-11e9-977a-c4a67b450727.png">

## Context

- Python package version: 0.8.x

- Extension version: 0.8.x

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
In the rework of #438, this is corrected by removing the `flex-wrap` attribute on filename. The consequence is that the revert and diff icon appears at the right edge like in vs code and no more right after the filename.

**Comment by jaipreet-s** [comment]
> In the rework of #438, this is corrected by removing the flex-wrap attribute on filename.

Great!

> The consequence is that the revert and diff icon appears at the right edge like in vs code and no more right after the filename.

Do you have screenshots of the updated UX? I didn't see any in the referenced PR.

**Comment by fcollonval** [comment]
@jaipreet-s here is the screenshot for the current code:

![image](https://user-images.githubusercontent.com/8435071/68884522-a1e2f480-0713-11ea-98cc-9b0415980dda.png)
