### ISSUE TITLE
Installation guide with docker for version <0.9

### ISSUE THREAD

**Issue by Racle** [jupyterlab/jupyterlab-git#445]
After searching and trying to figure why installation guide doesn't work, I got it working with this on my custom jupyter Dockerfile (base is jupyter/pyspark-notebook)

```
RUN pip install jupyterlab-git && \
    jupyter serverextension enable --py --sys-prefix jupyterlab_git && \
    jupyter labextension install @jupyterlab/git
```

With these commands git is installed and working.

I couldn't get extension up with guide in readme.

UPDATE: almost works, extension doesn't find any git repositories
UPDATE2: it works. seems that `--sys-prefix` was required.

**Comment by fcollonval** [comment]
@Racle thank you for reporting. Actually, the readme in github is providing the latest way (not yet publish) to install the extension.

I'll keep this open for reference.

**Comment by telamonian** [comment]
With the release of `v0.9.0`, the install instructions and the README do indeed now match. There's also a note in the README about running `jupyter serverextension enable` if you get into trouble during the install
