### ISSUE TITLE
Failed to fetch diff

### ISSUE THREAD

**Issue by Racle** [jupyterlab/jupyterlab-git#446]
Server responds: `HTTP 422: Unprocessable Entity (Invalid notebook: pipelines/base/index.ipynb)`

On my filesystem, I have files like this

```
/ (/home/jovyan)
|-- pipelines/ (my cloned git repo)
|---- base/
```

On request payload it shows as `"file_path":"pipelines/base/index.ipynb"`

I can commit/push/pull, but cannot view difference.

I tried to run request with postman and changing `file_path`, but even when I changed `file_path` to `/home/jovyan/pipelines/base/index.ipynb` or `base/index.ipynb` or `/base/index.ipynb` it always returns HTTP 422.

And I'm running this in docker-compose. base image is `jupyter/pyspark-notebook` with root + sudo enabled.

**Comment by fcollonval** [comment]
Thx for reporting this should be fixed by #406
