### ISSUE TITLE
Lost @jupyterlab/git icon and menu from Jupyterlab

### ISSUE THREAD

**Issue by cmclinton** [jupyterlab/jupyterlab-git#457]
I initially installed @jupyterlab/git via the extension manager within Jupyterlab. After installation, I had the jupyterlab/git icon in the sidepanel on the left and the Git menu within Jupyterlab. However, no actual git functionality was present (due to the lack of serverextension when installing through the extension manager). I then uninstalled @jupyterlab/git via the extension manager which removed the Git icon and top-level menu item. 

After reading through the issues list, I then installed @jupyterlab/git via (from #341):

```
jupyter labextension install @jupyterlab/git
pip install jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```

I now see git on the notebook task bar which correctly shows diffs against my prior git commit of the notebook, but the icon on the left and the Git menu at the Jupyterlab level are not present.

I uninstalled Jupyterlab via the Anaconda interface and then reinstalled both Jupyterlab via the Anaconda interface and the @jupyterlab/git extension using the commands above. However, this did not bring back the icon or menu items.

I did try another `jupyter lab build` to see if this would bring things back, but that did not work either.

Thank you

![Capture](https://user-images.githubusercontent.com/18710968/69662186-e21a6f00-1051-11ea-8876-59cb3de2b0f0.PNG)

**Comment by cmclinton** [comment]
Also adding the following...
`
C:\>jupyter serverextension list
config dir: C:\Users\clintonc\.jupyter
    jupyter_nbextensions_configurator enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git  ok
config dir: C:\Users\clintonc\AppData\Local\Continuum\anaconda3\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 1.2.3 ok
    nbdime enabled
    - Validating...
      nbdime 1.1.0 ok
    voila.server_extension enabled
    - Validating...
      voila.server_extension  ok

C:\>jupyter labextension list
JupyterLab v1.2.3
Known labextensions:
   app dir: C:\Users\clintonc\AppData\Local\Continuum\anaconda3\share\jupyter\lab
        @jupyterlab/git v0.8.2 enabled  ok
        @jupyterlab/plotly-extension v1.0.0 enabled  ok
        jupyterlab-chart-editor v0.2.0 enabled  ok
        jupyterlab-flake8 v0.4.0 disabled ok
        jupyterlab_autoversion v0.1.1 enabled  ok
        nbdime-jupyterlab v1.0.0 enabled  ok

Uninstalled core extensions:
    @jupyterlab/git
    jupyterlab-chart-editor
`

**Comment by telamonian** [comment]
It appears that you have some crud in your Jupyterlab app dir. Specifically, it looks like `<your-jlab-app-dir>/settings/build_config.json` has some bad values. You should be able to fix it by running:

```bash
jupyter lab clean && jupyter lab build
```

The above command heals many weird installation issues, especially those that carry over between different versions and installed copies of jlab.

**Comment by cmclinton** [comment]
Thanks - I ran your suggestion and it did not fix the issue. I then reviewed the contents of my build_config.json file and it contains the following

`{
    "uninstalled_core_extensions": [
        "jupyterlab-chart-editor",
        "@jupyterlab/git"
    ]
}`

I also ran `jupyter labextension list` which is pasted below...

`C:\>jupyter labextension list
JupyterLab v1.2.3
Known labextensions:
   app dir: C:\Users\[Iuserdirectory]\AppData\Local\Continuum\anaconda3\share\jupyter\lab
        @jupyterlab/git v0.8.2 enabled  ok
        @jupyterlab/plotly-extension v1.0.0 enabled  ok
        jupyterlab-chart-editor v0.2.0 enabled  ok
        jupyterlab-flake8 v0.4.0 disabled ok
        jupyterlab_autoversion v0.1.1 enabled  ok
        nbdime-jupyterlab v1.0.0 enabled  ok

Uninstalled core extensions:
    @jupyterlab/git
    jupyterlab-chart-editor`

**Comment by telamonian** [comment]
@cmclinton This is a weird one. I showed your problem to some of the people in the jlab core team who wrote the `labextension` app in the first place, and it's apparently a new one on them too.

The best advice that I can pass on to you is to manually delete the entire contents of your jlab app dir, then do another `jupyter lab build`. The big downside to this approach is that this wipes your extensions, so you will have to reinstall your whole list of them from scratch.

You might be able to skip having to reinstall your extensions simply by leaving the `<app-dir>/extensions` directory in place while deleting everything else in `<app-dir>`. On the other, it may be that nothing less than a complete wipe will suffice to get your setup back into a valid state.

**Comment by cmclinton** [comment]
Thanks for the suggestion.

I deleted the jlab app directory completely and then re-ran the following sequence.
`jupyter labextension install @jupyterlab/git
pip install jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
`
The git sidepanel functionality is now back and the git menu is present again. The only issue is that the git icon at the top of the notebook, which allows you to do diffs, is no longer present.

I ran another `jupyter lab build` just to see, but that did not bring back the icon.

Git functionality is present. I'm able to stage and commit, which is great.

Thanks for the help.

**Comment by telamonian** [comment]
With the release of `v0.9.0` yesterday, you should in the future be able to get everything installed and activated just by running:

```
pip install -U jupuyterlab-git
jupyter lab build
```

The buttons in the toolbar above the notebook are supplied by the `nbdime` extension, not by us. For our extension, you can see a diff by clicking on the diff button that shows up next to notebooks with changes in git sidepanel UI (the little black icon all the way to the right):

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2263641/70255478-7cfb0380-174c-11ea-9abf-0ed6ccb913ae.png">

`nbdime` has a build system similar to our new one, so you may be able to fix the new issue by running

```
pip install -U nbdime
jupyter lab build
```

Since your `jupyterlab-git` install is working, at least, I'm going to close this issue. If you have further issues with `nbdime` post on their issue board, or if you have more trouble with the general labextension build system, post those issues on jupyterlab core.

**Comment by telamonian** [comment]
To clarify, if you do run into further labextension trouble, please do post an issue to core. We're actively trying to improve the user experience around extensions, and there's lots of people there who may have more insight than me
