### ISSUE TITLE
Supporting non-public and non-GitHub repositories

### ISSUE THREAD

**Issue by kgryte** [jupyterlab/jupyterlab-git#468]
## Description

Upon clicking the file icon in the Git history panel for a single file, the extension attempts to [open](https://github.com/jupyterlab/jupyterlab-git/blob/a78cac8482ff5d4c7258515b75d3dfd0606cc4bf/src/components/SinglePastCommitInfo.tsx#L213) a public GitHub URL.

Such behavior is likely not desirable when a repository is not hosted or, if hosted, not hosted on GitHub.

## Reproduce

1. Open JupyterLab with the Git extension installed.
2. Click on the Git extension icon.
3. Click on the history tab.
4. Scroll down to a past commit.
5. Click on the commit.
6. Double click the file icon next to a changed file.

## Expected behavior

I'm not sure the optimal behavior here. For internal usage, opening a GitHub URL is not applicable. Maybe this could be configured?

Or potentially down the road, one may want to open the file directly within JupyterLab to see the diff for that file in that commit. In fact, maybe this should be the default behavior?

This would, I presume, require diffing of plain text files (see #406).

## Context

- Python package version: 0.9.0

- Extension version: 0.9.0

**Comment by fcollonval** [comment]
Thanks for reporting this bug. 

I think at the file level component, we should drop that double click action and indeed prefer the _open diff_ action (on simple click). 

But should we have a similar although more generic action on the commit hash?

https://github.com/jupyterlab/jupyterlab-git/blob/a78cac8482ff5d4c7258515b75d3dfd0606cc4bf/src/components/PastCommitNode.tsx#L81-L83

**Comment by jamesjnadeau** [comment]
FYI for anyone who comes here and wants to use a host other than github.

Install you repo via the cli and this extension will pick it up. I'm currently using this with Azure DevOps repositories just fine.

If you use ssh keys and ssh-agent, you'll have an easier time with access management.
