### ISSUE TITLE
Create TS class with API to REST service

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#47]
There should be a standalone TypeScript class with methods for each git command/action. Each of those methods should take simple types, make the HTTP request and return a promise to the result. The API probably won't look very different from this:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/git.ts

But it will instead make HTTP requests to the server which has the python class with all of the logic.

**Comment by zzhangjii** [comment]
TS class created, currently this Git class only have add, checkout, commit, reset, status, showtoplevel( show the top level of a repo),  returns are in the form of Promise<ServerConnection.IResponse>
