### ISSUE TITLE
Update README screencast

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#476]
The extension deserves a more recent screencast.

**Comment by telamonian** [comment]
I didn't understand what you meant by "screencast", but you're talking about the animated `.gif` near the top of the README, right? In that case I agree 100%. Lots of things have changed (for the better), and we should inform about/advertise that.

@fcollonval Here's a stab at a replacement `.gif`:

![ui_glow_up_090](https://user-images.githubusercontent.com/2263641/70192929-fb12c800-16c2-11ea-8058-5dad860223f8.gif)

If this looks good to you, I'll make a PR for it

**Comment by telamonian** [comment]
I went ahead and made the PR at #482. @fcollonval let's continue the conversation there

**Comment by fcollonval** [comment]
Thanks a lot @telamonian for all the repo maintenance work. Indeed I meant an animated gif. Yours is pretty good. I'll try to produce a second one for your awesome simple UI; I think it makes sense to present the two separately in the readme.

**Comment by fcollonval** [comment]
Thanks a lot @telamonian for all the repo maintenance work. Indeed I meant an animated gif. Yours is pretty good. I'll try to produce a second one for your awesome simple UI; I think it makes sense to present the two separately in the readme.
