### ISSUE TITLE
styling defect: gap between list of logs and bottom of git UI panel in history tab

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-git#481]
Currently, the bottom of the log list in the history tab looks a bit weird, especially if the git sidepanel is set narrow enough for there to be a horizontal scrollbar:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2263641/70192775-7627ae80-16c2-11ea-9a8b-6301d21379a9.png">

There's a gap between the bottom of the log list and the bottom of the actual `GitPanel` widget (outlined in red below):

<img width="635" alt="image" src="https://user-images.githubusercontent.com/2263641/70192697-411b5c00-16c2-11ea-8d1c-36fa892c0283.png">

We should fix this

**Comment by kgryte** [comment]
@telamonian Just assigned myself. Will submit a PR shortly.
