### ISSUE TITLE
followup #406: fix diffing from commits in history view for code files and notebooks

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-git#484]
ref #406

With #406 merged in, at least some files can be diffed successfully from any commit in the history view. However, trying to diff any code file (`.py`, '.ts', etc) results in:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/2263641/70212541-139fd400-16fd-11ea-9115-2ec0812698f4.png">

and trying to diff an `.ipynb`  notebook produces a similar, but slightly different error:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/2263641/70212599-2c0fee80-16fd-11ea-9798-c3e8d35d81f3.png">

**Comment by fcollonval** [comment]
@telamonian I'm not able to reproduce this. Does it happen only for diff from the history and for any code file in any case?

**Comment by telamonian** [comment]
Yeah, only from the history, and for any code file (which I assume is really any file recognized by `isText`?) and any `.ipynb`. I'll see if I can repro in a clean venv

**Comment by fcollonval** [comment]
The error for plain text file is corrected in #489 

For the notebook, was it a diff on an notebook addition? Because I have seen such error in that case.

**Comment by telamonian** [comment]
I was originally seeing the diffing issue with all notebooks from the history. After the last couple of rebuilds, though, I can't reproduce that particular error.

However, what I do see now is that notebooks added in a repo's very first commit:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2263641/70369729-6905ed80-1883-11ea-9298-774367d71f5b.png">

produce the same diff error that I was seeing before:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2263641/70369732-715e2880-1883-11ea-834b-d5835717b988.png">

**Comment by telamonian** [comment]
This is fixed in latest master
