### ISSUE TITLE
Simplify commands

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#491]
Two issues (and associated PR) have been submitted to JLab core to add arguments to
- `'help:open'` command: https://github.com/jupyterlab/jupyterlab/pull/7603
- `'terminal:create-new'` command: https://github.com/jupyterlab/jupyterlab/pull/7605

If they are accepted, the commands define there could be removed:
- https://github.com/jupyterlab/jupyterlab-git/blob/master/src/gitMenuCommands.ts#L15
- https://github.com/jupyterlab/jupyterlab-git/blob/master/src/gitMenuCommands.ts#L13

**Comment by krassowski** [comment]
It looks like it was solved, or at least the `gitMenuCommands.ts` file does not exist anymore.

**Comment by fcollonval** [comment]
Thanks @krassowski
