### ISSUE TITLE
It always shows you aren't in a git repository (0.9.0)

### ISSUE THREAD

**Issue by roccqqck** [jupyterlab/jupyterlab-git#496]
It always shows you aren't in a git repository.

But I am sure I am in one.

jupyterlab-git 0.9.0

**Comment by fcollonval** [comment]
@roccqqck Could you try two different git repository to see if both are failing?

Could you check the frontend extension installed is 0.9.0 (to do so execute `jupyter labextension list`)?
Could you report any error message in the web browser console and the server terminal?

**Comment by roccqqck** [comment]
when I create a new virtualenv, it worked fine.

But when I upgraded one from 0.8.2 to 0.9, it failed


```
Fail to get the server root path.
Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data model.js:21:8
    v model.js:21
Fail to find git top level for path home/barry/projects/github/news_bert.
TypeError: JSON.parse: unexpected character at line 1 column 1 of the JSON data 2 model.js:106:21
Fail to find git top level for path home/barry/projects/github/stock_eland.
TypeError: JSON.parse: unexpected character at line 1 column 1 of the JSON data model.js:106:21
```
```
[W 00:27:41.800 LabApp] 404 GET /git/server_root?1576081660665 (140.xxx.xxx.47) 14.24ms referer=http://140.xxx.xxx.174:8900/lab?
```
​

**Comment by fcollonval** [comment]
It looks like your frontend extension has been updated but not the serverextension.

Could you check the python package `jupyterlab_git` v0.9.0 is installed?
You can upgrade it using `pip install -U jupyterlab-git`

**Comment by roccqqck** [comment]
It was installed.

**Comment by stackoverflowed** [comment]
Hi,
    Any updates on this issue? I just installed and am getting the same message. When I click find a repo, I am redirected to my filesystem. Would love to have this working.

**Comment by fcollonval** [comment]
@stackoverflowed, the extension is connected to the current folder opened on the filebrowser tab. So normally if you select a folder within a git repository in the file browser, the git panel should change and show the repository status.

**Comment by DevMui** [comment]
I have the same issue - I think it would be helpful if the users with same symptom share their setting. I've been running `jupyterhub` with `jupyterlab` and `jupyterlab-git`.  I assume `jupyterhub` or maybe `conda` does not have good compatibility with either `jupyterlab` or `jupyterlab-git` which generates errors...

```
$ conda list
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterhub                1.0.0                    py37_0
jupyterlab                1.2.4                      py_0    conda-forge
jupyterlab-git            0.9.0                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0

$ jupyter serverextension list
config dir: /opt/local/anaconda3/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 1.2.4 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git  OK

$ jupyter labextension list
JupyterLab v1.2.4
Known labextensions:
   app dir: /opt/local/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        @jupyterlab/git v0.9.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK
```

**Comment by telamonian** [comment]
@roccqqck @stackoverflowed @DevMui I've dug into this and the related issues. If you're getting 404s with error messages like:

```
TypeError: JSON.parse: unexpected character at line 1 column 1 of the JSON data 2 model.js:106:21
```

that means that either:

1. The `jupyterlab-git` serverextension isn't correctly installed
2. The `jupyterlab-git` serverextension isn't correctly activated

Here's how you can diagnose your own problem. First, run:

```
jupyter serverextension list
```

and make sure that you see something like:

```
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git  OK
```

If you don't, try running this:

```
pip install -U jupyterlab-git
jupyter serverextension enable --py jupyterlab_git --sys-prefix
```

**Comment by telamonian** [comment]
@DevMui In your case, it looks like everything is installed/activated just fine, so I'm not sure what's wrong. Did you remember to restart any running instances of the jupyter server and/or jupyterhub after you installed and activated the latest `jupyterlab-git`?

**Comment by DevMui** [comment]
@telamonian I have restarted the `jupyterhub` server instance multiple times but still no luck. The error messages I am seeing at Chrome Dev Tools look like:
```
model.js:30 Fail to get the server root path. Error: SyntaxError: Unexpected token < in JSON at position 1
VM147:1 POST http://SERVER:8000/user/USER/git/show_top_level?1576861896162 404 (Not Found)
model.js:114 Fail to find git top level for path . TypeError: Unexpected token < in JSON at position 1
```
I will try to clean up the jupyterlab app folder and rebuild the lab.

**Comment by elettra0384** [comment]
Hi! I have the same behaviour and this is the error I get from Conda:

```
[E 10:33:49.070 LabApp] Uncaught exception POST /git/show_top_level?1581503629063 (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/show_top_level?1581503629063', version='HTTP/1.1', remote_ip='::1')
[E 10:33:49.073 LabApp] 500 POST /git/show_top_level?1581503629063 (::1) 8.02ms referer=http://localhost:8888/lab
```

Here's all the lists:
```
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab-git            0.9.0                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0
```
```
jupyter serverextension list

    jupyterlab enabled
    - Validating...
      jupyterlab 1.1.4 ok
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git  ok
    nbdime enabled
    - Validating...
      nbdime 1.1.0 ok
```
```
jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   
        @jupyterlab/git v0.9.0 enabled  ok
        nbdime-jupyterlab v1.0.0 enabled  ok

```

**Comment by mausch** [comment]
I had the same issue and got it to work by upgrading my base image (i.e. was using an old version of jupyterlab?)

This works for me:

```
FROM jupyter/minimal-notebook:36bce751008f

USER root
RUN apt-get update && apt-get install -y openssh-client
USER $NB_UID

RUN jupyter labextension install @jupyterlab/git
RUN pip install --upgrade jupyterlab-git
RUN jupyter serverextension enable --py jupyterlab_git --sys-prefix
```

**Comment by fcollonval** [comment]
Closing this as the latest version is 0.10.0.
