### ISSUE TITLE
Some sketch of how to use settings to provide an API object to the handlers

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#50]
Let's say you have a Python `Git` class that has methods such as `status`, `add`, etc. that talk to git using the command line. You want to use that class in all your handlers.

In your server extension code you will instantiate one of these `Git` objects:

```python
def load_jupyter_server_extension(nbapp):
    git = Git() # The Python class all of your handlers will need/use
    nbapp.web_app.settings['git'] = git
    setup_handlers(nbapp.web_app)
```

Then to access that from your handlers, you will want a property on all your handlers (in a common base class:

```python
@property
def git(self):
    return self.settings['git']
```

Then in your actual handler methods you can use this instance, like this:

```python

class StatusHandler(BaseHandler):

    def get(self):
        result = self.git.status(..)

```

**Comment by zzhangjii** [comment]
It's working, now the handlers on server side use their git property and git class's methods(add, reset, checkout, commit)
