### ISSUE TITLE
Does not work if there is a version mismatch between the jupyterlab-git serverextension and the @jupyterlab/git labextension

### ISSUE THREAD

**Issue by scoobymib3** [jupyterlab/jupyterlab-git#501]
Hi,

I've seen this elsewhere but none seem to relate to my issue. I am using TLJH with jupyterlab-git installed and mostly it is working great, apart from the git tab.

I can clone a project with no problems but it always tells me I am not in a git repo. Even if I create and init from within the lab.

![Screenshot 2019-12-19 at 15 49 42](https://user-images.githubusercontent.com/6632188/71187567-38f11e00-2277-11ea-98e3-0e1a56ffd2bc.png)

![Screenshot 2019-12-19 at 15 49 31](https://user-images.githubusercontent.com/6632188/71187584-3e4e6880-2277-11ea-9249-0e3601d17711.png)

![Screenshot 2019-12-19 at 15 49 08](https://user-images.githubusercontent.com/6632188/71187589-40b0c280-2277-11ea-86ef-8bc372e2e765.png)

Looking at the console logs I can see a 500 error when connecting to /user/<user_name>/git/all_history

![Screenshot 2019-12-19 at 15 51 43](https://user-images.githubusercontent.com/6632188/71187862-d2b8cb00-2277-11ea-8720-f64734a02ed5.png)

I've followed a few similar threads but cant seem to make any progress with this one. Any advice or guidance greatly appreciated!!

cheers
Martin

**Comment by scoobymib3** [comment]
![Screenshot 2019-12-19 at 16 57 05](https://user-images.githubusercontent.com/6632188/71192660-9dfd4180-2280-11ea-84ae-dacd64bad3a5.png)

Just noticed that the git interface doesnt seem to take any notice what folder Im looking at in the folder view. It always just says /

**Comment by scoobymib3** [comment]
Just for added information, calling git terminal opens up in the correct directory

Also tried adding the following to jupyterhub_config.py

c.NotebookApp.nbserver_extensions = {
    'jupyterlab_git': True,
}

**Comment by DevMui** [comment]
It seems this is a duplicate of #496

**Comment by telamonian** [comment]
@DevMui Sadly, this one isn't a duplicate

@scoobymib3 You have a terrible version clash, which the labextension management tools in jlab core have no way to deal with. The most important problem (there are others) is that you're using a really old version of the `jupyterlab` package. Any hope you have of unfutzing your current install will have to start with upgrading to `jupyterlab==1.2.4`. Here's one possible set of commands that should leave you with a clean, functional build in the end:

```
# install latestest jupyterlab
pip install -U jupyerlab

# wipe jlab app dir
jupyter lab clean --all

# this will install the latest versions of everything for both juptyerlab-git and nbdime
pip install -U jupyterlab-git

# reinstall your other labextensions
jupyter labextension install @jupyter-widgest/jupyterlab-manager @jupyterlab/hub-extension --no-build

# do a build to include all of your labextensions
jupyter lab build
```

Then, to verify that everything is working, first do:

```
jupyter serverextension list
```

If everything is okay, you should see something like:

```
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git  OK
```

You should also run:

```
pip list
jupyter labextension list
```

and make sure that the versions of `jupyterlab_git` in the output of `pip list` and `@jupyterlab/git` in the output of `jupyter labextension list` match (currently, both should be `0.9.0`).

**Comment by scoobymib3** [comment]
Thank you, that has solved my problem perfectly 👍
