### ISSUE TITLE
Version inconsistency using conda between server and jupyterlab extension

### ISSUE THREAD

**Issue by gideonsimpson** [jupyterlab/jupyterlab-git#504]
## Description

While the tool displays changes that have been made along with the history properly, I am unable to stage changes.

## Reproduce

When I click on the arrow for staging a change, nothing happens.  In the console, an error is reported (see below).

## Expected behavior

I expected that the change would be listed as staged so that it could be committed and pushed.

## Context

- Python package version: 3.7.5

- Extension version: jupyterlab-git            0.8.2                      py_0    conda-forge

JupyterLab v1.2.4
Known labextensions:
   app dir: /anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @jupyterlab/git v0.9.0  enabled  OK
        @jupyterlab/latex v1.0.0  enabled  OK
        @jupyterlab/toc v1.0.1  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK

<details><summary>Command Line Output</summary>
<pre>
(base) me@server:~$ cat error.txt 
[E 08:57:20.953 LabApp] Uncaught exception POST /git/add?1577109440809 (141.152.251.27)
    HTTPServerRequest(protocol='https', host='my.server:9999', method='POST', uri='/git/add?1577109440809', version='HTTP/1.1', remote_ip='141.152.251.27')
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/anaconda3/lib/python3.7/site-packages/jupyterlab_git/handlers.py", line 220, in post
        my_output = self.git.add(filename, top_repo_path)
      File "/anaconda3/lib/python3.7/site-packages/jupyterlab_git/git.py", line 429, in add
        my_output = subprocess.check_output(["git", "add", filename], cwd=top_repo_path)
      File "/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/anaconda3/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/anaconda3/lib/python3.7/subprocess.py", line 1482, in _execute_child
        restore_signals, start_new_session, preexec_fn)
    TypeError: expected str, bytes or os.PathLike object, not list
[W 08:57:20.953 LabApp] Unhandled error
[E 08:57:20.954 LabApp] {
      "Host": "my.server:9999",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:72.0) Gecko/20100101 Firefox/72.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://my.server:9999/lab?",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|9f067a2c|4e67f72520ec3afc1e1bb57add69ef5f|1575945254",
      "Origin": "https://my.server:9999",
      "Content-Length": "120",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|9f067a2c|4e67f72520ec3afc1e1bb57add69ef5f|1575945254; username-my-server-9999=\"2|1:0|10:1577066171|35:username-my-server-9999|44:Y2E4MWRmNDYxYjY4NGIxMmJjM2U1ZTViMjE0YzUxMTk=|47e44481c6ee70b2f74bb7f4d00a3e1007c3a93d2f3456d955646ec7f77654f2\"",
      "Dnt": "1",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 08:57:20.954 LabApp] 500 POST /git/add?1577109440809 (141.152.251.27) 2.03ms referer=https://my.server:9999/lab?
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Dear @gideonsimpson 

You have a version inconsistency. The conda package installed is 0.8.2 when the jupyterlab one is 0.9.0. You need to have the same version for the server and the jupyterlab extension.

Try removing both extension:

```bash
conda remove jupyterlab-git
jupyter labextension uninstall @jupyterlab/git
```

Then reinstall the extension using the two commands:

```bash
conda install jupyterlab-git=0.9.0
jupyter lab build
```

**Comment by gideonsimpson** [comment]
I did as suggested, and now it won't recognize git repos (when I click on the git button, it says "You aren't in a git repository")

**Comment by fcollonval** [comment]
Could you check the server extension is enabled? Run :

```bash
jupyter serverextension list
```

If it is, you will see something like this:

```bash
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git ok
```

Else try to enable it manually:

```bash
jupyter serverextension enable --py jupyterlab_git
```

If it was already enabled, could you provide error messages from the server console and the web browser console?

**Comment by gideonsimpson** [comment]
Yes, it was disabled and enabling it now seems to have resolved that matter.
