### ISSUE TITLE
Inherit from notebook's APIHandler

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-git#51]
All of our handlers should inherit from the Jupyter notebook's base `APIHandler` class:

https://github.com/jupyter/notebook/blob/master/notebook/base/handlers.py#L426

This provides lots of security settings, as well as useful methods for getting the json data, sending errors back, etc.

**Comment by ellisonbg** [comment]
This is done right? Please close if done.

**Comment by ashutoshbondre** [comment]
Yes, done.
