### ISSUE TITLE
Use dialog to switch branch

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#513]
I'll like to replace the current UI to switch branches by a dialog with a combobox. What do you think @kgryte @telamonian ?

![image](https://user-images.githubusercontent.com/8435071/71514189-cba84300-289d-11ea-937f-f1b09d3410db.png)

**Comment by kgryte** [comment]
I was actually considering working on cleaning up the branch UI next and am in agreement that it needs work and clean-up.

As far as how this is implemented, not sure whether it needs to be a dialog or whether we just need to provide a better dropdown UX. For example, to recreate the GitHub desktop app functionality, this could either be a dialog (as the desktop app does) or an in-panel component. Personally, I am slightly biased toward the latter.

As for implementing these changes, is this something that you @fcollonval want to tackle or should I do it?

**Comment by fcollonval** [comment]
Hey @kgryte 
I don't have a better idea than a dialog. So I happily wait for your PR on this 😉
I'll focus on three other tasks:
- ability to pin the repository
- improve file list
- adding widget on status bar

**Comment by kgryte** [comment]
@fcollonval Awesome. Should have a PR up shortly!
