### ISSUE TITLE
Use a dialog to create a new branch

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#514]
The current UI to create a branch is not pretty:

![image](https://user-images.githubusercontent.com/8435071/71514289-3fe2e680-289e-11ea-8a3f-0dcb5b2a7825.png)

It would be better to use a dialog.

**Comment by fcollonval** [comment]
@kgryte will you cover this when working on #513?

**Comment by kgryte** [comment]
@fcollonval Yes, was planning on addressing this, as well.

**Comment by kgryte** [comment]
This was resolved in #518.
