### ISSUE TITLE
Binder demo is not working

### ISSUE THREAD

**Issue by benjello** [jupyterlab/jupyterlab-git#522]
## Description

I do not see the git widget on the binder demo

## Reproduce

1. Go to github/jupyterlab-git page
2. Click on binder demo link
3. Open examples/demo.ipynb

## Expected behavior

See the git widget

## Context

Run on binder from the repo demo link

**Comment by fcollonval** [comment]
@benjello Thanks for pointing this one. This is a terrible mistake, I start a fix for it in #523.
