### ISSUE TITLE
JLab not responsive when loading a git repo with a considerable commit history or clone such a repo

### ISSUE THREAD

**Issue by chrisjohn2306** [jupyterlab/jupyterlab-git#525]
## Description
I was trying out the extension with jupyterlab version 1.2.3. When i am trying to load a git repo with a considerable commit history or clone such a repo, my lab is getting stuck and not responsive

## Reproduce

1. Open JupyterLab with the extension enabled
2. Clone a git repository with lot of commits, branches, or try to open a git repo already cloned of the same nature

## Expected behavior
Expecting to show some status to let the user know of the progress, either a loading bar or some sort of messge

## Context

- Python package version:
python 3.5

- Extension version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting @chrisjohn2306 

The trouble comes probably from the `git` commands being currently executed synchronously #439. It will hopefully be fixed by #493. If you have time, would you be willing to test that PR on your case?

**Comment by chrisjohn2306** [comment]
Thank you @fcollonval 
Will go through the changes and try it out

**Comment by chrisjohn2306** [comment]
@fcollonval I had tested out the changes. The git operations are working smooth now. But the authentication part is failing with "pexpect.exceptions.TIMEOUT: Timeout exceeded". 

Any aid or suggestion on how to handle it?

**Comment by chrisjohn2306** [comment]
With the async changes too, if the user tries to clone and existing repo the window is freezing.

**Comment by fcollonval** [comment]
@chrisjohn2306 thanks for reporting back. 

I looked quickly into it. I modified #493 to remove the timeout and try using asynchronous call for the authentication case too. If you could try this new version, it will be great.

**Comment by chrisjohn2306** [comment]
I was testing it out. But now the window is not freezing  but the clone also is not happening. The user can work in parallel but cannot know whether the clone happens or not

**Comment by chrisjohn2306** [comment]
This has been fixed as part of the Asynchronous command changes.
