### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by goofts** [jupyterlab/jupyterlab-git#526]
jupyter serverextension list

**Comment by goofts** [comment]
VM819:1 GET https://nbs.goofts.online/jupyter/git/server_root?1579253166187 404 (Not Found)

**Comment by fcollonval** [comment]
Please have a look at the [Troubleshooting section](https://github.com/jupyterlab/jupyterlab-git#troubleshooting) and report here if you still have an error.

Note: I was able to reach your endpoint without error

```
{"server_root": "/***"}
```

@blink1073 @telamonian I think we have a security problem with this extension handlers... 😨 🚨 I should not have been able to get that answer. Trying https://nbs.goofts.online/jupyter/ redirect me correctly to the password page.

I am not too familiar with the security. Will using the `@tornado.web.authenticated` decorator on the handler solve this?

**Comment by telamonian** [comment]
Yeah, my understanding is that you would at least need the token as part of the url in order to access anything from any endpoint in the jupyter notebook server, but I guess that's not the case...
