### ISSUE TITLE
Jlab freezes if incorrect clone url or credentials or already cloned repo url is given

### ISSUE THREAD

**Issue by chrisjohn2306** [jupyterlab/jupyterlab-git#528]
## Description

When the user tries to clone a repo that already exists in the base path, the window freezes and no error or status are shown.
Same behaviour is seen if the clone url is incorrect, or the credentials entered by the user is incorrect.
## Reproduce

1. Open the jupyter lab with the extension enabled.
2. Clone a repo in to the home folder
3. (a)After the clone is finished, try to clone the same repo again
(b) In the terminal prompt for entering clone url, enter a invalid one
(c) After entering the correct clone url, in the credential form, enter incorrect username or password
4. Window freezes with no error in browser console or logs

## Expected behavior

Either a dialog box appears saying that the repo already exists or some status that indicates that the operation has failed. 
Input Validation on the entered values 
## Context

- Python package version: 3.5

- Extension version: v0.10.0

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting @chrisjohn2306 

Which OS are you using?
Did you have to authenticate through the extension or were your credentials managed by git directly?

**Comment by chrisjohn2306** [comment]
I am using MacOS. When the repeated clone is given it never reaches the authentication part. Window freezes before that.

**Comment by chrisjohn2306** [comment]
While looking more into the issue i could note that, if an existing repo is attempted to clone again, instead of clone a git pull happens. But no message or progress bar is present to indicate that. 
Is it a default behaviour of git?

**Comment by chrisjohn2306** [comment]
I have a fix for this issue along with the fix for the concern raised in https://github.com/jupyterlab/jupyterlab-git/issues/534 regarding the confusing warning message.

I would like to contribute it to the repository. Is there any T&C formalities to contribute to the repo ?

**Comment by fcollonval** [comment]
> I have a fix for this issue along with the fix for the concern raised in #534 regarding the confusing warning message.

Awesome!!

> I would like to contribute it to the repository. Is there any T&C formalities to contribute to the repo ?

The contribution rules are those of JupyterLab: https://github.com/jupyterlab/jupyterlab-git#contributing

So feel free to open a PR with your fix.

**Comment by chrisjohn2306** [comment]
Changes to avoid Jlab freezing is raised in https://github.com/jupyterlab/jupyterlab-git/pull/556

**Comment by telamonian** [comment]
Fixed by #556
