### ISSUE TITLE
How to use the "jlpm run add:sibling " ? it does not work when i used to add git extension in dev mode.

### ISSUE THREAD

**Issue by mail2julian** [jupyterlab/jupyterlab-git#532]

**Comment by telamonian** [comment]
What did I say on the other thread? Sibling install is not a supported use case for this extension. If you want to go ahead and do it anyway, you're going to have to debug on your own

**Comment by mail2julian** [comment]
how else to add git extension to jupyterlab in dev mode.

**Comment by telamonian** [comment]
What exactly are you trying to do? Why do you need this extension in dev mode?
