### ISSUE TITLE
"Unexpected end of JSON output" error modal when discarding unstaged changes to notebook (.ipynb)

### ISSUE THREAD

**Issue by karenin-overseas** [jupyterlab/jupyterlab-git#533]
## Description

Jupyterlab git's "discard unstaged changes" feature is throwing an "Unexpected end of JSON output" error when invoked in the UI

## Reproduce

1. Create a blank new notebook in an empty git repo.
2. Write any code into a cell and save the changes.
3. Click the trash can icon in the jupyterlab-git pane to discard the changes.

<img width="1765" alt="Screen Shot 2020-02-11 at 1 40 43 PM" src="https://user-images.githubusercontent.com/17558590/74268358-bf553980-4cd5-11ea-9b1e-ffc0c4aebcdf.png">

4. You should see the error modal. Changes made to the notebook seem like they aren't discarded, although the jupyterlab-git pane is now empty

<img width="1724" alt="Screen Shot 2020-02-11 at 1 40 12 PM" src="https://user-images.githubusercontent.com/17558590/74268366-c2502a00-4cd5-11ea-9907-429f9ece85c3.png">

## Expected behavior
Error modal shouldn't appear. Unstaged changes to notebook should be discarded.

## Context

- Python package version:

Name: jupyterlab-git
Version: 0.9.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /Users/rlin/venv/lib/python3.7/site-packages
Requires: pexpect, nbdime, notebook
Required-by: 
- Extension version:

JupyterLab v1.2.6
Known labextensions:
   app dir: /Users/rlin/venv/share/jupyter/lab
        @jupyterlab/git v0.9.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK

<details><summary>Command Line Output</summary>

[lab.log](https://github.com/jupyterlab/jupyterlab-git/files/4187640/lab.log)

</details>

<details><summary>Browser Output</summary>
When the JSON error appears:

<pre>
2default.js:1496 Kernel: connected (5bfd7f09-d935-4364-ad19-26b8ec8a7ed4)
backend.js:6 Showing error: SyntaxError: Unexpected end of JSON input
    at v.checkout (model.js:573)
    at async Object.discardChanges [as discardFile] (FileList.js:116)
r @ backend.js:6
m @ dialog.js:32
discardChanges @ FileList.js:120
async function (async)
discardChanges @ FileList.js:116
discardSelectedFileChanges @ FileItem.js:120
async function (async)
discardSelectedFileChanges @ FileItem.js:114
onClick @ FileItem.js:137
l @ react-dom.production.min.js:14
h @ react-dom.production.min.js:15
m @ react-dom.production.min.js:15
S @ react-dom.production.min.js:17
A @ react-dom.production.min.js:18
L @ react-dom.production.min.js:18
P @ react-dom.production.min.js:21
On @ react-dom.production.min.js:84
tl @ react-dom.production.min.js:250
Be @ react-dom.production.min.js:39
Nn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
rl @ react-dom.production.min.js:251
zn @ react-dom.production.min.js:85</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting this issue @karenin-overseas. This should be fixed in #493

**Comment by lresende** [comment]
Fixed by #493 as described above.
