### ISSUE TITLE
Git Push/Pull credentials dialog box always showing "Incorrect username or password"

### ISSUE THREAD

**Issue by chrisjohn2306** [jupyterlab/jupyterlab-git#534]
## Description
When ever the user attempts a git push or pull the dialog box asking for the credentials always comes up with the message "Incorrect Username or password".
Internally the extension is trying to execute the git operation by using any kind of saved passwords but if the user has disabled such options, the git operation fails prompting for the dialog box to enter credentials with error message. But from the user point of view even before entering the credentials, error message is showing which does not seem to be the apt way.
<img width="692" alt="Screenshot 2020-02-12 at 10 19 56 AM" src="https://user-images.githubusercontent.com/58581644/74305894-123af980-4d87-11ea-9ea9-30883a706811.png">

## Reproduce

1. Start the jupyter lab with the git extension enabled
2. Clone a repo
3. Disable all kinds of saved passwords for git
4. Try a git pull or push
5. View the dialog box with credentials form

## Expected behavior
The credentials box when appears initially should not have the error message. In case of incorrect credentials , the extension is throwing error. So no need of the error message in the credentials form.

## Context
I could see in the code part that 

`let result = await showDialog({
            title: `Git ${operation}`,
            body: new GitPullPushDialog(model, operation),
            buttons: [Dialog.okButton({ label: 'DISMISS' })]
        });
        let retry = false;
        while (!result.button.accept) {
            retry = true;
            let response = await showDialog({
                title: 'Git credentials required',
                body: new GitCredentialsForm('Enter credentials for remote repository', retry ? 'Incorrect username or password.' : ''),
                buttons: [Dialog.cancelButton(), Dialog.okButton({ label: 'OK' })]
            });`

The first time when the credentials box comes the error message is set because of retry flag

- Python package version:

jupyterlab-git            0.10.0 
- Extension version:

@jupyterlab/git v0.10.0

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.

</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting this issue.
Could you provide me details on how/what you did for point 3?

> Disable all kinds of saved passwords for git

**Comment by chrisjohn2306** [comment]
I could see in the code part that 

`let result = await showDialog({
            title: `Git ${operation}`,
            body: new GitPullPushDialog(model, operation),
            buttons: [Dialog.okButton({ label: 'DISMISS' })]
        });
        let retry = false;
        while (!result.button.accept) {
            retry = true;
            let response = await showDialog({
                title: 'Git credentials required',
                body: new GitCredentialsForm('Enter credentials for remote repository', retry ? 'Incorrect username or password.' : ''),
                buttons: [Dialog.cancelButton(), Dialog.okButton({ label: 'OK' })]
            });`

The first time when the credentials box comes the error message is set because of retry flag

**Comment by chrisjohn2306** [comment]
To disable the stored passwords, in mac i disabled Mac Keychain for git and remove any form of saved passwords from browser, git files.

**Comment by chrisjohn2306** [comment]
Can we go with any of these steps?

- Remove the message as it doesn't add any value to the feature
- Rephrase the message to "Missing credentials"  or more appropriate wording

**Comment by chrisjohn2306** [comment]
Changes for this, is raised in https://github.com/jupyterlab/jupyterlab-git/pull/556

**Comment by chrisjohn2306** [comment]
Changes done and merged
