### ISSUE TITLE
Cannot diff .py, .yaml or Dockerfile files (at least)

### ISSUE THREAD

**Issue by dbdean** [jupyterlab/jupyterlab-git#537]
## Description

I've installed jupterlab-git in our jupyterlab by adding the following lines to a Dockerfile based on `jupyter/datascience-notebook`:

```
RUN python -m pip install -U jupyterlab-git
RUN jupyter lab build
```

It seems to be working, and when I looked at changed notebooks, I get a friendly diff of the notebook. However, every time I try to look at a diff of a plaintext file I get an error like

![image](https://user-images.githubusercontent.com/12725310/75007004-dfe87500-54c7-11ea-9cc2-924289aa0641.png)

So far, this has happened for `.py` files, `.yaml` files and a `Dockerfile`. I have yet to find a plaintext file it supports. I think there might be a configuration issue, given I've seen examples of text diffing in your materials, but I'm not sure what.

## Reproduce

1. Change a python file using jupterlab
2. Try to diff the python file

## Expected behavior

A plaintext diff of the python file would display

## Context

- Python package version:
```
$ python -m pip show jupyterlab-git
Name: jupyterlab-git
Version: 0.9.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /opt/conda/lib/python3.7/site-packages
Requires: notebook, nbdime, pexpect
Required-by: 

```
- Extension version:
```
jovyan@cdeb83fcc502:/work$ python -m pip show jupyterlab-git
Name: jupyterlab-git
Version: 0.9.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /opt/conda/lib/python3.7/site-packages
Requires: notebook, nbdime, pexpect
Required-by: 
```

<details><summary>Command Line Output</summary>
Having trouble making this happen from the datascience-notebooks.
</details>

<details><summary>Browser Output</summary>
There doesn't seem to be any relevant JS console output while attempting to diff.
</details>

**Comment by fcollonval** [comment]
Thank you for reaching out. This is included in the master (you can try it on binder). Stay tune for the next release.

**Comment by dbdean** [comment]
Thanks @fcollonval! When is the next release expected. Alternatively, is the master branch stable enough that I could install it for now using `pip install git+https://...`?

**Comment by fcollonval** [comment]
I would say it is stable. But before going on that road, I would suggest you test the master branch on [Binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-git/master?urlpath=lab/tree/examples/demo.ipynb) to test the feature you are looking for. And if needed don't hesitate to open further issue.
