### ISSUE TITLE
npm dependencies failed to install => Unexpected end of JSON input

### ISSUE THREAD

**Issue by EmCeBeh** [jupyterlab/jupyterlab-git#538]
## Description & Reproduction

After a first time install of
Winpython64-3.7.6.0
and an install of jupyterlab-git via
pip install --upgrade jupyterlab-git
I try to build it:
jupyter lab build
but i get stuck at
npm dependencies failed to install
and when I go to the log file, it says:
C:\\Users\\EmCeBeh\\AppData\\Local\\Yarn\\Cache\\v4\\npm-@jupyterlab-docmanager-1.2.1-0d98f00c0b012348512a534d787a1ac541684512\\node_modules\\@jupyterlab\\docmanager\\.yarn-metadata.json: Unexpected end of JSON input
This error message seems to be known in different contexts, but I have not found a fix that works for me, yet.
npm cache clean
as recommended on multiple sites, also did nothing.

## Expected behavior

Build of jupyter lab to use git

## Context
- Python package version:
Name: jupyterlab-git
Version: 0.9.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: c:\users\borchert\wpy64-3760\python-3.7.6.amd64\lib\site-packages
Requires: notebook, pexpect, nbdime
Required-by:
- Extension version:
JupyterLab v1.2.6
Known labextensions:
   app dir: c:\users\EmCeBeh\wpy64-3760\python-3.7.6.amd64\share\jupyter\lab
        @bokeh/jupyter_bokeh v1.1.1 enabled  ok
        @jupyter-voila/jupyterlab-preview v0.1.3 enabled  ok
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        @jupyterlab/git v0.9.0 enabled  ok
        @jupyterlab/vega3-extension v1.0.0 enabled  ok
        @pyviz/jupyterlab_pyviz v0.8.0 enabled  ok
        bqplot v0.5.1 enabled  ok
        jupyter-leaflet v0.11.6 enabled  ok
        jupyter-matplotlib v0.5.0 enabled  ok
        jupyter-threejs v2.1.1 enabled  ok
        jupyterlab-datawidgets v6.2.0 enabled  ok
        nbdime-jupyterlab v1.0.0 enabled  ok

Build recommended, please run `jupyter lab build`:
    @bokeh/jupyter_bokeh needs to be included in build
    bqplot needs to be included in build
    jupyter-leaflet needs to be included in build
    jupyter-matplotlib needs to be included in build
    jupyter-threejs needs to be included in build
    @jupyter-voila/jupyterlab-preview needs to be included in build
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    jupyterlab-datawidgets needs to be included in build
    @jupyterlab/git needs to be included in build
    nbdime-jupyterlab needs to be included in build
    @pyviz/jupyterlab_pyviz needs to be included in build
    @jupyterlab/vega3-extension needs to be included in build

Thank you in advaence :)

**Comment by fcollonval** [comment]
@EmCeBeh could you try to clean the yarn cache too? You could do so with the following command:

```
jlpm cache clean
```

Then try rebuilding Jupyterlab again.

**Comment by fcollonval** [comment]
I close this as this is not related directly to the extension.
