### ISSUE TITLE
Unicode values for file names for a file name using Chinese

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-git#543]
## Description

When using the git extension in Jupyterlab and trying to list the status of files named using Chinse characters only unicode values are displayed.

JupyterLab file browser

<img width="401" alt="image" src="https://user-images.githubusercontent.com/382917/75341170-26f1b400-5894-11ea-926a-30dd588675d0.png">

Git status panel

<img width="406" alt="image" src="https://user-images.githubusercontent.com/382917/75341202-396bed80-5894-11ea-950d-b9cd5f1ec604.png">

## Reproduce

Name a file using Chinese characters and try to view its status on the git panel

## Expected behavior

The filename would display properly as in the FileBrowser

**Comment by lresende** [comment]
Investigating this issue further, it seems to be a general git configuration issue, as you would get the same result if you use the git command line:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	"pipelines/\303\263\303\255.ipynb"
	"\346\237\220\344\272\213.ipynb"

```

Git has a configuration to disable this behavior:

```
git config --global core.quotepath false
```

Which then give you the proper result in the git command line

```
git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pipelines/óí.ipynb
	某事.ipynb

```

As well as in the jupyterlab git ui:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/382917/75341633-23aaf800-5895-11ea-9bd4-f6f577af81c2.png">

**Comment by ajbozarth** [comment]
I already have a fix for this in my fork and was going to bring it up at scrum today
