### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab-git#549]
The JupyterLab extension @jupyterlab/git in current master is marked as NPM package version 0.10.0, and contain dependencies that allow for use with JupyterLab 2.0.0. This has not yet been released to NPM though, where it remains at 0.9.0.

As I understand it from https://github.com/jupyter/nbdime/pull/512#issuecomment-594185766, this release is awaited by the `nbdime-jupyterlab` jupyterlab extension in order for it to go JupyterLab 2.0.0 compatible.

Thank you for all your work on this! :heart:

## References
- https://www.npmjs.com/package/@jupyterlab/git

**Comment by telamonian** [comment]
There's already a discussion about the 0.10.0 release at #517, so I'll close this issue as a duplicate. The executive summary:

- 0.10.0 will be jlab 1.0 compatible, and will not work with jlab 2.0
- 0.10.0 is waiting on [at least 3 open PRs](https://github.com/jupyterlab/jupyterlab-git/milestones/0.10.0), and possibly a couple of others
- Once 0.10.0 is released, we'll switch development on the master branch to a jlab-2.0 compatible version (see #520, #550 for the actual 2.0 fixes)
- We'll release the first jlab-2.0 compatible version 0.20.0 (reserving everything in between 0.10.0 and 0.20.0 for backport releases) once the above is dealt with and nbdime updates

**Comment by consideRatio** [comment]
Thank you @telamonian for this great summary! Sorry for not looking properly and duplicating an issue.

**Comment by telamonian** [comment]
@consideRatio As of a couple days ago 0.10.0 has been released
