### ISSUE TITLE
Problem with install in the build step

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#551]
Having `jlpm install` in the [package.json's build](https://github.com/jupyterlab/jupyterlab-git/blob/master/package.json#L16) is somewhat problematic. I happened to have set `NODE_ENV=production yarn run build`, which yarn took to mean uninstall all my dev dependencies.

Not a high priority, but thought it was worth flagging.

**Comment by kgryte** [comment]
@mlucool Not clear the problem in this case, given that `yarn` respected the `NODE_ENV` environment variable as discussed [elsewhere](https://github.com/yarnpkg/yarn/issues/2739), mirroring `npm` install behavior.

What were you wanting to have happen when setting `NODE_ENV` to `production` if not the installation of only dependencies and not development dependencies?

**Comment by mlucool** [comment]
I expect that `NODE_ENV=production yarn run build` builds for production. This does not work because it uninstalls my build tools first (I don't have tsc globally installed) so it just errors.
