### ISSUE TITLE
Discard changes fails due to index.lock already exists

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-git#555]
## Description

Discard changes fails due to index.lock already exists

## Reproduce

1. Go to a directory that represents cloned git repository
2. Make changes to a given file
3. Click on the icon to pull from the repository
![image](https://user-images.githubusercontent.com/382917/76171722-afe9d480-614b-11ea-8a1c-58b6b35106e5.png)

4. Now, try go discard the changes in order to be able to pull from the repository
![image](https://user-images.githubusercontent.com/382917/76171748-00613200-614c-11ea-8a5f-899c2c2842a4.png)

5. Discard fails due to `index.lock` is already present
![image](https://user-images.githubusercontent.com/382917/76171727-c2640e00-614b-11ea-8360-01d672c1cbf5.png)

## Expected behavior

Discard should discard the changes for the file

## Context

- Python package version:
  - JupyterLab 1.2.7
  - Jupyterlab-git master

## Workaround

It seems that on the second try it actually behaves well, needs to investigate it further.

**Comment by lresende** [comment]
This seems related to the following git config in my environment
```
[branch]
        autosetuprebase = always
```
Maybe we could check for this and decide if we should use `git merge --abort` versus `git rebase --abort`

**Comment by fcollonval** [comment]
This should be fixed by #564
