### ISSUE TITLE
Extension outdated with JupyterLab v2.0.1

### ISSUE THREAD

**Issue by kir0ul** [jupyterlab/jupyterlab-git#559]
## Description

Can't use `jupyterlab-git` with `JupyterLab` v2.0.1, it says `jupyterlab-git` is outdated.

## Reproduce

1. `conda create -n testenv python=3.8`
2. `conda activate testenv`
3. `conda -c conda-forge install jupyterlab jupyterlab-git`
4. `jupyter lab build` outputs: `[LabBuildApp] WARNING | The extension "@jupyterlab/git" is outdated.`
5. If I try `jupyter labextension update --all`, it outputs `No compatible version found for @jupyterlab/git!`

## Expected behavior

I would really like to be able to use `jupyterlab-git` with `JupyterLab` v2.0.*.

## Context

- Python package version:

```
conda list jupyterlab-git
# packages in environment at /home/apierre/miniconda3/envs/testenv:
#
# Name                    Version                   Build  Channel
jupyterlab-git            0.9.0                      py_0    conda-forge
```

- Extension version:

```
jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /home/apierre/miniconda3/envs/testenv/share/jupyter/lab
        @jupyterlab/git v0.9.0  enabled   X
        nbdime-jupyterlab v2.0.0  enabled  OK

   The following extension are outdated:
        @jupyterlab/git
        
   Consider running "jupyter labextension update --all" to check for updates.
```

**Comment by kgryte** [comment]
@kir0ul Feel free to try this [PR](https://github.com/jupyterlab/jupyterlab-git/pull/520). The need to support `2.0` has to be balanced with the need to support users unable to immediately migrate from `1.0`.

**Comment by phish108** [comment]
Cheers, 

I have just upgraded my docker containers and I don't see the point of not being able to migrate immediately from 1.2.x to 2.0.x - it works absolutely smoothly for me - just now the environment is without git support.

In other words: The upgrade from 1.2.x to 2.0.x is not immediately possible, only if the git extension is used :( 

PR #520 also appears to be broken with the master branch and has no conda or npm release, which makes "trying out" more complicated in containerized environments.

Isn't it possible to branch off the version for JL 2.0.x and release it separately using semantic versioning? This would make sense for people who are able to use version pinning.

**Comment by viotemp1** [comment]
Same issue:
Conflicting Dependencies:
JupyterLab              Extension         Package
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/application
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/apputils
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/console
>=4.0.0 <4.1.0          >=3.1.0 <4.0.0    @jupyterlab/coreutils
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/filebrowser
>=5.0.0 <5.1.0          >=4.1.0 <5.0.0    @jupyterlab/services
>=2.0.0 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/terminal
>=16.9.0 <16.10.0       >=16.8.4 <16.9.0  react
>=16.9.0 <16.10.0       >=16.8.4 <16.9.0  react-dom
Can this be fixed?

**Comment by DraTeots** [comment]
Cmon guys, you are breaking your own extenstion and make is useless

**Comment by kgryte** [comment]
@DraTeots Feel free to use JupyterLab `1.x` in the meantime.

**Comment by saravanabalagi** [comment]
@kgryte Thanks for the workaround. Have you planned any release date (if not is there an ETA) that you can let us know for shipping the update that works with jupyterlab 2?

**Comment by DraTeots** [comment]
**Now it is [Jupyterlab 2.1](https://pypi.org/project/jupyterlab/)**

Don't get my previous post as offensive. The "problem" I see is that when people do pip install jupyterlab they get 2.1 (now). And it is hard to "tame" them to use old version. 

At the same time Jupyterlab development model is such that "the later version is more stable" as I see it at this point.

**Comment by camelator** [comment]
hi!
Same issue here.

**Comment by farooq-omer** [comment]
I also received the following error and unable to use git in Jupyterlab:
(base) omer@Falcon-7:~$ jupyter serverextension list
config dir: /home/omer/anaconda3/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.1 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.10.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.0.0 OK
(base) omer@Falcon-7:~$ jupyter labextension list
JupyterLab v2.1.1
Known labextensions:
   app dir: /home/omer/anaconda3/share/jupyter/lab
        @jupyterlab/git v0.10.0  enabled   X
        nbdime-jupyterlab v2.0.0  enabled  OK

   The following extension are outdated:
        @jupyterlab/git
        
   Consider running "jupyter labextension update --all" to check for updates.

(base) omer@Falcon-7:~$ jupyter labextension update --all
No compatible version found for @jupyterlab/git!
Extension 'nbdime-jupyterlab' already up to date

**Comment by fcollonval** [comment]
Follow the issue #602 to see the progress of publication for JLab 2.

In the meantime, for those willing to test the upcoming release, you could try installing the release candidate using the following commands:

```bash
python -m pip install --pre jupyterlab-git==0.20.0rc0
jupyter lab build
```

**Comment by DaveDeCaprio** [comment]
I tried this release and I get the following error when notebooks start up:

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed',)).History will not be written to the database.

 

I never saw this before the upgrade.  It doesn’t seem to be causing an issue though, Jupyter appears to b e working fine.

 

Dave

**Comment by fcollonval** [comment]
@DaveDeCaprio Thanks for reporting. Could you open an separate issue and provide as much details as possible? Especially because googling your error message is only pointing to an SQLite exception that has nothing to do with this extension (nor JupyterLab actually)...

**Comment by fcollonval** [comment]
I'm closing this one as 0.20.0 has been released now.
