### ISSUE TITLE
Conflict dependencies trying to install on JLab 1.2.4-1.2.7

### ISSUE THREAD

**Issue by LukaPitamic** [jupyterlab/jupyterlab-git#563]
Following official installation guide on newly created environment...
![image](https://user-images.githubusercontent.com/34914144/76813580-6ee66580-67c6-11ea-98e8-540b0de0189e.png)

I've spend hours trying to make it work, is there something I'm missing? Thank you in advance for any direction.

if it helps, here's output of `jupyter serverextension list`:
![image](https://user-images.githubusercontent.com/34914144/76813554-5d9d5900-67c6-11ea-8d71-2a93b998c33b.png)

**Comment by lresende** [comment]
I just merged #560 which should fix this problem. You will need to use master while a release is not available.

**Comment by LukaPitamic** [comment]
@lresende Thank you very much for quick response. Will do...
