### ISSUE TITLE
git log and git diff

### ISSUE THREAD

**Issue by zzhangjii** [jupyterlab/jupyterlab-git#58]
use git log to obtain info for user to view previous commits;

research git diff to design a user friendly interface to:
1. view differences
2. make changes?
3. solve file conflicts??

**Comment by vidartf** [comment]
Note that this is partially/mostly solved for notebooks by nbdime, which is currently working on a jlab extension as well. It would be good if this plugin exposed an API for other plugins to register diff providers.

**Comment by zzhangjii** [comment]
great!!! it uses git, that's exactly what we need right now,

**Comment by ellisonbg** [comment]
Please target this to a milestone

**Comment by ashutoshbondre** [comment]
we have decided to go ahead with opening the `git diff` files inside JupyterLab (Just like Help Menu References) Moving it to #106
