### ISSUE TITLE
UX: Git Push/Pull

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#582]
## Description

When push does not error, the UI always says:
![image](https://user-images.githubusercontent.com/1813603/78080802-04fcbd00-737d-11ea-897e-6002d5135d80.png)

While this is not wrong, it's misleading when nothing was pushed. The git CLI says:
```
$ git push
Everything up-to-date
```

We should do something similar in the UI so people know that everything was up to date and nothing happened. The same is also true for the pull messages.

**Comment by fcollonval** [comment]
When tackling this one, a good improvement would be also to use a non-blocking UI to display push-pull progress - may be a status-bar indicator.
