### ISSUE TITLE
Git Init Menu

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#584]
The menu has "Git Init" in it.  I suggest two separate things:
1. Remove git init when inside a git repo already (its rare to have one git repo int another)
2. Allow users, via a config option, to change the default command from `git init` to something else.

The reason for 2, is I typically want `git init && setup_notebook_filters`.

What do people think?

**Comment by fcollonval** [comment]
>     Remove git init when inside a git repo already (its rare to have one git repo int another)
👍 
I'm not a big fan of hiding UI element. I would suggest disabling the command in such case as done for the `add remote` command:
https://github.com/jupyterlab/jupyterlab-git/blob/2787178ecdf50a8adb3ed576ea03b6de4feddef5/src/gitMenuCommands.ts#L118

>     Allow users, via a config option, to change the default command from `git init` to something else.
👎 
In #494, it was decided to suppress the ability to run custom commands in terminal to follow the rules of JupyterLab. So I vote to reject this proposal for the same security reason.

**Comment by mlucool** [comment]
> In #494, it was decided to suppress the ability to run custom commands in terminal to follow the rules of JupyterLab. So I vote to reject this proposal for the same security reason.

That is a good point. Do you have any suggestions? What if we add the ability to set in in the server config (`jupyter_notebook_config.py`)? I think that should mitigate the security concern. 

My use case is for init to setup [nbstripout](https://github.com/kynan/nbstripout) (update .gitattibutes) and on clone to rerun the setup to re-add to the git filters (they are not stored for security reasons). So I'd want some way to say when you init or clone - run this command (or run this command after init or clone is fine too).

**Comment by jaipreet-s** [comment]
> Remove git init when inside a git repo already (its rare to have one git repo int another)

👍 as well. For reference, the _Git Clone_ button used to be disabled if already inside a Git repo, to discourage nesting of Git repos #260,  though I'm not sure if this is still the case after the recent refactoring)

**Comment by fcollonval** [comment]
There is a hanging feature request for cleaning notebooks (https://github.com/jupyterlab/jupyterlab-git/issues/392). So it may be better to introduce this feature specifically through an extension option - I imagine that using a tooglable menu item would be appropriate.

There is also some issues with `nbdime` and `nbstripout` on Windows (see https://github.com/jupyterlab/jupyterlab-git/issues/471#issuecomment-578417925).
Another point often mentioned is the poor performance of `nbstripout` (see [here](http://timstaley.co.uk/posts/making-git-and-jupyter-notebooks-play-nice/)). So some people prefer using [`jq`](https://stedolan.github.io/jq/) (see previous link).

**Comment by mlucool** [comment]
I don't think we'll find a one size fits all solution to cleaning notebooks (e.g. don't count out [jupytext](https://jupytext.readthedocs.io/en/latest/introduction.html)).

I think it's better to focus this solely on a git UI as any feature that is added here must also work via CLI anyway. That is not to say we shouldn't enable people to use these useful tools, but, IMO, there should be no choice made in this project that isn't generic.

FWIW, nbstripout isn't fast, but it has features jq make hard to implement making it my current preferred choice in this area.

**Comment by fcollonval** [comment]
@mlucool would you like to propose a PR for this one?

**Comment by ianhi** [comment]
A PR modifying `init` in the menu the could be combined with: https://github.com/jupyterlab/jupyterlab-git/issues/456
