### ISSUE TITLE
Failed to diff text files in staging

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#585]
## Description

Attempting to diff a Markdown file (.md) or a Python file (.py) in the "Staged" section leads to an error `Failed to fetch diff with error:Error while determining if file is binary or text 'fatal: bad revision '' '.`

## Reproduce

1. Clone a git repo `git clone https://github.com/jupyterlab/jupytelrab-git` and create a new Markdown file using the Launcher.
2. From the _Untracked_ section, click the "+" button to add it to the _Staged_ section
3. Click the diff button next to the file
4. See error `Failed to fetch diff with error:Error while determining if file is binary or text 'fatal: bad revision '' '.`

## Expected behavior

I see a line-level diff of this plaintext file.

## Context

- Python package version: 0.10
```
sh-4.2$ pip show jupyterlab-git
Name: jupyterlab-git
Version: 0.10.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
```
- Extension version:

```
sh-4.2$ jupyter labextension list
JupyterLab v1.2.8
Known labextensions:
   app dir: /home/ec2-user/anaconda3/envs/JupyterSystemEnv/share/jupyter/lab
        @jupyterlab/celltags v0.2.0  enabled  OK
        @jupyterlab/git v0.10.0  enabled  OK
        @jupyterlab/toc v2.0.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK

```

<details><summary>Browser Output(500 from the /diff content API) </summary>

The request payload is 
```json
{"filename":"examples/untitled.md","prev_ref":{"git":"HEAD"},"curr_ref":{"special":"INDEX"},"top_repo_path":""}
```

The response payload is
```json
{"message": "Error while determining if file is binary or text 'fatal: bad revision ''\n'.", "reason": null}
```
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

The logs from the server don't add much more either

```

[W 03:55:27.798 NotebookApp] 500 POST /git/diffcontent?1585799727736 (10.0.0.41): Error while determining if file is binary or text 'fatal: bad revision ''
    '.
[W 03:55:27.798 NotebookApp] Error while determining if file is binary or text 'fatal: bad revision '
```

**Comment by jaipreet-s** [comment]
![Screen Shot 2020-04-01 at 9 04 17 PM](https://user-images.githubusercontent.com/43826141/78209613-621b7000-745c-11ea-84a5-fc4fedd7414a.png)

**Comment by jaipreet-s** [comment]
Confirmed this doesn't happen in the _Changed_ section for text files
![Screen Shot 2020-04-01 at 9 09 07 PM](https://user-images.githubusercontent.com/43826141/78209878-2503ad80-745d-11ea-8046-a713512d1645.png)

Confirmed this doesn't happen for notebook files

**Comment by fcollonval** [comment]
Thanks for reporting @jaipreet-s !

I took the liberty to fulfill the request and response payload.

**Comment by fcollonval** [comment]
I'm working on a fix.
