### ISSUE TITLE
jupyterlab-git not found

### ISSUE THREAD

**Issue by soerendip** [jupyterlab/jupyterlab-git#587]
> Internal Error:
> Fail to get the server root path. Error: Git server extension is unavailable. Please ensure you have installed the JupyterLab Git server extension by running: pip install --upgrade jupyterlab-git. To confirm that the server extension is installed, run: jupyter serverextension list
> 

```
conda install -c conda-forge jupyterlab-git
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

Also this command does not change anything:

     pip install --upgrade jupyterlab-git

Using jupyterlab 1.2.6.

**Comment by soerendip** [comment]
I also had to install jupyter_nbextensions_configurator with 

    conda install -c conda-forge jupyter_nbextensions_configurator

**Comment by DevMui** [comment]
@soerendip I had the same error and installing `jupyter_nbextensions_configurator` helped! Thanks a lot!

**Comment by ajila-123** [comment]
how to update the version of jupyter lab git? wen i checked with server extension it shows version 2.0.0,but jupyterlab  is aking for a higher version of git and after trying all these also still the same version and not able to add gitplus

**Comment by ajila-123** [comment]
git command not found - please ensure you have Git > 2 installed

**Comment by ajila-123** [comment]
can anyone help pls...I am new to this

**Comment by fcollonval** [comment]
@ajila-123 please open a new issue and provide the required information (which OS, which JupyterLab version, which git version, which jupyterlab-git version, which package manager).
