### ISSUE TITLE
To list tags of a repository

### ISSUE THREAD

**Issue by chrisjohn2306** [jupyterlab/jupyterlab-git#588]
## Description

To add a drop down in the extension git panel that lists all the tag versions of a repository. On clicking a tag version should be checked out.

<img width="390" alt="Screenshot 2020-04-14 at 9 43 30 AM" src="https://user-images.githubusercontent.com/58581644/79185721-6456d480-7e35-11ea-9a6d-72cf4188fc93.png">

## Reproduce

Will be a new addition to the git panel

## Expected behavior

The tag drop down should be populated with the list of tag versions and on clicking a tag version should be checked out. The checked out version should be a new branch with specified repository version

## Context

- Python package version:

- Extension version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for the proposal.

As much as I like the idea, I am not to found of adding a button below the branch selector. We already have lots of elements taking vertical space. An alternative solution - for example grouping it somehow with the branches - should be imagined.

**Comment by kgryte** [comment]
I agree with @fcollonval. Also, some friction should be introduced for checking out based on a tag as this puts the user in a detached state, which could be confusing for new users.

One possibility is to add the tag icon to the top toolbar along with the push, pull, and refresh icons. On click, a dialog could be opened which lists the tags, provides intro text with warnings, and allows a tag to be checked out.

As this is more of an "advanced" use case, I don't think we should make it a prominent UI element.

**Comment by chrisjohn2306** [comment]
Thanks for the suggestions @fcollonval and @kgryte . I will be looking into the UI part and incorporating the ideas.

For the checkout part , when a user wants to checkout a tag version, i was thinking to create a new branch and checkout, to minimise the confusions. If it is a new branch then the functionality will not vary much. Although we might have to disable commit and push functionalities in such cases, to reduce the chances of conflicts occurring.

I hope that this will not impact the usability.

**Comment by chrisjohn2306** [comment]
The tag icon has been added next to the git pull/push icons. 
<img width="348" alt="Screenshot 2020-05-04 at 10 13 32 AM" src="https://user-images.githubusercontent.com/58581644/80936795-4820d480-8df0-11ea-9749-d38bbee79e62.png">

A dialogue box pops up when clicked on listing all the tag versions.
<img width="392" alt="Screenshot 2020-05-04 at 10 15 31 AM" src="https://user-images.githubusercontent.com/58581644/80936800-4eaf4c00-8df0-11ea-9ab3-fc04b487fa57.png">

On click, the tag version is checked out to a new branch, instead of a detached head. 
<img width="335" alt="Screenshot 2020-05-04 at 10 15 40 AM" src="https://user-images.githubusercontent.com/58581644/80936804-5111a600-8df0-11ea-9ecc-92dfc5c0d5d3.png">

**Comment by fcollonval** [comment]
Closed by #713
