### ISSUE TITLE
improve GitPanel UI when not in a git repository.

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#589]
## Description
I think that the following changes could improve the user experience of opening the GitPanel when not currently in a repository

1. Change the message to say "`current path` is not a git repository"
2. Add a git init button
3. Style the buttons similarly to the rest of the extension.
4. Reword "Find a repository" => "Open FileBrowser"
I think a `git init` button should be added to the git panel when not currently in a repo.

**Justifications**
1. I often see this error message when I'm off by one directory, so the immediate feedback makes it quicker to figure out what has gone wrong.
2. I also run into this version of the panel when I want to run `git init`. Despite using this extension a good amount I was unaware of the git init in the menu, this will make it very obvious that this capability exists.
3. The current button's style doesn't match with the more recently added buttons in the application and the new ones are nicer.
4. I think this makes it clearer what the button will do.

**Current UI**:
![image](https://user-images.githubusercontent.com/10111092/79181115-a2bea600-7dd9-11ea-9ffe-cc14101f5b58.png)

**Proposed UI**:

![image](https://user-images.githubusercontent.com/10111092/79186114-c0ded300-7de6-11ea-9f13-3b2e0868e85e.png)

If these seem like useful and acceptable changes I can open a PR with the changes I made to create above image.

**Comment by fcollonval** [comment]
@ianhi That is a great idea. If you get the chance to push a PR, I'll review it.

Suggestions:
- It may be interesting to change the text _Current Repository_ in such case or to hide it.
- You should make the button labels more expressive (i.e. not reflecting the API used but the consequence for the user). As inspiration, here is the panel content in VS Code:

![image](https://user-images.githubusercontent.com/8435071/79632425-5bc90b80-815f-11ea-8706-03afff270fd7.png)

Of course in this case, that will be initializing the repository not cloning one.
