### ISSUE TITLE
Put master branch at top of New Branch Dialog

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#595]
## Description
When I make a new branch I am often basing it off the master branch rather than the current branch. The current UI sorts the current branch to the top of the list of branches to build off of. But if there are enough branches then the master branch can be hidden. For example here is the jupyterlab repo:
![image](https://user-images.githubusercontent.com/10111092/79477780-9e141080-7fd8-11ea-8b44-530d36283104.png)
Contrast to GitHub desktop which only provides the master branch and the current branch in this dialog:
![image](https://user-images.githubusercontent.com/10111092/79477913-c69c0a80-7fd8-11ea-8077-1e9d34dfbe74.png)

I think it's nice that jupyterlab-git provides more options but it would be nice if the list was sorted as:
- Master
- Current Branch
- rest of branches

As well, maybe the master branch could be pre-selected?

**Comment by kgryte** [comment]
You would not want it to be the `master` branch, per se, but the repository's default branch. TMK the extension does not currently track which branch is the "default" branch, but I could be wrong.

**Comment by ianhi** [comment]
It seems that git doesn't have a concept of a "default branch", rather that is something added on by services like github ([ref](https://stackoverflow.com/a/51274682)):
> As far as I know, git has no concept of a "default branch". User interfaces such as GitHub do have a default branch in the sense that when you open the web page, you see a certain branch (generally master) by default

That said, I agree that the default branch should be used when that concept is applicable. Based on https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch it seems that checking the contents of `.git/refs/remotes/origin/HEAD` is a reasonably robust way of detecting the default branch if there is one. The answers all imply that this should work for github and I tested it for gitlab using (https://gitlab.com/ianhi/test2) and found it worked for both.

When this file is unavailable then it would be nice to default to the master branch. The master branch enjoys special status by dint of being the default branch on sites like github and also is the first branch created by `git init`. My sense is that guessing the master branch as the default is the correct choice in the vast majority of cases.

**Comment by fcollonval** [comment]
@ianhi if you get some time to at least get the master branch as second choice if it is the current.
Tracking the default will be complicated. as per your research, it implies looking at the remotes - there may be more than one, the names can be something else than origin.
So as a first improvement for the majority of cases, just considering *master* as special seems a good ratio between coding effort and number of users having a better experience.

**Comment by ianhi** [comment]
Great. I opened a PR. While this dialog is being looked at the other thing I found slightly weird is that if I switch branches the initially selected branch doesn't change. The branch that is selected by default seems to always the branch that the repo was on when the page was last refreshed.
You can see how in the below gif the `asdf` branch is selected by default the second time I open the dialog:
![weird_branch_selection](https://user-images.githubusercontent.com/10111092/79661543-5335fc80-8182-11ea-8b11-251678664500.gif)
