### ISSUE TITLE
Provide feedback on git command execution

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#601]
This is a follow-up of #564.

Proposal:

1.  Allow retry timeout configurability for acquiring the index.lock.
2.  Suspend UI interactions until pending command complete (e.g., a modal with a spinner). I believe this should be straightforward, as we just need to enable a UI element until receiving an HTTP response.

The need for the latter is to prevent/dissuade the user from closing the JupyterLab server before pending commands have had a chance to complete (e.g., before an `index.lock` file is removed and `git add && git commit` run, thus potentially leading to the discarding of user changes).

_Originally posted by @kgryte in https://github.com/jupyterlab/jupyterlab-git/pull/564#issuecomment-612141351_

**Comment by kgryte** [comment]
Assigning myself. Am currently working on this.

**Comment by jaipreet-s** [comment]
I'm not sure if any UX discussions have happened around this, but the JupyterLab Status Bar is a candidate for to notify the user that an async background process is running, without having a dialog blocking their view.

(JFYI the Status Bar was not present in JL core while many of these Git actions were implemented)

**Comment by kgryte** [comment]
Thanks for the suggestion. I'd still lean toward using a backdrop or other UI element to prevent further user action. The main impetus for this is to guard against the "race condition" of a user ending the server process before commands have finished executing. A status bar indicator is unlikely to dissuade users from prematurely doing so.
