### ISSUE TITLE
Release jupyterlab-git 0.20.0 based on JupyterLab 2.x

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-git#602]
We are getting ready to merge #599 which brings support for JupyterLab 2.x and we should make a release. 

Release Plan

- [x] Merge #599 
- [x] Create 0.20.0 release candidate
- [x] After a week or so, create final release if no issues found.

**Comment by lresende** [comment]
@telamonian @fcollonval

**Comment by dragoljub** [comment]
Awesome! Looking forward to support on JupyterLab 2.1.0! 👍

**Comment by fcollonval** [comment]
The bug fix PR https://github.com/jupyterlab/jupyterlab-git/pull/586 should be approved and merged.

There is also the PR https://github.com/jupyterlab/jupyterlab-git/pull/583. As I am not a English native speaker, I let somebody more confortable with Shakespeare language accept it or not.

**Comment by telamonian** [comment]
@fcollonval I just merged #583

**Comment by fcollonval** [comment]
Version 0.20.0rc0 has been released.

**Comment by luminoso** [comment]
Thank you for this release. When I click `View file changes` using the commit log tree view, for an older commit I have this error in the new tab:

`Failed to fetch diff with error:JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Does this happen to anyone else? It is worthy of a new bug report?

**Comment by fcollonval** [comment]
Known issues:
- https://github.com/jupyterlab/jupyterlab-git/issues/602

**Comment by fcollonval** [comment]
@luminoso could you please 

- check the serverextension and lab extension version installed
- create a separate issue 
- provide as much information as possible on it 
  - JupyterLab version
  - OS
  - Type of file you tried diffing (notebook or plain text)?
  - HTTP request that failed if you can

**Comment by fcollonval** [comment]
Version 0.20.0 has been released.

**Comment by dragoljub** [comment]
Thanks! This is working great for me on Windows 10! 👍

**Comment by xiaokunx** [comment]
> Thank you for this release. When I click `View file changes` using the commit log tree view, for an older commit I have this error in the new tab:
> 
> `Failed to fetch diff with error:JSON.parse: unexpected character at line 1 column 1 of the JSON data`
> 
> Does this happen to anyone else? It is worthy of a new bug report?

same issue here, will create a new issue
