### ISSUE TITLE
Is it possible to use jupyterlab-git in JupyterLab 2.0.1?

### ISSUE THREAD

**Issue by kwon14** [jupyterlab/jupyterlab-git#603]
I'm using Dockerfile by launching it with jupyter-base-notebook.
I'm trying to install an extension of jupyterlab-git into jupyterlab 2.0.1.
but It doesn't work.
Is it possible to use jupyterlab-git in JupyterLab 2.0.1?

Here is error : 
-------------------
An error occured.
ValueError: The extension "@jupyterlab/git" does not yet support the current version of JupyterLab.
Conflicting Dependencies:
JupyterLab              Extension         Package
>=2.0.2 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/application
>=2.0.2 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/apputils
>=2.0.2 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/console
>=4.0.2 <4.1.0          >=3.1.0 <4.0.0    @jupyterlab/coreutils
>=2.0.2 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/filebrowser
>=5.0.2 <5.1.0          >=4.1.0 <5.0.0    @jupyterlab/services
>=2.0.2 <2.1.0          >=1.1.0 <2.0.0    @jupyterlab/terminal
>=16.9.0 <16.10.0       >=16.8.4 <16.9.0  react
>=16.9.0 <16.10.0       >=16.8.4 <16.9.0  react-dom
-----------------------------------

Here is my code in dockerfie:
-----------------------------------
RUN conda install --quiet --yes \
         'notebook=6.0.3' \
         'jupyterhub=1.1.0' \
         'jupyterlab=2.0.1' && \
          conda clean --all -y && \
          npm cache clean --force && \
          jupyter notebook --generate-config && \
          rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
         rm -rf /home/$NB_USER/.cache/yarn && \
         fix-permissions $CONDA_DIR && \
         fix-permissions /home/$NB_USER

RUN jupyter labextension install @jupyterlab/git --no-build && \
        jupyter serverextension enable --py --sys-prefix jupyterlab_git

**Comment by telamonian** [comment]
Short answer, no. Long answer, wait a week.
