### ISSUE TITLE
binder on README is not running master

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#605]
The binder link on the README is not running master. The easiest way to see this is to verify the version of lab being run. It is not `2.x`, which is a requirement of master. This is at least partly due to [environment.yaml](https://github.com/jupyterlab/jupyterlab-git/blob/master/binder/environment.yml)

**Comment by fcollonval** [comment]
Thanks for reporting this @mlucool. Indeed you cornered the error source.
