### ISSUE TITLE
Add setting to change behavior of clicking on file in changes tab

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#616]
## Description
Currently doubling clicking a file in the changes tab opens the file in jupyterlab. While this is a reasonable default I'd like to be able to double click to open a diff of the file. Could a setting be added that allows for toggling the behavior from opening the file to opening a diff of the file?

This preference is because I find that I mostly use the git interface to check the diffs of files I'm currently working or about to commit. I also seem to have residual expectations of this behavior from github desktop.

**Comment by fcollonval** [comment]
Good idea. This implies to add a settings to choose a behavior. And a new action button to open the file would be welcomed.

**Comment by ianhi** [comment]
Should the default action be kept as is? My sense is that diffing ought to be the default, but I'm clearly biased.

**Comment by fcollonval** [comment]
@ianhi yes please try avoiding changing the default behavior.
