### ISSUE TITLE
Styling of filenames in error/warning dialogs

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#617]
## Description
Currently in the Error Switch branch dialog or in the Discard warning dialog the filename is not visually distinct from the rest of the text.

![image](https://user-images.githubusercontent.com/10111092/80055326-68e35300-84ef-11ea-9b1e-3f9b92aca212.png)

![image](https://user-images.githubusercontent.com/10111092/80055036-b9a67c00-84ee-11ea-9586-4551c8acacb0.png)

### Expected behavior
The file would stand out so I can easily identify what file(s) are causing the problem/being discarded.

the `showErrorMessage` used in the branch error only accepts a string as input, but the `showDialog` used by discard can take a react element, so with a small change the filename can be made to stand out more:
```diff
diff --git a/src/components/FileList.tsx b/src/components/FileList.tsx
index 0d5c8cc..2b4a5d1 100644
--- a/src/components/FileList.tsx
+++ b/src/components/FileList.tsx
@@ -237,7 +237,7 @@ export class FileList extends React.Component<IFileListProps, IFileListState> {
   discardChanges = async (file: string) => {
     const result = await showDialog({
       title: 'Discard changes',
-      body: `Are you sure you want to permanently discard changes to ${file}? This action cannot be undone.`,
+      body: <span>Are you sure you want to permanently discard changes to <b>{file}</b>? This action cannot be undone.</span>,
       buttons: [Dialog.cancelButton(), Dialog.warnButton({ label: 'Discard' })]
     });
     if (result.button.accept) {
```
![image](https://user-images.githubusercontent.com/10111092/80055227-2faae300-84ef-11ea-806a-0fef8c30fa46.png)

**Comment by fcollonval** [comment]
Don't hesitate to open a PR.

**Comment by ianhi** [comment]
Done. I thought best practice was to open an issue first to allow for discussion? Is it ok to sometimes go straight to a PR?

**Comment by fcollonval** [comment]
Thanks for the PR.

Yes opening an issue before a PR is the good practice. As the issue list is first place people will look before reporting something. So you did perfectly 👏
