### ISSUE TITLE
TypeError: "this.props.model.currentBranch is null" (v0.20.0rc0 )

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-git#625]
Hi,
we are using jupyterlab-git/0.20.0rc0 in jupyterlab/2.1 and get the error  `TypeError: "this.props.model.currentBranch is null"`  by this extension in the WebKonsole every roughly every second once.

It seems to my as if the name of a branch is searched in the current folder, which is not a git directory.

![jupyterlab-git-0 20 0rc0_branchnull](https://user-images.githubusercontent.com/9266792/80586215-eab60d80-8a14-11ea-8ce9-086922d902fe.png)

**Comment by fcollonval** [comment]
@jhgoebbert Thanks for reporting this. 

Was it working with JLab 1 and the 0.10 version?
Do you see an error on the server side?

**Comment by jhgoebbert** [comment]
We have jupyterlab-git in version 0.8.1 installed in our jupyterlab 1.2.6 installation.  
There it does not show any errors on the webkonsole.

**Comment by jhgoebbert** [comment]
Just as an additional information:  
Most of the other extensions report this error once or multiple times  
"TypeError: 'NetworkError when attempting to fetch resource.'"  
And they fail to activate.
This is not the case if I do not include the extension jupyterlab_git
![jupyterlab_git-errors](https://user-images.githubusercontent.com/9266792/80816317-9c993980-8bcf-11ea-8eef-4c66976df0ea.png)

**Comment by jhgoebbert** [comment]
I am using Firefox 75.0 (64bit) on Windows10 for testing.

**Comment by fcollonval** [comment]
@jhgoebbert Ok that is quite a jump in features for you then...

As you seem experienced with JS debugging, would you mind placing a break point on the line:

https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/src/components/Toolbar.tsx#L316

and report the value you get for `repo`.

To explain a bit more the extension logic, the extension is listening to the file browser to get any changes of the current folder. If such change occurs, the extension will ask the server what is the root folder of the git repository (or `null` if the folder is not in a git repository). If you are not in git repository, the current branch should not requested.

To get the top level folder the following git command is executed:

https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/jupyterlab_git/git.py#L576

Could you run that command on the non-repository folder to check it is failing?

**Comment by jhgoebbert** [comment]
@fcollonval I just send you this screenshot as it might say more than I can write (even though some words are german)
![jupyterlab-git_debugging1](https://user-images.githubusercontent.com/9266792/81115438-009b6500-8f24-11ea-82e1-a92dcbb021e0.png)
. I see that repo is "undefined", but pathRepository is set (to `/p/project/cjsc/goebbert/workspace/vis-software`. This is supprising, as I steped over the "const repo = ..."-line to line 110 and repo should be set then.  
The command `git rev-parse --show-toplevel` in the same directory succeeds with `/p/project/cjsc/goebbert/workspace/vis-software`

**Comment by aagrosch** [comment]
I seem to have narrowed down the source of the error. The response of the `_branch()` function in `model.js` does not have a response code of 0, but instead 128 with an error message of "fatal: unknown field name: HEAD", causing `_currentBranch` to be set to `null`. 

<img width="1257" alt="Error in response causes `_currentBranch` to be set to `null`" src="https://user-images.githubusercontent.com/38324489/81286650-ae605e00-9061-11ea-9648-5eb569cbffe9.png">

If it helps any, this is for a Repository on GitLab, not GitHub.

**Comment by fcollonval** [comment]
Thanks for diving in @aagrosch and @jhgoebbert 

This sounds like you are using a old version of `git`. `HEAD` is a valid field name in 2.x (https://git-scm.com/docs/git-for-each-ref). But I tested with `git` 1.8 and I got the same error: `HEAD` is not a known field name.

Could you update git on your infrastructure or at least in the environment JupyterLab is executed? For instance, git is available as a conda package. On my company infrastructure, I use conda environment to get a more recent git for Jupyter environment.

In case, you can't update `git`, I'm afraid we don't have the bandwith to support older git version. But PR are of course welcomed. However using an older version may bring problems on other features - there is at least one other known bug with git 1.8: #399.

**Comment by jhgoebbert** [comment]
Thank you @fcollonval . This is really good to know and actually easy to fix :) We will update our systems to a newer git version.

(perhaps you want to check the version of git in jupyterlab-git and warn the user, if they use a too old git)

**Comment by fcollonval** [comment]
> perhaps you want to check the version of git in jupyterlab-git and warn the user, if they use a too old git

Yep, that sounds like a reasonable check.

Could you report back once you have tested the extension with a newer git version? Then close this if it solves the issue.

Thank again for reporting and diving in.

**Comment by jhgoebbert** [comment]
I can confirm, that with an update on git 2.21.0 this problem does not occur any more.
Thanks for all your help and of course thanks for jupyterlab-git
