### ISSUE TITLE
Impossible to update an open diff

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#628]
## Description
If you have a tab with the diff of a file and then make further changes to the file you will be unable to see these changes reflected in the diff until you close the diff tab and create a new one. 
![diff-not-updating](https://user-images.githubusercontent.com/10111092/80667105-38aa3000-8a6c-11ea-8c6b-cc21d6ef8039.gif)

Clicking the diff action button again does not update the diff on account of the checking done here:
https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/src/components/diff/DiffWidget.tsx#L31-L35

## Reproduce

1. Make changes to a file
2. Open a diff of that file
3. make more changes
4. try to update the diff without closing the diff tab.

## Expected behavior
When clicking the Diff button the diff will be recomputed.

Two nice to have features would be:
1. Option to refresh the diff from a context menu when right clicking the diff widget
2. diffs that are visible are recomputed every so often, or whenever the diff is focused. 

## Context

- Python package version:
0.20.0rc0

- Extension version:
0.20.0-rc.0

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by kgryte** [comment]
Ideally, this would not be configurable. We should not display stale diffs.

**Comment by jaipreet-s** [comment]
Agreed with @kgryte that this shouldn't be configurable. 

https://github.com/jupyterlab/jupyterlab-git/blob/8d56986409461cd9968d7208da4946fca8c70392/src/components/diff/DiffWidget.tsx#L31-L35

The intent of this line was to not open a new tab every-time the diff button is clicked. I do think we should retain that UX while addressing this to avoid an explosion of diff tabs.

 Now, if a `mainAreaItem` with an `id` is found, We could address this in two ways to ensure the content gets updated with the latest diff.

1. Close that one and create a new one its place, rather than activating it, or
2. Just update the content of the `mainAreaItem` and then activate it.

P.S. Thanks for all the recent reports and PRs @ianhi !

**Comment by ianhi** [comment]
The second way makes the most sense to me. Perhaps the diff widget could update the diff with with the function `onActivateRequest` and regularly recompute the diff if it is visible (with the same polling interval as the rest of the extension)?

> P.S. Thanks for all the recent reports and PRs

It's been great fun learning about typescript through this, and it's awesome to be allowed to fix things in a tool that I would use anyway!

**Comment by kgryte** [comment]
Another way would be similar to the GitHub web interface where the extension would poll for stale diffs, display an indicator if a particular diff is stale along with a button to manually refresh the diff, and then refresh the diff upon click.

**Comment by ianhi** [comment]
> similar to the GitHub web interface 

I looked around the git documentation a little bit and didn't see any obvious way to check if a diff was stale other than recomputing it. I think the git web interface can do this because it shows diffs between commits, whereas this extension shows them between `working` and `HEAD` so there isn't an easy way to track changes between `working` at time 1 and `working` at time 2. Though my search of the documentation was more cursory than exhaustive so I could easily be missing something.

**Comment by ianhi** [comment]
Another weird issue with the diff tabs is that if you have both an editor of the file and the diff open, then right click to close the diff tab the editor:
![closing-wrong-tab](https://user-images.githubusercontent.com/10111092/80896226-684e7780-8cba-11ea-86e5-b18766d82031.gif)

This might be an issue in jupyterlab though?

**Comment by ianhi** [comment]
Recomputing a diff when it's not needed could be avoided by saving the last time the file was modified as part of the diff widget state. Then when we only compute a diff if it was modified more recently. On the python side this might look like:
```python
def maybeComputeDiff(file, last_modified, top_repo_path):
    """
    file : file path
    last_modified : time since epoch
    """
    if os.path.getmtime(file) > last_modified:
        #compute and return diff
    else:
        # return message saying diff doesn't need to be recomputed
```

**Comment by fcollonval** [comment]
First I want to second @jaipreet-s by thanking @ianhi for all his work.

Back to the feature itself, polling should be avoided (computing and displaying the diff can be costly).
I think you should take advantage of the signal emitted by the filebrowser when a file is changed. That signal is already used to force refreshing the git status:

https://github.com/jupyterlab/jupyterlab-git/blob/51ce549f57081d84e7ee38bd9aad7b6a1bf8690c/src/index.ts#L95

The signal passes an object `change` from which you can retrieve the modified file; see for example:

https://github.com/jupyterlab/jupyterlab/blob/23d7624d30ed7abc2f43480e9466947610e53ac6/packages/filebrowser/src/model.ts#L587

I think a good pattern would be to wrap the diff widget in a component that reacts to the `fileChanged` signal; maybe using the component `UseSignal`. See for example:

https://github.com/jupyterlab/jupyterlab-git/blob/5d536dde1da01da90b2ea0dcae63b807f1ddd86c/src/widgets/gitClone.tsx#L22

But one thing to check is that the diff is not recomputed each time a signal is received although it concerned another file than the one shown.

**Comment by ianhi** [comment]
What if the user discards changes to a file that they have an open diff of? My intuition is that the diff window should be closed. I think that in the this case the diff will become empty, which maybe could be used as a sign that the diff view should close?

**Comment by telamonian** [comment]
Don't autoclose the diff, that's too confusing. Just show some notification that the contents are the same (or whatever nbdime normally does on an empty diff)

**Comment by ianhi** [comment]
> Don't autoclose the diff, that's too confusing. Just show some notification that the contents are the same (or whatever nbdime normally does on an empty diff)

:+1: 

> Another weird issue with the diff tabs is that if you have both an editor of the file and the diff open, then right click to close the diff tab the editor:

Turns out this is indeed a jupyterlab issue: https://github.com/jupyterlab/jupyterlab/issues/8509
