### ISSUE TITLE
the server extension and the frontend extension have not the same version

### ISSUE THREAD

**Issue by weera-tech** [jupyterlab/jupyterlab-git#631]
I am using Jupyter Lab 2.1.1, after installing jupyterlab-git, its dropdown menu and tab are invisible, but the extension is enabled (according to what I see in the extensions tab).
After running "jupyter serverextension list" and "jupyter labextension list", I got results below:
config dir: /home/user/.jupyter
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.10.1 OK

JupyterLab v2.1.1
Known labextensions:
   app dir: /home/user/.local/share/jupyter/lab
        @jupyterlab/git v0.20.0-rc.0  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

As you see, the server extension and the frontend extension have not the same version. Could anyone help me how to resolve this problem?

**Comment by ianhi** [comment]
How did you install? I'd try running: `pip install jupyterlab-git==0.20.0rc0`

I believe that you also need to have nodejs in your environment when running the install command.
i.e. `conda install nodejs` before pip install jupyterlab-git

**Comment by weera-tech** [comment]
Thank you ianhi, now both server and lab extension have same version, but problem still persists and both dropdown menu and tab are invisible

**Comment by ianhi** [comment]
Does running `jupyter lab build` fix it? This is what you'll need nodejs for.

**Comment by weera-tech** [comment]
No, jupyter lab build running has not any positive effect. I have both nodejs and npm in environment by name node and npm.

**Comment by ianhi** [comment]
wacky. I'm at a bit of loss then. If you had jupyter open when you rebuilt did you refresh the jupyterlab page in the browser?

If you start in a fresh environment do you get the same issue? i.e. run:
```bash
conda create -n test -c conda-forge jupyterlab nodejs && conda activate test
pip install jupyterlab-git==0.20.0rc0
jupyter lab build
jupyter lab
```

**Comment by weera-tech** [comment]
I don't have conda installed on my machine. Except conda, I did rest of them so many times and still nothing!

**Comment by fcollonval** [comment]
@weera-tech 

As you can see in the message you reported, the JupyterLab extensions are located in `/home/user/.local/share/jupyter/lab`. Could you try : 

1. Uninstalling jupyterlab, jupyterlab-git and nbdime
2. Removing the folder `/home/user/.local/share/jupyter/lab`
3. Installing Jupyterlab and jupyterlab-git:

```
pip install jupyterlab~=2.1
pip install --pre jupyterlab-git==0.20.0rc0
jupyter lab build --debug
```

**Comment by weera-tech** [comment]
@fcollonval 
Thank you! It is working after re-installation

**Comment by telamonian** [comment]
that's great! glad we were able to help
