### ISSUE TITLE
Check Git version

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#635]
perhaps you want to check the version of git in jupyterlab-git and warn the user, if they use a too old git (i.e. git < 2)

_Originally posted by @jhgoebbert in https://github.com/jupyterlab/jupyterlab-git/issues/625#issuecomment-625235178_

**Comment by ianhi** [comment]
Or if git isn't present?

Also the readme currently specifies 
> Git (version >=1.7.4)
