### ISSUE TITLE
Unable to detect a Git repository.

### ISSUE THREAD

**Issue by soerendip** [jupyterlab/jupyterlab-git#636]
I installed the program extention with:

```
conda create -c conda-forge -n MLPB -y python=3.8 pandas>1.0 scikit-learn pip matplotlib seaborn biopython pyvis jupyterlab jupyterlab-git ipywidgets jupyter_nbextensions_configurator xlrd statsmodels
conda activate MLPB
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @jupyterlab/git
```

The extension appears in Jupyter lab but it is unable to detect existing git repositories. 

Clicking on detect repositories gets me to the file browser. I can navigate to a git repository and go back to the git tab, but the same message appears.

**Comment by fcollonval** [comment]
Hey @soerendip 

Could you test if the frontend and server extensions are enabled and have the same version by executing:

```sh
jupyter labextension list
jupyter serverextension list
```

If the server extension is disable, execute in your environment:

```sh
jupyter serverextension enable --sys-prefix --py jupyterlab_git
```

Note: if the serverextension is still disabled after running the previous command, this means you have conflicts between your user settings and the environment settings. Run again `jupyter serverextension list` and look at the path mentioned to discover where the bad setting is stored; for example for me:

config dir: **C:\Users\myname\Anaconda3\etc\jupyter**
    jupyterlab enabled
    - Validating...

**Comment by AyrtonB** [comment]
I'm having the same issue with both the front and backends enabled

```
(root) C:\Users\User>jupyter labextension list
JupyterLab v2.1.1
Known labextensions:
   app dir: C:\Users\path\to\my\dir
        @jupyterlab/git v0.20.0 enabled  ok
        nbdime-jupyterlab v2.0.0 enabled  ok

(root) C:\Users\User>jupyter serverextension list
config dir: C:\Users\path\to\my\dir
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git 0.20.0 ok
config dir: C:\Users\path\to\my\dir
    jupyterlab enabled
    - Validating...
      jupyterlab 2.1.1 ok
    jupyterlab_git enabled
    - Validating...
      jupyterlab_git 0.20.0 ok
    nbdime enabled
    - Validating...
      nbdime 2.0.0 ok
```

The console is logging an error however
![image](https://user-images.githubusercontent.com/29051639/81506429-2e9af380-92ee-11ea-86b6-aee6752112d0.png)

**Comment by ianhi** [comment]
That the second error should be printing the name of the repository you're in (see code below). It seems like it somehow got passed a blank path.
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/model.ts#L138-L173

If I force v to be an empty string with `v='';` then I can get the second error, but can't recreate the server error. 

@AyrtonB is there any error logging in the command line where you ran `jupyter lab` (ideally run with `jupyter lab --debug`)? Also, if you run `git rev-parse --show-toplevel` in the terminal in the repository folder does it return any errors?

**Comment by scdevries** [comment]
My lab-git is also unable to see a repository (or even to make one). I also get a 500 error, although it is slightly different.. Installed everything according to instructions and tried all the fixes already that I found on the internet. No results so far.

[E 10:25:21.751 LabApp] 500 POST /git/show_top_level?1589185521657 (::1) 79.01ms referer=http://localhost:8888/lab
[E 10:25:21.779 LabApp] Uncaught exception POST /git/show_top_level?1589185521659 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/show_top_level?1589185521659', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\site-packages\jupyterlab_git\handlers.py", line 98, in post
        result = await self.git.show_top_level(current_path)
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\site-packages\jupyterlab_git\git.py", line 579, in show_top_level
        cwd=os.path.join(self.root_dir, current_path),
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\site-packages\jupyterlab_git\git.py", line 123, in execute
        None, call_subprocess, cmdline, cwd, env
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\site-packages\jupyterlab_git\git.py", line 92, in call_subprocess
        cmdline, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\xxxxxx\Miniconda3\envs\exttest\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 10:25:21.787 LabApp] Unhandled error
[E 10:25:21.789 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "95",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36",
      "X-Xsrftoken": "2|cfe76bb2|8a4c05d8e79e0eaceef6dfd4759fa46a|1588598187",
      "Authorization": "token 2a68a2c987c0c94000bddc093ac5c7c591e3198c2ee7951e",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|cfe76bb2|8a4c05d8e79e0eaceef6dfd4759fa46a|1588598187; username-localhost-8888=\"2|1:0|10:1589185521|23:username-localhost-8888|44:ZGRmYzBlZjMyMWExNGJmMTg4NmUzODRhZThiMWY0OWI=|e5cf3d42cc71ede9f41f794583503046c436ec83dae5eedddc6ebf21f0f8a5c4\""
    }
[E 10:25:21.792 LabApp] 500 POST /git/show_top_level?1589185521659 (::1) 122.01ms referer=http://localhost:8888/lab

**Comment by AyrtonB** [comment]
@scdevries thanks!

I had to do the same with global Git installation and now it works fine

**Comment by fcollonval** [comment]
Thanks @scdevries to share back here to help the community. An issue is opened #635 that will result with checking existence and compatibility version of Git and the jupyter server extension. So l let this one opened for the moment.
