### ISSUE TITLE
Change the commit button title attribute to reflect why it is disabled

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#640]
Even if there was no error it might be nice to change the title attribute of the commit button to reflect why it is disabled. It can be disabled due to no text in commit message, or no files staged.
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/components/CommitBox.tsx#L70
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/components/CommitBox.tsx#L90-L97

_Originally posted by @ianhi in https://github.com/jupyterlab/jupyterlab-git/issues/639#issuecomment-630302921_

**Comment by ianhi** [comment]
How about also changing the disabled styling of the button from grey to semi transparent? 
This is what jupyterlab does. 
https://github.com/jupyterlab/jupyterlab/blob/f0cb758333df2bb622689bcc8b92e63bb9c533c6/packages/apputils/style/toolbar.css#L86-L88

vs the current disabled styling:
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/style/CommitBox.ts#L102-L106

**Comment by kgryte** [comment]
@ianhi I don't see the advantage of changing the transparency.
