### ISSUE TITLE
Cache git credentials via the jupyterlab-git extension

### ISSUE THREAD

**Issue by rdelubi** [jupyterlab/jupyterlab-git#659]
As a feature request: 

Can jupyterlab-git extension provide a UI to cache git credentials so that user doesn't have to enter the credentials every time he/she needs to interact with remote repo? e.g. wrap the functionality of "git config credential.helper 'cache --timeout=xxx'" in the extension UI

**Comment by fcollonval** [comment]
Tasks:

1. First add a settings in the extension to determine if the user wants to cache its credentials:
   1. Add a that settings in schema/plugin.json
   2. Maybe add a other one for the timeout
2. Pass that settings with the user authentication to the backend
3. If the settings needs to be cached
   1. Check if there is already a credentials helper
   2. if not and setting is true add the _cache helper_
   
That is
