### ISSUE TITLE
Display blank when simpleStaging is enabled

### ISSUE THREAD

**Issue by rdelubi** [jupyterlab/jupyterlab-git#660]
I'm using jupyterlab-git extension. In default mode (where simpleStaging is false), everything is displayed properly.

When I change the simpleStaging to true, the jupyterlab-git extension section displays blank. Please see screen snapshot below.

![simplestaging](https://user-images.githubusercontent.com/62430782/83305389-a57d2b00-a1ce-11ea-992d-8c6613e5f4dd.png)

My setting:
Jupyterlab 2.1.2
@jupyterlab/git v0.20.0  enabled  OK

Note that I tried restarting the jupyter notebook server instance after changing the setting to true, it didn't make any difference.

**Comment by kgryte** [comment]
@rdelubi Can you open up your browser developer console and see if there are any relevant errors displayed?

**Comment by rdelubi** [comment]
There are error in developer console as seen in snapshot below.

![simplestaging](https://user-images.githubusercontent.com/62430782/83422937-40a51900-a3f8-11ea-8859-e8399a7a5215.png)

**Comment by ianhi** [comment]
@rdelubi what version of Git do you have installed? The root cause of several similar errors has been having a Git version < 2

**Comment by ianhi** [comment]
Oh wait. I spoke too soon, I see that everything works properly when you are not in simple staging :thinking:
