### ISSUE TITLE
Current Branch panel not visible and Current Repository blank

### ISSUE THREAD

**Issue by ronigold** [jupyterlab/jupyterlab-git#661]
Hi, thanks for the useful expansion.

We want to start using it in our DS team.

We have installed the plugin on the jupyter-hub and it is functioning properly, but its display is different than usual and it lacks the current branch window and in the current repository nothing appears.
So we have no control over which branch of the Hagit we push and that makes it difficult for us to work.

Attaching screenshots
jupyterlab in jupyter-hub:
![image](https://user-images.githubusercontent.com/33024750/82557366-425b1b00-9b74-11ea-8c11-686adaab00f5.png)
jupyterlab in local machine:
![image](https://user-images.githubusercontent.com/33024750/82557393-4edf7380-9b74-11ea-81c2-a35e44a2f051.png)
version:
![5427aa90-2b6f-42c3-afcd-7cd52f7b9b56](https://user-images.githubusercontent.com/33024750/83350386-61139b80-a344-11ea-8960-824f79283db8.jpg)
![5427aa90-2b6f-42c3-afcd-7cd52f7b9b56](https://user-

I would appreciate help.

**Comment by fcollonval** [comment]
Hey @ronigold 

Could you look at the Web Console of your webbrowser (look for web developer tools) and report the error you are getting in JupyterHub?

Could you also look in the web developer tools to the network requests tab to see if some are failing?

Best would be to have also the errors from the Jupyter server spinned by JupyterHub - but I don't know if this is easy to obtain.

Reference:
Firefox: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console
Chrome: https://developers.google.com/web/tools/chrome-devtools

**Comment by ronigold** [comment]
@fcollonval Thanks,

Attaches the errors I receive on JupyterHu.
My local machine does not have these errors.

1. Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

2. TypeError: Cannot read property 'name' of null
    at Os._syncState (Toolbar.js:203)
    at m (index.js:475)
    at Object.c [as emit] (index.js:433)
    at e.emit (index.js:106)
    at ke._setStatus (model.js:896)
    at ke.refreshStatus (model.js:749)
    at async ke.refresh (model.js:708)
t.exceptionHandler @ vendors~main.975de773489ad479ae7a.js:1
m @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
e.emit @ vendors~main.975de773489ad479ae7a.js:1
_setStatus @ vendors~main.975de773489ad479ae7a.js:1
refreshStatus @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
refreshStatus @ vendors~main.975de773489ad479ae7a.js:1
refresh @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
refresh @ vendors~main.975de773489ad479ae7a.js:1
factory @ vendors~main.975de773489ad479ae7a.js:1
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1
setTimeout (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
async function (async)
schedule @ vendors~main.975de773489ad479ae7a.js:1
(anonymous) @ vendors~main.975de773489ad479ae7a.js:1
Promise.then (async)
_execute @ vendors~main.975de773489ad479ae7a.js:1
c @ vendors~main.975de773489ad479ae7a.js:1

![123](https://user-images.githubusercontent.com/33024750/83398675-7a7e1b80-a408-11ea-9eb8-70169c37811f.png)

**Comment by kgryte** [comment]
@fcollonval The current branch is not resolved. I believe that this [line](https://github.com/jupyterlab/jupyterlab-git/blob/8e79eae1277f8a9b8a07123717dbd5cc8ba5f83d/src/components/Toolbar.tsx#L319) just needs to be modified to

```
branch: (repo && this.props.model.currentBranch) ? this.props.model.currentBranch.name : ''
```

**Comment by fcollonval** [comment]
Thank you both.

@kgryte unfortunately, I think the error is more critical as the current repository is not shown neither (no folder name is displayed in the screenshot of Roni).
This looks similar to https://github.com/jupyterlab/jupyterlab-git/issues/625.

@ronigold Could you check that the git installed on JupyterLab on JupyterHub is at least v2? You could do that by opening a terminal in JupyterLab and executing `git --version`.
If you are not on v2, you should update git on JupyterHub user image.

**Comment by ronigold** [comment]
@ronigold
Yes.
My current version is 1.8.3.1.
I'll update the version through the admin and update.
Thank you!

**Comment by ronigold** [comment]
@fcollonval @kgryte 
Our system administrator has updated the Git version to version 2.22.0  and the problem was solved.

Thank you very much!

**Comment by kgryte** [comment]
@ronigold Awesome! Thanks! Closing this out.
