### ISSUE TITLE
this extensions can freeze browser tab

### ISSUE THREAD

**Issue by stphnlyd** [jupyterlab/jupyterlab-git#663]
The issue is not seen at my home PC. But at our workplace for some unknown reason if the jupyter root directory (the directory where we run jupyter) is a git repository, having this extension would cause the browser tab that runs jupyter to freeze and won't restore. This issue does not happen immediately the browser tab's connected to jupyter, but happens usually in like one minute after we operate the jupyterlab UI a little bit like clicking buttons on the very left bar. And when it happens, it's does not yet recognize the directory to be a git repository. 

If the extension is not installed then the issue won't happen. Also, we were using jupyterlab 1.2.x and jupyterlab-git python package version 0.10.0 npm package version 0.9.0, and did not saw this. This issue is seen after we upgrade to jupyterlab 2.1.3 and version 0.20.0 of this extension. 

How can I further investigate?

**Comment by fcollonval** [comment]
Hey @stphnlyd thanks for reporting.

First of all could you confirm, the version combination:
_  | working | buggy
--- | --- | ---
jlab | 1.2 | 2.1.3
python | 0.10.0 | 0.20.0
npm | 0.9.0 | 0.20.0

Then could you provide the OS and the Python version you are using?

Does it freeze also if the jupyter root directory is not a git repository?

Could you report any error seen in the server log and in the web console?

Reference:
Firefox: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console
Chrome: https://developers.google.com/web/tools/chrome-devtools

**Comment by stphnlyd** [comment]
@fcollonval Thanks for your response. I realized it's related to the fact that I ran jupyter lab from a venv directory which is for jupyterlab and has over 40K files, and I don't have it in my .gitignore. I see jupyterlab-git for its "git status" command has the "-u" option so it would get all the files recursively and regard them as untracked, and that output could be too many for the browser to handle. 

And I confirmed that it's not really about jupyterlab-git version. Our earlier jupyterlab 1.2 + jupyterlab-git 0.10.0 environment were actually different and did not have so many files..

**Comment by ivan-gomes** [comment]
This is plaguing my users who have large repositories cloned as well, which is making it difficult to leaving the extension enabled by default since there is no way to anticipate how it will affect an user's experience. :/

**Comment by ianhi** [comment]
Hey @ivan-gomes there is some discussion of the underlying cause for this over at https://github.com/jupyterlab/jupyterlab-git/issues/667. Could you see how long git status takes to run with `time git status --porcelain -u -z` and post the results in that issue? It sounds as though `git status` is taking longer than the `refreshInterval` setting (default 3 seconds). Other useful information would be: OS, git version, python package version, and npm extension version.

(@fcollonval maybe this issue should be closed to consolidate with 667?)

**Comment by fcollonval** [comment]
Agreed @ianhi, so I'm closing this in favor for #667
