### ISSUE TITLE
Allow diffs of images

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#664]
Currently standalone diffs of images are not supported. However they are supported inside of notebook diffs. I propose having the standalone present diffs of images the same way they are handled by nbdime: showing the old version and new version side by side:

**notebook diff:**
![image](https://user-images.githubusercontent.com/10111092/83477061-4e8e8480-a460-11ea-8d4c-a93726e5d221.png)
**vscode:**
![image](https://user-images.githubusercontent.com/10111092/83477210-c197fb00-a460-11ea-8f12-5985b01072bf.png)
**Github desktop:**
Provides several options beyond side by side
![image](https://user-images.githubusercontent.com/10111092/83477195-bb098380-a460-11ea-967d-c986c2d1bf6b.png)

## Approach
I think that this can be accomplished by using `git show HEAD:./img.png` to get the image as bytes. At least I found that  `git show HEAD:./img.png > test.png` produced a working image that was indeed from the previous commit. So the flow would be:
- Request diff of image
    - One of the handlers realizes this is an image and swaps request to be `git show`
- Return bytes to frontend
- convert to blob
- generate `ObjectUrl` for use in an `img` tag

**Comment by fcollonval** [comment]
Nice idea.

One comment:

You should be able to display it more simply by injecting the bytes as base64 encoded string. See for example the image viewer in JupyterLab:
https://github.com/jupyterlab/jupyterlab/blob/e7317f21b48183423e375dc266476a4289eb0fa3/packages/imageviewer/src/widget.ts#L175

> It may be worth to reuse that widget actually

**Comment by ianhi** [comment]
Typescript library with a react component for doing this: https://octoframes.github.io/compare_view/

Which is used in this jupyter magic: https://github.com/Octoframes/jupyter_compare_view#jupyter-compare_view

**Comment by fcollonval** [comment]
Closing as resolved by #1223
