### ISSUE TITLE
Best practice usage

### ISSUE THREAD

**Issue by Nathan-Furnal** [jupyterlab/jupyterlab-git#665]
How should we approach the usage of this API?

Is it better to install jupyter-lab git in each virtual environment and build from there or should I add it to my jupyter lab install (in my home dir, not within environments) instead ?

Thanks for the great package!

**Comment by fcollonval** [comment]
This extension needs to be installed along side jupyterlab but it does not need to be installed in each kernel like jupyter widgets.

So it very much depends on your habits. If you prefer to get only one jupyterlab with multiple execution kernels (matching for example multiple environments), you only need to install this extension once. Or if you prefer to install jupyterlab on each environment, then you will need to install this extension also on each environment.

**Comment by Nathan-Furnal** [comment]
Alright that makes sense, thanks
