### ISSUE TITLE
mapping between JupyterHub user name and git

### ISSUE THREAD

**Issue by ronigold** [jupyterlab/jupyterlab-git#672]
Hi, thanks for the useful extension.

We started using it in our DS team on JupyterLab installed on JupyterHab.

My problem is this:

If I run push or pull from JupyterLab in my local machine, I do not have to enter a username or password, probably because it is already set in my git.

On the other hand, in JupyterHub, I am required to enter a username and password in every re-action, and in addition to insert a name and email to commit and this does not happen automatically.

Do I have a way to set up a mapping between JupyterHab user name in git to:

1. avoid inserting a username and password over and over again with every action in git  
2. avoid inserting a name and email for commit so that it happens automatically by the username in JupyterLab like in my local machine?

We would like to save username and password and name and email to any team member who has a JupyterHab username. 
But we only have one git account so the regular configuration commands don't help.

in JupyterHab:
![123](https://user-images.githubusercontent.com/33024750/84362268-a30ad000-abd5-11ea-8bfc-bae0b31e4dac.png)

in the JupyterHab:
![server](https://user-images.githubusercontent.com/33024750/84380741-892ab680-abf0-11ea-8b5a-80ac32560fb2.gif)

in the local machine:
![local](https://user-images.githubusercontent.com/33024750/84364301-9471e800-abd8-11ea-99cc-ae49644321aa.gif)

version:
![83350386-61139b80-a344-11ea-8960-824f79283db8](https://user-images.githubusercontent.com/33024750/84362272-a56d2a00-abd5-11ea-8cc6-edf4e79a99be.jpg)

**Comment by fcollonval** [comment]
Dear @ronigold 

The solution should be implemented on the JupyterHub Spawner side of your infrastructure; so a concrete solution depend on the spawner your are using. If this is the default, you could for example use the `pre_spawn_hook` to set the git configuration parameters for the user.

https://github.com/jupyterhub/jupyterhub/blob/b5defabf495c49a73747dadfbfa9b95abe0be0d6/jupyterhub/spawner.py#L638-L657

Regarding the credentials, the same apply: see 
- https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
- https://www.softwaredeveloper.blog/git-credential-storage-libsecret

**Comment by ronigold** [comment]
Thanks for the response.

I'm pretty new to this topic and could not figure out how to link Credential Storage to spawner.

We use the default spawner and do not really know what to register in the function so that it will initialize the accounts in Git for each user on a regular basis.

Also how do I make the distinction that for each user there will be a different username and password?

Can you show me a sample code for spawner that initializes git configuration Suppose username, password and email?

Thank you very much

Roni

**Comment by fcollonval** [comment]
@ronigold, you could for example execute a script as the user using the `pre_spawn_hook`:

```py
def setup_user_hook(spawner):
    # Run actions as user
    username = spawner.user.name
    subprocess.check_call(
        [
            "su",
            username,
            "-p",
            "-c",
            " ".join(("bash", join(JUPYTERHUB_CONFIG_DIR, "setup_user.sh"))),
        ],
        env=spawner.get_env(),
    )


c.Spawner.pre_spawn_hook = setup_user_hook
```

In the `setup_user.sh`, you can set user specific options, like name and email:

```sh
if [ ! "$(git config --get user.name)" ]
then
    name=$(some commands to get a name)
    git config --global --add user.name "${name}"
fi
if [ ! "$(git config --get user.email)" ]
then
    email=$(some commands to get the email)
    git config --global --add user.email "${email}"
fi
```

For instance, if you are using a ldap, you could use `ldapsearch` to obtain such information for the users.

Regarding the credential storage, the easiest is to set up globally - for example using libsecret (see links in my previous reply):
```sh
sudo apt-get install libsecret-1-0 libsecret-1-dev
cd /usr/share/doc/git/contrib/credential/libsecret
sudo make
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
```

So once the user authenticate successfully, its credentials will be store in the credential helper. And they will not be requested again.

**Comment by VictorDataEngineer** [comment]
Hi @ronigold ,

I was looking for the same functionality for our JupyterHub and git.

I have managed to resolve the part of "Who is committing", by configuring one time the .gitconfig file for each user, with the command below:

`git config --global --edit` 

The second part is more tricky, I hope you have resolved it as well.

Best,
    Victor

**Comment by ronigold** [comment]
Thanks for the response. We also managed to solve the problem by the following commands:

To save username and password:
1.	Clone a repo
2.	Open the git command line
3.	run: git config --global credential.helper 'store --file ~/.my-credentials’
4.	git pull
5.	Enter user’s company credentials

To set name and mail for commit:
1.	Form git repo open the git command line
2.	git config --global user. name  ‘#NAME’
3.	git config --global user.email ‘#EMAIL’

**Comment by VictorDataEngineer** [comment]
Thanks for sharing the steps it helped ! 

Only I chose the standard way of saving the username and passwords running the below command that enables the saving:

`git config --global credential.helper store`

After the first login, it will save the passwords to the ~/.git-credentials file, for each user automatically.

Summary of alternative way:

1. `git config --global credential.helper store` - automatically saves the username and password after first login.
2. `git config --global --edit`  - each user fill his name and email for 'Who is Committing' information.


Best,
   Victor

**Comment by fcollonval** [comment]
I want to highlight the security risk of using **store** credential helper as it stores in plain text the passwords.

So it should be avoided as much as possible and if you use it please don't use the default file name (and don't write your exact setting in public website such this one) because it will ease stealing user information.

See for example: https://www.softwaredeveloper.blog/git-credential-storage-libsecret for alternative credential helpers.
