### ISSUE TITLE
Split view shortcut

### ISSUE THREAD

**Issue by wanghankun** [jupyterlab/jupyterlab-git#675]
What shortcut can I use to switch between vertical split views?

**Comment by fcollonval** [comment]
@wanghankun Could you be more specific? Which views are you speaking about? What are you trying to achieve?

**Comment by wanghankun** [comment]
Sorry. I mean the "New View for Notebook" when you right click on a tab, this splits the jupyter lab vertically. I would like to be able to switch between the split views with shortcut. I know I can switch tabs using Ctrl + Shift + [ or ], but it is not very practical when I have multiple tabs opened on both sides of the vertical splits.

**Comment by fcollonval** [comment]
Thanks for the context.

The handling of the tabs are not part of this extension. You should report on the [lumino](https://github.com/jupyterlab/lumino) repository - the UI technology used by JupyterLab. But I don't think there is such feature.

**Comment by wanghankun** [comment]
Thank you
