### ISSUE TITLE
Relative line number

### ISSUE THREAD

**Issue by quantum-booty** [jupyterlab/jupyterlab-git#680]
Is it possible to add relative line numbers in Jupyter lab? I use the vim plugin and navigating would be a lot easier if I could see the relative line numbers.

**Comment by fcollonval** [comment]
Could you please add a screenshot and specify in which context you would like the one numbers to appear?

**Comment by wanghankun** [comment]
Relative line numbers are probabily most useful in the text editor, but it would be nice to see it within the notebook cells as well.
![image](https://user-images.githubusercontent.com/28958399/85132166-22308180-b230-11ea-86b2-f8ff7eb88e56.png)
![image](https://user-images.githubusercontent.com/28958399/85132211-36747e80-b230-11ea-9716-d9f0e1296545.png)

**Comment by ianhi** [comment]
I think this ought to be transferred to the jupyterlab issue list - (@fcollonval the triage rights changed so now they only work on the jupyterlab repo - meaning I cannot actually do that)

@wanghankun  you may also want to ask this on one of the jupyterlab_vim repos. Unfortunately I don't think there is any ready to go codemirror setting for this. Someone will need to make an extension that does this or add this to the jupyterlab_vim extension. A technique for getting relative line numbers can be found here https://github.com/codemirror/CodeMirror/issues/4116

**Comment by holdmygithub** [comment]
Is there relative line numbering in jupyter notebook (like that in vim)?
It is pretty convenient to use vim emulator in jupyter

**Comment by fcollonval** [comment]
I'm closing this one as it is not related to this repository (i.e. the git extension).

XRef jupyterlab core related issue: https://github.com/jupyterlab/jupyterlab/issues/6718

**Comment by ianhi** [comment]
This has also come up in vim support for the notebook. See discussion https://github.com/jupyterlab/jupyterlab/pull/9068#issuecomment-701457040 essentially the answer is that at the moment this will either require a separate extension or be perhaps be incorporated in https://github.com/ianhi/jupyterlab-vimrc

**Comment by telamonian** [comment]
Uhhh, I'm confused. "Show Line Numbers" has been an option that you can toggle on/off in Jupyterlab's "View" menu at least since the release of Jlab 1.0:

![image](https://user-images.githubusercontent.com/2263641/95779135-7eb02480-0c97-11eb-919e-39c5c1883944.png)


Or was the OP asking for something more complicated than the existing per-cell line numbering?

**Comment by quantum-booty** [comment]
> Uhhh, I'm confused. "Show Line Numbers" has been an option that you can toggle on/off in Jupyterlab's "View" menu at least since the release of Jlab 1.0:
> 
> ![image](https://user-images.githubusercontent.com/2263641/95779135-7eb02480-0c97-11eb-919e-39c5c1883944.png)
> 
> Or was the OP asking for something more complicated than the existing per-cell line numbering?

I meant vim-like relative numbers. Like this:
![image](https://user-images.githubusercontent.com/28958399/95779628-48d46580-0cc2-11eb-84af-175919130de8.png)

**Comment by ianhi** [comment]
@telamonian they are asking after this behavior in vim:
![image](https://user-images.githubusercontent.com/10111092/95779591-4f4de780-0c98-11eb-87f1-f1f4711c9f36.png)

**Comment by telamonian** [comment]
Wow, I've been using vim for more than a decade now and I've never seen that. So many weird corners to that ancient tool...

**Comment by holdmygithub** [comment]
Yes! we need that in jupyter. Relative numbering is very convenient to use in Vim mode!

**Comment by xaviernogueira** [comment]
Any updates here?
