### ISSUE TITLE
'git' not recognized when trying to copy repository on jupyterlab

### ISSUE THREAD

**Issue by achien1** [jupyterlab/jupyterlab-git#681]
## Description

git extensions have been downloaded and enabled
directory git was created, appears on the lefthand side
git copy URL leads to error git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ git clone --depth 5 the_url_you_just_copied
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

mkdir -p ~/git
cd ~/git
git clone url

## Expected behavior

I expected repository to be copied over onto local computer

## Context

- Python package version: 3.7

- Extension version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
[D 04:10:07.161 LabApp] Searching ['C:\\Users\\yang1\\git', 'C:\\Users\\yang1\\.jupyter', 'C:\\Users\\yang1\\anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter']
 for config files
[D 04:10:07.161 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 04:10:07.162 LabApp] Looking for jupyter_config in C:\Users\yang1\anaconda3\etc\jupyter
[D 04:10:07.162 LabApp] Looking for jupyter_config in C:\Users\yang1\.jupyter
[D 04:10:07.162 LabApp] Looking for jupyter_config in C:\Users\yang1\git
[D 04:10:07.164 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 04:10:07.165 LabApp] Loaded config file: C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 04:10:07.166 LabApp] Looking for jupyter_notebook_config in C:\Users\yang1\anaconda3\etc\jupyter
[D 04:10:07.167 LabApp] Loaded config file: C:\Users\yang1\anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 04:10:07.167 LabApp] Looking for jupyter_notebook_config in C:\Users\yang1\.jupyter
[D 04:10:07.174 LabApp] Loaded config file: C:\Users\yang1\.jupyter\jupyter_notebook_config.json
[D 04:10:07.174 LabApp] Looking for jupyter_notebook_config in C:\Users\yang1\git
[D 04:10:07.183 LabApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[D 04:10:07.201 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 04:10:07.205 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\yang1\anaconda3\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\Users\yang1\anaconda3\etc\jupyter\jupyter_notebook_config.d\jupyterlab_git.json
        C:\Users\yang1\anaconda3\etc\jupyter\jupyter_notebook_config.d\nbdime.json
        C:\Users\yang1\anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 04:10:07.210 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\yang1\.jupyter\jupyter_notebook_config.json
[I 04:10:08.442 LabApp] The port 8888 is already in use, trying another port.
[I 04:10:08.443 LabApp] The port 8889 is already in use, trying another port.
[I 04:10:08.445 LabApp] The port 8890 is already in use, trying another port.
[I 04:10:08.446 LabApp] The port 8891 is already in use, trying another port.
[I 04:10:08.447 LabApp] The port 8892 is already in use, trying another port.
[I 04:10:09.206 LabApp] JupyterLab extension loaded from C:\Users\yang1\anaconda3\lib\site-packages\jupyterlab
[I 04:10:09.207 LabApp] JupyterLab application directory is C:\Users\yang1\anaconda3\share\jupyter\lab
[D 04:10:09.382 LabApp] Using default logger
[D 04:10:09.382 LabApp] Using default logger
[D 04:10:09.383 LabApp] Using default logger
[D 04:10:09.384 LabApp] Using default logger
[I 04:10:09.387 LabApp] Serving notebooks from local directory: C:\Users\yang1\git
[I 04:10:09.387 LabApp] The Jupyter Notebook is running at:
[I 04:10:09.387 LabApp] http://localhost:8965/?token=2e9c144ccd080f84a10b3de9155f8daa1767e08fbd1a31da
[I 04:10:09.388 LabApp]  or http://127.0.0.1:8965/?token=2e9c144ccd080f84a10b3de9155f8daa1767e08fbd1a31da
[I 04:10:09.388 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 04:10:09.489 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/yang1/AppData/Roaming/jupyter/runtime/nbserver-10876-open.html
    Or copy and paste one of these URLs:
        http://localhost:8965/?token=2e9c144ccd080f84a10b3de9155f8daa1767e08fbd1a31da
     or http://127.0.0.1:8965/?token=2e9c144ccd080f84a10b3de9155f8daa1767e08fbd1a31da
[D 04:10:11.121 LabApp] Accepting token-authenticated connection from ::1
[D 04:10:11.128 LabApp] Using contents: services/contents
[D 04:10:11.149 LabApp] 200 GET /lab?token=2e9c144ccd080f84a10b3de9155f8daa1767e08fbd1a31da (::1) 29.11ms
[D 04:10:11.198 LabApp] Path main.d8b638230707e6b842aa.js served from C:\Users\yang1\anaconda3\share\jupyter\lab\static\main.d8b638230707e6b842aa.js
[D 04:10:11.207 LabApp] 200 GET /static/lab/main.d8b638230707e6b842aa.js (::1) 14.72ms
[D 04:10:11.211 LabApp] Path vendors~main.6591aa6154de708ba15d.js served from C:\Users\yang1\anaconda3\share\jupyter\lab\static\vendors~main.6591aa6154de708ba15d.
js
[D 04:10:11.887 LabApp] 200 GET /static/lab/vendors~main.6591aa6154de708ba15d.js (::1) 677.42ms

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>
![image](https://user-images.githubusercontent.com/67100109/85013801-0e92f700-b11a-11ea-9626-93601b10c4f3.png)

**Comment by fcollonval** [comment]
Thanks for reporting.

If I got your description correctly, you execute a set of commands including the `git clone` command in a terminal within JupyterLab - not using the menu of this extension.

If so, you have to be aware that the terminal on Windows emulates a Powershell and not a command shell. Then the error comes from Powershell being unaware of the git application installed on your system.

Did you try cloning from the menu _Git -> Clone_?

**Comment by fcollonval** [comment]
Closing by lack of follow-up from the author
