### ISSUE TITLE
Error push in branch with "/" character

### ISSUE THREAD

**Issue by charliwardbd** [jupyterlab/jupyterlab-git#686]
In my repo if i create a repo that the name contains "/" character like "feature/testing" when i try to push i get the next error 

and the push never end. 

Im using jupyterlab-git==0.10.0

![Captura de pantalla 2020-07-06 a las 13 33 00](https://user-images.githubusercontent.com/24396580/86589178-786e2600-bf8d-11ea-8b51-4ed67fd0ce19.png)

E 11:27:14.282 LabApp] Uncaught exception POST /git/push?1594034834216 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/push?1594034834216', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_git/handlers.py", line 441, in post
        current_path, current_local_branch
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_git/git.py", line 900, in get_upstream_branch
        error, " ".join(command)
    Exception: Error [fatal: no such branch: 'prueba'
    ] occurred while executing [git rev-parse --abbrev-ref prueba@{upstream}] command to get upstream branch.
[E 11:27:14.283 LabApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_git/handlers.py", line 441, in post
        current_path, current_local_branch
      File "/usr/local/lib/python3.5/dist-packages/jupyterlab_git/git.py", line 900, in get_upstream_branch
        error, " ".join(command)
    Exception: Error [fatal: no such branch: 'prueba'
    ] occurred while executing [git rev-parse --abbrev-ref prueba@{upstream}] command to get upstream branch.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1112, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/kernels/kernelmanager_intelligence.py", line 59, in write_error
        reply['traceback'] = ''.join(traceback.format_exception(*exc_info))
    NameError: name 'traceback' is not defined
[E 11:27:14.286 LabApp] {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0",
      "Accept-Encoding": "gzip, deflate",
      "Pragma": "no-cache",
      "Accept": "*/*",
      "Host": "localhost:8888",
      "Content-Length": "70",
      "Origin": "http://localhost:8888",
      "Cache-Control": "no-cache",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|c447d094|f8dae638a540914bd1887252b19581d1|1593762065",
      "Referer": "http://localhost:8888/lab?",
      "Vnd.bbva.user-Id": "XE52265",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|c447d094|f8dae638a540914bd1887252b19581d1|1593762065",
      "Accept-Language": "en-US,es-ES;q=0.8,es;q=0.5,en;q=0.3"
    }
[E 11:27:14.288 LabApp] 500 POST /git/push?1594034834216 (172.17.0.1) 29.20ms referer=http://localhost:8888/lab?

**Comment by ianhi** [comment]
What was the full branch name? It looks like the branch names was `prueba`
>  Exception: Error [fatal: no such branch: 'prueba'

I'd like to 
A few questions:
1. If you run `git push` from the terminal what is the output?
2. What version of Git do you have installed?


I can't replicate your exact error but there does seem to be something going wrong with the branch name parsing. When I try to push the branch `feature/yikes` it seems to be trying to push the branch `yikes`:

![image](https://user-images.githubusercontent.com/10111092/87112138-189ba780-c239-11ea-88d9-3a2453139ffd.png)

**Comment by ianhi** [comment]
I think the offending line is here:
https://github.com/jupyterlab/jupyterlab-git/blob/99849b7b8c6d5f244748b3d3824580690c2850ee/jupyterlab_git/handlers.py#L445

**Comment by ianhi** [comment]
oh wow two places where this is an issue. Also an issue here:
https://github.com/jupyterlab/jupyterlab-git/blob/99849b7b8c6d5f244748b3d3824580690c2850ee/jupyterlab_git/git.py#L887-L898

**Comment by ianhi** [comment]
Ok so the first line I linked is trickier to fix because what is it trying to do is split `<remote name>/<remote-branch-name>` and both the remote name and the branch can have an arbitrary number of `/`s in them. I think the correct solution will use this SO answer: https://stackoverflow.com/questions/32887048/git-show-remote-name-of-remote-branch to appropriately split away the `<remote name>` otherwise you have to resort to guessing about the number of slashes

**Comment by ianhi** [comment]
The command is:
```bash
symref=$(git symbolic-ref --short HEAD)
git config --local "branch.$symref.remote"
```

but currently git config method doesn't allow for this
