### ISSUE TITLE
new minor release?

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#690]
## Description
Since the last release there have been 14 PRs merged ([ref](https://github.com/jupyterlab/jupyterlab-git/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E%3D2020-05-05+base%3Amaster+sort%3Aupdated-desc+)) of which 7 have changes that will improve the user experience with this extension. Is this enough to justify a 0.21.0 release? If not would it be helpful to come up with a list of open issues/PRs that would justify a release?

**Comment by ianhi** [comment]
Similarly the `0.11.x` could get a release as I think all of these changes have been backported.

**Comment by fcollonval** [comment]
Hey @ianhi 

Sorry I got carry away.

I updated the milestone [0.21.0](https://github.com/jupyterlab/jupyterlab-git/milestone/19) with the list of issues and PR to be closed before releasing. Let me know if you see something else - or add them yourself as you have triage rights :wink:

**Comment by ianhi** [comment]
Awesome.

How do you feel about pushing #628 and #620 to a later milestone (0.22?)- both of those will be non-trivial to fix

**Comment by fcollonval** [comment]
@kgryte @mlucool @ianhi @telamonian @lresende 

I released a pre version 0.21.0a0 on pypi. I hope to get #700 and #721 before a final release. If you could try it, that would be great.

**Comment by ianhi** [comment]
@fcollonval I wasn't able to test this until now as I got trapped a whirlwind of only using zoom and powerpoint for work :(. But I just went through and tried vs 0.21.0rc0. It seems good I found one thing that may be a visual regression but I don't think that's reason to hold this up any longer:

The branch icon of the current branch in the new branch dialog is weirdly transparent
![image](https://user-images.githubusercontent.com/10111092/91643669-4b754700-ea03-11ea-893c-635f5c8fb616.png)



Also, maybe it would be good to consider doing more regular patch releases. Several of the PRs in the release are bug fixes rather than new features, it would be cool to get those out more easily. Thoughts?

**Comment by ianhi** [comment]
Icon issue fixed by https://github.com/jupyterlab/jupyterlab-git/pull/745

**Comment by fcollonval** [comment]
Thanks @ianhi for all the testing and support.

> Also, maybe it would be good to consider doing more regular patch releases. Several of the PRs in the release are bug fixes rather than new features, it would be cool to get those out more easily. Thoughts?

Yes definitely. This is why I pushed forward on Continuous Deployment. So I can do a release even from my mobile phone 😉 

I'll test the release on JLab 1.x and merge your fix. And if nothing is really blocking. I'll do the release.

**Comment by fcollonval** [comment]
I release the version 0.11.0 and 0.21.0 on pip and npm (soon to appear on conda-forge). Special thanks to you @ianhi for your PRs and user support.
