### ISSUE TITLE
git commit --amend

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#695]
## Description
It would be handy to have the option equivalent to `git commit --amend` - This would need to paired with an option to force push. 

Perhaps this could go into the Git menu similar to vscode:
![image](https://user-images.githubusercontent.com/10111092/87264877-2fd3d280-c48f-11ea-84bb-6d722c5c3ba8.png)

**Comment by fcollonval** [comment]
cc @sinakhalili

**Comment by fcollonval** [comment]
Closed by #973
