### ISSUE TITLE
Git status API recursively lists all untracked files causing browsers to hang

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#703]
## Description

The current implementation of git status uses the `-u` flag which recursively lists _all_ untracked files in _all_ sub-directories in a Git repository. Jupyter users often work with data sets that involve a large number of small files. When such datasets are untar'd into a working Git repository, this causes the `/git/status` API to return an unbounded response and freezes the entire JupyterLab front-end as well as the browser.

This operation is *not* paginated and the amount of files that are returned is unbounded.  For e.g., see the notebook [here](https://github.com/udacity/sagemaker-deployment/blob/master/Project/SageMaker%20Project.ipynb). This downloads the IMDb dataset. Downloading the data causes **the entire JupyterLab application to become unresponsive and the browser to hang**. I noticed my browser taking ~10GB of RAM and causing general machine slowness. 

## Reproduce

(Warning: This will hang your browser) 

Download and untar the [IMDB Dataset](http://ai.stanford.edu/~amaas/data/sentiment/) in your working directory.

Alternatively, 
1. `git clone https://github.com/udacity/sagemaker-deployment`
2. Run the `SageMaker Project` notebook in /Project

## Expected behavior

In general, any unpaginated approach is undesirable and the default behavior of the extension should provide sensible defaults that are performant. For e.g, in the `/git/all_history` API, the output from `git log` is intentionally restricted to 10 by default to avoid such scenarios (See https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyterlab_git/git.py#L317-L325).  

Since there is no native pagination in the `git status` command and the adverse effects of this issue,  the proposed approach is to just use `-u='normal'` or omit the option altogether. (https://git-scm.com/docs/git-status#Documentation/git-status.txt---untracked-filesltmodegt). This option doesn't recursive list every untracked file in each sub-directory and still returns a reasonable default . This is the same UX as just doing `git status` in a terminal. Power users can fall back to the terminal to display each untracked file using additional flags in the API.
 
## Context

- Python package version: 0.10.1

- Extension version: 0.10.1

- Git version: 2.13

- Operating System and its version: Amazon Linux

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jaipreet-s** [comment]
cc @fcollonval as you have context here.

**Comment by ianhi** [comment]
A related issue is: https://github.com/jupyterlab/jupyterlab-git/issues/667 - dropping `-u` would ameliorate that issue but not solve it completely as there will still be issues on entering a directory with many files.

**Comment by jaipreet-s** [comment]
Thanks for pointing that issue @ianhi, a good investigation there.

However,  it's pretty easy for a user to get a directory in untracked (downloading data sets as I pointed out) as that is a normal part of a data scientist's workflow. 

I would still go ahead with #704 to improve the behavior in certain scenarios and track broader improvements around repos with large number of files in #667

**Comment by mone27** [comment]
As a quick fix you can add your data folder to `.gitignore` and make jupyterlab-git it is usable again. At least this worked for me.

**Comment by fcollonval** [comment]
So the `-u` does not seem the best answer. But this is indeed a annoying for users with lots of untracked files. So as @ianhi's tests demonstrates (thank you for those), I propose to have some kind of threshold depending on the number of files:

```
cmd = ["git", "status", "--porcelain", "-z"]
if (len(`git status -su`)) < threshold:
    cmd.append("-u")
```

So this will dynamically reduce the number of files - but it will still be only a first step.

At best the threshold should be an extension settings like for the history.

**Comment by ca-scribner** [comment]
Just ran into this myself.  In my case I created a virtual environment inside a git tracked folder - easy way to make +5k files and lock jupyter lab up pretty bad. 

I don't have a good solution for the problem, but give +1 to finding a solution.  This is an easy problem to mitigate when you know it is happening (.gitignore the files and everything is fixed) but a hard problem for a user to identify the cause of (especially since it they can cause it outside jupyter lab and might not notice the consequence for hours or days till they open lab back up)

**Comment by ianhi** [comment]
The fix proposed by @fcollonval will also require tracking the which subfolder we are in in the current repository. Currently `pathRepository` only tracks the top level of the current repo so if `-u` is not appended to the command then you will be never be able to see the git files in subfolders. So it would not emulate the behavior of `status` as might be expected.

**Comment by reesscot** [comment]
Any update on this issue?

**Comment by fcollonval** [comment]
I prototype windowing the files list in #767. This is definitely a better way to go than this proposal.
