### ISSUE TITLE
After JL 2.1.x upgrade, HTTP 403 on POST to /git/branch?1234...

### ISSUE THREAD

**Issue by metasim** [jupyterlab/jupyterlab-git#715]
## Description

After upgrading to JupyterLab 2.1.5 the git tab stopped working.

<img src="https://user-images.githubusercontent.com/131013/89226463-00097d80-d5aa-11ea-9a25-3293a6b4db99.png" width=300 />

Digging into the browser console shows `403`s when communicating with the server extension.

<img src="https://user-images.githubusercontent.com/131013/89226728-7312f400-d5aa-11ea-8ffb-0e771f58179e.png" width=400 />

## Reproduce

1. Go to file browser
2. Double click on a git repo
3. Click on git plugin tab
4. See error 'Unable to detect a Git Repository'

## Expected behavior

Show git status

## Context

- Python package version:

```
Name: jupyterlab-git
Version: 0.20.0
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /opt/conda/lib/python3.8/site-packages
Requires: notebook, pexpect, nbdime
Required-by: 
```
- Extension version:

```
JupyterLab v2.1.5
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-sidecar v0.5.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        jupyter-leaflet v0.13.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
```

- Server extension version:
```
config dir: /opt/conda/etc/jupyter
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.5 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.20.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.0.0 OK
    nbresuse  enabled 
    - Validating...
      nbresuse  OK
```

- Git version:

`git version 2.25.1`

- Operating System and its version:

```
Ubuntu 20.04 LTS
Linux jupyter-12345 4.14.146-119.123.amzn2.x86_64 #1 SMP Mon Sep 23 16:58:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by metasim** [comment]
Sorry for the noise.... the issue was with AWS WAF blocking the request via the `AWS-AWSManagedRulesSQLiRuleSet` filter; it was thinking the POST contents were an SQL injection attack 🤷‍♂️

**Comment by fcollonval** [comment]
Thanks @metasim to report back the source of the error.
