### ISSUE TITLE
Cancelling a push by clicking away from the dialog incorrectly asks for git credentials

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#725]
## Description
In the below gif I interact with the push dialog in three different ways
1. Let it finish
    - Works - no issues with credentials
2. Dismiss using the dismiss button
   - Works as expected
3. Cancel the full screen modal by clicking somewhere other than the push dialog
    - This incorrectly brings up the credentials dialog

![pushing](https://user-images.githubusercontent.com/10111092/89819285-26cf3300-db19-11ea-93da-2ed0d85f56d2.gif)

## Reproduce

With setting ` "blockWhileCommandExecutes": true`:

1. Enter a repo you have approriate credentials for
2. click push button 
3. click somewhere on the screen
4. Git credentials box pops up

## Expected behavior

Credentials box does not pop up

## Context

- Python package version: 0.21.0a0

- Extension version: 0.21.0a0

- Git version: 2.25.1

- Operating System and its version: PopOs 20.04

No interesting output in either console

**Comment by fcollonval** [comment]
@ianhi Thank for testing the extension. I'm working on this one as part of #721

**Comment by ianhi** [comment]
If I just click ok on the credentials dialog then the push will complete:
![pushing-2](https://user-images.githubusercontent.com/10111092/89819936-2daa7580-db1a-11ea-9df1-265c0187520c.gif)

but clicking multiple times will continue to spawn the box:
![pushing-3](https://user-images.githubusercontent.com/10111092/89820016-4f0b6180-db1a-11ea-9ca5-5c6405c1343e.gif)

**Comment by ianhi** [comment]
From https://github.com/jupyterlab/jupyterlab-git/pull/721#issuecomment-672010448 this is not an issue with the new modal. It is partially and issue with jupyterlab dialogs and partially with how the push dialog handles cancelling of the dialog.
