### ISSUE TITLE
Make this extension localizable and test translation infrastructure for extensions

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab-git#727]

**Comment by fcollonval** [comment]
@goanpeca could you please provide more information on :
* how to make the extension localized
* where to define the various translation (is it in this project, in a separated one, in the jupyterlab one)?
* how to distribute the translations

**Comment by goanpeca** [comment]
Hi @fcollonval sure thing.

So there are two parts, frontend and backend. I will explain in more detail what is needed. I can open a small PR to illustrate what needs to be done :)

**Comment by fcollonval** [comment]
> So there are two parts, frontend and backend. I will explain in more detail what is needed. I can open a small PR to illustrate what needs to be done :)

That would be awesome - thanks!

**Comment by JessicaBarh** [comment]
Hi @goanpeca and @fcollonval,

I'm working on a PR for this and so far I've followed a similar concept as the changes made to the jupyterlab packages on [this commit](https://github.com/jupyterlab/jupyterlab/commit/15ac2db4973d77c478474bf93fc820be53ecfb91). What I can't figure out is the po file (how would that be generated) and if there are any other backend or frontend stuff that need to be done. 
If you can open such PR that would be super helpful, thank you!

**Comment by fcollonval** [comment]
Closing this one as the work was mainly done in #888. Remaining translation holes are tracked in #1023
