### ISSUE TITLE
Error switching branch: failed to fetch

### ISSUE THREAD

**Issue by Freshwood** [jupyterlab/jupyterlab-git#741]
Actually the git plugin can not re checkout a remote branch
Steps to reproduce:

* Create a repository to with an additional remote branch e.g. remotes/origin/test
* Then checkout the remote/origin/test branch
* The checkout is successful. A new local branch with name 'test' is in the list.
* Later on when the user click again on the remotes/origin/test branch then the following error is shown:

Error switching branch
Failed to fetch

Please, find attached the STR as GIF:

![error-switching-remote-branch](https://user-images.githubusercontent.com/18640690/91153379-69b80b80-e6c0-11ea-88e4-36dd97463cfd.gif)

Desired behavior:
* The plugin re checkout the remote branch and will overwrite (Display dialog box?) the local branch
OR
* The plugin will block the checkout of an already checked out remote branch.

**Comment by ianhi** [comment]
Hi @Freshwood I think this may be due to the slashes in the branch name ref: https://github.com/jupyterlab/jupyterlab-git/issues/686

Can you try installing the latest release candidate and see if the issue persists:

```
pip install jupyterlab-git==0.21.0rc0
```

**Comment by Freshwood** [comment]
Hello @ianhi,

thank you for your reply.
I looked at the code.
The error will be raised in the following line:
https://github.com/jupyterlab/jupyterlab-git/blob/bf58cece4d991c47369ac8efd5436cfb0a5cd76f/jupyterlab_git/git.py#L760

The first try will always work. When you retry to checkout the remote branch (with tracking --track) then you will get an exception. (This is a normal git behavior)

Many thanks

Freshwood

**Comment by 3coins** [comment]
I can look into this. Please assign this to me.

**Comment by fcollonval** [comment]
Thanks @3coins
