### ISSUE TITLE
branch panel missing from UI

### ISSUE THREAD

**Issue by CerebralMastication** [jupyterlab/jupyterlab-git#744]
Greetings y'all. Thank you for a really great Jupyter Extension. I've had some good luck running the extension locally on Macs, but I'm running into a weird snag with our JupyterHub install that runs JupyterLab using Docker Spawner. Everything seems to work great, but we aren't getting a branch pane (right word?) in the UI when a repo has more than one branch. 

Here's a screen shot of a repo with two branches. Both the terminal window and the browser are in the same directory. 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/126879/91506505-3e8c1280-e8a0-11ea-8448-a043cb7aac59.png">

This is the part where I would typically show a reproducible example, but that's a bit tricky here. I'm really here to ask for help in debugging. Any clues how I go about seeing what might be going on or why that pane is missing? 

I'm running JupyterLab 2.2.2 and jupyterlab-git version 0.20.0

Any nudges or ideas on how I should be attacking this would be greatly appreciated. 

Cheers, 

JD

**Comment by ianhi** [comment]
Hi @CerebralMastication, thanks for the report. I suggest you check the following things:
1. What version of Git is installed?
2. Are there any errors in the browser console?
    - https://support.monday.com/hc/en-us/articles/360002197259-How-to-Open-the-Developer-Console-in-your-Browser
3. Any errors showing up in the jupyterlab output in the terminal?
     - I know this may be trickier with jupyterhub so I'd focus on 1 and 2 first.

**Comment by CerebralMastication** [comment]
aaaaaand we have a suspect in custody: my git version is 1.8.3.1... this is a problem, isn't it?

**Comment by ianhi** [comment]
It likely is a problem, there are several git commands used by the extension that are only available in Git>=2. Unfortunately I don't know exactly which ones they are, or if they are related to branching. Still I'd recommend upgrading regardless. On the next release (`0.21.0`) the extension will check the Git version, and raise a dialog warning you if it is too low.

Were there any browser console errors as well? It's not great if the branch menu just silently fails to appear. We should try to inform the user of the issue so that they can rectify it.

**Comment by CerebralMastication** [comment]
Thank you for the link on checking the browser console. I'm more "data science" than "developer" so that tip really helped me. 

Most def something going wrong with branching in the console error log:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/126879/91581949-273f3a80-e91d-11ea-9c2f-93f2091b215a.png">

then a number of errors along this line:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/126879/91582049-46d66300-e91d-11ea-9992-0ad164258fde.png">

and it seems that it's throwing new errors every few seconds... I presume that's because of polling git. 

I'll work with my system admin folks to see if we can slip in a new version of git and see if the behavior changes. I'm optimistic. 

Thanks again for the debugging help.

**Comment by ianhi** [comment]
> Thank you for the link on checking the browser console. I'm more "data science" than "developer" so that tip really helped me.

We should probably include that link or something similar in the issue template so it's easier for users to know what is meant. 


Thanks for exploring the console, those errors look similar to https://github.com/jupyterlab/jupyterlab-git/issues/674 although the end result is different. If I had to guess what was happening it is:
1. Old version of Git causes failure of commands w.r.t branching
2. On the frontend something goes wrong similar to the linked issue

So I think that upgrading Git should fix it. Though you can also upgrade to the latest release candidate which has some fixes with branch menu rendering:
`pip install jupyterlab-git==0.21.0rc0`


> and it seems that it's throwing new errors every few seconds... I presume that's because of polling git.

Yup! The default polling interval is every 3 seconds, though you can change this in the settings.

**Comment by CerebralMastication** [comment]
Thank you all for the fast and helpful debugging advice. I am closing this as it's certainly not a bug. Upgrading git fixed my issues. Thanks again.
