### ISSUE TITLE
Context menu not working on Debian Firefox 68

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#757]
## Description

The context menu is showing but the file is not selected. Therefore the context menu is not working.

Note: it is working on Chromium on the same OS. And the action button are working too.

Fixing #712 may correct this one.

## Context

- Python package version: 0.21.0

- Extension version: 0.21.0

- Git version:

- Operating System and its version:
Firefox 68.12.0esr (64-bit)
Debian 4.19.132-1

**Comment by ianhi** [comment]
Are you able to upgrade to 78 which I believe is also esr? I'm on PopOS which is debian based and I don't have this issue wen using Firefox 80.0
