### ISSUE TITLE
Start Using a Changelog

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#768]
I think it would be good to maintain a CHANGELOG for this project (similar to the [comment here](https://github.com/jupyterlab/jupyterlab-git/issues/453#issuecomment-557220964)).

I suggest we follow [keep a changelog](https://keepachangelog.com/en/1.0.0/) formatting as it's very clear. A downside to this is I think we'd be the only Jupyter project using this format.

Examples from other Jupyter projects:
https://github.com/ipython/traitlets/blob/master/docs/source/changelog.rst
https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/getting_started/changelog.rst

**Comment by fcollonval** [comment]
@mlucool I would prefer to fill the information in [GitHub release](https://github.com/jupyterlab/jupyterlab-git/releases) page as I started since 0.21.

It makes it easier for now; in particular to link to issues and PR as you get the GitHub completion.
