### ISSUE TITLE
jupyter lab build is not responsive 

### ISSUE THREAD

**Issue by lingxueli** [jupyterlab/jupyterlab-git#769]
Hello,

I m stuck at "jupyter lab build" when I install this tool.
The output is:
root@ip-172-31-2-202:~# jupyter lab build
[LabBuildApp] JupyterLab 2.2.7
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:dev:minimize)
/

It's been there for 30 mins and not finished. 

I installed node.js and nmp. Can you please let me know how could I know the issue and fix it?

Not sure if this could be useful but here's my output from "jupyter lab"

root@ip-172-31-2-202:~# jupyter lab
[I 05:39:31.655 LabApp] The port 8888 is already in use, trying another port.
[I 05:39:31.655 LabApp] The port 8889 is already in use, trying another port.
[I 05:39:32.123 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 05:39:32.124 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[C 05:39:32.230 LabApp] Running as root is not recommended. Use --allow-root to bypass.

root@ip-172-31-2-202:~# jupyter lab --allow-root
[I 05:40:32.332 LabApp] The port 8888 is already in use, trying another port.
[I 05:40:32.332 LabApp] The port 8889 is already in use, trying another port.
[I 05:40:32.682 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 05:40:32.682 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 05:40:32.711 LabApp] Serving notebooks from local directory: /root
[I 05:40:32.712 LabApp] Jupyter Notebook 6.1.4 is running at:
[I 05:40:32.712 LabApp] http://ip-172-31-2-202:8890/
[I 05:40:32.712 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Thanks,

Lisa

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Hey,

Could you report the results of the two following commands:
- `jupyter labextension list`
- `jupyter serverextension list`

Do you have access to the internet? In particular you need to be able to access npmjs.com.

You can also try to build in debug mode to get more feedback:
`jupyter lab build --debug`

**Comment by lingxueli** [comment]
Update:

The output is changed a bit when I stopped my background process from "jupyter notebook". Now i run the "jupyter lab build" again. It's not responsive so I terminated the process.

Then I start the lab by "jupyter lab --allow-root", the GUI is not accessible from either http://ip-172-31-2-202:8889/ or my public DNS:8889

root@ip-172-31-2-202:~/Notebooks# jupyter lab --allow-root
[I 05:55:02.392 LabApp] The port 8888 is already in use, trying another port.
[I 05:55:02.859 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 05:55:02.859 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 05:55:02.924 LabApp] Serving notebooks from local directory: /root/Notebooks
[I 05:55:02.924 LabApp] Jupyter Notebook 6.1.4 is running at:
[I 05:55:02.925 LabApp] http://ip-172-31-2-202:8889/
[I 05:55:02.925 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Now my server is crushed.
Should I not install the normal jupyter before I install this? Are they compatible?
Please let me know if you need anything from me in order to fix this issue. Thanks in advance for your help!

Thanks,

Lisa

**Comment by lingxueli** [comment]
Okay Let me try to get my server back up and send you the results of the two commands. Thanks you.

**Comment by lingxueli** [comment]
> Hey,
> 
> Could you report the results of the two following commands:
> 
> * `jupyter labextension list`
> * `jupyter serverextension list`
> 
> Do you have access to the internet? In particular you need to be able to access npmjs.com.
> 
> You can also try to build in debug mode to get more feedback:
> `jupyter lab build --debug`

Okay Let me try to get my server back up and send you the results of the three commands. Thank you.

**Comment by lingxueli** [comment]
Hi,

Thank you so much! So the debug mode really helps. When I use it, it gets installed in secs. Now I can see the app is running fine!

root@ip-172-31-2-202:~# jupyter serverextension list
config dir: /root/.jupyter
    githubcommit  enabled
    - Validating...
      githubcommit  OK
config dir: /usr/etc/jupyter
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git 0.22.0a0 OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.7 OK
    nbdime  enabled
    - Validating...
      nbdime 2.0.0 OK
root@ip-172-31-2-202:~# jupyter labextension list
JupyterLab v2.2.7
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyterlab/git v0.22.0-alpha.0  enabled  OK*
        nbdime-jupyterlab v2.0.0  enabled  OK

   local extensions:
        @jupyterlab/git: /jupyterlab-git



> Hey,
> 
> Could you report the results of the two following commands:
> 
> * `jupyter labextension list`
> * `jupyter serverextension list`
> 
> Do you have access to the internet? In particular you need to be able to access npmjs.com.
> 
> You can also try to build in debug mode to get more feedback:
> `jupyter lab build --debug`

**Comment by fcollonval** [comment]
Nice to hear you got it fixed.
