### ISSUE TITLE
Ctrl + enter to commit

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#773]
##  Description

I would like to be able to commit by pressing <kbd>Ctrl</kbd> + <kbd>Enter</kbd> when the focus is on Summary or Description field. Technically, I would propose to reuse the shortcut that is used by the notebook to run the cell (as different operating systems may have different bindings for such actions).

## Context

- Extension version:
@jupyterlab/git v0.21.1  enabled  OK

**Comment by fcollonval** [comment]
Thanks for this nice suggestion
