### ISSUE TITLE
repository linked outside the root directory are not working

### ISSUE THREAD

**Issue by sperezconesa** [jupyterlab/jupyterlab-git#775]
## Description
Hello,

Love the extension! But I see a behaviour I don't understand. When I try to add a file to gitignore it  adds it to gitignore but the gitignore file is not opened and I get the message: 404 file not found.

Thank you very much for your help and best regards,
Sergio

## Reproduce

![image](https://user-images.githubusercontent.com/27727343/93574228-79adcd00-f998-11ea-9349-f10ccbe40994.png)

![image](https://user-images.githubusercontent.com/27727343/93573995-1fad0780-f998-11ea-8b7d-c4c83c165414.png)

## Expected behavior

I guess it should open the gitignore file

## Context

- Python package version:
Name: jupyterlab-git
Version: 0.21.1
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: /data/sperez/bin2/anaconda3/envs/lab_env_0/lib/python3.8/site-packages
Requires: pexpect, notebook, nbdime, packaging
Required-by: 
- Extension version:
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/sperez/data_partition/bin2/anaconda3/envs/lab_env_0/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/fasta-extension v2.0.0  enabled  OK
        @jupyterlab/git v0.21.1  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v2.0.6  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK
        jupyterlab-favorites v2.0.0  enabled  OK
        jupyterlab_conda v2.2.4  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
        nglview-js-widgets v2.7.7  enabled  OK

- Git version:
git version 2.17.1
- Operating System and its version:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

<details><summary>Command Line Output</summary>
<pre>
[D 10:25:34.076 LabApp] 200 POST /git/branch?1600417534047 (127.0.0.1) 22.39ms
[D 10:25:34.080 LabApp.jupyterlab_git] Execute ['git', 'status', '--porcelain', '-u', '-z'] in /data/sperez/Projects/nmr_assign_state.
[D 10:25:34.091 LabApp.jupyterlab_git] Code: 0
    Output:  M .gitignore M notebooks/bayesian_assign_state.ipynb M notebooks/study_amino_acids.ipynb?? models/bayesian/normal_model_sparta_plus_CA.nc?? models/bayesiannormal_model_sparta_plus_CA.nc?? reports/critique/normal_model_sparta_plus_CA/autocorr.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_c.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_fo.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_o.png?? reports/critique/normal_model_sparta_plus_CA/trace_sd_c...
    Error: 
[D 10:25:34.091 LabApp.jupyterlab_git] Execute ['git', 'diff', '--numstat', '-z', '--cached', '4b825dc642cb6eb9a060e54bf8d69288fbee4904'] in /data/sperez/Projects/nmr_assign_state.
[D 10:25:34.198 LabApp.jupyterlab_git] Code: 0
    Output: 12  0       .env35  0       .gitignore10    0       LICENSE31       0       Makefile12      0       README.md0      0       build/lib/src/__init__.py0      0       build/lib/src/data/__init__.py30        0       build/lib/src/data/make_dataset.py0     0       build/lib/src/features/__init__.py50    0       build/lib/src/features/build_features.py0       0       build/lib/src/models/__init__.py0       0       build/lib/src/models/predict_model.py0  0       build/lib/src/models/train_model.py0    0       build/lib/src/visualization/__init__.py0        0       build/lib/src/visualization/visualize.py-       -       data/aa_resid_dic.pkl0  0       data...
    Error: 
[D 10:25:34.198 LabApp] 200 POST /git/status?1600417534077 (127.0.0.1) 119.16ms
[D 10:25:35.706 LabApp] 200 GET /api/contents/Projects/nmr_assign_state?content=1&1600417535701 (127.0.0.1) 3.16ms
[D 10:25:35.723 LabApp] 200 GET /api/kernels?1600417535721 (127.0.0.1) 0.73ms
[D 10:25:35.724 LabApp] 200 GET /api/sessions?1600417535722 (127.0.0.1) 0.76ms
[D 10:25:36.605 LabApp] 200 GET /metrics?1600417536584 (127.0.0.1) 14.43ms
[D 10:25:37.189 LabApp] 200 POST /git/ignore?1600417537186 (127.0.0.1) 0.74ms
[D 10:25:37.248 LabApp.jupyterlab_git] Execute ['git', 'status', '--porcelain', '-u', '-z'] in /data/sperez/Projects/nmr_assign_state.
[D 10:25:37.249 LabApp] Using contents: services/contents
[W 10:25:37.254 LabApp] 404 GET /data/sperez/Projects/nmr_assign_state/.gitignore?format=text&type=file&content=1&1600417537247 (127.0.0.1) 5.77ms referer=http://0.0.0.0:9999/lab/workspaces/auto-8
[D 10:25:37.259 LabApp.jupyterlab_git] Code: 0
    Output:  M .gitignore M notebooks/bayesian_assign_state.ipynb M notebooks/study_amino_acids.ipynb?? models/bayesian/normal_model_sparta_plus_CA.nc?? reports/critique/normal_model_sparta_plus_CA/autocorr.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_c.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_fo.png?? reports/critique/normal_model_sparta_plus_CA/trace_mu_o.png?? reports/critique/normal_model_sparta_plus_CA/trace_sd_c.png?? reports/critique/normal_model_sparta_plus...
    Error: 
[D 10:25:37.259 LabApp.jupyterlab_git] Execute ['git', 'diff', '--numstat', '-z', '--cached', '4b825dc642cb6eb9a060e54bf8d69288fbee4904'] in /data/sperez/Projects/nmr_assign_state.

</pre>
</details>

**Comment by fcollonval** [comment]
Thanks for reporting @sperezconesa 

Indeed it should open the gitignore file. That definitely exists as git report it's been modified.

Is your root directory (i.e. the home in JupyterLab) within your git repository? For example do you open JupyterLab within your notebooks folder? If so JupyterLab can only display files that are below that folder. Hence the gitignore file won't be accessible.

**Comment by sperezconesa** [comment]
I think you found the root of the problem!
I run the notebook from /home/sergio but the repository is in /data/sergio/Projects that I access through a symbolic link placed in /home/sergio/Projects --> /data/sergio/Projects. 

If I run the lab from /data/sergio/Projects there is no problem.

Can this be fixed for future releases?

**Comment by fcollonval** [comment]
> Can this be fixed for future releases?

That is not gonna be easy.

So for your case, the troubles probably comes from that line:

https://github.com/jupyterlab/jupyterlab-git/blob/eafec1310036a7fdd5dcae362f772378fef66b4f/src/model.ts#L569

The server root folder is probably your `/home/sergio/Projects` directory. But git resolves the path repository to `/data/sergio/Projects`. So that statement that should provide a understable path for JupyterLab is actually not succeeding.

**Comment by sperezconesa** [comment]
Well, it is only a minor problem. But hopefully you can figure it out!
Thanks for the wonderfull extension! I have become a more disciplined and expert user of git thanks to it :)

**Comment by ianhi** [comment]
> By the way, I wish I could help with the code but my skills are very far from being usefull in this case.

@sperezconesa I think you'd be surprised at how much you can accomplish. I thought the same at first, but by just trying to solve my problems with this extension I learned a lot along the way. If you do want to give it a go feel free to ask questions :)

**Comment by fcollonval** [comment]
@ianhi thanks for sharing your feedback. Add you're one or the recent contributors.

**Comment by fcollonval** [comment]
@sperezconesa I tagged a couple of issue as `Good first issue` if you are interested.

**Comment by sperezconesa** [comment]
Thanks a lot!
