### ISSUE TITLE
Update for jupyterlab 3

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab-git#779]
**edit - Install jupyterlab-git beta**: Jupyterlab-git has a beta release which you can install with:
```
pip install --upgrade --pre jupyterlab-git
```

## Description
Jupyterlab version 3 is nearly upon us (rc this week I think?). 
The update to jlab3 may be as simple as running: `python -m jupyterlab.upgrade_extension .` but what should be done w.r.t branches on this repo? Should master track jlab 3 and then create a `0.2x.y` branch for bugfixes for jlab2?

**Comment by fcollonval** [comment]
Yes the master should follow the latest major JupyterLab. And for older JupyterLab, the branches `0.#x.y` works fine. 

We should also think what is required to reach 1.x => but not in an issue rather linking issue to milestone.

**Comment by orome** [comment]
With 3.0 I get `The extension "@jupyterlab/git" is outdated.`. Does this extension not currently work with 3.0?

**Comment by jasongrout** [comment]
> With 3.0 I get `The extension "@jupyterlab/git" is outdated.`. Does this extension not currently work with 3.0?

This issue is not closed, and the corresponding PR (https://github.com/jupyterlab/jupyterlab-git/pull/818) has not been merged, so it's probably reasonable to assume that it hasn't been updated for 3.0 yet?

**Comment by fcollonval** [comment]
It is not yet release for JupyterLab 3 as it requires first [nbdime](https://github.com/jupyter/nbdime/pull/551) to be released on it.

**Comment by spouyllau** [comment]
Hello,
Have a idea of the disposability on jupyterlab 3 of jupyterlab-git ?
Best,

**Comment by GoingMyWay** [comment]
Hello,

When will you support the jupyterlab 3?

Best

**Comment by KPouianou** [comment]
Is there any ETA on this? It is a serious limitation for us a we use multiple plugins that require Lab v3

**Comment by fcollonval** [comment]
I'm reopening as the current status is beta for JLab3 (waiting for final release of nbdime).

**Comment by fcollonval** [comment]
A beta version has been released for JupyterLab 3. To test it you can install it with:

```
pip install --pre jupyterlab-git==0.30.0b1
```

CC @ajbozarth

**Comment by hawlcat** [comment]
I tried this, and got this:

![Capture](https://user-images.githubusercontent.com/62461046/105253925-6003d880-5b78-11eb-91b8-e12ff5500b8d.PNG)

Any idea?

**Comment by hawlcat** [comment]
Thank you @ianhi 

I am using jupyterhub, and have this problem:
![image](https://user-images.githubusercontent.com/62461046/105427469-20ef8900-5c45-11eb-88f1-eb6b8a1037e6.png)

I checked using jupyter server extension list, and jupyter labextension list to check, looks everything fine.
![image](https://user-images.githubusercontent.com/62461046/105427633-788df480-5c45-11eb-8d02-bedd34ed5941.png)

If I run jupyterlab directly on the server, and everything is fine including git operation as I tried.

Anyone has any idea about this issue?

Thank you.

**Comment by JessicaBarh** [comment]
> Thank you @ianhi
> 
> I am using jupyterhub, and have this problem:
> ![image](https://user-images.githubusercontent.com/62461046/105427469-20ef8900-5c45-11eb-88f1-eb6b8a1037e6.png)
> 
> I checked using jupyter server extension list, and jupyter labextension list to check, looks everything fine.
> ![image](https://user-images.githubusercontent.com/62461046/105427633-788df480-5c45-11eb-8d02-bedd34ed5941.png)
> 
> If I run jupyterlab directly on the server, and everything is fine including git operation as I tried.
> 
> Anyone has any idea about this issue?
> 
> Thank you.

Also having this issue. Any suggestions?

**Comment by fcollonval** [comment]
With JupyterHub and JupyterLab 3, the setting to start JupyterLab has changed - see [the documentation](https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html).

> To change the user’s default user interface to JupyterLab, set the following configuration option in your jupyterhub_config.py file:

```
c.Spawner.cmd=["jupyter-labhub"]
```

**Comment by JessicaBarh** [comment]
> With JupyterHub and JupyterLab 3, the setting to start JupyterLab has changed - see [the documentation](https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html).
> 
> > To change the user’s default user interface to JupyterLab, set the following configuration option in your jupyterhub_config.py file:
> 
> ```
> c.Spawner.cmd=["jupyter-labhub"]
> ```

My default user interface is Jupyterlab. Would this have anything to do with nbdime? I'm using the newest beta version 3.0.0.b1

**Comment by hawlcat** [comment]
@JessicaBarh ,  FYI, I downgraded jupyterlab to 2.x, and also git. Everything goes back normal.

**Comment by krassowski** [comment]
@JessicaBarh what about this one: https://github.com/krassowski/jupyterlab-lsp/issues/375#issuecomment-761078622

I think predicted it will affect jupyterlab-git users here: https://github.com/jupyterlab/jupyterlab/pull/9616#issuecomment-761048731 ;)

But, seriously know, is there a way we could help JupyterHub to release a version defaulting to `jupyter_server` sooner? I will open an issue on jupyter-hub repo.

**Comment by ajbozarth** [comment]
What's the timeline on releasing 0.30.0 with the lab 3 support?

**Comment by fcollonval** [comment]
> What's the timeline on releasing 0.30.0 with the lab 3 support?

We need nbdime for JLab3 to get out of beta. I think what is holding nbdime is the broken tests if you want to help with that.

**Comment by william-sheldon** [comment]
I am facing the exact same issue as @hawlcat and @JessicaBarh 

running jupyterhub and installing in notebook server using:

` ``pip install --pre jupyterlab-git==0.30.0b1

RUN jupyter labextension install @jupyterlab/git```

Is there a workaround that doesn't require downgrading?

**Comment by JessicaBarh** [comment]
@william-sheldon @hawlcat I got it working using `jupyter server` vs `jupyter notebook` to start up my image.
You'll also need to rename your jupyter_notebook_config.py file to jupyter_server_config.py and rename all c.NotebookApp traits to c.ServerApp in it. see https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html for more info

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-git-in-jupyter-hub/8108/2

**Comment by stonebig** [comment]
nbdime-3.0.0 is out

**Comment by fcollonval** [comment]
The first version supporting JupyterLab 3 (jupyterlab-git==0.30.0) has been released on pypi.org. conda release will follow soon.
