### ISSUE TITLE
Failed to load the jupyterlab-git server extension

### ISSUE THREAD

**Issue by JupyterPS** [jupyterlab/jupyterlab-git#789]
When I run this \forked\ repo I get the following message as it finishes building

Failed to load the jupyterlab-git server extension
gitcommand not found - please ensure you have Git > 2 installed

Please help if possible

 
 
 

## Context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
This means `git` is not available in the Jupyter server. You need to install it or add it to your PATH to make it available.

Note: you should not use this repo or a fork. But install it with pip or conda; see https://github.com/jupyterlab/jupyterlab-git#install.

**Comment by JupyterPS** [comment]
Hi Frédéric

This is what I have in my Dockerfile. I take it that git is just an 'ordinary' extension like github and toc and therefore should be handled likewise? Still get the same error message after my last try: https://mybinder.org/v2/gh/JupyterPS/MySecondRepo/master?urlpath=lab

RUN python -m pip install --upgrade jupyterlab jupyterlab-git  ========> LAST TRY

RUN python -m pip install jupyterlab_github
RUN python -m pip install jupyterlab_git

RUN jupyter serverextension enable --py jupyterlab_github --sys-prefix
RUN jupyter serverextension enable --py jupyterlab_git --sys-prefix

RUN jupyter labextension install @jupyterlab/github
RUN jupyter labextension install @jupyterlab/git
RUN jupyter labextension install @jupyterlab/toc

RUN jupyter lab build

Regards
Henning Reckey
________________________________
Fra: Frédéric Collonval <notifications@github.com>
Sendt: 30. september 2020 09:33
Til: jupyterlab/jupyterlab-git <jupyterlab-git@noreply.github.com>
Cc: JupyterPS <henningreckey@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [jupyterlab/jupyterlab-git] Failed to load the jupyterlab-git server extension (#789)


This means git is not available in the Jupyter server. You need to install it or add it to your PATH to make it available.

Note: you should not use this repo or a fork. But install it with pip or conda; see https://github.com/jupyterlab/jupyterlab-git#install.

**Comment by telamonian** [comment]
you'll need to add an install of git itself to your dockerfile. Something along the lines of:

```dockerfile
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    git \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
```

but this isn't really a jupyterlab-git issue. Any further questions/trouble you have, you should either consult the Docker docs, or maybe the repo for your base image: https://github.com/jupyter/docker-stacks/tree/master/base-notebook.

**Comment by corralm** [comment]
I had this same issue (though with Docker) and it was due to Xcode being uninstalled after a macOS upgrade.

Solution: Reinstall Xcode via the App Store.

I hope this helps someone with this issue.
