### ISSUE TITLE
Unable to enter Name and Email in author box

### ISSUE THREAD

**Issue by metalhead95** [jupyterlab/jupyterlab-git#799]
## Description

When 'Who is committing' dialog box is shown, clicking on name or email input fails with following error in console -
![image](https://user-images.githubusercontent.com/34500690/95863457-d62abf00-0d81-11eb-8c39-31fe5db03d47.png)

To be clear, typing any character in name and email input box is disabled.

## Reproduce

1. Ensure user.name and user.email is not set in git config.
2. After making some changes in repo, click on 'Commit' in git panel.
3. Click on 'Name' input in 'Who is committing?' dialog box
4. 'Name' doesn't accept any input. 

## Expected behavior

Should be able to type in Name and Email in dialog box.

## Context

- Python package version:
0.21.1

- Extension version:
0.21.1

- Git version:
2.23.3

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
dialog.js:285 Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLButtonElement.focus (<anonymous>)
    at f._evtFocus (dialog.js:285)
    at f.handleEvent (dialog.js:174)
    at HTMLDivElement.focus (<anonymous>)
    at HTMLDocument.t (Unstable_TrapFocus.js:77)
    at HTMLButtonElement.focus (<anonymous>)
    at f._evtFocus (dialog.js:285)
    at f.handleEvent (dialog.js:174)
    at HTMLDivElement.focus (<anonymous>)
    at HTMLDocument.t (Unstable_TrapFocus.js:77)
</pre>
</details>

**Comment by fcollonval** [comment]
@metalhead95 could you update to the latest version (0.22.1)?  And test if the bug is still present.

**Comment by metalhead95** [comment]
Upgrading to v0.22.1 resolved the issue, thanks @fcollonval.
