### ISSUE TITLE
Prompt User to commit changes after a pull

### ISSUE THREAD

**Issue by ashutoshbondre** [jupyterlab/jupyterlab-git#80]
We have made the `git pull` command as `git pull upstream master --no-commit` , which means user can pull the changes,but those changes are not automatically committed. As good practice, we should ask the user to commit those pulled changes. 

Also another reason to prompt the commit is, user WILL NOT be able to pull further changes if he/she has not committed previous changes.

**Comment by ashutoshbondre** [comment]
make the pull button unclickable if there are uncommitted changes.

**Comment by ellisonbg** [comment]
The pull command should just be `git pull`. Otherwise you risk pulling from the wrong branch. Targeting to 0.1.

**Comment by ashutoshbondre** [comment]
Yes, its just `git pull` . User will enter his remote branch name on prompt.
