### ISSUE TITLE
UX: Bottom Bar Distracting

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#803]
## Description

Hi,

The bottom toolbar is distracting as it keeps pushing things to the right for a second then back. Below shows Python3 moving over:
![idling](https://user-images.githubusercontent.com/1813603/96640770-aafc1e80-12f1-11eb-9556-0a92f531b9e9.gif)

Given this happens every couple seconds, I don't think it's a net positive to users to have anything shown when it is working correctly. If people feel strongly on keeping this, can we ensure that it takes up always the same amount of space?

## Context

jupyterlab-git@0.21.1

**Comment by ianhi** [comment]
That was discussed a bit here: https://github.com/jupyterlab/jupyterlab-git/pull/630#issuecomment-640793100
You can turn it off using by turning the `displayStatus` setting to `false`. That said I'm still :+1: to at least having take it take the same amount of space.

**Comment by mlucool** [comment]
That worked :). We can leave this open or close it - whatever you think is right. I plan to disable this feature.

**Comment by fcollonval** [comment]
> That said I'm still +1 to at least having take it take the same amount of space.

To achieve this, I think the direction should be to use an icon telling the user if the extension is doing things or not (similary the kernel indicator at the top right of a notebook panel) and to get more details on the current action by setting an appropriate title when hovering the icon.

@mlucool by curiosity, did you open a similar issue about the kernel status in the statusbar - it has the same none-fixed width ?

**Comment by mlucool** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/7403, seems like we can add that there.
