### ISSUE TITLE
Large Number of Files Make Lab Unresponsive

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#804]
## Description

If you have a large number of files in a git repo, jupyterlab-git makes all of lab slow/unresponsive.

While I am not sure of what should define large nor how the status of each file is taken into account, I have included a reproducer below as a starter. This issue was found when someone had a spurious `.git` in a home directory making lab unresponsive, but things like `node_modules` can sometimes have this number of files.

While there are a lot of possible fixes, one ideas during the request to somewhat specify what you think the state of the world is and the backend only sends the diff. 

## Reproduce

Create a new directory and run:
```
git init
for n in {1..10000}; do touch $n.txt; done
```

Navigate to that directory in lab. Play around and you'll notice lab becomes unusable. If lab still works fast, crank up `n` above.

## Expected behavior

Git should not slow down lab.

## Context

jupyterlab-git@0.21.1
Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by ianhi** [comment]
Can you upgrade to v `0.22`? @fcollonval should added virtualized lists in https://github.com/jupyterlab/jupyterlab-git/pull/767 that should fix this problem.

**Comment by ianhi** [comment]
> While there are a lot of possible fixes, one ideas during the request to somewhat specify what you think the state of the world is and the backend only sends the diff.

fwiw the main culprit seemed to be rendering 1000s of dom nodes when creating the untracked files list see https://github.com/jupyterlab/jupyterlab-git/issues/667#issuecomment-639688149

**Comment by fcollonval** [comment]
0.22 should indeed solve the trouble thanks to the virtualization of the file lists.
