### ISSUE TITLE
Use jupyterlab-git to init workspace for JupyterHub users?

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyterlab/jupyterlab-git#805]
If I create a new user on JupyerHub I would like to autmatically init the corresponding workspace with some getting started  examples. Is it possible to define some default git repository?
Also see
https://stackoverflow.com/questions/64485967/how-to-init-content-of-notbooks-working-directory-in-jupyterhub-jupyterlab

**Comment by fcollonval** [comment]
This is up to you to get the best way to do that; especially as it depends on the kind of spawner you are using. The approach of the pre spawn hook is one possibility. You could improve it by changing the behaviour (i.e. the executed git commands) depending if the folder already exists (fetch-clean-pull) or not (clone).
