### ISSUE TITLE
Git clone doesn't prompt for user to enter credentials

### ISSUE THREAD

**Issue by rdelubi** [jupyterlab/jupyterlab-git#806]
## Description

The git clone function of the extension in 0.22.1 appears to be broken. It used to work in 0.21.1.

## Reproduce

1. Go to Menu->Git->Clone a repository
2. Enter the git repo URL and hit "Clone"
3. It shows "Successfully cloned" message at bottom right.
4. But nothing gets cloned and shows up in file system.

## Expected behavior

In between step 2 and 3, it prompts user to enter credentials.

## Context

(condaenv) sh-4.2$ jupyter labextension list
JupyterLab v2.2.8
Known labextensions:
   app dir: /opt/conda/envs/condaenv/share/jupyter/lab
        @j123npm/jupyterlab-dash v0.1.0-alpha.4  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.3.0-beta.3  enabled  OK
        @jupyterlab/git v0.22.1  enabled  OK
        @jupyterlab/latex v2.0.1  enabled  OK
        ipytree v0.1.8  enabled  OK
        jupyterlab-plotly v4.8.0  enabled  OK
        jupyterlab-sql v0.3.3  enabled   X
        nbdime-jupyterlab v2.0.1  enabled  OK
        plotlywidget v4.8.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK

   The following extension are outdated:
        jupyterlab-sql
        
   Consider running "jupyter labextension update --all" to check for updates.

(condaenv) sh-4.2$ git --version
git version 2.27.0
(condaenv) sh-4.2$ pip list |grep git
gitdb                     4.0.5
jupyterlab-git            0.22.1
(condaenv) sh-4.2$

**Comment by fcollonval** [comment]
Thanks you for reporting @rdelubi 

Is it possible for you to run jupyterlab in debug mode: `jupyter lab --debug` and report here the trace you got when it is not working.

Could you also report here any error displayed in the webbrowser console? (usually you can open it by pressing F12)

**Comment by inih** [comment]
Running version 0.22.1

I'm also having the same issue. Error occurs when entering any value in the clone url field.

I done `jupyter lab --debug` and tried to clone a repository by entering the value 'test' and the successfully cloned icon appeared but the logs shows the follow:

```
[D 13:56:11.970 LabApp.jupyterlab_git] Execute ['git', 'clone', 'test'] in /home/jovyan/.
[D 13:56:11.976 LabApp.jupyterlab_git] Code: 128
    Output:
    Error: fatal: repository 'test' does not exist

[D 13:56:11.977 LabApp] 200 POST /git/clone?1603461371964  8.26ms
```
When cloning a private repo, the below happens:

```

[D 14:18:28.703 LabApp.jupyterlab_git] Code: 128
    Output:
    Error: Cloning into 'repo_name'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

**Comment by fcollonval** [comment]
@inih Thanks for the detailed information. A fix is coming in #807.

**Comment by fcollonval** [comment]
version 0.22.2 has been released with a fix for this issue.

**Comment by sake4567** [comment]
We are also facing same issue. Please find below required. 

(app-root) (condaenv) bash-4.2$ pip show jupyterlab-git 
WARNING: Package(s) not found: jupyterlab-git
(app-root) (condaenv) bash-4.2$ jupyter labextension list
JupyterLab v2.2.8
Known labextensions: 
app dir: /opt/conda/envs/condaenv/share/jupyter/lab
@j123npm/jupyterlab-dash v0.1.0-alpha.4  enabled  OK
@jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK 
@jupyterlab/debugger v0.3.0-beta.3  enabled  OK 
@jupyterlab/git v0.22.2  enabled  OK 
@jupyterlab/latex v2.0.1  enabled  OK 
ipytree v0.1.8  enabled  OK 
jupyterlab-plotly v4.8.0  enabled  OK
 jupyterlab-sql v0.3.3  enabled   X 
nbdime-jupyterlab v2.0.1  enabled  OK 
plotlywidget v4.8.0  enabled  OK 
qgrid2 v1.1.3  enabled  OK 
The following extension are outdated: 
jupyterlab-sql 
Consider running "jupyter labextension update --all" to check for updates.

(app-root) (condaenv) bash-4.2$ git --version 
git version 2.29.0

**Comment by ianhi** [comment]
> (app-root) (condaenv) bash-4.2$ pip show jupyterlab-git
> WARNING: Package(s) not found: jupyterlab-git

Looks like you don't have the jupyterlab-git python package installed. I would try running `pip install --upgrade jupyterlab-git`
