### ISSUE TITLE
Fails to discard unstaged changes - cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-git#823]
## Description

![git-fails-to-discard-changes](https://user-images.githubusercontent.com/382917/98893899-6549f600-2458-11eb-8bb7-cd6cab843ccb.gif)

This is using 0.23.0 but I believe I saw similar behavior on 0.22.x as well.

**Comment by ianhi** [comment]
on master I get this error: 
![image](https://user-images.githubusercontent.com/10111092/98898765-52491d00-247c-11eb-954b-c50fa1ca6d4b.png)

I think two things are happening:
1. `options` is being used outside of the check for if it is undefined here:
https://github.com/jupyterlab/jupyterlab-git/blob/582ef5af67b8363b316dc29b92d935ed208ffaad/src/model.ts#L399
2. discard all changes doesn't use the options to specify the files that are being discarded. instead it just run `git checkout`. This will revert the changes but if there are open editors then they won't be updated to reflect the state on disk. (I think this is also a bug)

**Comment by ianhi** [comment]
Changing the revertFile lines to:
```typescript
        } else if (body.filename) {
          this._revertFile(body.filename);
        }
```

fixes the error, but there will still be the issue that open editors aren't updated when doing revert all changes
