### ISSUE TITLE
Creating a new branch

### ISSUE THREAD

**Issue by simonwhite71** [jupyterlab/jupyterlab-git#828]
If I try and make a new branch called "test" with the UI it says 
`ambiguous argument 'test': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'`
Which is the same error I see if on the command line I run 
`git diff test`
rather than
`git checkout -b test`
Am I doing something wrong?

Also if in the UI I try to make a branch with name `-b test` I get the error message
`usage: git diff [<options>] [<commit> [<commit>]] [--] [<path>...]`

**Comment by ianhi** [comment]
Hey @simonwhite71 thanks for the report. You aren't doing anything wrong, this looks like a bug that was introduced by https://github.com/jupyterlab/jupyterlab-git/pull/824

In that PR we started checking for what files will be changed by the git action before we switch branches. But that breaks down if we are opening a new branch. The relevant lines are these:
https://github.com/jupyterlab/jupyterlab-git/blob/1a57cab0b5babb7186e8f12795d284f47146e957/src/model.ts#L385-L405

**Comment by ianhi** [comment]
Also, great job tracking down that it was a git diff error. The reason `git diff` is called when checking out a branches is so that we can keep track of what files are being touched by the git action  to make sure that if they are open in an editor then the editor is kept up to date with the version on disk.

**Comment by simonwhite71** [comment]
Oh good, glad I could help, any idea when it might be resolved (not an issue for now, we can always branch manually)

**Comment by ianhi** [comment]
Fix is here: https://github.com/jupyterlab/jupyterlab-git/pull/829

So waiting on review of that - then we can do a patch release. You can also downgrade to `0.22.x` or maybe even `0.23.0`

**Comment by simonwhite71** [comment]
Thats great, thanks for being so responsive, I will wait for the next patch release 👍
