### ISSUE TITLE
Don't erase commit message when commit fails

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#836]
When using git hook (for example such as black), it may happen that the commit is rejected. Unfortunately in case of error the commit message is erased. It would be nice to keep it as the user will want to carry small correction (like add the black format correction) before retrying to commit.

**Comment by krassowski** [comment]
The relevant code is in:

https://github.com/jupyterlab/jupyterlab-git/blob/f60ed323212de9f51fe3c7a9e4fc5966a7df2c1f/src/components/CommitBox.tsx#L147-L153

The `_reset()` should only be called upon successful completion of the promise returned by `onCommit(msg)`.
