### ISSUE TITLE
Allow `commit & push`

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#837]
To help git beginners (but expert too :wink:), it would be nice to have a setting to transform the commit button in `commit & push` button (if there is a remote...).

**Comment by adammclaurin** [comment]
Definitely a good idea!

**Comment by ktaletsk** [comment]
Hey @fcollonval @adammclaurin , I really like this idea!

I just opened a PR implementing this feature, hope it would help. Seems to work for my limited testing, please take a look too.

**Comment by fcollonval** [comment]
Fixed by #887
