### ISSUE TITLE
Extension not visible in demo binder

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyterlab/jupyterlab-git#839]
## Description
The extension is not loading into the binder attached to this repo. (It is also not possible to install it the build fails)

![image](https://user-images.githubusercontent.com/18068320/101475293-81a05c00-394c-11eb-9152-b261c7153131.png)

## Reproduce
Click on the binder link

## Expected behavior
Extension installed

**Comment by fcollonval** [comment]
Closing following #841
