### ISSUE TITLE
Jupyterlab-git fails to load in JupyterHub

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyterlab/jupyterlab-git#840]
## Description
I am unable to install the jupyterlab-git extension on system wide jupyterhub. I am the admin of the server and I ran

```
/opt/jupyterhub/bin/python -m pip install --upgrade jupyterlab jupyterlab-git
```

to install jupyterlab for ecery user of the hub.

Running:

```
/opt/jupyterhub/bin/jupyter serverextension list
config dir: /opt/jupyterhub/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.9 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git 0.23.2 OK
    nbdime  enabled
    - Validating...
      nbdime 2.1.0 OK
```

and

```
/opt/jupyterhub/bin/jupyter labextension list
JupyterLab v2.2.9
Known labextensions:
   app dir: /opt/jupyterhub/share/jupyter/lab
        @jupyterlab/git v0.23.2  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK
```

I have tried using `sudo /opt/jupyterhub/bin/jupyter serverextension enable --py --sys-prefix jupyterlab_git`and `sudo /opt/jupyterhub/bin/jupyter serverextension enable --py --system jupyterlab_git` and still can not get jupyterlab git to load.

One interesting thing is I get this in my console:

```
XHR GET http://localhost:9999/user/wbanfield/git/settings?version=0.23.2&1607434143083
```

## Reproduce
Following JupyterHub guide then follow jupyterlab-git install instructions using python version used to launch jupyterhub

## Context

The JupyterHub is behind a jump proxy and I am using an SSH tunnel to tunnel port 8000 through to port 9999 on localhost hence the request above. I don't know if this affects the install in any manner?

**Comment by fcollonval** [comment]
@WesleyTheGeolien Could you try running `jupyter lab clean` and then retry `jupyter lab build`?

**Comment by WesleyTheGeolien** [comment]
@fcollonval Thanks for the tip that cleared up the problem not sure why it didnt build first time though.

I'd be happy to close this issue

**Comment by fcollonval** [comment]
Yep recently more users hit that problem (and binder too it seems). But I cannot figure out what induces it unfortunately.
