### ISSUE TITLE
Staging and commits never concludes

### ISSUE THREAD

**Issue by jmbenedetto** [jupyterlab/jupyterlab-git#844]
## Description

HI. When I try to stage changes or commit then, jupyter lab enters in a loop and never finishes.

![Captura de Tela 2020-12-16 às 22 47 21](https://user-images.githubusercontent.com/28365534/102427763-bff2e680-3ff0-11eb-89f0-6bd72da2d6b7.png)

At the terminal that is running jupyter lab I get the same message over and over:

![Captura de Tela 2020-12-16 às 22 49 02](https://user-images.githubusercontent.com/28365534/102427965-ec0e6780-3ff0-11eb-9794-39661e93b508.png)

## Reproduce

1. Go to 'Changer'
2. Fill a title
2. Click on 'Commit'

## Expected behavior

A commit as I see on Github for Mac.

## Context

- Python package version:

- Extension version: 0.23.2 Conda-Forge

- Git version: 0.23.2

- Operating System and its version: 2.24.3 (Apple Git-128)

<details><summary>Command Line Output</summary>

[E 22:51:53.282 LabApp] 500 POST /git/branch?1608169893275 (::1) 20001.71ms referer=http://localhost:8888/lab/workspaces/auto-e
[E 22:52:46.505 LabApp] {
      "Host": "localhost:8888",
      "Pragma": "no-cache",
      "Accept": "*/*",
      "Authorization": "token c4e5fb855d4f6fec7fd0ea4c12951fabe0b14cfa23ee4cce",
      "X-Xsrftoken": "2|12c59fbf|e75f3a122082bdbadf308b93fd0fc141|1607386923",
      "Accept-Language": "pt-br",
      "Cache-Control": "no-cache",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "text/plain;charset=UTF-8",
      "Origin": "http://localhost:8888",
      "Content-Length": "77",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
      "Referer": "http://localhost:8888/lab/workspaces/auto-e",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1608169893|23:username-localhost-8888|44:MTY5ODQ4ZGY0YTZlNGIyZjliZDJjNGJiMzI3NzM4NDU=|77e8ef66c12275dc5be90be7eb930351c37d92b82c8f8ac614862d319290360a\"; _xsrf=2|12c59fbf|e75f3a122082bdbadf308b93fd0fc141|1607386923"
    }

**Comment by fcollonval** [comment]
@jmbenedetto thank you for reporting.

Could you run JupyterLab in debug mode `jupyter lab --debug` ? And report here the server console output, it should contain the output of the git commands. An output example can be seen in https://github.com/jupyterlab/jupyterlab-git/issues/842.

**Comment by jmbenedetto** [comment]
@fcollonval thanks for your prompt reply. I remove jupyter conda env and reinstalled. It worked after this. Sorry to make you loose time.
