### ISSUE TITLE
Bug: lstrip in get_upstream_branch function

### ISSUE THREAD

**Issue by rrao24** [jupyterlab/jupyterlab-git#848]
There is a bug in the `get_upstream_branch()` function concerning the usage of `lstrip()` on line 1107 https://github.com/jupyterlab/jupyterlab-git/blob/0e1e6971d330d7925a5c187fa91582d3eed09d1b/jupyterlab_git/git.py#L1107

Say that line 1106 https://github.com/jupyterlab/jupyterlab-git/blob/0e1e6971d330d7925a5c187fa91582d3eed09d1b/jupyterlab_git/git.py#L1106 evaluates to `origin` (as it must do so commonly). The subsequent line will attempt to transform the full remote branch name (remote name + branch name) into just the branch name. If you have a branch name which starts with any combination of the characters `o,r,i,g,n`, then `lstrip()` can potentially strip those characters away as well.

For example, given `remote_name` = `origin`, and `rev_parse_output` = `origin/games`, `"origin/games".lstrip("origin/")` will evaluate to `"ames"`, causing the wrong branch to be pushed. This bug should be fairly easy to reproduce.

EDIT: Opened https://github.com/jupyterlab/jupyterlab-git/pull/849 for fix

**Comment by fcollonval** [comment]
Fixed by #849
