### ISSUE TITLE
Better handle case of unsaved changes

### ISSUE THREAD

**Issue by adammclaurin** [jupyterlab/jupyterlab-git#853]
I keep running into the same unexpected behavior where I run a notebook to test my final changes, then go to the git extension to commit & push the changes, but then find afterwards that some of the changes didn't get pushed because the file wasn't saved. It'd be nice if the git extension could catch this and either auto-save the file or prompt the user to save.

**Comment by quachtridat** [comment]
I believe it would be nice if there were a warning box saying there are unsaved files, and the user can save the files and/or stage the changes if they want to commit those.

**Comment by fcollonval** [comment]
Reopening as the warning box introduced in #1075 needs to be applied in simple mode too for consistency.
