### ISSUE TITLE
Add 'Discard All and Pull' button

### ISSUE THREAD

**Issue by adammclaurin** [jupyterlab/jupyterlab-git#860]
We're trying to enable an operating model where some members of the team are 'creators' of notebooks, and others are 'runners' of those notebooks. The latter group is fairly non-technical, e.g. not familiar with Python code or Git. The model to share notebooks is through Git for a few reasons (esp. compliance), but we're running into frictions because the 'runner' group easily gets confused and frustrated by the details of Git. This is often caused by the simple fact that running a notebook changes the notebook file (since the output gets saved in the file), which requires an explicit discard per file before pulling updates from the Git repo.

Perhaps an easier operating model here would be a simple 'Discard All and Pull' button to allow the 'runner' to have a one-click way to sync their local sandbox with whatever is on the repo (e.g. when the 'creator' pushes an update), without having to worry about what files changed, merging, etc.

What do you think?

Fwiw this is similar to the reason why I created #856 , and why I think #837 and #659 are such good ideas.

**Comment by adammclaurin** [comment]
Alternatively, perhaps we could introduce a 'Discard' button near the 'Pull' button, that discards changes to all files at the same time, rather than requiring the user to discard one by one. We could reuse the icon from the existing Discard button.

In that case, the user could quickly click two adjacent buttons to achieve the 'Discard All and Pull' capability that I'm trying to achieve.

**Comment by fcollonval** [comment]
Hey @adammclaurin thanks for the suggestion

FYI, there is already a button to discard all changes on hover of the header section (the *undo* arrow):
![image](https://user-images.githubusercontent.com/8435071/106482348-a842c500-64ad-11eb-8115-3bff267bb1bb.png)

And alternative would be to prompt the user to choose between discarding the changes and continuing the pull or stopping pulling.

**Comment by adammclaurin** [comment]
Thanks @fcollonval, I never noticed that button was there. It might be more obvious if it was up next to Pull/Push/Refresh.

Your idea re: the prompt would work as well. I'm not much of a UX person so I'll let people smarter than me figure out the most elegant way. All I'm trying to do is provide a fairly non-technical person the ability to express "just make my local copy look exactly like what's on the server" in as obvious and easy way as possible.
