### ISSUE TITLE
RHEL7 and issues with GIT v2

### ISSUE THREAD

**Issue by BlueCog** [jupyterlab/jupyterlab-git#862]
## Description

Hello all, I'm hoping you can help met with my issue:

I'm using Jupyterhub (1.2.1) & Jupyterlab (2.2.9) based on RHEL 7 (running on OpenShift)

RHEL 7 comes default with an old GIT version <2.0 so I'm installing git using `yum -y install rh-git218-git` (Software Collections) 
After that I can run `source scl_source enable rh-git218` what enables the just installed git. 

But this command only works for the current session, a solution would be to add this to a start up script / bash profile. But I cannot get that to work in the Jupyterlab context. 

With a bash profile i'm still getting the follwing error when spawning an Notebook:

Failed to load the jupyterlab-git server extension
git command not found - please ensure you have Git > 2 installed

Does anyone knows a solution (or workaround) for this?

**Comment by fcollonval** [comment]
Hey @BlueCog 

This means the user server is spawned via docker? If so indeed there is not so much you can do except changing the Docker definition.

If you have time, you could also submit code modifications to support git < 2.

**Comment by BlueCog** [comment]
> 
> 
> Hey @BlueCog
> 
> This means the user server is spawned via docker? If so indeed there is not so much you can do except changing the Docker definition.
> 
> If you have time, you could also submit code modifications to support git < 2.

Hey fcollonval, thnx for the reply.

Yeah I guess you could compare it to a Docker deployment. What do you mean with changing the Docker defintion? Is there a environt var I could set? Of change some config file?

Greets

**Comment by fcollonval** [comment]
On JupyterHub, the JLab servers can be started with various technologies. It can be a process on the JupyterHub server or a docker on the server or on cloud. How you can tune the JLab server is therefore different. So if JLab server is defined by a Dockerfile, you need to ask your administrator to modify it to install and activate git v2 in the docker before starting JLab. If it is a local process, then you can modify your user profile to do so (but from your original post, you don't seem to be in that configuration).

**Comment by BlueCog** [comment]
Ok, fixed it in the Docker file by symlinking rg-git to /usr/bin/git:

`RUN ln -s /opt/rh/rh-git218/root/bin/git /usr/bin/git`

**Comment by BlueCog** [comment]
Thnx for your pointers fcollonval

**Comment by fcollonval** [comment]
Great to hear you figure out a workaround.

**Comment by paravatha** [comment]
@BlueCog thanks for your suggestion

@fcollonval 

RUN ln -s /opt/rh/rh-git227/root/usr/bin/git /usr/bin/git
RUN echo "source scl_source enable rh-git227" >> /etc/profile.d/enablegit.sh

After adding these 2, git clone works from the command line
But, git clone button doesn't work
![image](https://user-images.githubusercontent.com/8755869/123903458-599e3780-d934-11eb-82d3-dc0cfaa2b976.png)

**Comment by fcollonval** [comment]
@paravatha it sounds like some dependencies are missing or your PATH is not set properly.

**Comment by paravatha** [comment]
@fcollonval 
Thanks for the suggestion. 
I tried several options, was able to 
git clone from the terminal. 
Wondering if anyone got Git extension working while using rh-git2.x
