### ISSUE TITLE
Where can I find the commit description

### ISSUE THREAD

**Issue by hawlcat** [jupyterlab/jupyterlab-git#866]
Hi there,

For committing, a commit message could be input including a title and description. After committing, I can see the commit title, but cannot find the description. Just wondering it is lost or just hidden somewhere? If hidden, where can I find this description because usually put lots of update information there so it is easy for other people to get the update idea at the first glance.

thanks

**Comment by ianhi** [comment]
Hi @hawlcat, I don't think this is currently possible from the extension UI, but this would a nice improvement.

It looks as though the commit message is making it to the frontend in the `ISingleCommitInfo` but not in the `ISinglePastCommitInfo` and the latter is used for rendering the items in the history tab.


https://github.com/jupyterlab/jupyterlab-git/blob/0e1e6971d330d7925a5c187fa91582d3eed09d1b/src/tokens.ts#L638-L644

https://github.com/jupyterlab/jupyterlab-git/blob/3c28978d8c6fc5ca6376e37c259a85368e4de9bf/src/components/SinglePastCommitInfo.tsx#L60

**Comment by ianhi** [comment]
Actually maybe I was confused. It seems that `commit_msg` is only the commit title, not the body of the commit message. Perhaps `ISingleCommitInfo` will need to be modified to also contain the commit message body. And then a 
`{this.props.commit.commit_body}` should be added here:
https://github.com/jupyterlab/jupyterlab-git/blob/4efb0a776cd22756b80cae7ec2c1cda5f701ab93/src/components/PastCommitNode.tsx#L107-L111


Though perhaps it's best to leave ISingleCommitInfo without the commit message to reduce the size of packets being passed between the front and backend. Instead the backend function `detailed_log` should return all of the details of a commit, including the body of the commit:
https://github.com/jupyterlab/jupyterlab-git/blob/3c28978d8c6fc5ca6376e37c259a85368e4de9bf/jupyterlab_git/git.py#L449

Then the frontend calls `detailed_log` here: https://github.com/jupyterlab/jupyterlab-git/blob/4efb0a776cd22756b80cae7ec2c1cda5f701ab93/src/components/SinglePastCommitInfo.tsx#L134

**Comment by ianhi** [comment]
I marked this a Good first issue, because I think that my final proposal shouldn't require any significant changes to data flow. But anyone feel free to clear that if this is harder than I think

**Comment by fcollonval** [comment]
Closing as resolved by #1134
