### ISSUE TITLE
conda install -c conda-forge jupyterlab jupyterlab-git installs (or downgrades to) JupyterLab 2.2.9

### ISSUE THREAD

**Issue by mallman** [jupyterlab/jupyterlab-git#870]
## Description

README.md says jupyterlab-git requires JupyterLab >= 3.0 and can install with

```sh
conda install -c conda-forge jupyterlab jupyterlab-git
```

However this installs jupyterlab 2.2.9.

## Reproduce

1. Remove (or don't install) anything Jupyter related.
2. Run `conda install -c conda-forge jupyterlab jupyterlab-git`

## Expected behavior

Install or keep jupyterlab >= 3.

## Context

Using miniconda py38_4.9.2 installed from https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh.

**Comment by fcollonval** [comment]
The JupyterLab 3 is still in beta stage. So the package has not been published on conda yet.

If you want to be notified when it will become available, please subscribe to #779

**Comment by mallman** [comment]
> The JupyterLab 3 is still in beta stage. So the package has not been published on conda yet.

I'm confused. [JupyterLab 3.0.7](https://anaconda.org/conda-forge/jupyterlab) is a beta release?

**Comment by fcollonval** [comment]
Sorry my sentence was not clear - JupyterLab 3 is out. But this extension does not support it yet. There is a beta version for this extension supporting JLab3. But it has been released on pypi only for now (see #779 for more details if you want to try the beta version)
