### ISSUE TITLE
add i18n for jupyterlab-git

### ISSUE THREAD

**Issue by JessicaBarh** [jupyterlab/jupyterlab-git#871]
jupyterlab 3 now supports i18n and i10n and all included extensions. will this be available for the new jupyterlab-git v0.30.0?

**Comment by fcollonval** [comment]
Hey @JessicaBarh 

No one is working on that. But if you get time to do it, this will be great. 

I must say I don't know where and how to specify the translation for JupyterLab extensions. So I raised some questions in #727. Feel free to comment there.

This is a duplicate of #727 - so I'm closing this one.

**Comment by JessicaBarh** [comment]
Hi @fcollonval, I'd for sure love to help with this, I'm looking to have this feature as soon as possible! 
Yes, #727  should definitely help me in getting started.
