### ISSUE TITLE
Error: Unable to get the lock on the directory

### ISSUE THREAD

**Issue by savemuri** [jupyterlab/jupyterlab-git#873]
**Problem**:
I am able to setup the extension and when I clone the repository and perform any git operation after cloning (Like checkout, commit, pull etc.) it throws the following error

![image](https://user-images.githubusercontent.com/41452484/107658064-c6e65000-6c53-11eb-902c-cc9c746c6174.png)

![image](https://user-images.githubusercontent.com/41452484/107657396-23953b00-6c53-11eb-99cc-4966b7a1ea3f.png)

Update: This is what I see in my jupyter log. It asks for username and token for my **gitlab** access there. And when I enter the right credentials, it still keeps asking again and again.
![image](https://user-images.githubusercontent.com/41452484/107728460-22e4bf00-6cbc-11eb-8f3e-1705251e42e6.png)

**My environment**: 
- AWS EMR running on Amazon Linux
- No sudo rights for my machine
- Using conda virtual env
- Jupyterlab V3.0.0

**Fixes Tried**:
- Tried removing index.lock file in .git directory
- Tried different versions of jupyterlab
Nothing worked.

Please let me know if I am missing something simple.

**Comment by savemuri** [comment]
**Update**: Fixed it. Turns out the issue was that my git credentials were not saved due to some permission issue. It works great now. So I had to enter creds for every action.

**Comment by atnjqt** [comment]
@savemuri I am running into a similar issue on installing Jupyterlab-git extension on a CentOS 8 VM... When you say permission issue with your git credentials, is this via HTTPS (username & password) or SSH pub & private key? 

I'm using the latter and the git extension keeps failing with similar errors if I inspect the console:

```
Failed to refresh git status Error: Unable to get the lock on the directory
    at ve (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
    at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async Ee._branch (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
    at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async Ee.refreshBranch (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
    at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async e.Ee._refreshModel [as _factory] (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)

```

Curious for specific steps you took to resolve this! Thanks

**Comment by savemuri** [comment]
> @savemuri I am running into a similar issue on installing Jupyterlab-git extension on a CentOS 8 VM... When you say permission issue with your git credentials, is this via HTTPS (username & password) or SSH pub & private key?
> 
> I'm using the latter and the git extension keeps failing with similar errors if I inspect the console:
> 
> ```
> Failed to refresh git status Error: Unable to get the lock on the directory
>     at ve (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
>     at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async Ee._branch (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
>     at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async Ee.refreshBranch (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
>     at async Ce.execute (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
>     at async e.Ee._refreshModel [as _factory] (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
> ```
> 
> Curious for specific steps you took to resolve this! Thanks

@atnjqt it was a simple mistake on my part. I later realized the issue was because I did not setup my git credential helper store. It works after that

```
git config --global user.name "YOURNAME"
git config --global user.email "YOUREMAIL@MAIL.COM"
git config --global credential.helper store
git clone https://GIT_URI/codebase.git

```

**Comment by atnjqt** [comment]
Thank you for the reply, @savemuri

I am unfamiliar with this helper configuration though I found some info here: [https://git-scm.com/docs/git-credential-store](https://git-scm.com/docs/git-credential-store)

I did try the following (I already had user name & email configured) but I don't think this resolves my problem...

```bash
git config --global credential.helper store
```

What is strange is that _occasionally_ it has connected and I was able to quickly commit / stage, create a new branch, and then push to the new remote branch... Suddenly after it failed again where the push & pull icons are grayed out... Now even the SCM git widget has dissapeared and I get the following output if I inspect the browser Console:

```
664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1 Failed to load the jupyterlab-git server extension settings Error: git command not found - please ensure you have Git > 2 installed
    at activate (664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1)
    at async Promise.all (index 102)
activate @ 664.1e7f16b3afb000957a27.js?v=1e7f16b3afb000957a27:1
jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2 Showing error: git command not found - please ensure you have Git > 2 installed
k @ jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
lab:1 Uncaught (in promise) undefined
```
I'm thinking I should open a new issue rather than reopen this one given the strange behavior I am experiencing... Would be great to have this consistently working.

**Comment by savemuri** [comment]
@atnjqt maybe its a version mismatch with jupyterlab and the git plugin? Adding the combination that worked for me 
`conda install -c conda-forge jupyterlab=2.2.9 jupyterlab-git=0.23.3 --yes
`

**Comment by fcollonval** [comment]
> I should open a new issue rather than reopen this one

👍
