### ISSUE TITLE
pip install of jupyterlab-git==0.30.0b1 for jupyterlab 3 installs nbdime-jupyterlab v.2.1.0-beta.1 labextension

### ISSUE THREAD

**Issue by mtracy-core** [jupyterlab/jupyterlab-git#874]
## Description
pip install of jupyterlab-git==0.30.0b1 for jupyterlab 3 includes nbdime-jupyterlab v.2.1.0-beta.1 labextension. This requires a rebuild of jupyterlab assets. My understanding was that downloading a prebuilt extension for jupyterlab 3 doesn't require a rebuild of jupyterlab. I also notice that the serverextension is using nbdime 3.0.0.b1. 

## Reproduce
pip install "jupyterlab-git==0.30.0b1"

## Expected behavior
a labextension that didn't require jupyterlab to be rebuilt

- Python package version:
python 3.9
pip 20.3.3
jupyterlab 3.0.5
- Extension version:
@jupyterlab/git v0.30.0-beta.1
nbdime-jupyterlab v2.1.0-beta.1
- Git version:
2.30.0
- Operating System and its version:
Ubuntu 18.04

**Comment by ianhi** [comment]
Can you try adding the `--pre` flag: `pip install --upgrade --pre jupyterlab-git`

**Comment by mtracy-core** [comment]
@ianhi that appears to have worked. The extension nbdime-jupyterlab v.2.1.0-beta.1 is not used with jupyterlab-git==0.30.0b1 correct?

**Comment by ianhi** [comment]
Yup that''s correct. Although it's not actually clear to me that nbdime is used anywhere in the extension. The ndime javascript package is used to generate notebook diffs, but that comes from package.json, we never actually make use of the nbdime extension apis I think. So perhaps jlab-git doesn't need to have nbdime as a python dependency? @fcollonval  am I missing something?

**Comment by fcollonval** [comment]
> jlab-git doesn't need to have nbdime as a python dependency? @fcollonval am I missing something?

@ianhi you are correct. The nbdime dependency was added historically as a nice companion to have.

**Comment by fcollonval** [comment]
> My understanding was that downloading a prebuilt extension for jupyterlab 3 doesn't require a rebuild of jupyterlab.

@mtracy-core in fact this is partially true. The old way is still possible - it depends on how the extension author is providing the extension (aka as a prebuilt extension - the new way - or as a source extension - the old way).

See documentation: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions
