### ISSUE TITLE
Failing to install on Jupyterlab 3.0.8 running on Windows 10

### ISSUE THREAD

**Issue by flow4u** [jupyterlab/jupyterlab-git#879]
## Description

In Jupyterlab 3 I can't get the github 

## Reproduce

1. install git 2.30.1  (default except for notepad++)
2. miniconda latest version
2. in miniconda promptsdfsadf:
    1. conda install -c conda-forge jupyterlab=3 nodejs
          jupyterlab 3.0.8, nodejs 15.3  
    2. conda install -c conda-forge jupyterlab jupyterlab-git
         nbdime 2.1.0 gitdb 4.0.5  jupyterlab-git-0.22 smmap 3.0.5 gitpython 3.1.13
        ptyprocess 0.7.0 expect 4.8.0
3. start jupyterlab
    update needed of extensions: @jupyterlab/git  nbdime-jupyterlab
4. In Jupyterlab update nbdime-jupyterlab
5. In Jupyterlab update @jupyterlab/git & rebuild
    ===> FAILED to load jupyter-git server extension
6. conda update --all
7. jupyter lab build (fails in Jupyter Labs)
   ===> jupyter lab is now 2.2.6
8. conda install -c conda-forge jupyterlab=3
  ===> extensions up-to-date
  ===> no Github available
 - jupyterlab-git 0.22.0
 - jupterlab_server 2.3.0
 - @jupyterlab/git v0.30.0-beta.2 enabled ok
 - nbdime-jupyterlab v2.1.0-beta.1 enabled ok
9. conda install -c conda-forge nodejs (was v10.x)
10. jupyter lab build
     ===> FAILED: failed to load the jupyterlab-git server extension
    jupyterlab extension list = jupyterlab v3.0.8
   jupyter server extension list = jupyterlab 3.0.8 ok
 

- Operating System and its version:
Windows 10

**Comment by ianhi** [comment]
jupyterlab-git for jlab3 is still in beta until nbdime releases a non-beta version. So until then you need to install with pip. Can you try to install using `pip install --upgrade --pre jupyterlab-git`

(May be worth doing in a fresh env)

**Comment by flow4u** [comment]
Thanx. Is it normal that on Menu Git, initialize a Rep and clone a Repo are grayed out?  I manage to do it once, but now I’m kind of stuck in a github repo.

 

What works:

*	Refresh
*	Open git in terminal
*	Open .gitignore

 

What fails:

*	Switch branch: fatal: ambiguous argument 'master': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'
*	Push to remote: fatal: The current branch master has no upstream branch.
*	Pull from remote: There is no tracking information for the current branch. Please specify which branch you want to merge with. See git-pull(1) for details. git pull <remote> <branch> If you wish to set tracking information for this branch you can do so with: git branch --set-upstream-to=<remote>/<branch> master
*	Add remote repo: error: remote origin already exists.

 

So maybe the better question is: how to do clean up around git.

 

 

Kind regards

 

Stefan

**Comment by ianhi** [comment]
> Thanx. Is it normal that on Menu Git, initialize a Rep and clone a Repo are grayed out?  I manage to do it once, but now I’m kind of stuck in a github repo.


This is normal when your jupyterlab filebrowser is in a repo. Those commands don't make sense to use when that is true. If you're stuck I suggest starting your jupyterlab in a directory above the git dir.


For the other issues can you get them working from the terminal? Also what is the output of `git branch` in the terminal?
