### ISSUE TITLE
Shortcuts do not work in diff widgets

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#882]
## Description

Default or custom shortcuts are not applied to the diffs, for example the default:

```js
{
    "command": "application:close",
    "keys": [
        "Alt W"
    ],
    "selector": ".jp-Activity"
}
```

This is probably related to how the documentsearch does not work in the diff widgets (although it easily could IMO).

## Reproduce

1. Open the diff widget
2. Try to close tab with a shortcut
3. See no action (or entire browser window getting closed if - like me - you have it configured to `ctrl + w`).

## Expected behavior

Shortcuts should work as in any other tab.

## Context

- Python package version: 0.30.0b1
- Extension version:
nbdime-jupyterlab v2.1.0-beta.1
@jupyterlab/git v0.30.0-beta.1
- Operating System and its version: Ubuntu

**Comment by fcollonval** [comment]
Thanks @Zxun2 for testing this one. In the latest version, that specific shortcut is working.

i'm closing this as it targets an old version. Don't hesitate to open a new one if you hit a case not working.
