### ISSUE TITLE
"Add remote repository" option is enabled when repository is already cloned

### ISSUE THREAD

**Issue by tumido** [jupyterlab/jupyterlab-git#886]
## Description

"Add remote repository" option is enabled when repository is already cloned. Trying to add a new repository via the modal fails, because remote is already present.

## Reproduce

1. Clone a git repo to JupyterLab
2. Click on "Git" menu
3. Click on "Add Remote Repository" entry in the dropdown
4. Enter any git repo url
5. See the error

## Expected behavior

The entry is disabled if a repo is already cloned

## Context

- Python package version: `0.30.0b1`
- Extension version:
```
JupyterLab v3.0.7
/opt/app-root/share/jupyter/labextensions
        jupyterlab_requirements v0.4.6 enabled OK (python, jupyterlab-requirements)
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @jupyterlab/git v0.30.0-beta.1 enabled OK (python, jupyterlab-git)
        @krassowski/jupyterlab-lsp v3.3.1 enabled OK (python, jupyterlab_lsp)

Other labextensions (built into JupyterLab)
   app dir: /opt/app-root/share/jupyter/lab
        @elyra/code-snippet-extension v2.0.1 enabled OK
        @elyra/metadata-extension v2.0.1 enabled OK
        @elyra/pipeline-editor-extension v2.0.1 enabled OK
        @elyra/python-editor-extension v2.0.1 enabled OK
        @elyra/theme-extension v2.0.1 enabled OK
        nbdime-jupyterlab v2.1.0-beta.1 enabled OK
```
Disabled extensions:
    @jupyterlab/launcher-extension (all plugins)
- Git version: `2.27.0`

![image](https://user-images.githubusercontent.com/7453394/109299872-0f962f80-7836-11eb-8324-efb77cb45505.png)

![image](https://user-images.githubusercontent.com/7453394/109300509-e1651f80-7836-11eb-88e5-840d7329abed.png)

![image](https://user-images.githubusercontent.com/7453394/109300543-e9bd5a80-7836-11eb-9b26-28c877d72ed3.png)

**Comment by fcollonval** [comment]
@tumido Thank you for reporting this issue. It actually should still be enabled - because multiple remote repositories is common when using repository forks. But definitely the extension should support the ability to define the remote name to support that.

**Comment by fcollonval** [comment]
Resolved by https://github.com/jupyterlab/jupyterlab-git/pull/1146
