### ISSUE TITLE
Important links for HTTP requests and RESTful Web Services examples

### ISSUE THREAD

**Issue by ashutoshbondre** [jupyterlab/jupyterlab-git#9]

**Comment by ashutoshbondre** [comment]
https://github.com/Microsoft/vscode/blob/master/extensions/git/src/git.ts#L298

**Comment by ashutoshbondre** [comment]
https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/serverconnection.ts

**Comment by ashutoshbondre** [comment]
Here are some examples of how we are using that ServerConnection utility in lab:
https://github.com/jupyterlab/jupyterlab/search?utf8=%E2%9C%93&q=ServerConnection&type=
Or even better these calls to ServerConnection.makeRequest
https://github.com/jupyterlab/jupyterlab/search?utf8=%E2%9C%93&q=makeRequest&type=

**Comment by ellisonbg** [comment]
Closing as reference.
