### ISSUE TITLE
The UI is malformed when using Safari

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab-git#901]
## Description

When using the sidebar widget in Safari, some sections of the UI overlap with each other and can become difficult to use.

## Reproduce

1. Go to 'a git dir in lab
2. Click on the git sidebar tab

## Expected behavior

UI behavior should work in all modern browsers

## Context

- Python package version:
0.30.0b1
- Extension version:
v0.30.0-beta.1
- Git version:
git version 2.24.3 (Apple Git-128)
- Operating System and its version:
macOS 10.15.6

<img width="511" alt="Screen Shot 2021-03-08 at 5 58 20 PM" src="https://user-images.githubusercontent.com/13952758/111203272-04efd000-8582-11eb-9d3e-80d265b0ff9b.png">

**Comment by JasonWeill** [comment]
With jupyterlab-git 0.50.1, and Safari version 17.5 (19618.2.12.11.6) on macOS "Sonoma" 14.5 (23F79), I see the UI with no defects as mentioned above. This issue should be closed as not reproducible.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/1e37c06a-6e15-4fe4-b57d-f724cd6afa71">
