### ISSUE TITLE
jupyterlab-git server extension failed to load

### ISSUE THREAD

**Issue by SnkSynthesis** [jupyterlab/jupyterlab-git#903]
## Description

I tried installing `jupyterlab-git` but it fails to load. I did try both the [Troubleshoot](https://github.com/jupyterlab/jupyterlab-git#troubleshoot) section and the instructions given by the error message, however, both didn't work. 

## Reproduce

**NOTE**: Make sure extensions are enabled
1. `pip install --upgrade jupyterlab jupyterlab-git`
2. `jupyter labextension install @jupyterlab/git`
3. `jupyter lab`
4. See error message:
![image](https://user-images.githubusercontent.com/63564282/111556843-b0e31800-8748-11eb-8b69-8848ee9780e1.png)

## Context

- Python package version:

```
Name: jupyterlab-git
Version: 0.23.3
Summary: A server extension for JupyterLab's git extension
Home-page: https://github.com/jupyterlab/jupyterlab-git
Author: Jupyter Development Team
Author-email: None
License: BSD
Location: c:\users\USER\appdata\local\programs\python\python39\lib\site-packages
Requires: nbdime, packaging, notebook, pexpect
Required-by:
```

- Extension version:

```
JupyterLab v3.0.11
Other labextensions (built into JupyterLab)
   app dir: C:\Users\SA\AppData\Local\Programs\Python\Python39\share\jupyter\lab
        @jupyterlab/git v0.30.0-beta.2 enabled ok
```

- Git version: `git version 2.29.2.windows.2`
- Operating System and its version: Windows 10
- Python Version: Python 3.9.2

<details><summary>Command Line Output</summary>
<pre>
[W 2021-03-17 18:03:25.533 ServerApp] 404 GET /git/settings?version=0.30.0-beta.2&1616029403814 (::1) 18.00ms referer=http://localhost:8888/lab
[D 2021-03-17 18:03:25.536 LabApp] 200 GET /lab/api/settings/@jupyterlab/shortcuts-extension:shortcuts?1616029403977 (::1) 20.00ms
[D 2021-03-17 18:03:25.540 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1616029403978 (::1) 19.00ms
[I 2021-03-17 18:03:25.541 LabApp] Build is up to date
[D 2021-03-17 18:03:25.542 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:25.543 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:25.545 LabApp] 200 GET /lab/api/build?1616029403773 (::1) 1769.16ms
[D 2021-03-17 18:03:25.917 LabApp] Yarn configuration loaded.
[D 2021-03-17 18:03:25.936 ServerApp] Paths used for configuration of page_config:
        C:\ProgramData\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:25.937 ServerApp] Paths used for configuration of page_config:
        c:\users\sa\appdata\local\programs\python\python39\etc\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:25.938 ServerApp] Paths used for configuration of page_config:
        C:\Users\SA\.jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.022 ServerApp] Paths used for configuration of page_config:
        C:\ProgramData\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.023 ServerApp] Paths used for configuration of page_config:
        c:\users\sa\appdata\local\programs\python\python39\etc\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.024 ServerApp] Paths used for configuration of page_config:
        C:\Users\SA\.jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.065 ServerApp] Paths used for configuration of page_config:
        C:\ProgramData\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.066 LabApp] Fetching URL: https://registry.yarnpkg.com/@jupyterlab%2Fgit
[D 2021-03-17 18:03:26.067 ServerApp] Paths used for configuration of page_config:
        c:\users\sa\appdata\local\programs\python\python39\etc\jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.084 ServerApp] Paths used for configuration of page_config:
        C:\Users\SA\.jupyter\labconfig\page_config.json
[D 2021-03-17 18:03:26.142 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:26.144 ServerApp] Paths used for configuration of default_setting_overrides:
        C:\ProgramData\jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.145 ServerApp] Paths used for configuration of default_setting_overrides:
        c:\users\sa\appdata\local\programs\python\python39\etc\jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.145 ServerApp] Paths used for configuration of default_setting_overrides:
        C:\Users\SA\.jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.148 LabApp] 200 GET /lab/api/settings/@jupyterlab/shortcuts-extension:shortcuts?1616029405669 (::1) 6.00ms
[D 2021-03-17 18:03:26.149 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:26.152 LabApp] 200 GET /lab/api/workspaces/default?1616029405645 (::1) 4.00ms
[D 2021-03-17 18:03:26.264 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:26.267 ServerApp] Paths used for configuration of default_setting_overrides:
        C:\ProgramData\jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.267 ServerApp] Paths used for configuration of default_setting_overrides:
        c:\users\sa\appdata\local\programs\python\python39\etc\jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.268 ServerApp] Paths used for configuration of default_setting_overrides:
        C:\Users\sa\.jupyter\labconfig\default_setting_overrides.json
[D 2021-03-17 18:03:26.413 LabApp] > "C:\Program Files\nodejs\npm.CMD" pack @jupyterlab/git@0.30.0-beta.2
-[D 2021-03-17 18:03:26.439 LabApp] 200 GET /lab/api/settings?1616029406262 (::1) 176.00ms
/[D 2021-03-17 18:03:26.772 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:26.773 LabApp] 204 PUT /lab/api/workspaces/default?1616029406769 (::1) 2.00ms
[D 2021-03-17 18:03:26.829 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:26.850 ServerApp] 200 GET /api/contents?content=1&1616029406827 (::1) 21.00ms
-[D 2021-03-17 18:03:27.340 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-03-17 18:03:27.342 LabApp] 204 PUT /lab/api/workspaces/default?1616029407337 (::1) 2.00ms
-[D 2021-03-17 18:03:28.714 LabApp] npm notice
    npm notice package: @jupyterlab/git@0.30.0-beta.2
    npm notice === Tarball Contents ===
    npm notice 1.5kB   LICENSE
    npm notice 382B    style/base.css
    npm notice 3.1kB   style/diff-common.css
    npm notice 10.0kB  style/diff-nb.css
    npm notice 1.4kB   style/diff-text.css
    npm notice 25B     style/index.css
    npm notice 494B    style/variables.css
    npm notice 592B    lib/components/ActionButton.js
    npm notice 788B    lib/style/ActionButtonStyle.js
    npm notice 3.2kB   lib/components/Alert.js
    npm notice 1.0kB   lib/widgets/AuthorBox.js
    npm notice 9.9kB   lib/components/BranchMenu.js
    npm notice 2.9kB   lib/style/BranchMenu.js
    npm notice 23.0kB  lib/commandsAndMenu.js
    npm notice 3.5kB   lib/components/CommitBox.js
    npm notice 3.0kB   lib/style/CommitBox.js
    npm notice 648B    lib/style/common.js
    npm notice 1.5kB   lib/widgets/CredentialsBox.js
    npm notice 1.5kB   lib/components/diff/Diff.js
    npm notice 2.8kB   lib/components/Feedback.js
    npm notice 3.4kB   lib/components/FileItem.js
    npm notice 1.7kB   lib/style/FileItemStyle.js
    npm notice 20.6kB  lib/components/FileList.js
    npm notice 217B    lib/style/FileListStyle.js
    npm notice 901B    lib/components/FilePath.js
    npm notice 531B    lib/style/FilePathStyle.js
    npm notice 2.6kB   lib/git.js
    npm notice 799B    lib/widgets/gitClone.js
    npm notice 1.0kB   lib/widgets/GitCloneForm.js
    npm notice 12.6kB  lib/components/GitPanel.js
    npm notice 1.8kB   lib/style/GitPanel.js
    npm notice 1.7kB   lib/components/GitStage.js
    npm notice 1.3kB   lib/style/GitStageStyle.js
    npm notice 2.2kB   lib/widgets/GitWidget.js
    npm notice 314B    lib/style/GitWidgetStyle.js
    npm notice 617B    lib/components/HistorySideBar.js
    npm notice 293B    lib/style/HistorySideBarStyle.js
    npm notice 2.4kB   lib/style/icons.js
    npm notice 5.4kB   lib/index.js
    npm notice 21B     style/index.js
    npm notice 647B    lib/logger.js
    npm notice 49.1kB  lib/components/diff/mergeview.js
    npm notice 252B    lib/components/diff/model.js
    npm notice 40.5kB  lib/model.js
    npm notice 5.3kB   lib/components/diff/NbDiff.js
    npm notice 1.3kB   lib/components/diff/NBDiffHeader.js
    npm notice 10.5kB  lib/components/NewBranchDialog.js
    npm notice 6.0kB   lib/style/NewBranchDialog.js
    npm notice 3.5kB   lib/components/PastCommitNode.js
    npm notice 1.7kB   lib/style/PastCommitNode.js
    npm notice 3.3kB   lib/components/diff/PlainTextDiff.js
    npm notice 7.7kB   lib/components/ResetRevertDialog.js
    npm notice 4.5kB   lib/style/ResetRevertDialog.js
    npm notice 1.6kB   lib/server.js
    npm notice 8.6kB   lib/components/SinglePastCommitInfo.js
    npm notice 1.8kB   lib/style/SinglePastCommitInfo.js
    npm notice 267B    lib/style/StatusWidget.js
    npm notice 5.1kB   lib/widgets/StatusWidget.js
    npm notice 1.2kB   lib/components/SuspendModal.js
    npm notice 256B    lib/style/SuspendModal.js
    npm notice 6.9kB   lib/components/TagMenu.js
    npm notice 3.0kB   lib/taskhandler.js
    npm notice 1.5kB   lib/tokens.js
    npm notice 9.3kB   lib/components/Toolbar.js
    npm notice 2.8kB   lib/style/Toolbar.js
    npm notice 916B    lib/utils.js
    npm notice 102B    lib/version.js
    npm notice 5.3kB   package.json
    npm notice 3.0kB   schema/plugin.json
    npm notice 1.8kB   lib/components/ActionButton.js.map
    npm notice 1.7kB   lib/style/ActionButtonStyle.js.map
    npm notice 6.2kB   lib/components/Alert.js.map
    npm notice 2.3kB   lib/widgets/AuthorBox.js.map
    npm notice 17.3kB  lib/components/BranchMenu.js.map
    npm notice 5.2kB   lib/style/BranchMenu.js.map
    npm notice 39.0kB  lib/commandsAndMenu.js.map
    npm notice 6.4kB   lib/components/CommitBox.js.map
    npm notice 4.8kB   lib/style/CommitBox.js.map
    npm notice 1.2kB   lib/style/common.js.map
    npm notice 3.1kB   lib/widgets/CredentialsBox.js.map
    npm notice 3.1kB   lib/components/diff/Diff.js.map
    npm notice 6.2kB   lib/components/Feedback.js.map
    npm notice 8.1kB   lib/components/FileItem.js.map
    npm notice 3.1kB   lib/style/FileItemStyle.js.map
    npm notice 36.8kB  lib/components/FileList.js.map
    npm notice 522B    lib/style/FileListStyle.js.map
    npm notice 2.1kB   lib/components/FilePath.js.map
    npm notice 1.1kB   lib/style/FilePathStyle.js.map
    npm notice 3.8kB   lib/git.js.map
    npm notice 2.1kB   lib/widgets/gitClone.js.map
    npm notice 1.9kB   lib/widgets/GitCloneForm.js.map
    npm notice 23.5kB  lib/components/GitPanel.js.map
    npm notice 3.2kB   lib/style/GitPanel.js.map
    npm notice 4.0kB   lib/components/GitStage.js.map
    npm notice 2.6kB   lib/style/GitStageStyle.js.map
    npm notice 4.8kB   lib/widgets/GitWidget.js.map
    npm notice 661B    lib/style/GitWidgetStyle.js.map
    npm notice 1.9kB   lib/components/HistorySideBar.js.map
    npm notice 668B    lib/style/HistorySideBarStyle.js.map
    npm notice 4.8kB   lib/style/icons.js.map
    npm notice 9.7kB   lib/index.js.map
    npm notice 1.4kB   lib/logger.js.map
    npm notice 106.2kB lib/components/diff/mergeview.js.map
    npm notice 1.2kB   lib/components/diff/model.js.map
    npm notice 64.3kB  lib/model.js.map
    npm notice 10.2kB  lib/components/diff/NbDiff.js.map
    npm notice 2.2kB   lib/components/diff/NBDiffHeader.js.map
    npm notice 18.8kB  lib/components/NewBranchDialog.js.map
    npm notice 10.5kB  lib/style/NewBranchDialog.js.map
    npm notice 7.2kB   lib/components/PastCommitNode.js.map
    npm notice 3.3kB   lib/style/PastCommitNode.js.map
    npm notice 5.7kB   lib/components/diff/PlainTextDiff.js.map
    npm notice 14.0kB  lib/components/ResetRevertDialog.js.map
    npm notice 7.6kB   lib/style/ResetRevertDialog.js.map
    npm notice 2.6kB   lib/server.js.map
    npm notice 15.7kB  lib/components/SinglePastCommitInfo.js.map
    npm notice 3.4kB   lib/style/SinglePastCommitInfo.js.map
    npm notice 575B    lib/style/StatusWidget.js.map
    npm notice 7.5kB   lib/widgets/StatusWidget.js.map
    npm notice 2.4kB   lib/components/SuspendModal.js.map
    npm notice 578B    lib/style/SuspendModal.js.map
    npm notice 12.4kB  lib/components/TagMenu.js.map
    npm notice 4.8kB   lib/taskhandler.js.map
    npm notice 24.4kB  lib/tokens.js.map
    npm notice 16.8kB  lib/components/Toolbar.js.map
    npm notice 5.0kB   lib/style/Toolbar.js.map
    npm notice 1.8kB   lib/utils.js.map
    npm notice 264B    lib/version.js.map
    npm notice 17.3kB  README.md
    npm notice 260B    style/icons/add.svg
    npm notice 1.4kB   style/icons/branch.svg
    npm notice 1.3kB   style/icons/clone.svg
    npm notice 307B    style/icons/deletions.svg
    npm notice 258B    style/icons/desktop.svg
    npm notice 517B    style/icons/diff.svg
    npm notice 603B    style/icons/discard.svg
    npm notice 680B    style/icons/git.svg
    npm notice 326B    style/icons/insertions.svg
    npm notice 518B    style/icons/open-file.svg
    npm notice 173B    style/icons/plus.svg
    npm notice 661B    style/icons/pull.svg
    npm notice 642B    style/icons/push.svg
    npm notice 240B    style/icons/remove.svg
    npm notice 352B    style/icons/rewind.svg
    npm notice 809B    style/icons/tag.svg
    npm notice 247B    style/icons/trash.svg
    npm notice 671B    lib/components/ActionButton.d.ts
    npm notice 216B    lib/style/ActionButtonStyle.d.ts
    npm notice 1.5kB   lib/components/Alert.d.ts
    npm notice 427B    lib/widgets/AuthorBox.d.ts
    npm notice 2.7kB   lib/components/BranchMenu.d.ts
    npm notice 461B    lib/style/BranchMenu.d.ts
    npm notice 1.9kB   lib/commandsAndMenu.d.ts
    npm notice 2.1kB   lib/components/CommitBox.d.ts
    npm notice 196B    lib/style/CommitBox.d.ts
    npm notice 49B     lib/style/common.d.ts
    npm notice 470B    lib/widgets/CredentialsBox.d.ts
    npm notice 1.1kB   lib/components/diff/Diff.d.ts
    npm notice 940B    lib/components/Feedback.d.ts
    npm notice 1.4kB   lib/components/FileItem.d.ts
    npm notice 454B    lib/style/FileItemStyle.d.ts
    npm notice 4.8kB   lib/components/FileList.d.ts
    npm notice 51B     lib/style/FileListStyle.d.ts
    npm notice 371B    lib/components/FilePath.d.ts
    npm notice 136B    lib/style/FilePathStyle.d.ts
    npm notice 754B    lib/git.d.ts
    npm notice 271B    lib/widgets/gitClone.d.ts
    npm notice 336B    lib/widgets/GitCloneForm.d.ts
    npm notice 4.1kB   lib/components/GitPanel.d.ts
    npm notice 315B    lib/style/GitPanel.d.ts
    npm notice 755B    lib/components/GitStage.d.ts
    npm notice 263B    lib/style/GitStageStyle.d.ts
    npm notice 1.2kB   lib/widgets/GitWidget.d.ts
    npm notice 45B     lib/style/GitWidgetStyle.d.ts
    npm notice 780B    lib/components/HistorySideBar.d.ts
    npm notice 50B     lib/style/HistorySideBarStyle.d.ts
    npm notice 723B    lib/style/icons.d.ts
    npm notice 329B    lib/index.d.ts
    npm notice 607B    lib/logger.d.ts
    npm notice 4.4kB   lib/components/diff/mergeview.d.ts
    npm notice 782B    lib/components/diff/model.d.ts
    npm notice 20.7kB  lib/model.d.ts
    npm notice 1.6kB   lib/components/diff/NbDiff.d.ts
    npm notice 433B    lib/components/diff/NBDiffHeader.d.ts
    npm notice 2.9kB   lib/components/NewBranchDialog.d.ts
    npm notice 1.1kB   lib/style/NewBranchDialog.d.ts
    npm notice 1.7kB   lib/components/PastCommitNode.d.ts
    npm notice 526B    lib/style/PastCommitNode.d.ts
    npm notice 1.0kB   lib/components/diff/PlainTextDiff.d.ts
    npm notice 3.1kB   lib/components/ResetRevertDialog.d.ts
    npm notice 575B    lib/style/ResetRevertDialog.d.ts
    npm notice 392B    lib/server.d.ts
    npm notice 3.0kB   lib/components/SinglePastCommitInfo.d.ts
    npm notice 484B    lib/style/SinglePastCommitInfo.d.ts
    npm notice 48B     lib/style/StatusWidget.d.ts
    npm notice 1.1kB   lib/widgets/StatusWidget.d.ts
    npm notice 952B    lib/components/SuspendModal.d.ts
    npm notice 54B     lib/style/SuspendModal.d.ts
    npm notice 1.9kB   lib/components/TagMenu.d.ts
    npm notice 1.4kB   lib/taskhandler.d.ts
    npm notice 23.4kB  lib/tokens.d.ts
    npm notice 2.9kB   lib/components/Toolbar.d.ts
    npm notice 624B    lib/style/Toolbar.d.ts
    npm notice 402B    lib/utils.d.ts
    npm notice 48B     lib/version.d.ts
    npm notice === Tarball Details ===
    npm notice name:          @jupyterlab/git
    npm notice version:       0.30.0-beta.2
    npm notice filename:      jupyterlab-git-0.30.0-beta.2.tgz
    npm notice package size:  217.1 kB
    npm notice unpacked size: 1.0 MB
    npm notice shasum:        4c292e83b2bc3f30d4ac31405162c5e17ca74994
    npm notice integrity:     sha512-Y1tQgQ/qJRnKR[...]xQLsYa/ueIjuA==
    npm notice total files:   205
    npm notice
    jupyterlab-git-0.30.0-beta.2.tgz

[D 2021-03-17 18:03:28.760 LabApp] 200 GET /lab/api/extensions?1616029404332 (::1) 3219.74ms
[D 2021-03-17 18:03:28.760 LabApp] 200 GET /lab/api/extensions?1616029405342 (::1) 3217.72ms
</pre>
</details>

<details><summary>Web Browser Output</summary>
<img src="https://user-images.githubusercontent.com/63564282/111558335-d0c80b00-874b-11eb-85b1-38bd8a6ce3ba.png">
</details>

**Comment by ianhi** [comment]
@SnkSynthesis can you try with `pip install --upgrade --pre jupyterlab-git` unfortunately as nbdime is still in a beta release so too is jupyterlab-git

**Comment by SnkSynthesis** [comment]
@ianhi Yes, this worked. Thank you!
