### ISSUE TITLE
Ability to switch to specific tabs with ctrl + number

### ISSUE THREAD

**Issue by Zethson** [jupyterlab/jupyterlab-git#922]
## Is your feature request related to a problem? Please describe.
I usually have many many tabs open and switch to them one by one is slow and annoying.

## Describe the solution you'd like
At least for tabs 1-10 it should be possible to switch to them with ctrl + [1-9]. E.g. ctrl + 5 switches to tab 5.
This is also how people access tabs in their browser. Moreover, ctrl + 9 could also switch the VERY LAST tab. Again, this is how the browsers do it. 

Since we are running in a browser environment it might be better to have alt + number or something. I guess that you guys know better which combinations are not yet occupied.

Thank you very much!

**Comment by ianhi** [comment]
Hi @Zethson is this specific to git extension or a request for jupyterlab in general? If it's the latter lets close this issue and you can open the same feature request at: https://github.com/jupyterlab/jupyterlab

**Comment by Zethson** [comment]
Oh, I am very sorry. Apparently in the wrong repository :)

It's the latter.

**Comment by ianhi** [comment]
> Oh, I am very sorry. Apparently in the wrong repository :)

This actually happens all the time! Must be something weird with the SEO - but don't worry you're not the first nor will you be the last :)
