### ISSUE TITLE
Jupyterlab-git not working with `jupytext.TextFileContentsManager`

### ISSUE THREAD

**Issue by sntgluca** [jupyterlab/jupyterlab-git#928]
## Description

Dear all,
when I start my JupyterLab session from a directory _which is **root** of a git repository_ I encounter the following error, preventing the plugin to recognise the git space and to operate correctly:

```python
Uncaught exception POST /git/show_top_level?1618747672880 (<IP_ADDRESS>)
    HTTPServerRequest(protocol='http', host='<HOST>', method='POST', uri='/git/show_top_level?1618747672880', version='HTTP/1.1', remote_ip='<IP_ADDRESS>')
    Traceback (most recent call last):
      File "<PYTHON_ENV>/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "<PYTHON_ENV>/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 109, in post
        result = await self.git.show_top_level(current_path)
      File "<PYTHON_ENV>/lib/python3.8/site-packages/jupyterlab_git/git.py", line 678, in show_top_level
        code, my_output, my_error = await execute(
      File "<PYTHON_ENV>/lib/python3.8/site-packages/jupyterlab_git/git.py", line 158, in execute
        return code, output, error
    UnboundLocalError: local variable 'code' referenced before assignment
```

If I start JupyterLab from the parent directory it works perfectly.

## Reproduce

1. `cd my_git_project`
2. `jupyter lab ...`
3. Go to the GIT plugin tab
4.  "You are not currently in a Git repository..." message appears

## Expected behavior

The GIT content should be shown instead

## Context

- Python package version:

jupyterlab-git            0.30.0b2

- Extension version:

@jupyterlab/git v0.30.0-beta.2
- Git version:

git version 2.18.0
- Operating System and its version:
CentOS 7
<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Fail to find Git top level for path .
Error: Unhandled error
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @sntgluca thank you for reporting this error. 

Do you have a warning in the log before the exception? If so could you please report it.

Here is a fix - albeit I'm pretty sure you got another error.

Could you modify your python file
`<PYTHON_ENV>/lib/python3.8/site-packages/jupyterlab_git/git.py` at line 156 like this:

```diff
     except BaseException:
         get_logger().warning("Fail to execute {!s}".format(cmdline), exc_info=True)
+        raise
     finally:
         execution_lock.release()

     return code, output, error
```

**Comment by sntgluca** [comment]
Hi @fcollonval ,
thanks for answering so quickly.

I tried something very similar to your suggestion, 

```python
except BaseException as error:
        get_logger().warning("Fail to execute {!s}".format(cmdline), exc_info=True)
        get_logger().error("Failed: {}".format(error))
...
```
and the logs show:

```python
[E 2021-04-19 16:32:29.004 ServerApp.jupyterlab_git] Failed: [Errno 2] No such file or directory: ''
```

After further inspection I figured out that the `cwd` variable was not set for at least one `git` call.

By adding the following at line 121 of the same file (which I don't think is the right solution, nor the best way to write it) the error disappears:
```python
try:
        if not cwd: cwd = '.'
...
```

So far, it seems the error comes _only_ from the call to `git', 'rev-parse', '--show-toplevel'`. The command is fine, but the `cwd` variable is not set.
May you help to come up with the "real" error? I don't know enough about the library to dig further.

**Comment by fcollonval** [comment]
Thanks for digging up the trouble.

I was wandering, do you have symbolic link in the root server folder? This may explain why `cwd` is empty.

> For example when starting the binder demo on this project, you end up in your situation (aka JupyterLab root folder is the git root folder) and everything works. So you may be hitting the error due to a symbolic link.

Xref: https://github.com/jupyterlab/jupyterlab-git/issues/775

**Comment by sntgluca** [comment]
Hi,
First of all thanks for following up.

Actually, no symlinks. But I think I found what went wrong. I write it here for further reference.

First of all, the problem is due to having an empty value for the `self.root_dir` parameter used to create `cwd` in `git.py`.

This parameter is initially set based on a `contents_manager` defined in `jupyter_server.base.handlers.APIHandler`.

Now, in a "normal" environment the contents manager is based on
```python
<jupyter_server.services.contents.largefilemanager.LargeFileManager>
``` 

but after installing `jupytext==1.11.1`, and configuring it explicitly in `jupyter_lab_config.py` (sort of legacy decision based on https://jupytext.readthedocs.io/en/latest/install.html):
```python
c.ServerApp.contents_manager_class = "jupytext.TextFileContentsManager"
```
the contents manager became
```python
<jupytext.contentsmanager.build_jupytext_contents_manager_class.<locals>.JupytextContentsManager object at ...>
```
this was messing things up.
Removing the configuration line, while keeping `jupytext` works for me!

Hope it helps others in the future...

**Comment by fcollonval** [comment]
Waw thanks a lot @sntgluca for nailing that one. I will update the title of this issue to help others find it.
