### ISSUE TITLE
Failed to load the jupyterlab-git server extension on The Littlest JupyterHub

### ISSUE THREAD

**Issue by Comee** [jupyterlab/jupyterlab-git#929]
## Description

Failed to load the jupyterlab-git server extension on The Littlest JupyterHub, but it worked if I run  `jupyter lab` which give me a new visit url (different to  The Littlest JupyterHub url)

## Reproduce

1. Install The Littlest JupyterHub
2. Install jupyterlab-git extension
3. Open a git nootbook will get the follow error

![image](https://user-images.githubusercontent.com/5416227/115983606-cca5cd80-a5d4-11eb-91fa-ac52350af8b6.png)

4. In The Littlest JupyterHub Terminal run `jupyter lab` , it give me a new jupyterlab url, in which jupyterlab-git works

![image](https://user-images.githubusercontent.com/5416227/115983507-104c0780-a5d4-11eb-9a4a-4335f4b10b38.png)

## Context

- Python package version:

![image](https://user-images.githubusercontent.com/5416227/115983234-97987b80-a5d2-11eb-8c29-1d983059da12.png)

- Extension version:

![image](https://user-images.githubusercontent.com/5416227/115983546-69b43680-a5d4-11eb-9958-13f85e4dc312.png)

![image](https://user-images.githubusercontent.com/5416227/115983246-ab43e200-a5d2-11eb-8383-0b7bbe417201.png)

- Git version:

![image](https://user-images.githubusercontent.com/5416227/115983262-bf87df00-a5d2-11eb-8c9d-df8275f32b71.png)

- Operating System and its version:

<pre>
Linux version 5.8.0-50-generic (buildd@lgw01-amd64-051) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1) #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021
</pre>

**Comment by Comee** [comment]
When I empty the user home dir , it worked.

**Comment by fcollonval** [comment]
Thanks @Comee to report your workaround. I am not familiar with TLJH; so I'm sorry that I cannot advice nor explain more.

I only have one comment about that statement:

> In The Littlest JupyterHub Terminal run jupyter lab , it give me a new jupyterlab url, in which jupyterlab-git works

In fact the notebook toolbar buttons you are seeing does not come from this extension but from `nbdime` (a dependency of this package). This extension adds a sidebar panel and a menu `Git`.

**Comment by Comee** [comment]
@fcollonval  Thanks for your explaination, the menu `Git` now is ok.

**Comment by mounaTay** [comment]
@Comee how did you solve this? my home folder is already empty so what did you remove in precise?

**Comment by Comee** [comment]
@mounaTay you can try [Elyra](https://github.com/elyra-ai/elyra) extension, it will auto setup  jupyterlab-git

**Comment by vsisl** [comment]
Hey @Comee, how did you add Elyra to TLJH? For me it's not showing up among available extensions in the JupyterLab UI
<img width="512" alt="image" src="https://github.com/jupyterlab/jupyterlab-git/assets/28457179/61647b3d-711a-4058-83e2-d509e46335d1">
