### ISSUE TITLE
Don't erase commit message when switching to the History tab

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#931]
## Description

When switching to the History tab with a commit summary/description entered, the values get discarded.
Similar to #836

## Reproduce

![message-discarded](https://user-images.githubusercontent.com/5832902/116210924-3a6c0980-a73b-11eb-94ae-b114ac7cc64b.gif)

## Expected behavior

The message is preserved when switching to history and back. I sometimes switch to check what was the message of my previous commit (or do `git log` if in terminal) and do not like to have to type the commit message again.

## Context

- Python package version: 0.30.0
- Extension version: v0.30.0
- Git version: 2.31.1
- Operating System and its version: Ubuntu

**Comment by fcollonval** [comment]
Thanks for the suggestion @krassowski
