### ISSUE TITLE
git extension not showing up when running `jupyter server extension list`

### ISSUE THREAD

**Issue by sarahspak** [jupyterlab/jupyterlab-git#937]
## Description

I ran `pip install jupyterlab-git`, and I see the frontend extension , but cannot see the server extension (see screenshots below).

labextension is present
![Screen Shot 2021-05-19 at 1 59 01 PM](https://user-images.githubusercontent.com/52671374/118883782-a3224e00-b8c3-11eb-90c6-ba0e8a62c9a3.png)

server extension is missing
![Screen Shot 2021-05-19 at 2 00 37 PM](https://user-images.githubusercontent.com/52671374/118883866-c0efb300-b8c3-11eb-8d28-18f3d0818784.png)

## Reproduce

`pip install jupyterlab-git`
`jupyter server extension list`

## Expected behavior

Expect to see jupyterlab-git server extension

## Context

- Python package version:
```
pip freeze | grep jupyter
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-packaging==0.10.2
jupyter-server==1.7.0
jupyter-server-mathjax==0.2.2
jupyterlab==3.0.16
jupyterlab-git==0.30.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.5.2
jupyterlab-widgets==1.0.0
```

- `pip show jupyterlab-git`
```
Name: jupyterlab-git
Version: 0.30.1
Summary: A JupyterLab extension for version control using git
Home-page: https://github.com/jupyterlab/jupyterlab-git.git
Author: Jupyter Development Team
Author-email: None
License: BSD-3-Clause
Location: /Users/spak/.pyenv/versions/3.9.1/envs/jlab3_extension_dev/lib/python3.9/site-packages
Requires: nbformat, jupyter-server, pexpect, nbdime, packaging
Required-by: 
```

- Extension version:
```
        @jupyterlab/git v0.30.1 enabled OK
```

- Git version:
``` 
git version 2.31.1
```

- Operating System and its version:
Mac OS Catalina 10.15.7 (19H1030)

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by krassowski** [comment]
Looks suspiciously similar to an issue we are having over at https://github.com/krassowski/jupyterlab-lsp/issues/598 - also on Mac.

Could you please try running:

jupyter server extension enable --py jupyterlab-git

or

jupyter server extension enable --sys-prefix --py jupyterlab-git

And see if it shows up on the list afterwards?

**Comment by sarahspak** [comment]
@krassowski neither of those commands worked; still seeing the following error message: 
`      X Validation failed: The module 'jupyterlab-git' could not be found. Are you sure the extension is installed?`


![Screen Shot 2021-05-20 at 11 08 14 AM](https://user-images.githubusercontent.com/52671374/119027856-d244c800-b974-11eb-86cc-a9737f91d631.png)

**Comment by krassowski** [comment]
Sorry, it should be:

```
jupyter server extension enable --py jupyterlab_git
```

(underscore not hyphen). Does this one help?

**Comment by sarahspak** [comment]
unfortunately not :(

**Comment by krassowski** [comment]
Is the message the same or different?

**Comment by sarahspak** [comment]
noticed that it's writing the config to `/usr/local/Cellar/jupyterlab/3.0.14/libexec/etc/jupyter` but I use pyenv (environment is called `jlab3_extension_dev`. Should it be writing to:
`~/.pyenv/versions/jlab3_extension_dev/etc/jupyter` instead?

**Comment by sarahspak** [comment]
some more digging: 
when I run `which jupyter`, I get 
```
/usr/local/bin/jupyter
```

but when I run `pyenv which jupyter`, I get 
```
/Users/spak/.pyenv/versions/jlab3_extension_dev/bin/jupyter
```

**Comment by krassowski** [comment]
That's strange. I also use pyenv but for me it is:

```
(my-env) $ which jupyter
/home/krassowski/.pyenv/shims/jupyter
(my-env) $ pyenv which jupyter
/home/krassowski/.pyenv/versions/my-env/bin/jupyter
```

Though I have no idea how things are supposed to work on Mac sorry :(

**Comment by sarahspak** [comment]
Ok I think I figured it out - I deleted this directory `/usr/local/Cellar/jupyterlab/3.0.14/libexec/etc/jupyter`, and now things are working as expected
```
which jupyter
/Users/spak/.pyenv/shims/jupyter
```

Many thanks @krassowski !
