### ISSUE TITLE
Can’t see git panel

### ISSUE THREAD

**Issue by BretG137** [jupyterlab/jupyterlab-git#944]
## Description

I cannot see the git panel but the extension is installed and is visible in the advanced settings.  Not sure what to do because I don't see anything wrong and have tried to reboot and also jupyter lab build.

- Python package version:
3.7

- Extension version:
0.30.1 enabled Ok

- Git version: 2.20.1

- Operating System and its version:
debian 10

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @BretG137 could you please copy here the output of the following commands:

- `jupyter labextension list`
- `jupyter server extension list`
- `jupyter lab`  
Copy the log you are seeing in the console when launching JupyterLab

**Comment by BretG137** [comment]
> 
> 
> Hey @BretG137 could you please copy here the output of the following commands:
> 
>     * `jupyter labextension list`

/home/user/.local/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

/home/user/jupyterenvironment/share/jupyter/labextensions
        @jupyterlab/git v0.30.1 enabled OK (python, jupyterlab-git)

Other labextensions (built into JupyterLab)
   app dir: /home/user/jupyterenvironment/share/jupyter/lab


>     * `jupyter server extension list`

Config dir: /home/user/.jupyter

/home/user/jupyterenvironment/lib/python3.7/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
Config dir: /home/user/jupyterenvironment/etc/jupyter
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.30.1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.1.0 OK

Config dir: /usr/local/etc/jupyter
 
>     * `jupyter lab`

/home/user/jupyterenvironment/lib/python3.7/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[I 2021-06-04 13:38:34.906 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2021-06-04 13:38:34.917 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-06-04 13:38:34.917 ServerApp] jupyterlab_git | extension was successfully linked.
[W 2021-06-04 13:38:34.920 NotebookApp] 'allow_credentials' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-06-04 13:38:34.920 NotebookApp] 'allow_credentials' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-06-04 13:38:34.921 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-06-04 13:38:34.921 NotebookApp] 'password_required' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-06-04 13:38:34.921 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-06-04 13:38:34.921 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-06-04 13:38:35.327 ServerApp] nbclassic | extension was successfully linked.
[I 2021-06-04 13:38:35.327 ServerApp] nbdime | extension was successfully linked.
[I 2021-06-04 13:38:35.365 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-06-04 13:38:35.366 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2021-06-04 13:38:35.367 LabApp] JupyterLab extension loaded from /home/user/jupyterenvironment/lib/python3.7/site-packages/jupyterlab
[I 2021-06-04 13:38:35.367 LabApp] JupyterLab application directory is /home/user/jupyterenvironment/share/jupyter/lab
[I 2021-06-04 13:38:35.370 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-06-04 13:38:35.373 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2021-06-04 13:38:35.444 ServerApp] nbdime | extension was successfully loaded.
[I 2021-06-04 13:38:35.444 ServerApp] The port 9999 is already in use, trying another port.
[I 2021-06-04 13:38:35.445 ServerApp] Serving notebooks from local directory: /home/user
[I 2021-06-04 13:38:35.445 ServerApp] Jupyter Server 1.8.0 is running at:
[I 2021-06-04 13:38:35.446 ServerApp] http://192.168.1.121:10000/lab
[I 2021-06-04 13:38:35.446 ServerApp]     http://127.0.0.1:10000/lab
[I 2021-06-04 13:38:35.446 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2021-06-04 13:38:35.450 ServerApp] No web browser found: could not locate runnable browser.

>       Copy the log you are seeing in the console when launching JupyterLab

Also I tried removing the extension in jupyterhub and then reinstall it and now when I login to jupyterhub I get the following error message:
Failed to load the jupyterlab-git server extension
"Git server extension is unavailable. Please ensure you have installed the JupyterLab Git server extension by running: pip install --upgrade jupyterlab-git. To confirm that the server extension is installed, run: jupyter serverextension list."
previously I had installed it from the command line.  Thanks!

**Comment by BretG137** [comment]
I think it has something to do with the virtual environment I created.  If I type:

source jupyterenvironment/bin/activate
jupyter lab --certfile=mycert.pem --keyfile mykey.key

then the extension is visible but no pip packages work because I'm outside the virtual env.  Normally I type:

virtualenv jupyterenvironment 
source jupyterenvironment/bin/activate
jupyter lab --certfile=mycert.pem --keyfile mykey.key

but this causes this extension to not work.  I installed the extension inside the virtual env so I don't know why this is a problem.  Do you have any idea how to fix this?  Thanks!

**Comment by BretG137** [comment]
I got this to work by specifying an older version using the following:
pip install jupyterlab==3
pip install jupyterlab-git==0.30
as mentioned here:
https://stackoverflow.com/questions/65918842/failed-to-load-jupyterlab-git-server-extension

**Comment by fcollonval** [comment]
I'm glad you succeeded. But this is really strange because there is almost no difference between 0.30.0 and 0.30.1.

**Comment by fcollonval** [comment]
With the command:
```
pip install jupyterlab==3
```

You actually downgraded JupyterLab to 3.0.0. Would you be willing to try upgrading jupyterlab (`pip install -U jupyterlab`) to see if the bug is back?
