### ISSUE TITLE
HybridContentsManager not supported

### ISSUE THREAD

**Issue by altruistcoder** [jupyterlab/jupyterlab-git#947]
I am working on a use case where I am running Jupyter as a pod in OpenShift, and I want to leverage several JupyterLab extensions such as JupyterLab-git. 
But, when I try to initialize a git repository in a particular folder or try to clone a git repository, I am getting the below error:

![Git Error](https://user-images.githubusercontent.com/31319270/120942455-b009c300-c746-11eb-8744-3aac2a4cea1f.png)

I am facing this path related problem with some other jupyterlab extensions as well such as Elyra.

Can you please suggest what I might be doing wrong here. Is this problem occurring due to a wrong value being set of a particular path, is it coming up because of some environmental variable's value being set to an incorrect value or there is probably some other reason behind happening of such a behavior? 
I am stuck on this issue for a long time now and haven't got the right solution yet.

**Comment by fcollonval** [comment]
Hey this sounds like Linux permission trouble. You need to check that the JupyterLab process is launched with an user having write permission on the drive.

**Comment by altruistcoder** [comment]
Hey @fcollonval thanks for replying on the issue. As per my understanding, the user is having the permissions of writing on the drive as I am able to use all types of git commands from the terminal integrated in the JupyterLab environment successfully. If there's any mistake in my understanding, please do correct me.

**Comment by fcollonval** [comment]
Some additional questions:

Are you using a specific content manager (like hybridscontent)?
Could you copy here the jupyterlab log? It should contain a bit more information (in particular try to run jupyter lab with `--debug` flag to get more insight).
Could you try in a notebook the git command using subprocess:
```
import subprocess
subprocess.run(['git', 'clone', 'https://github.com/jupyterlab/jupyterlab-git'])
```
> You can of course pick a different repository than this one for testing git clone.

**Comment by altruistcoder** [comment]
Yes, I am making use of two content managers, viz. "S3ContentsManager" and "HybridContentsManager" along with the "LargeFileManager" for mounting the bucket of a user (created using Rook-Ceph as an S3 API compatible storage) in their JupyterHub pod.
You can check out the updated `jupyter_server_config.py` file that I a using [here](https://github.com/altruistcoder/s2i-minimal-notebook/blob/py-38-s3/jupyter_server_config.py).

As far as I was able to figure out in this issue, when I am trying to initialize a git repository in the `/opt/app-root/src` folder of the pod, it is instead trying to initialize the repo in the `/` folder due to which it shows permission error. But, when I do not mount the S3 buckets in the pod, the extension starts to work properly and there is no permission error and if we initialize a git repo in `/opt/app-root/src` now, then it initializes the git repo in the correct folder, instead of initializing it in `/` folder,

I have tried hard but I have not been able to figure out what is exactly getting changed in the pod environment after mounting the S3 buckets.

As you suggested, I tried running the commands specified by you using the subprocess module and it worked fine. I was able to clone a git repository successfully using the code given by you.

Also, I am running the jupyterhub using its official docker image, hence it is bit hard for me to run the jupyterlab server with `--debug` flag.

Can you please suggest me if there's anything else that I can try doing for resolving this error?

**Comment by fcollonval** [comment]
Ok this is the reason. The _HybridContentsManager_ is not supported on the latest version. I pushed recently #939 that adds support for it. I triggered an alpha release of the package. So you can try it.

To install the alpha version, execute:

```
python -m pip install --pre jupyterlab-git==0.31.0a0
```

**Comment by altruistcoder** [comment]
This worked!
Thanks a lot @fcollonval for helping me in resolving this issue. Do you have any idea when are these changes going to be reflected in the latest version?

Also, I am facing another issue with the **Elyra extension** of JupyterLab. The issue seems to be similar to the issue I was facing with the Git extension as I shared above.
I am trying to execute a sample pipeline provided in[ Elyra examples repo](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world) in my environment. But, I am facing the below error when I tried to run it in the JupyterLab notebook images having S3 buckets mounted in them (**Using same HybridContentsManager**):

![elyra-extension-error](https://user-images.githubusercontent.com/31319270/121540020-c1dbb680-ca23-11eb-978e-44966950104f.png)

But, I am able to run the pipeline successfully on JupyterLab notebook images which do not have S3 buckets mounted in them.
As far as I was able to figure out with this issue as well, when I am trying to run the pipeline in an environment where HybridContentsManager is being used, the extension is trying to find files in the `/examples/pipelines/` folder which gives the error as shown in the above screenshot, while it tries to find files in the `/opt/app-root/src/examples/pipelines/` folder in the other case.

**Comment by fcollonval** [comment]
To resolve the real path of a file on a machine, extension are using the root directory information from the content manager. The hybrid content manager is not providing such information as it federates multi sources (hence the root directory is not singleton).

I'm sorry but you will have to open an issue on their extension: https://github.com/elyra-ai/elyra

> You can point on this issue. As they may be interested in the fix implemented for hybridcontentsmanager.

**Comment by altruistcoder** [comment]
@fcollonval 
Can you please tell me when is this update in the **jupyterlab-git** extension, going to be rolled out in the **latest version** of the extension?

**Comment by fcollonval** [comment]
The version 0.31.0 has been released but there is one bug that needs to be fixed #989

**Comment by altruistcoder** [comment]
@fcollonval does the version 0.32.0 release have all the relevant fixes?

**Comment by fcollonval** [comment]
> @fcollonval does the version 0.32.0 release have all the relevant fixes?

Yes it does.
