### ISSUE TITLE
failed to load the jupyterlab-git server extension git command not found 

### ISSUE THREAD

**Issue by Gregory-Essuman** [jupyterlab/jupyterlab-git#952]
## Description

I installed jupyterlab git extension via conda and jupyter can't seem to load the extension upon opening. I keep getting this error below:

failed to load the jupyterlab-git server extension git command not found - please ensure you have Git > 2 installed

I have uninstalled and reinstalled but still the problem persists. This is bugging me as i need to fix it and work with it. Would be glad to get a fix.  

Below are some screenshots. 

Feedback from Opening Jupyterlab

![JupyterGit Issua](https://user-images.githubusercontent.com/84207002/121424508-50d7c880-c969-11eb-801f-f9a1ad5e916d.JPG)
 
![JupyterGit Issue1](https://user-images.githubusercontent.com/84207002/121424519-53d2b900-c969-11eb-8f99-56821b4f6479.JPG)

Feedback from running jupyter labextension list
![JupyterGit Issue2](https://user-images.githubusercontent.com/84207002/121425931-e32c9c00-c96a-11eb-92e5-2e359fe0a515.JPG)

Feedback from running jupyter server extention list
![JupyterGit Issue3](https://user-images.githubusercontent.com/84207002/121425958-e758b980-c96a-11eb-8f42-5af98881b497.JPG)

Feedback from running jupyter lab
![JupyterGit Issue4](https://user-images.githubusercontent.com/84207002/121425973-ec1d6d80-c96a-11eb-81a2-60fe27008265.JPG)

## Context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by fcollonval** [comment]
@Gregory-Essuman The error is due to Git being unavailable. You can check that by opening a terminal in JupyterLab and execute:

```
git --version
```

If this returns an error, Git needs to be installed on your system.

> One way of doing that is by installing the conda package:

```
conda install -c conda-forge -y git
```

**Comment by Gregory-Essuman** [comment]
I had to install git and it's working now. Thanks a lot.
