### ISSUE TITLE
Failed to commit, Fail to set your identity. Unhandled error

### ISSUE THREAD

**Issue by DarkmatterVale** [jupyterlab/jupyterlab-git#958]
## Description

When attempting to commit from the Git UI in Jupyterlab, I receive an error: `Failed to commit, Fail to set your identity. Unhandled error`

## Reproduce

1. Go to the Git extension
2. Stage some changes
3. Fill out the commit name & description
4. Click commit
5. The following error appears:

```
HTTPServerRequest(protocol='http', host='...', method='POST', uri='/user/.../git/test123/config?...', version='HTTP/1.1', remote_ip='...')
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.7/site-packages/jupyterlab_git/handlers.py", line 650, in post
        options = data.get("options", {})
    AttributeError: 'NoneType' object has no attribute 'get'
```

## Expected behavior

I am able to commit changes to the git repository.

## Context

- Python package version: 0.31.0a0
- Extension version: v0.31.0-alpha.0
- Git version: 2.23.4
- Operating System and its version: Amazon Linux 2

I've traced the error back to https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyterlab_git/handlers.py#L649. As specified at https://github.com/jupyterlab/jupyterlab-git/blob/master/src/model.ts#L507, the body of the `POST` request can be null if options are not set. This in turn causes the `data = self.get_json_body()` object to return `None`, leading to the error on the following line of code.

If I manually find the offending `/config` request in my browser, and inspect the `body`, I can confirm it is empty. If I resend the request with a body of `{}`, the endpoint returns the expected value.

**Comment by DarkmatterVale** [comment]
I'm aware that there is a similar issue (https://github.com/jupyterlab/jupyterlab-git/issues/498) that already exists. However, the reasons for the error appear to be very different, so I created a new issue.

**Comment by fcollonval** [comment]
Thanks @DarkmatterVale for the detailed issue. Indeed the root cause is not the same as of #498.

Would you be willing to propose a PR?

**Comment by DarkmatterVale** [comment]
I'm happy to submit a PR.

Any preference to the expected behavior? It seems most logical to add a check on https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyterlab_git/handlers.py#L650 to handle the case where `data` is `None`.

**Comment by fcollonval** [comment]
Sounds good to me.

**Comment by avishmehta68710** [comment]
@fcollonval is the issue solved ???
Thanks

**Comment by fcollonval** [comment]
Thanks indeed it has been solved.
