### ISSUE TITLE
Receive error message directly

### ISSUE THREAD

**Issue by Niklas5** [jupyterlab/jupyterlab-git#969]
Hello everybody!

Unfortunately the plug-in is currently not working for us. 

## Description
We installed the plug-in correctly. However, when we want to work with it, we instantly get an error message. 
Here you can find an extract of the logs:
"Content-Length": "19",
"Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
"X-Xsrftoken": "2|8b656fdf|3e644050f47349420e1c333255401d73|1624738382",
"Sec-Ch-Ua-Mobile": "?0",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
"Content-Type": "text/plain;charset=UTF-8",
"Accept": "*/*",
"Origin": "https://kubeflow....",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Dest": "empty",
"Referer": "https://kubeflow....",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9,de;q=0.8",
"Cookie": "_xsrf=2|8b656fdf|3e644050f47349420e1c333255401d73|1624738382;",
"X-Envoy-External-Address": "10.26.56.187",
"X-Request-Id": "6d32ae0f-e254-90d0-bbe3-c186fae44f3a",
"Kubeflow-Userid": "...",
"X-Envoy-Original-Path": "/notebook/.../test4/git/init?1625140720697",
"X-B3-Traceid": "b5cc7b2d4dab5d60084705cf4c599194",
"X-B3-Spanid": "3ac784f95fcfd0e5",
"X-B3-Parentspanid": "084705cf4c599194",
"X-B3-Sampled": "1"
}
[E 2021-07-01 11:58:40.892 ServerApp] 500 POST /`

Note that the program runs within a Kubernetes cluster (but we don't think this is the problem).

Thank you for your help!

**Comment by fcollonval** [comment]
Hey @Niklas5 

Could you add more information on the version and OS you are using? Also could you run JupyterLab in debug mode (CLI `--debug` or configurable `ServerApp.log_level=DEBUG` and report the error you are seeing?

In debug mode, you will get more insight on what is going on on the server side - hopefully getting more information about the reason behind the error.
