### ISSUE TITLE
Failed to commit changes due to "Author identity unknown" after setting global user.name and user.email 

### ISSUE THREAD

**Issue by Brettem** [jupyterlab/jupyterlab-git#972]
## Description

I am trying to use the Jupyterlab-git extension to commit staged files but when I hit Commit I am prompted with an error: 

"Error
Author identity unknown *** Please tell me who you are. Run git config --global user.email "you@example.com" git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: empty ident name (for <>) not allowed"

This is after I already ran 'git config --global user.email "ME@example.com"' and 'git config --global user.name "ME ME"'

## Reproduce

1. In Git Extension stage file(s)
2. add summary
3. hit "Commit"

## Expected behavior

My file to be committed to my existing intended repo just like through the terminal.

## Context

I have run 'git config --global user.email' and 'git config --global user.name' which both output my email and name respectively no issues, and I checked my gitconfig file for [user] and inserted my information. No luck

When I first started up the Git Extension I was prompted to insert my name and email and accidentally hit enter without inputting anything. Thinking this was the issue I uninstalled and reinstalled the extension but was not prompted with the same name/email textboxes and still have the same issue.

I am now getting the same issue in the Terminal but am not sure if this only happened after setting up the Git Extension or not.

- Python package version:
0.30.1
- Extension version:
JupyterLab v3.0.14
- Git version:
2.32.0.windows.2
- Operating System and its version:
Windows 10

**Comment by fcollonval** [comment]
Hey @Brettem does it work to commit from the terminal? If not is the error the same one?

Other question what is the content of your  `%USERPROFILE%\.gitconfig`?

**Comment by Brettem** [comment]
- Fails in terminal too:

"Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed"

I figured this counts as an Git Extension issue since that initial setup window I failed to enter any info in might have caused the issue.

- As for my %USERPROFILE%\.gitconfig:

[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[http]
	sslBackend = openssl
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
	autocrlf = true
	fscache = true
	symlinks = false
[pull]
	rebase = false
[credential]
	helper = manager-core
[credential "https://dev.azure.com"]
	useHttpPath = true
[init]
	defaultBranch = master
[user]
	name = My Name
	email = myemail@correct.com

Where I manually inserted the [user] section after the issue had already manifested but it did not resolve it.

**Comment by Brettem** [comment]
Solved it! Completely user error (never sent git init) thank you @fcollonval sorry for the silly issue

**Comment by fcollonval** [comment]
Thanks for taking the time to report back.
