### ISSUE TITLE
Failed to load the Jupyter-git server

### ISSUE THREAD

**Issue by raghulkrishna** [jupyterlab/jupyterlab-git#978]
hello guyz i deployed jupyterhub to eks using this helm chart https://artifacthub.io/packages/helm/jupyterhub/jupyterhub when I try to install git extension I am getting this I went through issues in this  repo nothing works.
is there any dependency has to be installed?

tried solutions in these https://github.com/jupyterlab/jupyterlab-git/issues/903, https://github.com/jupyterlab/jupyterlab-git/issues/951 seems to be not working 

<img width="1435" alt="Screenshot 2021-07-19 at 12 18 26 PM" src="https://user-images.githubusercontent.com/62284209/126147777-007852e2-ac3d-4598-88f2-a221b72401ab.png">

**Comment by fcollonval** [comment]
Hey @raghulkrishna how did you install the extension? From the screenshot, it sounds like you used the extension manager. For this extension, this will not fully work as there is a python part of the extension that needs to be loaded before launching the JupyterLab server. I don't know anything about helm chart. The only advice I can provide is that you need to pip or conda install `jupyterlab-git` in the image before spinning it.

**Comment by raghulkrishna** [comment]
@fcollonval  thank you creating a custom docker image worked
