### ISSUE TITLE
Add ability to display the diff of any two commits in the file history panel

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#985]
Select two arbitrary commits and view their diff (`Select for compare` & `Compare with selected` from VSCode)

_Originally posted by @navn-r in https://github.com/jupyterlab/jupyterlab-git/issues/980#issuecomment-886121034_

**Comment by willyyang** [comment]
Is this feature being worked on ?

**Comment by fcollonval** [comment]
Hey @willyyang no at the moment nobody is working into this. Go ahead and open a PR if you want; I'm happy to give you pointers to do so.

**Comment by avishmehta68710** [comment]
Hey
i think this is already implemented 
![image](https://user-images.githubusercontent.com/69706506/140262779-c45ed08a-7448-43eb-aaa3-778e9e8eef57.png)

**Comment by fcollonval** [comment]
Hey @avishmehta68710, the proposed feature is not yet implement. The goal is to go a step further than displaying the diff for one commit as you show in your screenshot by being able to select two arbitrary commits.

**Comment by fcollonval** [comment]
Reopening as it will be good to add the feature for a single file.
