### ISSUE TITLE
How to use jupyterlab-git extension's language pot

### ISSUE THREAD

**Issue by xiongjiamu** [jupyterlab/jupyterlab-git#987]
HI, there

I found you guys have done some great translations in Crowdin which provide a Chinese version of this extension, I tried my best and I still couldn't find a way to use this language pot .

Is there any documentation or usage for this ?  Thanks a lot :)

here is the link I found in Crowdin <https://crowdin.com/project/jupyterlab/zh-CN#/master/extensions/jupyterlab_git>

**Comment by fcollonval** [comment]
Hey @xiongjiamu 

It has not been published yet unfortunately. I'm currently working on publishing a first version. But I don't have a release date yet. I'll update this issue when it is available.

**Comment by xiongjiamu** [comment]
HI @fcollonval , thx.

I'm looking forward to your new version, good luck!

**Comment by fcollonval** [comment]
Hey @xiongjiamu you should be able to test the chinese translation by installing:

```
pip install --pre jupyterlab-language-pack-zh-CN
```

> This is still an early version.

**Comment by xiongjiamu** [comment]
Got it ~~~
