### ISSUE TITLE
Switch from a detached head to a branch not working

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#995]
If the repository is in detached head (for example after switching to a tag), then switching to a branch will fail.

Error message:

```
fatal: ambiguous argument '(HEAD detached at v0.20.0)': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]' 
```

![Peek 2021-08-03 19-06](https://user-images.githubusercontent.com/8435071/128057755-4437e620-6cba-4189-92a8-3ccb083b151d.gif)

**Comment by Bl4ck-h00d** [comment]
Hi! I would like to work on this, can you help me how to get started?!

**Comment by fcollonval** [comment]
Hey @Bl4ck-h00d 

Thanks for kicking in.

The extension has two parts: a front-end in Typescript and a back-end in Python. Whenever you trigger an action from the front-end, it will call a `git` command in the back-end.

In this case, to switch branch, the command call is done there:

https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/jupyterlab_git/git.py#L880

The action is triggered in the frontend with that callback:

https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/src/components/BranchMenu.tsx#L402

The workflow is the following:

1. `onClick` is triggered with the branch name
2. it calls the `model.checkout` method  https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/src/model.ts#L426
> The model is handling the repository state and the call to the backend
3. That trigger a call to the backend https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/src/model.ts#L469
4. The call is catch by a Python handler: https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/jupyterlab_git/handlers.py#L443
5. That handler calls the git command mentioned above: https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/jupyterlab_git/handlers.py#L456

The troubles is in the front-end because we want to deal with files that are different between two branches at

https://github.com/jupyterlab/jupyterlab-git/blob/02c6d9aa8cf3344b37397e303c8d345efab12aff/src/model.ts#L458

This calls:
![image](https://user-images.githubusercontent.com/8435071/128057548-e28a3394-8f5f-4bea-96b6-0ca9d92f7a46.png)

with

```json
{"base":"(HEAD detached at v0.21.0)","remote":"master"}
```

`base` is not a valid ref; hence the error seen.

> I'll update the description with an animation.

Let me know if you need more information and don't hesitate to open a PR early to discuss your fix.

**Comment by fcollonval** [comment]
Transforming the fake branch name `(HEAD detached at #####)` to `#####` before calling `model.checkout` should solve this issue.
