### ISSUE TITLE
Provide a pull-only mode that completely overwrites local files

### ISSUE THREAD

**Issue by orome** [jupyterlab/jupyterlab-git#998]
## Is your feature request related to a problem? Please describe.
I would like to use `jupyterlab-git` in the context of a shared project (e.g., though Binder), where contributions from users are not supported, and where any pulls should completely overwrite (and prune) local files. I know there are limited existing solutions for similar scenarios, but they create a layer (or more) of abstraction above Git, that results in the loss of information (e.g. `jupyterlab-git` effectively provides notification of remote changes).

## Describe the solution you'd like
It would be great of `jupyterlab-git` provided settings that

1. prevented any pushing, and
2. where all pulls completely overwrote (and pruned) local files

while still providing all of the other file viewing, diffing, and other features it supports

## Describe alternatives you've considered
Other solutions like `nbgitpuller` are very limited.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/what-is-installed-by-default-with-binder/10217/11

**Comment by fcollonval** [comment]
Nice suggestion @orome 

If you want I can provide pointers to help you start a PR for this one.
